// Copyright 2026 Antfly, Inc.
//
// Licensed under the Elastic License 2.0 (ELv2); you may not use this file
// except in compliance with the Elastic License 2.0. You may obtain a copy of
// the Elastic License 2.0 at
//
//     https://www.antfly.io/licensing/ELv2-license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the Elastic License 2.0 is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// Elastic License 2.0 for the specific language governing permissions and
// limitations.

const table_write_cache = @import("table_writes/cache.zig");
const table_write_core = @import("table_writes/core.zig");
const table_write_index_config = @import("table_writes/index_config.zig");
const table_write_integrity = @import("table_writes/integrity.zig");
const table_write_integrity_types = @import("table_writes/integrity_types.zig");
const table_write_managed_db = @import("table_writes/managed_db.zig");
const table_write_relational_mutation = @import("table_writes/relational_mutation.zig");
const table_write_schema_jobs = @import("table_writes/schema_jobs.zig");
const table_write_sources = @import("table_writes/sources.zig");

pub const ForeignKeyIntegrityAction = table_write_integrity_types.ForeignKeyIntegrityAction;
pub const UniqueConstraintIntegrityAction = table_write_integrity_types.UniqueConstraintIntegrityAction;
pub const ForeignKeyIntegrityRequest = table_write_integrity_types.ForeignKeyIntegrityRequest;
pub const ForeignKeyIntegritySchemaControllerOptions = table_write_integrity_types.ForeignKeyIntegritySchemaControllerOptions;
pub const ForeignKeyIntegritySchemaControllerTableResult = table_write_integrity_types.ForeignKeyIntegritySchemaControllerTableResult;
pub const ForeignKeyIntegritySchemaControllerResult = table_write_integrity_types.ForeignKeyIntegritySchemaControllerResult;
pub const UniqueConstraintIntegrityRequest = table_write_integrity_types.UniqueConstraintIntegrityRequest;
pub const UniqueConstraintIntegritySchemaControllerOptions = table_write_integrity_types.UniqueConstraintIntegritySchemaControllerOptions;
pub const UniqueConstraintIntegrityGroupReport = table_write_integrity_types.UniqueConstraintIntegrityGroupReport;
pub const UniqueConstraintIntegrityResult = table_write_integrity_types.UniqueConstraintIntegrityResult;
pub const UniqueConstraintIntegritySchemaControllerTableResult = table_write_integrity_types.UniqueConstraintIntegritySchemaControllerTableResult;
pub const UniqueConstraintIntegritySchemaControllerResult = table_write_integrity_types.UniqueConstraintIntegritySchemaControllerResult;
pub const UniqueConstraintOwnerTopology = table_write_integrity_types.UniqueConstraintOwnerTopology;
pub const UniqueConstraintOwnerRange = table_write_integrity_types.UniqueConstraintOwnerRange;
pub const UniqueConstraintIntegrityProgress = table_write_integrity_types.UniqueConstraintIntegrityProgress;
pub const ForeignKeyIntegrityGroupReport = table_write_integrity_types.ForeignKeyIntegrityGroupReport;
pub const ForeignKeyIntegrityTupleValue = table_write_integrity_types.ForeignKeyIntegrityTupleValue;
pub const ForeignKeyIntegrityViolation = table_write_integrity_types.ForeignKeyIntegrityViolation;
pub const ForeignKeyIntegrityJobStatus = table_write_integrity_types.ForeignKeyIntegrityJobStatus;
pub const ForeignKeyIntegrityResult = table_write_integrity_types.ForeignKeyIntegrityResult;
pub const ForeignKeyIntegrityWorkUnit = table_write_integrity_types.ForeignKeyIntegrityWorkUnit;
pub const ForeignKeyIntegrityWorkState = table_write_integrity_types.ForeignKeyIntegrityWorkState;
pub const ForeignKeyIntegrityWorkStatus = table_write_integrity_types.ForeignKeyIntegrityWorkStatus;
pub const ForeignKeyIntegrityWorkClaim = table_write_integrity_types.ForeignKeyIntegrityWorkClaim;
pub const ForeignKeyIntegrityProgress = table_write_integrity_types.ForeignKeyIntegrityProgress;
pub const ForeignKeyActionJobStatus = table_write_integrity_types.ForeignKeyActionJobStatus;
pub const ForeignKeyActionJobResult = table_write_integrity_types.ForeignKeyActionJobResult;
pub const ForeignKeyActionJobProgressResult = table_write_integrity_types.ForeignKeyActionJobProgressResult;
pub const ForeignKeyActionScheduleStatus = table_write_integrity_types.ForeignKeyActionScheduleStatus;
pub const ForeignKeyActionScheduleProgressResult = table_write_integrity_types.ForeignKeyActionScheduleProgressResult;

pub const SecondaryIndexRebuildWorkerResult = table_write_schema_jobs.SecondaryIndexRebuildWorkerResult;
pub const SecondaryIndexRebuildWorkerPassResult = table_write_schema_jobs.SecondaryIndexRebuildWorkerPassResult;
pub const SecondaryIndexRebuildGroupRequest = table_write_schema_jobs.SecondaryIndexRebuildGroupRequest;
pub const RelationalColumnBackedIndexRepairGroupRequest = table_write_schema_jobs.RelationalColumnBackedIndexRepairGroupRequest;
pub const RelationalColumnBackedIndexRepairWorkerResult = table_write_schema_jobs.RelationalColumnBackedIndexRepairWorkerResult;
pub const RelationalColumnBackedIndexRepairWorkerPassResult = table_write_schema_jobs.RelationalColumnBackedIndexRepairWorkerPassResult;
pub const RelationalIndexRepairJobRecord = table_write_core.RelationalIndexRepairJobRecord;
pub const SchemaRewriteWorkerResult = table_write_schema_jobs.SchemaRewriteWorkerResult;
pub const SchemaRewriteWorkerPassResult = table_write_schema_jobs.SchemaRewriteWorkerPassResult;
pub const SchemaRewriteGroupRequest = table_write_schema_jobs.SchemaRewriteGroupRequest;
pub const TableEmptyingWorkerResult = table_write_schema_jobs.TableEmptyingWorkerResult;
pub const TableEmptyingWorkerPassResult = table_write_schema_jobs.TableEmptyingWorkerPassResult;
pub const TableEmptyingGroupRequest = table_write_schema_jobs.TableEmptyingGroupRequest;

pub const TableWriteSource = table_write_core.TableWriteSource;
pub const RaftBatcher = table_write_core.RaftBatcher;
pub const freeForeignKeyRefChildrenPage = table_write_core.freeForeignKeyRefChildrenPage;
pub const freeRelationalIndexRepairJobRecord = table_write_core.freeRelationalIndexRepairJobRecord;
pub const freeRelationalIndexRepairJobRecords = table_write_core.freeRelationalIndexRepairJobRecords;

pub const validateIndexConfig = table_write_index_config.validateIndexConfig;
pub const validateIndexConfigWithOptions = table_write_index_config.validateIndexConfigWithOptions;
pub const normalizeManagedEmbeddingIndexDimensionJsonWithOptions = table_write_index_config.normalizeManagedEmbeddingIndexDimensionJsonWithOptions;
pub const normalizeManagedEmbeddingIndexDimensionsJsonWithOptions = table_write_index_config.normalizeManagedEmbeddingIndexDimensionsJsonWithOptions;

pub const stableForeignKeyIntegrityJobIdAlloc = table_write_integrity.stableForeignKeyIntegrityJobIdAlloc;

pub const mutateRowsJoinedFromRecursiveCtePlanAlloc = table_write_relational_mutation.mutateRowsJoinedFromRecursiveCtePlanAlloc;
pub const mutateRowsJoinedFromRecursiveCtePlanWithSessionAlloc = table_write_relational_mutation.mutateRowsJoinedFromRecursiveCtePlanWithSessionAlloc;
pub const mutateRowsJoinedFromRecursiveCtePlanAutocommitAlloc = table_write_relational_mutation.mutateRowsJoinedFromRecursiveCtePlanAutocommitAlloc;
pub const mutateRowsJoinedFromRecursiveCtePlanAutocommitWithSessionAlloc = table_write_relational_mutation.mutateRowsJoinedFromRecursiveCtePlanAutocommitWithSessionAlloc;
pub const mergeRowsFromRecursiveCtePlanAlloc = table_write_relational_mutation.mergeRowsFromRecursiveCtePlanAlloc;
pub const mergeRowsFromRecursiveCtePlanWithSessionAlloc = table_write_relational_mutation.mergeRowsFromRecursiveCtePlanWithSessionAlloc;

pub const openManagedDbForStatusWithIndexesJsonAndCache = table_write_managed_db.openManagedDbForStatusWithIndexesJsonAndCache;

pub const ProvisionedTableWriteCache = table_write_cache.ProvisionedTableWriteCache;
pub const HostedManagedDbCacheDiagnostics = table_write_cache.HostedManagedDbCacheDiagnostics;
pub const closeHostedManagedDbCacheForRoot = table_write_cache.closeHostedManagedDbCacheForRoot;
pub const hostedManagedDbCacheDiagnosticsForRoot = table_write_cache.hostedManagedDbCacheDiagnosticsForRoot;

pub const BoundTableWriteSource = table_write_sources.BoundTableWriteSource;
pub const ProvisionedTableWriteSource = table_write_sources.ProvisionedTableWriteSource;
pub const HostedProvisionedTableWriteSource = table_write_sources.HostedProvisionedTableWriteSource;
