// Copyright 2026 Antfly, Inc.
//
// Licensed under the Elastic License 2.0 (ELv2); you may not use this file
// except in compliance with the Elastic License 2.0. You may obtain a copy of
// the Elastic License 2.0 at
//
//     https://www.antfly.io/licensing/ELv2-license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the Elastic License 2.0 is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// Elastic License 2.0 for the specific language governing permissions and
// limitations.

const table_read_core = @import("table_reads/core.zig");
const table_read_cache = @import("table_reads/cache.zig");
const table_read_relational_rows = @import("table_reads/relational_rows.zig");
const table_read_external_lake = @import("table_reads/external_lake.zig");
const table_read_remote_wire = @import("table_reads/remote_wire.zig");
const table_read_fanout = @import("table_reads/fanout.zig");
const table_read_graph = @import("table_reads/graph.zig");
const table_read_sources = @import("table_reads/sources.zig");

pub const parseTextStatsHttpResponse = table_read_remote_wire.parseTextStatsHttpResponse;
pub const ParallelFanoutMetricsSnapshot = table_read_fanout.ParallelFanoutMetricsSnapshot;
pub const parallelFanoutMetricsSnapshot = table_read_fanout.parallelFanoutMetricsSnapshot;

pub const LookupResponse = table_read_core.LookupResponse;
pub const ScanResponse = table_read_core.ScanResponse;
pub const TextStatsResponse = table_read_core.TextStatsResponse;
pub const BackgroundTextStatsResponse = table_read_core.BackgroundTextStatsResponse;
pub const LsmStorageStats = table_read_core.LsmStorageStats;
pub const ObservedDynamicFieldCapabilitySet = table_read_core.ObservedDynamicFieldCapabilitySet;
pub const ParsedTextStatsHttpResponse = table_read_core.ParsedTextStatsHttpResponse;
pub const HAReadGate = table_read_core.HAReadGate;
pub const ReadPreparation = table_read_core.ReadPreparation;
pub const backend_current_root_generation = table_read_core.backend_current_root_generation;
pub const GroupVisibleRootGenerationSource = table_read_core.GroupVisibleRootGenerationSource;
pub const ResidentDbLease = table_read_core.ResidentDbLease;
pub const ResidentDbSource = table_read_core.ResidentDbSource;
pub const RelationalRowsSourceGroupRequest = table_read_core.RelationalRowsSourceGroupRequest;
pub const RelationalRowsSourceGroupSystemTime = table_read_core.RelationalRowsSourceGroupSystemTime;
pub const TableReadSource = table_read_core.TableReadSource;
pub const appendScanLine = table_read_core.appendScanLine;

pub const testing = table_read_sources.testing;
pub const BoundTableReadSource = table_read_sources.BoundTableReadSource;
pub const ProvisionedTableReadSource = table_read_sources.ProvisionedTableReadSource;
pub const HostedProvisionedTableReadSource = table_read_sources.HostedProvisionedTableReadSource;

pub const ProvisionedTableReadCache = table_read_cache.ProvisionedTableReadCache;

pub const searchRequestFromVectorWorkerEnvelope = table_read_remote_wire.searchRequestFromVectorWorkerEnvelope;

pub const LoweredSqlReadPlanResult = table_read_relational_rows.LoweredSqlReadPlanResult;
pub const LoweredRelationPopulationRowsResult = table_read_relational_rows.LoweredRelationPopulationRowsResult;
pub const takeLoweredSqlReadRows = table_read_relational_rows.takeLoweredSqlReadRows;
pub const executeLoweredSqlReadPlanAlloc = table_read_relational_rows.executeLoweredSqlReadPlanAlloc;
pub const executeLoweredSqlReadPlanWithSessionAlloc = table_read_relational_rows.executeLoweredSqlReadPlanWithSessionAlloc;
pub const executeLoweredRelationPopulationPlanAlloc = table_read_relational_rows.executeLoweredRelationPopulationPlanAlloc;
pub const RecursiveCteMaterializedRows = table_read_relational_rows.RecursiveCteMaterializedRows;
pub const materializeLoweredSqlRecursiveCteRowsAlloc = table_read_relational_rows.materializeLoweredRecursiveCteRowsAlloc;
pub const materializeLoweredSqlRecursiveCteRowsWithSessionAlloc = table_read_relational_rows.materializeLoweredRecursiveCteRowsWithSessionAlloc;
pub const rowsInsertSourceBatchFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsInsertSourceBatchFromRoutedScansWithSchemasAlloc;
pub const rowsInsertSourceBatchFromRecursiveCtePlanAlloc = table_read_relational_rows.rowsInsertSourceBatchFromRecursiveCtePlanAlloc;
pub const rowsInsertSourceBatchFromRecursiveCtePlanWithSessionAlloc = table_read_relational_rows.rowsInsertSourceBatchFromRecursiveCtePlanWithSessionAlloc;
pub const rowsInsertSourcePlanBatchFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsInsertSourcePlanBatchFromRoutedScansWithSchemasAlloc;
pub const rowsLoweredInsertSourceBatchFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsLoweredInsertSourceBatchFromRoutedScansWithSchemasAlloc;
pub const rowsLoweredInsertSourceBatchFromRoutedScansWithSchemasAndDefaultContextAlloc = table_read_relational_rows.rowsLoweredInsertSourceBatchFromRoutedScansWithSchemasAndDefaultContextAlloc;
pub const rowsMergeMutationBatchFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsMergeMutationBatchFromRoutedScansWithSchemasAlloc;
pub const rowsMergeMutationBatchFromRoutedScansWithSchemasAndDefaultContextAlloc = table_read_relational_rows.rowsMergeMutationBatchFromRoutedScansWithSchemasAndDefaultContextAlloc;
pub const rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAlloc;
pub const rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAndSessionAlloc = table_read_relational_rows.rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAndSessionAlloc;
pub const rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAndSessionAndDefaultContextAlloc = table_read_relational_rows.rowsRecursiveMergeMutationBatchFromRoutedScansWithSchemasAndSessionAndDefaultContextAlloc;
pub const rowsJoinPlanFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsJoinPlanFromRoutedScansWithSchemasAlloc;
pub const rowsLateralPlanFromRoutedScansWithSchemasAlloc = table_read_relational_rows.rowsLateralPlanFromRoutedScansWithSchemasAlloc;

pub const PinnedExternalLakeRowsScanner = table_read_external_lake.PinnedExternalLakeRowsScanner;
pub const PinnedExternalLakeSidecarContext = table_read_external_lake.PinnedExternalLakeSidecarContext;
pub const PinnedExternalObjectStorageLakeRowsScanner = table_read_external_lake.PinnedExternalObjectStorageLakeRowsScanner;
pub const PinnedExternalObjectStorageLakeRowsSource = table_read_external_lake.PinnedExternalObjectStorageLakeRowsSource;
pub const ExternalObjectStorageLakeRowsSourceOptions = table_read_external_lake.ExternalObjectStorageLakeRowsSourceOptions;
pub const ExternalLakePinnedSourceState = table_read_external_lake.ExternalLakePinnedSourceState;
pub const ExternalLakePhysicalScanSummary = table_read_external_lake.ExternalLakePhysicalScanSummary;
pub const OwnedExternalObjectStorageLakeRowsSource = table_read_external_lake.OwnedExternalObjectStorageLakeRowsSource;
pub const OpenedExternalObjectStorageLakeRowsSource = table_read_external_lake.OpenedExternalObjectStorageLakeRowsSource;
pub const ExternalLakeObjectStoreResolver = table_read_external_lake.ExternalLakeObjectStoreResolver;
pub const RemoteUriExternalLakeObjectStoreResolver = table_read_external_lake.RemoteUriExternalLakeObjectStoreResolver;
pub const ConfiguredExternalLakeObjectStoreResolver = table_read_external_lake.ConfiguredExternalLakeObjectStoreResolver;
pub const ExternalLakeRoutingTableReadSource = table_read_external_lake.ExternalLakeRoutingTableReadSource;
pub const executePinnedExternalLakeRowsScanAlloc = table_read_external_lake.executePinnedExternalLakeRowsScanAlloc;
