apiVersion: v1
kind: ConfigMap
metadata:
  name: antfly-config
data:
  config.json: |
    {
      "deployment_mode": "distributed",
      "metadata": {
        "orchestration_urls": {
          "1": "http://antfly-metadata-0.antfly-metadata-svc.default.svc.cluster.local:12377",
          "2": "http://antfly-metadata-1.antfly-metadata-svc.default.svc.cluster.local:12377",
          "3": "http://antfly-metadata-2.antfly-metadata-svc.default.svc.cluster.local:12377"
        }
      },
      "inference": { "api_url": "http://127.0.0.1:11433" },
      "storage": { "engine": "local", "local": { "base_dir": "/antflydb" } },
      "max_shard_size_bytes": 64000000,
      "replication_factor": 3,
      "disable_shard_alloc": true,
      "log": { "level": "info", "style": "json" }
    }
