#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate CAVLC codewords from an independently downloaded, pinned source."""

import hashlib
import json
from pathlib import Path
import re
import sys

REVISION = "1a0073f0322c8b74cbcb75ca1bb1c3d19d75538d"
SHA256 = "07efde17fd518bbaf2f372948f82da11c758c54f839f776133105ce9f673c5e1"
raw = Path(sys.argv[1]).read_bytes()
if hashlib.sha256(raw).hexdigest() != SHA256:
    raise SystemExit("OpenH264 source digest does not match the pinned revision")
source = raw.decode()
license_text = source[: source.index("*/") + 2]
output = "\n".join("// " + line for line in license_text.splitlines())
output += f"\n// Generated by scripts/generate_h264_tables.py.\n// Cisco OpenH264 revision {REVISION}, encoder_data_tables.cpp.\n// BSD-2-Clause; see THIRD_PARTY_NOTICES.md. No OpenH264 runtime is linked.\n"
for name, target, dimensions in [
    ("g_kuiVlcCoeffToken", "coeff_token", "[5][17][4][2]u8"),
    ("g_kuiVlcTotalZeros", "total_zeros", "[16][16][2]u8"),
    ("g_kuiVlcTotalZerosChromaDc", "chroma_zeros", "[4][4][2]u8"),
    ("g_kuiVlcRunBefore", "run_before", "[8][15][2]u8"),
]:
    start = source.index("=", source.index("const uint8_t " + name + "[")) + 1
    end = source.index(";", start)
    data = re.sub(r"//[^\n]*", "", source[start:end]).strip()
    data = data.replace("{", "[").replace("}", "]")
    data = re.sub(r",\s*]", "]", data)

    def emit(values, indent=0):
        if isinstance(values[0], int):
            return ".{ " + ", ".join(map(str, values)) + " }"
        if isinstance(values[0][0], int):
            return ".{ " + ", ".join(emit(row) for row in values) + " }"
        return (
            ".{\n"
            + "".join(
                " " * (indent + 4) + emit(row, indent + 4) + ",\n" for row in values
            )
            + " " * indent
            + "}"
        )

    data = emit(json.loads(data))
    output += f"pub const {target}: {dimensions} = {data};\n"
(Path(__file__).resolve().parents[1] / "src/h264_tables.zig").write_text(output)
