#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate CABAC constants from pinned BSD-2-Clause OpenH264 source."""

from pathlib import Path
import hashlib
import re
import sys

source = Path(sys.argv[1]).read_bytes()
assert (
    hashlib.sha256(source).hexdigest()
    == "2cf0a5fc3fce813413566af2ced506eb91a1e0c3f625abc9ca9bf70e0ffef958"
)
text = source.decode()
root = Path(__file__).resolve().parents[1]
license = text[: text.index("*/") + 2]
result = (
    "\n".join("// " + line for line in license.splitlines())
    + "\n// Generated by scripts/generate_h264_cabac_tables.py.\n// OpenH264 1a0073f0322c8b74cbcb75ca1bb1c3d19d75538d, common_tables.cpp.\n"
)
for cname, zname, shape, kind in [
    ("g_kiCabacGlobalContextIdx", "initial", "[460][4][2]i8", "i8"),
    ("g_kuiCabacRangeLps", "lps", "[64][4]u8", "u8"),
    ("g_kuiStateTransTable", "transition", "[64][2]u8", "u8"),
]:
    body = text[text.index("=", text.index(cname)) + 1 :]
    body = body[: body.index(";")]
    body = re.sub(r"/\*.*?\*/|//[^\n]*", "", body, flags=re.S)
    body = body.replace("CTX_NA", "0")
    body = re.sub(r"\{", ".{", body)
    result += f"pub const {zname}: {shape} = {body.strip()};\n"
(root / "src/h264_cabac_tables.zig").write_text(result)
