// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for AntflyType.
const (
	AntflyTypeBlob            AntflyType = "blob"
	AntflyTypeBoolean         AntflyType = "boolean"
	AntflyTypeDatetime        AntflyType = "datetime"
	AntflyTypeEmbedding       AntflyType = "embedding"
	AntflyTypeGeopoint        AntflyType = "geopoint"
	AntflyTypeGeoshape        AntflyType = "geoshape"
	AntflyTypeHtml            AntflyType = "html"
	AntflyTypeKeyword         AntflyType = "keyword"
	AntflyTypeLink            AntflyType = "link"
	AntflyTypeNumeric         AntflyType = "numeric"
	AntflyTypeSearchAsYouType AntflyType = "search_as_you_type"
	AntflyTypeText            AntflyType = "text"
)

// Defines values for DynamicTemplateMatchMappingType.
const (
	DynamicTemplateMatchMappingTypeBoolean DynamicTemplateMatchMappingType = "boolean"
	DynamicTemplateMatchMappingTypeDate    DynamicTemplateMatchMappingType = "date"
	DynamicTemplateMatchMappingTypeNumber  DynamicTemplateMatchMappingType = "number"
	DynamicTemplateMatchMappingTypeObject  DynamicTemplateMatchMappingType = "object"
	DynamicTemplateMatchMappingTypeString  DynamicTemplateMatchMappingType = "string"
)

// Defines values for TemplateFieldMappingMissingNullPolicy.
const (
	TemplateFieldMappingMissingNullPolicyMissingRejected TemplateFieldMappingMissingNullPolicy = "missing_rejected"
)

// AntflyType Field type annotations for schema fields
type AntflyType string

// DocumentSchema Defines the structure of a document type
type DocumentSchema struct {
	// Description A description of the document type.
	Description string `json:"description,omitempty,omitzero"`

	// Schema A valid JSON Schema defining the document's structure.
	// This is used to infer indexing rules and field types.
	Schema map[string]interface{} `json:"schema,omitempty,omitzero"`
}

// DynamicTemplate A rule for mapping dynamically detected fields. Templates are checked in order
// and the first matching template's mapping is used.
type DynamicTemplate struct {
	// Mapping Field mapping to apply when a dynamic template matches
	Mapping TemplateFieldMapping `json:"mapping,omitempty,omitzero"`

	// Match Glob pattern for field name (last path element).
	// Supports * and ** wildcards. Example: "*_text" matches "title_text", "body_text"
	Match string `json:"match,omitempty,omitzero"`

	// MatchMappingType Filter by detected JSON type
	MatchMappingType DynamicTemplateMatchMappingType `json:"match_mapping_type,omitempty,omitzero"`

	// Name Optional identifier for the template (useful for debugging)
	Name string `json:"name,omitempty,omitzero"`

	// PathMatch Glob pattern for the full dotted path. Supports ** for matching multiple segments.
	// Example: "metadata.**" matches "metadata.author", "metadata.tags.primary"
	PathMatch string `json:"path_match,omitempty,omitzero"`

	// PathUnmatch Path exclusion pattern. If it matches the full path, the template is skipped.
	PathUnmatch string `json:"path_unmatch,omitempty,omitzero"`

	// Unmatch Exclusion pattern for field name. If it matches, the template is skipped.
	// Example: "skip_*" would exclude fields like "skip_this"
	Unmatch string `json:"unmatch,omitempty,omitzero"`
}

// DynamicTemplateMatchMappingType Filter by detected JSON type
type DynamicTemplateMatchMappingType string

// TableSchema Schema definition for a table with multiple document types
type TableSchema struct {
	// DefaultType Default type to use from the document_types.
	DefaultType string `json:"default_type,omitempty,omitzero"`

	// DocumentSchemas A map of type names to their document json schemas.
	DocumentSchemas map[string]DocumentSchema `json:"document_schemas,omitempty,omitzero"`

	// DynamicTemplates Rules for mapping dynamically detected fields. When a document contains fields
	// that don't have explicit mappings and dynamic mapping is enabled, templates are
	// evaluated in order to determine how those fields should be indexed.
	DynamicTemplates []DynamicTemplate `json:"dynamic_templates,omitempty,omitzero"`

	// EnforceTypes Whether to enforce that documents must match one of the provided document types.
	// If false, documents not matching any type will be accepted but not indexed.
	EnforceTypes bool `json:"enforce_types,omitempty,omitzero"`

	// TtlDuration The duration after which documents should expire, based on the ttl_field timestamp (optional).
	// Uses Go duration format (e.g., '24h', '7d', '168h').
	TtlDuration string `json:"ttl_duration,omitempty,omitzero"`

	// TtlField The field containing the timestamp for TTL expiration (optional).
	// Defaults to "_timestamp" if ttl_duration is specified but ttl_field is not.
	TtlField string `json:"ttl_field,omitempty,omitzero"`

	// Version Version of the schema. Used for migrations.
	Version uint32 `json:"version,omitempty,omitzero"`
}

// TemplateFieldMapping Field mapping to apply when a dynamic template matches
type TemplateFieldMapping struct {
	// Analyzer Analyzer name (e.g., "standard", "keyword", "en", "html_analyzer").
	// Used for text fields to control tokenization and normalization.
	Analyzer string `json:"analyzer,omitempty,omitzero"`

	// IncludeInAll Whether to include in the _all field for cross-field search
	IncludeInAll bool `json:"include_in_all,omitempty,omitzero"`

	// Index Whether to index the field (default true)
	Index bool `json:"index,omitempty,omitzero"`

	// MissingNullPolicy Missing/null sort policy for this mapped field. The current production
	// policy rejects missing or null native sort values so sorted cursors
	// remain replayable JSON scalar tuples.
	MissingNullPolicy TemplateFieldMappingMissingNullPolicy `json:"missing_null_policy,omitempty,omitzero"`

	// Sortable Whether this scalar field can be used in order_by. When true,
	// Antfly derives the internal typed doc-value structures required
	// for exact sorting; users should not configure doc_values directly.
	Sortable bool `json:"sortable,omitempty,omitzero"`

	// Store Whether to store the field value (default false)
	Store bool `json:"store,omitempty,omitzero"`

	// Type Field type annotations for schema fields
	Type AntflyType `json:"type,omitempty,omitzero"`
}

// TemplateFieldMappingMissingNullPolicy Missing/null sort policy for this mapped field. The current production
// policy rejects missing or null native sort values so sorted cursors
// remain replayable JSON scalar tuples.
type TemplateFieldMappingMissingNullPolicy string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RYX2/kthH/KgO2gH2GoktyRVu4TwdcGlzR9A49p3moCoErjlY8UyRLjmwrgb97MSS1",
	"q/Vq09yLvaLI+T+/31C/iM6N3lm0FMXtLyJ2A44y/XxrqTfz3eyRnxTGLmhP2llxK/6q0Sig2SNIax1J",
	"Xo/QuwBZAvS8I4pKoJ1GcftvQfhEohIDjUZU4h7nRxeUqISdRgy6E5XYOWdQWlEJJQlJjygqsUfnnbaU",
	"f8ZBel7FcYdKabvnY8btRCWMtveiEhFl6IZWxnZ2U8sWiv9UIv2/FZECn3muxDvXTSNa+pSsPXfwHfba",
	"YgQaECKFqaMpILgeJKhyNLkvKuGD8xhIYzwT81LqW1g9szQWfyKvFhvGxoORUinNZ6X5uNJKYcLqTNWD",
	"NFrB3z59+AdkL0GxU9ruT9RexaODdWPvBh1BR5giKiAH2vYYQFuFT3wyTAYjSKtygpPNsW7s0Wy3+4wd",
	"iefns5VKvJutHHV3h6M3kvCyR700ccMl1p6KbJTeszkqC5TGzKCQsCMslsUaFjURZEDoBuzuUYG24ILC",
	"0Fj2giPR6xAJRkndkIJTjl3Fg5oSj+znab7LFv75+4C9uBW/e31sqdeln14vtqTG+aGcea5E0npeKN8b",
	"twMviTDY5HCOtpUjwrWRkfjlAGiQU/iqbuynyXsXKMJNys7NDTxqozoZOBLfPcnRG7yFRty03IiNyP5i",
	"hEaQJoNluYJG7Jyay+M6scd6TEfb4nnusQ2EMIQBdqu8pFIsTbOgQhGaYGCH4QwFRLWUz1YXczzOVX/w",
	"uaBAK7Ske40hxZBzvSQXrqeI/WTSC4W7ab/Xdv9qy1uOdPtb85TqaTIGlCP2mQ/XcEzOTSnfUmvjZEh7",
	"gxBxz5nkVlola0SSSpKsb25OMnZYlxMNLuS0HRZJ7mPtgx5lmC+lMDk12QtufUzF9dSZKTJQFQdreN+D",
	"poMdB19ZWHUaXh0h3mvvUW0i2kXN371U+qL6X9hwWetJHHmx5RA+usmo7JnCAhRg9D0um2jQcTtmW3h2",
	"J3cGL1HICegmwGdXJBAfgkdNwzH9JxwQN0ill5OhC632Lr/NdEyOoQr64MYTmG8zUm8l47BlRf7bsPzr",
	"GPeCU5/P8XuUPrEeG8rZjGwuDajDMQKfo7NliFibewx6wfx2yfo57Yp/Jpb6zUTx04B2TeydsyQ1zzNp",
	"Q2NpkATK2SuCQT4g4JM3uktlmMRnRiw61qyBlpOtqkOJJi5qLD5IM0la0RFHgg0Lo7YIg3sEGlw81Ggc",
	"UuXuMFPxwkWacPz/eXnBusdKliHImZ/R9i50mIvkPJ4/DUhDtrHshBKSHLEI47RQKDiLy2jjg3vQCtWL",
	"+q4b+76HzPErGdatWFjaOdfJozaG/ZZdh54jtpsobT0JRHFoIQ92kUyrpiC3J7E7bo3yFmTPVPU46G5Y",
	"mVNCjk9eB6xgJ3kicjYjDpm2DEB6xEhy9HDtCu8wHf8YMcL37qijd2GUBNdY7+sKrr79w3BVwdWfFP/9",
	"5o9/Hq5e1dtIfVC17US2olTsMtsdjeIeuLv7e/YiW3JiZ8GO1IiNaA8HGwG6h3UME7h67JhPcxKOQdAp",
	"eRcceMAQN3Pwr/xiKZZcrjX8yHFOvav3WXXCgRxAcSsmbenNt0dN2hLuMVxA6K2568vGznzXWZqaHEjv",
	"zQyPBTRK0x84qDDTGYZLK838M4aNW0F5U8a7XCGNiCStkkFldi8XpvyANv/ny1S7CG5EKbwcPR7gFvQg",
	"lyokOAPk7tHqn0vhWwWW42rKyoUUapsIs9W2lcasGOlCyFZ4UY4yznGS+XypWTayCy7Gr/Jzvrlt9nJq",
	"9RO1W1eeE60Kn8pwz7Kv1cKRYcJXmzpGHSOPs3YypvXO6G4+0XjYEPBzog/xUv8PecNrlgDRBYIspgyG",
	"Ot8nFt6pgdu3m0JgXPTBqaljQY0tp7KeCEUvuABJspWkHzArYBrBCNGlR1QsL7oQGxtwlNpCQG/knCaO",
	"NH7HThoZgCZvlnvbMoqf+bc1cbMalvYFNcCOF7UFrKRlQE83zIX+2t1ceDhltrH56wMoDPqhzJrc6IHn",
	"erYqccpXyf/j/TVCwP9OOqBqmKYAn2RHKTTa7v/CGsMB15lCOmd7veebvXJdW4KpdMCOzHyJWCK5gF/U",
	"A+nEqhqz1YeaTMe3i3IZ+H6N3lffaTYg8Dm1T+825tNBBlTL95rEtcdZtXwAkKlBIatYvg702pStJTEd",
	"u7eSE/N0wLfugD0GtB1TxgwuReSDR/v24/vEJsu3A76CJihMWS+j810Zhg8MIr6pv66/5sA4j1Z6LW7F",
	"m/rr+o3IN5oobrlFnv8XAAD//+ltpurWEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
