// Package extracting provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extracting

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly/go/pkg/generating"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExtractionProvider.
const (
	Antfly  ExtractionProvider = "antfly"
	Mock    ExtractionProvider = "mock"
	Openai  ExtractionProvider = "openai"
	Pioneer ExtractionProvider = "pioneer"
)

// Valid indicates whether the value is a known member of the ExtractionProvider enum.
func (e ExtractionProvider) Valid() bool {
	switch e {
	case Antfly:
		return true
	case Mock:
		return true
	case Openai:
		return true
	case Pioneer:
		return true
	default:
		return false
	}
}

// Defines values for ExtractionResponseObject.
const (
	Extraction ExtractionResponseObject = "extraction"
)

// Valid indicates whether the value is a known member of the ExtractionResponseObject enum.
func (e ExtractionResponseObject) Valid() bool {
	switch e {
	case Extraction:
		return true
	default:
		return false
	}
}

// Defines values for ExtractionStructureField1Type.
const (
	Array  ExtractionStructureField1Type = "array"
	List   ExtractionStructureField1Type = "list"
	Str    ExtractionStructureField1Type = "str"
	String ExtractionStructureField1Type = "string"
)

// Valid indicates whether the value is a known member of the ExtractionStructureField1Type enum.
func (e ExtractionStructureField1Type) Valid() bool {
	switch e {
	case Array:
		return true
	case List:
		return true
	case Str:
		return true
	case String:
		return true
	default:
		return false
	}
}

// ExtractionClassification defines model for ExtractionClassification.
type ExtractionClassification struct {
	Label                string                 `json:"label"`
	Name                 string                 `json:"name"`
	Score                *float32               `json:"score,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ExtractionClassificationSchema defines model for ExtractionClassificationSchema.
type ExtractionClassificationSchema struct {
	Labels     []string `json:"labels"`
	MultiLabel *bool    `json:"multi_label,omitempty"`
	Name       string   `json:"name"`
}

// ExtractionConfig defines model for ExtractionConfig.
type ExtractionConfig struct {
	ApiKey      *string            `json:"api_key,omitempty"`
	ApiUrl      *string            `json:"api_url,omitempty"`
	BearerToken *string            `json:"bearer_token,omitempty"`
	Model       *string            `json:"model,omitempty"`
	Options     *ExtractionOptions `json:"options,omitempty"`
	Provider    ExtractionProvider `json:"provider"`

	// Schema Selects one extraction operation family per request. Entity labels may
	// accompany relation schemas so relation extraction can return its
	// participating entities in the same response.
	Schema *ExtractionSchema `json:"schema,omitempty"`
	Url    *string           `json:"url,omitempty"`
}

// ExtractionEntity defines model for ExtractionEntity.
type ExtractionEntity struct {
	End   *int     `json:"end,omitempty"`
	Label string   `json:"label"`
	Score *float32 `json:"score,omitempty"`
	Start *int     `json:"start,omitempty"`
	Text  string   `json:"text"`
}

// ExtractionInput defines model for ExtractionInput.
type ExtractionInput struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts: [{"type": "text", "text": "Hello"}]
	Content  externalRef0.ChatMessageContent `json:"content"`
	Id       *string                         `json:"id,omitempty"`
	Metadata *map[string]interface{}         `json:"metadata,omitempty"`
	Tokens   *[]ExtractionToken              `json:"tokens,omitempty"`
}

// ExtractionObject defines model for ExtractionObject.
type ExtractionObject struct {
	Classifications      *[]ExtractionClassification `json:"classifications,omitempty"`
	Entities             *[]ExtractionEntity         `json:"entities,omitempty"`
	Id                   *string                     `json:"id,omitempty"`
	Relations            *[]ExtractionRelation       `json:"relations,omitempty"`
	Structures           *map[string]interface{}     `json:"structures,omitempty"`
	AdditionalProperties map[string]interface{}      `json:"-"`
}

// ExtractionOptions defines model for ExtractionOptions.
type ExtractionOptions struct {
	FlatNer           *bool                    `json:"flat_ner,omitempty"`
	IncludeConfidence *bool                    `json:"include_confidence,omitempty"`
	IncludeSpans      *bool                    `json:"include_spans,omitempty"`
	Reader            *ExtractionReaderOptions `json:"reader,omitempty"`

	// Resolver Optional cross-input entity and relation deduplication.
	Resolver             *ExtractionResolverOptions `json:"resolver,omitempty"`
	Threshold            *float32                   `json:"threshold,omitempty"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// ExtractionProvider defines model for ExtractionProvider.
type ExtractionProvider string

// ExtractionReaderOptions defines model for ExtractionReaderOptions.
type ExtractionReaderOptions struct {
	ApiUrl               *string                `json:"api_url,omitempty"`
	Model                *string                `json:"model,omitempty"`
	Provider             *string                `json:"provider,omitempty"`
	Url                  *string                `json:"url,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ExtractionRelation defines model for ExtractionRelation.
type ExtractionRelation struct {
	Score                *float32                    `json:"score,omitempty"`
	Source               *ExtractionRelationEndpoint `json:"source,omitempty"`
	Target               *ExtractionRelationEndpoint `json:"target,omitempty"`
	Type                 string                      `json:"type"`
	AdditionalProperties map[string]interface{}      `json:"-"`
}

// ExtractionRelationEndpoint defines model for ExtractionRelationEndpoint.
type ExtractionRelationEndpoint struct {
	EntityIndex          *int                   `json:"entity_index,omitempty"`
	Id                   *string                `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ExtractionRelationSchema Optional source and target labels constrain relation endpoints. A target requires a source.
type ExtractionRelationSchema struct {
	Source *string `json:"source,omitempty"`
	Target *string `json:"target,omitempty"`
	Type   string  `json:"type"`
}

// ExtractionRequest defines model for ExtractionRequest.
type ExtractionRequest struct {
	Inputs  []ExtractionInput  `json:"inputs"`
	Model   string             `json:"model"`
	Options *ExtractionOptions `json:"options,omitempty"`

	// Schema Selects one extraction operation family per request. Entity labels may
	// accompany relation schemas so relation extraction can return its
	// participating entities in the same response.
	Schema ExtractionSchema `json:"schema"`
}

// ExtractionResolverOptions Optional cross-input entity and relation deduplication.
type ExtractionResolverOptions struct {
	DeduplicateRelations  *bool    `json:"deduplicate_relations,omitempty"`
	MinEntityConfidence   *float32 `json:"min_entity_confidence,omitempty"`
	MinRelationConfidence *float32 `json:"min_relation_confidence,omitempty"`
	SimilarityThreshold   *float32 `json:"similarity_threshold,omitempty"`
	TrackProvenance       *bool    `json:"track_provenance,omitempty"`
	TypeMustMatch         *bool    `json:"type_must_match,omitempty"`
}

// ExtractionResponse defines model for ExtractionResponse.
type ExtractionResponse struct {
	Data   []ExtractionObject       `json:"data"`
	Model  string                   `json:"model"`
	Object ExtractionResponseObject `json:"object"`
	Usage  *map[string]interface{}  `json:"usage,omitempty"`
}

// ExtractionResponseObject defines model for ExtractionResponse.Object.
type ExtractionResponseObject string

// ExtractionSchema Selects one extraction operation family per request. Entity labels may
// accompany relation schemas so relation extraction can return its
// participating entities in the same response.
type ExtractionSchema struct {
	Classifications      *[]ExtractionClassificationSchema     `json:"classifications,omitempty"`
	Entities             *[]string                             `json:"entities,omitempty"`
	Relations            *[]ExtractionRelationSchema           `json:"relations,omitempty"`
	Structures           *map[string]ExtractionStructureSchema `json:"structures,omitempty"`
	AdditionalProperties map[string]interface{}                `json:"-"`
}

// ExtractionStructureField defines model for ExtractionStructureField.
type ExtractionStructureField struct {
	union json.RawMessage
}

// ExtractionStructureField0 defines model for ExtractionStructureField.0.
type ExtractionStructureField0 = string

// ExtractionStructureField1 defines model for ExtractionStructureField.1.
type ExtractionStructureField1 struct {
	Enum                 *[]string                      `json:"enum,omitempty"`
	Type                 *ExtractionStructureField1Type `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}         `json:"-"`
}

// ExtractionStructureField1Type defines model for ExtractionStructureField.1.Type.
type ExtractionStructureField1Type string

// ExtractionStructureSchema defines model for ExtractionStructureSchema.
type ExtractionStructureSchema struct {
	Fields               map[string]ExtractionStructureField `json:"fields"`
	AdditionalProperties map[string]interface{}              `json:"-"`
}

// ExtractionToken defines model for ExtractionToken.
type ExtractionToken struct {
	Box  *[]int `json:"box,omitempty"`
	Text string `json:"text"`
}

// Getter for additional properties for ExtractionClassification. Returns the specified
// element and whether it was found
func (a ExtractionClassification) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionClassification
func (a *ExtractionClassification) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionClassification to handle AdditionalProperties
func (a *ExtractionClassification) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["label"]; found {
		err = json.Unmarshal(raw, &a.Label)
		if err != nil {
			return fmt.Errorf("error reading 'label': %w", err)
		}
		delete(object, "label")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["score"]; found {
		err = json.Unmarshal(raw, &a.Score)
		if err != nil {
			return fmt.Errorf("error reading 'score': %w", err)
		}
		delete(object, "score")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionClassification to handle AdditionalProperties
func (a ExtractionClassification) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["label"], err = json.Marshal(a.Label)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'label': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Score != nil {
		object["score"], err = json.Marshal(a.Score)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'score': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionObject. Returns the specified
// element and whether it was found
func (a ExtractionObject) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionObject
func (a *ExtractionObject) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionObject to handle AdditionalProperties
func (a *ExtractionObject) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["classifications"]; found {
		err = json.Unmarshal(raw, &a.Classifications)
		if err != nil {
			return fmt.Errorf("error reading 'classifications': %w", err)
		}
		delete(object, "classifications")
	}

	if raw, found := object["entities"]; found {
		err = json.Unmarshal(raw, &a.Entities)
		if err != nil {
			return fmt.Errorf("error reading 'entities': %w", err)
		}
		delete(object, "entities")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["relations"]; found {
		err = json.Unmarshal(raw, &a.Relations)
		if err != nil {
			return fmt.Errorf("error reading 'relations': %w", err)
		}
		delete(object, "relations")
	}

	if raw, found := object["structures"]; found {
		err = json.Unmarshal(raw, &a.Structures)
		if err != nil {
			return fmt.Errorf("error reading 'structures': %w", err)
		}
		delete(object, "structures")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionObject to handle AdditionalProperties
func (a ExtractionObject) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Classifications != nil {
		object["classifications"], err = json.Marshal(a.Classifications)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'classifications': %w", err)
		}
	}

	if a.Entities != nil {
		object["entities"], err = json.Marshal(a.Entities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'entities': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Relations != nil {
		object["relations"], err = json.Marshal(a.Relations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relations': %w", err)
		}
	}

	if a.Structures != nil {
		object["structures"], err = json.Marshal(a.Structures)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'structures': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionOptions. Returns the specified
// element and whether it was found
func (a ExtractionOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionOptions
func (a *ExtractionOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionOptions to handle AdditionalProperties
func (a *ExtractionOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["flat_ner"]; found {
		err = json.Unmarshal(raw, &a.FlatNer)
		if err != nil {
			return fmt.Errorf("error reading 'flat_ner': %w", err)
		}
		delete(object, "flat_ner")
	}

	if raw, found := object["include_confidence"]; found {
		err = json.Unmarshal(raw, &a.IncludeConfidence)
		if err != nil {
			return fmt.Errorf("error reading 'include_confidence': %w", err)
		}
		delete(object, "include_confidence")
	}

	if raw, found := object["include_spans"]; found {
		err = json.Unmarshal(raw, &a.IncludeSpans)
		if err != nil {
			return fmt.Errorf("error reading 'include_spans': %w", err)
		}
		delete(object, "include_spans")
	}

	if raw, found := object["reader"]; found {
		err = json.Unmarshal(raw, &a.Reader)
		if err != nil {
			return fmt.Errorf("error reading 'reader': %w", err)
		}
		delete(object, "reader")
	}

	if raw, found := object["resolver"]; found {
		err = json.Unmarshal(raw, &a.Resolver)
		if err != nil {
			return fmt.Errorf("error reading 'resolver': %w", err)
		}
		delete(object, "resolver")
	}

	if raw, found := object["threshold"]; found {
		err = json.Unmarshal(raw, &a.Threshold)
		if err != nil {
			return fmt.Errorf("error reading 'threshold': %w", err)
		}
		delete(object, "threshold")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionOptions to handle AdditionalProperties
func (a ExtractionOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FlatNer != nil {
		object["flat_ner"], err = json.Marshal(a.FlatNer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'flat_ner': %w", err)
		}
	}

	if a.IncludeConfidence != nil {
		object["include_confidence"], err = json.Marshal(a.IncludeConfidence)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'include_confidence': %w", err)
		}
	}

	if a.IncludeSpans != nil {
		object["include_spans"], err = json.Marshal(a.IncludeSpans)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'include_spans': %w", err)
		}
	}

	if a.Reader != nil {
		object["reader"], err = json.Marshal(a.Reader)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reader': %w", err)
		}
	}

	if a.Resolver != nil {
		object["resolver"], err = json.Marshal(a.Resolver)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resolver': %w", err)
		}
	}

	if a.Threshold != nil {
		object["threshold"], err = json.Marshal(a.Threshold)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'threshold': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionReaderOptions. Returns the specified
// element and whether it was found
func (a ExtractionReaderOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionReaderOptions
func (a *ExtractionReaderOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionReaderOptions to handle AdditionalProperties
func (a *ExtractionReaderOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_url"]; found {
		err = json.Unmarshal(raw, &a.ApiUrl)
		if err != nil {
			return fmt.Errorf("error reading 'api_url': %w", err)
		}
		delete(object, "api_url")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionReaderOptions to handle AdditionalProperties
func (a ExtractionReaderOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ApiUrl != nil {
		object["api_url"], err = json.Marshal(a.ApiUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'api_url': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Url != nil {
		object["url"], err = json.Marshal(a.Url)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'url': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionRelation. Returns the specified
// element and whether it was found
func (a ExtractionRelation) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionRelation
func (a *ExtractionRelation) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionRelation to handle AdditionalProperties
func (a *ExtractionRelation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["score"]; found {
		err = json.Unmarshal(raw, &a.Score)
		if err != nil {
			return fmt.Errorf("error reading 'score': %w", err)
		}
		delete(object, "score")
	}

	if raw, found := object["source"]; found {
		err = json.Unmarshal(raw, &a.Source)
		if err != nil {
			return fmt.Errorf("error reading 'source': %w", err)
		}
		delete(object, "source")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionRelation to handle AdditionalProperties
func (a ExtractionRelation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Score != nil {
		object["score"], err = json.Marshal(a.Score)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'score': %w", err)
		}
	}

	if a.Source != nil {
		object["source"], err = json.Marshal(a.Source)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source': %w", err)
		}
	}

	if a.Target != nil {
		object["target"], err = json.Marshal(a.Target)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'target': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionRelationEndpoint. Returns the specified
// element and whether it was found
func (a ExtractionRelationEndpoint) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionRelationEndpoint
func (a *ExtractionRelationEndpoint) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionRelationEndpoint to handle AdditionalProperties
func (a *ExtractionRelationEndpoint) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entity_index"]; found {
		err = json.Unmarshal(raw, &a.EntityIndex)
		if err != nil {
			return fmt.Errorf("error reading 'entity_index': %w", err)
		}
		delete(object, "entity_index")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionRelationEndpoint to handle AdditionalProperties
func (a ExtractionRelationEndpoint) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.EntityIndex != nil {
		object["entity_index"], err = json.Marshal(a.EntityIndex)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'entity_index': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionSchema. Returns the specified
// element and whether it was found
func (a ExtractionSchema) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionSchema
func (a *ExtractionSchema) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionSchema to handle AdditionalProperties
func (a *ExtractionSchema) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["classifications"]; found {
		err = json.Unmarshal(raw, &a.Classifications)
		if err != nil {
			return fmt.Errorf("error reading 'classifications': %w", err)
		}
		delete(object, "classifications")
	}

	if raw, found := object["entities"]; found {
		err = json.Unmarshal(raw, &a.Entities)
		if err != nil {
			return fmt.Errorf("error reading 'entities': %w", err)
		}
		delete(object, "entities")
	}

	if raw, found := object["relations"]; found {
		err = json.Unmarshal(raw, &a.Relations)
		if err != nil {
			return fmt.Errorf("error reading 'relations': %w", err)
		}
		delete(object, "relations")
	}

	if raw, found := object["structures"]; found {
		err = json.Unmarshal(raw, &a.Structures)
		if err != nil {
			return fmt.Errorf("error reading 'structures': %w", err)
		}
		delete(object, "structures")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionSchema to handle AdditionalProperties
func (a ExtractionSchema) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Classifications != nil {
		object["classifications"], err = json.Marshal(a.Classifications)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'classifications': %w", err)
		}
	}

	if a.Entities != nil {
		object["entities"], err = json.Marshal(a.Entities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'entities': %w", err)
		}
	}

	if a.Relations != nil {
		object["relations"], err = json.Marshal(a.Relations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relations': %w", err)
		}
	}

	if a.Structures != nil {
		object["structures"], err = json.Marshal(a.Structures)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'structures': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionStructureField1. Returns the specified
// element and whether it was found
func (a ExtractionStructureField1) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionStructureField1
func (a *ExtractionStructureField1) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionStructureField1 to handle AdditionalProperties
func (a *ExtractionStructureField1) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["enum"]; found {
		err = json.Unmarshal(raw, &a.Enum)
		if err != nil {
			return fmt.Errorf("error reading 'enum': %w", err)
		}
		delete(object, "enum")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionStructureField1 to handle AdditionalProperties
func (a ExtractionStructureField1) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Enum != nil {
		object["enum"], err = json.Marshal(a.Enum)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enum': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExtractionStructureSchema. Returns the specified
// element and whether it was found
func (a ExtractionStructureSchema) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExtractionStructureSchema
func (a *ExtractionStructureSchema) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExtractionStructureSchema to handle AdditionalProperties
func (a *ExtractionStructureSchema) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExtractionStructureSchema to handle AdditionalProperties
func (a ExtractionStructureSchema) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsExtractionStructureField0 returns the union data inside the ExtractionStructureField as a ExtractionStructureField0
func (t ExtractionStructureField) AsExtractionStructureField0() (ExtractionStructureField0, error) {
	var body ExtractionStructureField0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExtractionStructureField0 overwrites any union data inside the ExtractionStructureField as the provided ExtractionStructureField0
func (t *ExtractionStructureField) FromExtractionStructureField0(v ExtractionStructureField0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExtractionStructureField0 performs a merge with any union data inside the ExtractionStructureField, using the provided ExtractionStructureField0
func (t *ExtractionStructureField) MergeExtractionStructureField0(v ExtractionStructureField0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExtractionStructureField1 returns the union data inside the ExtractionStructureField as a ExtractionStructureField1
func (t ExtractionStructureField) AsExtractionStructureField1() (ExtractionStructureField1, error) {
	var body ExtractionStructureField1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExtractionStructureField1 overwrites any union data inside the ExtractionStructureField as the provided ExtractionStructureField1
func (t *ExtractionStructureField) FromExtractionStructureField1(v ExtractionStructureField1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExtractionStructureField1 performs a merge with any union data inside the ExtractionStructureField, using the provided ExtractionStructureField1
func (t *ExtractionStructureField) MergeExtractionStructureField1(v ExtractionStructureField1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExtractionStructureField) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExtractionStructureField) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFlbb9u+Ff8qBLeHDpCVZO2GwXsY0iLbjLVIkKR7qQ2Blo5tNhKpklRiI/B3/4MX3SxKlp30TTHJw3N+",
	"v3NlXnHMs5wzYEri6SuW8QYyYj5vtkqQWFHOvqRESrqiMdF/6TWSJFR/k/RO8ByEoiDxVIkCApw3fnnF",
	"KVlCqj/ULgc8xVIJytZ4H2BGMvAuyJgLs7LiIiMKT/Eq5UThoNzKimwJAu/3ARbwq6ACEjz9YQUG7sZF",
	"tZsvf0KstOA+ix6M0fpGj+7miyrIpFdZ9wMRguz031mRKhpVViewIkWq8HRFUgnV9iXnKRA2AMOAbfKY",
	"cZyt6LprDslp9AQ7rxl6rRB+opZABIhI8Sdg3g0ZT3o45rlWyNz+ZwErPMV/uqgd7sJ520Wt+607sDd+",
	"9EwTEOMP35UnjBOVnI4763xgH2A/DAd8VMoNU3HDFFW7LhXAksYdlClYW7X7w2V0VARYKiKUX76CrTpu",
	"ndXC7R62cMbyQnUNjDlTwNQx/GUOsYx4Dkw7oNwQAUm0BgaCKMrW0ZcNUd9ASrKGL07iPsA08bshKJIQ",
	"RY4lqI41xrPbcT7OaR5NSHSywAGaJRbDQN7a305KrnErjZ1jwUFq9yQ00C7s7jtRuPN+j9AeBgWkZ1ty",
	"7876rpNKFLEqhMuD431jP0xZnd3Gc7ZKiYqYTWvdakBZnBYJRLHO4QmwGIb3yZww6d8igJyUPe/N/kYC",
	"FiB5+nyaCHuiIURtBMgNT5ORBX0A7rtGQQBWZDq2CFOrdIcDnFPOAATWNQcYoViXpfipEXS1m/XZfBKP",
	"QxWzvyA2i1pnsbfyDIBSuf1Jyp9STHghrBeeFoc3LMk5tQlbEbEG9UYZRrFjlcusLkYhVgk/CTmTDncR",
	"ZQls/SXWm9vGkVg3ognIWNDcMoutg5IUWTIQYQmymCLbEaKYM6kEoQyVORSBs0+G6Lrc7aCSiDhRIe64",
	"RsV3RtlXYGu1wdMrTxTVpB7b6Jgb3HYOj78KkJ7eg+qW5JwSYnsZHb+UzezRK0+HXwb3EbPf0vue270e",
	"oGhVDUpEKrnHgG1n8X53jAWXcmKkIxsYxjUrF0wgKfLUNRddV6uXIWqV/mpqahXlRm3LKItcJLYrZXXy",
	"MujmtoxsaabrxpWRYL8vPTlPiy8V+i0XSJrRlAitf6tA1tLDf/ztLRdoLp8iXW2AkUPV+1DVv0RZIVWU",
	"ERVvRpw5ltZkzpmEboiWbfqJAXpbt+x9QdkNw6qvLnsGqOR5u4NCTxun94nNuHM/B1UAGnuHo67O/UP3",
	"tgPxAVKIlUScAaqtQvqQDcAVyWi6QzkIk/pBqhDZrrwsHBnZzRmJNeyE7erQdeAjyRsVpb4iJrrSqEIw",
	"RJWcs5wIRWOam7ENlTMDogypDSBJMkDCeUM4Z/h3DzL1ND9qnBlVwGoZ7zGm9Gs4ZlgZXRdKWZ3rxk04",
	"1fl/U7AZijO4XeHpj26kndZF6VAcz0BdkP/aBazsL8r4lkqPAe5wgFMqdSja7YvgeGe28EMwLkAPhj0N",
	"23vyaHmwiDQFXR1LSU6T4Rz0WD7xta1Y8q3vEbTR82Zk6/j51CTrk4esUQ9QvQ9PZzwYddoXt47cu0yI",
	"Hoo850JJpF44sjVXTudsgh5olqeArJJTNMf/hTTlAdrwF0QEoB0v/jXHeue1tg/xVSkU6YQop+jH69wY",
	"Mcf6uDZrjoPqqxI5x/uFSYt1eB1kequJPlbpjQNPDLaPVWqZZ+mMJ7ppa2qohYzKYEeBt1LviPDU50WA",
	"t5M1n1TqJj8lZ+E9eXFc4MaGCc00G1oh+zZe7tdVg+gMgYHFPKFsfWF+3o/xi4Z6HYe4bmGiPaCJl21v",
	"P2joA0Qz7Tnf778GiAtEWUoZoAwSSv4Stuh7C5aPsFVtPN8mb6aV/n7/9T1lftM2twQuRtBQatLlYFYC",
	"q3HV7RL6fj/rjgzuiaR99uAU+qC/poaqi5yt/7kkEv7+KQjD0JAEW6KDCU+xfx/9/+fb+5fL//1nzcPQ",
	"E2UHuUqrdE6q8rHSA0vpnpSh2xzY9Wxi+jVFlym4hNWFythVPlG9h/v4am19yWLUSB94T4wHreN2XcRs",
	"TC4pI2JnQ7PC7wMpEspdFAcIVGw9wj+ctOV+Ns4xMakHklK+3qslVJPacqcAezuYDKISvYN6NPt2g/SS",
	"0+/ihTw7HS/WdFV+5mzdULn3laVkxlg+mhVjc1PLc8g5zFsdSx8b5cubZrtklP1Cv6BRaBw0FMNg9HQf",
	"e/PuvuJddR4MFG5mmiSCPkNrWnKzl3scsWOQYdzUX0WVyUbX5i0bXc9Q3ZGhB/cP+QA/g5D2uqvwMry0",
	"T0yGCjzFH8PL8KMrkBq3/f6PAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
