#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate canonical normalization data from pinned CPython Unicode 15.0.0."""

import hashlib
import sys
import unicodedata as ud
from pathlib import Path as LicensePath

# Resolve the shared license renderer independently of invocation directory.
repository_root = next(
    parent
    for parent in LicensePath(__file__).resolve().parents
    if (parent / "scripts/generated_source_licenses.py").is_file()
)
sys.path.insert(0, str(repository_root / "scripts"))
from pathlib import Path

from generated_source_licenses import unicode_source_header

if ud.unidata_version != "15.0.0":
    raise SystemExit(f"expected Unicode 15.0.0, got {ud.unidata_version}")

decompositions, combining, compositions = [], [], []
for cp in range(0x110000):
    ch = chr(cp)
    if ud.combining(ch):
        combining.append((cp, ud.combining(ch)))
    raw = ud.decomposition(ch)
    if raw and not raw.startswith("<"):
        parts = [int(value, 16) for value in raw.split()]
        if not 1 <= len(parts) <= 2:
            raise SystemExit(f"unexpected canonical decomposition U+{cp:04X}")
        decompositions.append((cp, parts[0], parts[1] if len(parts) == 2 else 0))
        if len(parts) == 2 and ud.normalize("NFC", "".join(map(chr, parts))) == ch:
            compositions.append(((parts[0] << 21) | parts[1], cp))

lines = [
    "// Generated by tools/generate_unicode_nfc.py; do not edit by hand.",
    "// Canonical data: Unicode 15.0.0, CPython unicodedata. Hangul is algorithmic.",
    'pub const unicode_version = "15.0.0";',
    "pub const Decomposition = struct { cp: u21, first: u21, second: u21 };",
    "pub const Combining = struct { cp: u21, value: u8 };",
    "pub const Composition = struct { pair: u64, cp: u21 };",
    "pub const decompositions = [_]Decomposition{",
]
lines += [
    f"    .{{ .cp = 0x{cp:x}, .first = 0x{a:x}, .second = 0x{b:x} }},"
    for cp, a, b in decompositions
]
lines += ["};", "pub const combining = [_]Combining{"]
lines += [f"    .{{ .cp = 0x{cp:x}, .value = {value} }}," for cp, value in combining]
lines += ["};", "pub const compositions = [_]Composition{"]
lines += [
    f"    .{{ .pair = 0x{pair:x}, .cp = 0x{cp:x} }},"
    for pair, cp in sorted(compositions)
]
lines += ["};", ""]
output = Path(__file__).resolve().parents[1] / "src" / "unicode_nfc_data.zig"
data = (unicode_source_header(__file__) + "\n".join(lines)).encode()
output.write_bytes(data)
print(f"{output}: {len(data)} bytes sha256={hashlib.sha256(data).hexdigest()}")
