#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate Unicode 16 extended-grapheme tables and conformance vectors.

Inputs are the unmodified Unicode UCD files (Unicode-3.0 license).
Download URLs and digests are recorded in SOURCES. Pass their local directory;
no network access or third-party Python dependencies are needed by generation.
"""

import hashlib
import sys
from pathlib import Path

SOURCES = {
    "GraphemeBreakProperty": (
        "auxiliary/GraphemeBreakProperty.txt",
        "c29360bd6f7132811d701d29069541e827eb44bfc4c8fbde8c370d6982689dc1",
    ),
    "emoji-data": (
        "emoji/emoji-data.txt",
        "f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a",
    ),
    "DerivedCoreProperties": (
        "DerivedCoreProperties.txt",
        "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd",
    ),
    "GraphemeBreakTest": (
        "auxiliary/GraphemeBreakTest.txt",
        "ee2b9354d270ac061b29f09662cafea06341d77e704b8cc6bd72aaeeda363cb5",
    ),
}
# https://www.unicode.org/Public/16.0.0/ucd/<relative path>
CATEGORIES = [
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "Regional_Indicator",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
]
root = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1])
flags = bytearray(0x110000)
for name, (relative, digest) in SOURCES.items():
    raw = (source / (name + "-16.txt")).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise SystemExit(f"{name}: source digest mismatch")
    if name == "GraphemeBreakTest":
        tests = []
        for line in raw.decode().splitlines():
            body = line.split("#")[0].strip()
            if body:
                tests.append(body)
        (root / "src/testdata/grapheme-break-16.txt").write_text(
            "\n".join(tests) + "\n"
        )
        continue
    for line in raw.decode().splitlines():
        body = line.split("#")[0].strip()
        if not body:
            continue
        fields = [p.strip() for p in body.split(";")]
        if name == "GraphemeBreakProperty":
            value = CATEGORIES.index(fields[1])
        elif name == "emoji-data":
            if fields[1] != "Extended_Pictographic":
                continue
            value = 16
        else:
            if fields[1] != "InCB":
                continue
            value = {"Consonant": 32, "Linker": 64, "Extend": 128}.get(fields[2], 0)
            if not value:
                continue
        bounds = fields[0].split("..")
        lo, hi = int(bounds[0], 16), int(bounds[-1], 16)
        for cp in range(lo, hi + 1):
            flags[cp] |= value
header = (root / "src/grapheme.zig").read_text().split("//!")[0].rstrip().splitlines()
lines = header + [
    "",
    "// Generated by tools/generate_graphemes.py from Unicode 16.0.0 UCD.",
    "// Unicode data copyright Unicode, Inc.; Unicode-3.0 license in testdata/UNICODE-LICENSE.txt.",
    "pub const Range = struct { lo: u21, hi: u21, flags: u8 };",
    "pub const ranges = [_]Range{",
]
i = 0
while i < len(flags):
    j = i + 1
    while j < len(flags) and flags[j] == flags[i]:
        j += 1
    if flags[i]:
        lines.append(
            f"    .{{ .lo = 0x{i:x}, .hi = 0x{j - 1:x}, .flags = {flags[i]} }},"
        )
    i = j
lines += ["};", ""]
(root / "src/grapheme_data.zig").write_text("\n".join(lines))
