#!/usr/bin/env python3
"""Packaging regression tests for Antfly C ABI artifacts."""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import json
import os
import re
import stat
import subprocess
import sys
import tarfile
import tempfile
import unittest
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGING_DIR = Path(__file__).resolve().parent


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load module spec for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


package_cli_release = load_module(
    "package_cli_release_for_cabi_test",
    PACKAGING_DIR / "package_cli_release.py",
)


def write_release_archive(
    root: Path,
    version: str,
    os_name: str,
    arch: str,
    variant: str | None = None,
) -> Path:
    stage = root / f"{os_name}-{arch}"
    (stage / "include").mkdir(parents=True)
    (stage / "lib").mkdir()
    (stage / "share" / "antfly").mkdir(parents=True)
    (stage / "completions").mkdir()

    antfly = stage / "antfly"
    antfly.write_text("#!/bin/sh\n")
    antfly.chmod(antfly.stat().st_mode | stat.S_IXUSR)

    (stage / "include" / "antfly.h").write_text("/* antfly header */\n")
    lib_name = "libantfly.dylib" if os_name == "Darwin" else "libantfly.so"
    (stage / "lib" / lib_name).write_text("antfly library\n")
    (stage / "share" / "antfly" / "asset.txt").write_text("asset\n")
    for shell in ("bash", "zsh", "fish"):
        (stage / "completions" / f"antfly.{shell}").write_text(f"{shell} completion\n")

    suffix = f"_{variant}" if variant else ""
    archive = root / f"antfly_{version}_{os_name}_{arch}{suffix}.tar.gz"
    with tarfile.open(archive, "w:gz") as tar:
        for child in stage.iterdir():
            tar.add(child, arcname=child.name)
    return archive


class CompletionPackagingTests(unittest.TestCase):
    def test_generated_completions_include_nested_commands(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output_dir = Path(raw) / "completions"
            subprocess.run(
                [str(REPO_ROOT / "scripts" / "completions.sh"), str(output_dir)],
                cwd=REPO_ROOT,
                check=True,
            )

            zsh = (output_dir / "antfly.zsh").read_text()
            bash = (output_dir / "antfly.bash").read_text()
            fish = (output_dir / "antfly.fish").read_text()
            self.assertIn("Generated by `antfly completion zsh`", zsh)
            self.assertIn('case "$words[2]" in', zsh)
            self.assertIn("inference) subcommands=(run embed classify generate chat", zsh)
            self.assertIn("completion) subcommands=(bash zsh fish)", zsh)
            self.assertIn("_describe 'subcommand' subcommands", zsh)
            self.assertIn('compgen -W "bash zsh fish"', bash)
            self.assertIn("__fish_seen_subcommand_from completion", fish)


class CAbiPackagingTests(unittest.TestCase):
    def test_linux_abi_release_contract_stays_consistent(self) -> None:
        installer = (REPO_ROOT / "scripts" / "install.sh").read_text()
        minimum_match = re.search(r'^ANTFLY_MIN_GLIBC="([0-9]+\.[0-9]+)"$', installer, re.MULTILINE)
        self.assertIsNotNone(minimum_match)
        minimum_glibc = minimum_match.group(1)

        release_workflow = (REPO_ROOT / ".github" / "workflows" / "antfly-release.yml").read_text()
        container_workflow = (REPO_ROOT / ".github" / "workflows" / "antfly-container.yml").read_text()
        dev_publish = (REPO_ROOT / "scripts" / "publish-zig-runtime-dev.sh").read_text()
        for source in (release_workflow, container_workflow, dev_publish):
            gnu_floors = set(re.findall(r"(?:x86_64|aarch64)-linux-gnu\.([0-9]+\.[0-9]+)", source))
            self.assertEqual(gnu_floors, {minimum_glibc})

        wheel_floor = minimum_glibc.replace(".", "_")
        gnu_platforms = [platform for platform in package_cli_release.PLATFORMS if platform.npm_libc == "glibc"]
        self.assertEqual(len(gnu_platforms), 2)
        for platform in gnu_platforms:
            self.assertTrue(platform.wheel_platform.startswith(f"manylinux_{wheel_floor}_"))

        npm_cli = json.loads((REPO_ROOT / "ts" / "packages" / "cli" / "package.json").read_text())
        self.assertEqual(npm_cli["engines"]["node"], ">=24.0")

        package_workflow = (REPO_ROOT / ".github" / "workflows" / "cli-package.yml").read_text()
        self.assertNotIn("workflow_dispatch:", package_workflow)
        self.assertNotIn('tags:\n      - "cli/v*"', package_workflow)
        self.assertNotIn("cli-linux-arm64-gnu", package_workflow)
        self.assertNotIn("cli-linux-x64-gnu", package_workflow)
        self.assertNotIn("npm publish", package_workflow)
        self.assertNotIn("gh-action-pypi-publish", package_workflow)
        self.assertNotIn("releases.antfly.io", package_workflow)
        self.assertIn("source_commit:", package_workflow)
        self.assertIn("antfly-cli-snapshot", package_workflow)
        self.assertIn("publish_npm_package.sh", release_workflow)
        self.assertIn("uses: ./.github/workflows/cli-package.yml", release_workflow)
        self.assertNotIn("workflow_dispatch:", release_workflow)
        self.assertIn("repository_dispatch:", release_workflow)
        self.assertIn("promote-cli-release", release_workflow)
        self.assertIn("verify_release_ledger.py", release_workflow)
        self.assertIn("gh attestation verify", release_workflow)
        self.assertIn("actions/attest-build-provenance@v3", release_workflow)
        self.assertIn("--immutable-assets", release_workflow)
        self.assertIn("--content-addressed-prefix", release_workflow)
        self.assertIn("--signer-workflow", release_workflow)
        self.assertIn("prepare_pypi_promotion.py", release_workflow)
        self.assertNotIn("--replace-assets", release_workflow)
        self.assertNotIn("skip-existing:", release_workflow)
        platform_publish = [
            release_workflow.index(f"@antfly/cli-{name} \"$version\"")
            for name in ("darwin-arm64", "linux-arm64", "linux-x64")
        ]
        selector_publish = release_workflow.index('@antfly/cli "$version"')
        self.assertLess(max(platform_publish), selector_publish)

        cloud_build = (REPO_ROOT / "zig" / "cloudbuild.runtime.yaml").read_text()
        self.assertIn("_ARTIFACT_URI: __required__", cloud_build)
        self.assertIn("_ARTIFACT_URI must be an explicit gs:// GNU runtime artifact", cloud_build)

        release_design = (REPO_ROOT / "RELEASE.md").read_text()
        self.assertIn(f"glibc {minimum_glibc}", release_design)
        for platform in package_cli_release.PLATFORMS:
            expected_archive = package_cli_release.archive_name("<version>", platform)
            self.assertIn(f"`{expected_archive}`", release_design)

    def test_cli_platforms_select_libc_specific_linux_archives(self) -> None:
        names = {
            platform.key: package_cli_release.archive_name("1.2.3", platform)
            for platform in package_cli_release.PLATFORMS
        }
        self.assertEqual(names["darwin-arm64"], "antfly_1.2.3_Darwin_arm64.tar.gz")
        self.assertEqual(names["linux-arm64-gnu"], "antfly_1.2.3_Linux_arm64_gnu.tar.gz")
        self.assertEqual(names["linux-x64-gnu"], "antfly_1.2.3_Linux_x86_64_gnu.tar.gz")
        self.assertEqual(names["linux-arm64-musl"], "antfly_1.2.3_Linux_arm64.tar.gz")
        self.assertEqual(names["linux-x64-musl"], "antfly_1.2.3_Linux_x86_64.tar.gz")

    def test_npm_platform_manifests_declare_the_expected_libc(self) -> None:
        expected_dependencies = set()
        for platform in package_cli_release.PACKAGE_PLATFORMS:
            package_cli_release.validate_npm_package(REPO_ROOT, platform)
            expected_dependencies.add(f"@antfly/{platform.npm_package_dir}")

        musl_platforms = [platform for platform in package_cli_release.PLATFORMS if platform.key.endswith("-musl")]
        self.assertEqual(len(musl_platforms), 2)
        self.assertTrue(all(platform.npm_package_dir is None for platform in musl_platforms))

        top_level = json.loads((REPO_ROOT / "ts" / "packages" / "cli" / "package.json").read_text())
        self.assertEqual(set(top_level["optionalDependencies"]), expected_dependencies)

    def test_npm_publish_is_retry_safe_and_rejects_content_drift(self) -> None:
        helper = REPO_ROOT / "scripts" / "packaging" / "publish_npm_package.sh"
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            fake_bin = root / "bin"
            fake_bin.mkdir()
            npm = fake_bin / "npm"
            npm.write_text(
                "#!/bin/sh\n"
                "if [ \"$1\" = view ]; then\n"
                "  if [ -n \"${FAKE_NPM_INTEGRITY:-}\" ]; then printf '%s\\n' \"$FAKE_NPM_INTEGRITY\"; exit 0; fi\n"
                "  exit 1\n"
                "fi\n"
                "printf '%s\\n' \"$*\" >> \"$FAKE_NPM_LOG\"\n"
            )
            npm.chmod(0o755)
            tarball = root / "package.tgz"
            tarball.write_bytes(b"npm package")
            digest = base64.b64encode(hashlib.sha512(tarball.read_bytes()).digest()).decode()
            integrity = f"sha512-{digest}"
            log = root / "npm.log"
            env = {
                **os.environ,
                "PATH": f"{fake_bin}:{os.environ['PATH']}",
                "FAKE_NPM_LOG": str(log),
                "FAKE_NPM_INTEGRITY": integrity,
            }
            command = ["sh", str(helper), "@antfly/cli", "1.2.3", "latest", str(tarball)]

            subprocess.run(command, check=True, env=env, capture_output=True, text=True)
            self.assertFalse(log.exists())

            env["FAKE_NPM_INTEGRITY"] = "sha512-different"
            mismatch = subprocess.run(command, env=env, capture_output=True, text=True, check=False)
            self.assertNotEqual(mismatch.returncode, 0)
            self.assertIn("exists with different contents", mismatch.stderr)

            env["FAKE_NPM_INTEGRITY"] = ""
            subprocess.run(command, check=True, env=env, capture_output=True, text=True)
            self.assertIn("publish", log.read_text())

    def test_python_and_npm_packages_preserve_cabi_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            repo = root / "repo"
            extracted = root / "extracted"
            out = root / "out"
            archive_dir = root / "archives"
            archive_dir.mkdir()

            platform = package_cli_release.PLATFORMS[1]
            write_release_archive(
                archive_dir,
                "1.2.3",
                platform.release_os,
                platform.release_arch,
                platform.release_variant,
            )

            package_dir = repo / "ts" / "packages" / platform.npm_package_dir
            package_dir.mkdir(parents=True)
            (package_dir / "package.json").write_text(
                json.dumps(
                    {
                        "name": f"@antfly/{platform.npm_package_dir}",
                        "version": "0.0.0",
                        "files": ["bin", "include", "lib", "share", "README.md"],
                        "libc": [platform.npm_libc],
                    }
                )
                + "\n"
            )
            (repo / "zig" / "pkg" / "antfly" / "antfarm").mkdir(parents=True)
            (repo / "zig" / "pkg" / "antfly" / "antfarm" / "index.html").write_text("antfarm\n")
            (repo / "py" / "packages" / "cli" / "src" / "antfly_cli").mkdir(parents=True)
            (repo / "py" / "packages" / "cli" / "src" / "antfly_cli" / "__init__.py").write_text(
                "def main(): return 0\n"
            )
            (repo / "py" / "packages" / "cli" / "pyproject.toml").write_text(
                '[project]\nname = "antfly-cli"\nrequires-python = ">=3.10"\n'
            )

            package_cli_release.extract_archive(archive_dir, "1.2.3", platform, extracted)
            package_cli_release.copy_antfarm(repo, extracted)
            package_cli_release.populate_npm_package(repo, platform, extracted)

            npm_package = repo / "ts" / "packages" / platform.npm_package_dir
            self.assertEqual((npm_package / "include" / "antfly.h").read_text(), "/* antfly header */\n")
            self.assertEqual((npm_package / "lib" / "libantfly.so").read_text(), "antfly library\n")

            wheel = package_cli_release.package_python_wheel(repo, out, "1.2.3", platform, extracted)
            with zipfile.ZipFile(wheel) as zf:
                names = set(zf.namelist())
                metadata = zf.read("antfly_cli-1.2.3.dist-info/METADATA").decode()
            self.assertIn("antfly_cli/include/antfly.h", names)
            self.assertIn("antfly_cli/lib/libantfly.so", names)
            self.assertIn("antfly_cli/share/antfly/asset.txt", names)
            self.assertIn("Requires-Python: >=3.10", metadata)

    def test_homebrew_formula_installs_cabi_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            archive_dir = root / "archives"
            archive_dir.mkdir()
            write_release_archive(archive_dir, "1.2.3", "Darwin", "arm64")
            write_release_archive(archive_dir, "1.2.3", "Linux", "arm64", "gnu")
            write_release_archive(archive_dir, "1.2.3", "Linux", "x86_64", "gnu")

            formula = root / "Formula" / "antfly.rb"
            subprocess.run(
                [
                    sys.executable,
                    str(PACKAGING_DIR / "render_homebrew_antfly_formula.py"),
                    "--version",
                    "1.2.3",
                    "--tag",
                    "v1.2.3",
                    "--archive-dir",
                    str(archive_dir),
                    "--out",
                    str(formula),
                ],
                cwd=REPO_ROOT,
                check=True,
            )

            rendered = formula.read_text()
            self.assertIn("antfly_1.2.3_Darwin_arm64.tar.gz", rendered)
            self.assertIn("antfly_1.2.3_Linux_arm64_gnu.tar.gz", rendered)
            self.assertIn("antfly_1.2.3_Linux_x86_64_gnu.tar.gz", rendered)
            self.assertIn('include.install Dir["include/*"] if Dir.exist?("include")', rendered)
            self.assertIn('lib.install Dir["lib/*"] if Dir.exist?("lib")', rendered)
            self.assertIn('(share/"antfly").install Dir["share/antfly/*"] if Dir.exist?("share/antfly")', rendered)
            self.assertIn('bash_completion.install "completions/antfly.bash" => "antfly"', rendered)
            self.assertIn('zsh_completion.install "completions/antfly.zsh" => "_antfly"', rendered)
            self.assertIn('fish_completion.install "completions/antfly.fish"', rendered)


if __name__ == "__main__":
    unittest.main()
