// Copyright 2026 Antfly, Inc. SPDX-License-Identifier: Apache-2.0
// GLiNER2 base-v1 split checkpoint inventory. Shapes are precision-independent.
// gliner2-encoder.Q4_K.gguf: fa098b5a8836da5b3c992c2bfc2ee3e715c58009fefa94cf83c496a8315cc879
// gliner2-head.Q4_K.gguf: f1a14fd8f7700b885c4b842ee93985efc271bf1094d9229364b85758bbfaeb25
pub const Spec = struct { name: []const u8, shape: []const i64 };
pub const tensors = [_]Spec{
    .{ .name = "count_embed.gru.bias_hh_l0", .shape = &.{2304} },
    .{ .name = "count_embed.gru.bias_ih_l0", .shape = &.{2304} },
    .{ .name = "count_embed.gru.weight_hh_l0", .shape = &.{ 2304, 768 } },
    .{ .name = "count_embed.gru.weight_ih_l0", .shape = &.{ 2304, 768 } },
    .{ .name = "count_embed.pos_embedding.weight", .shape = &.{ 1, 1, 768 } },
    .{ .name = "count_embed.transformer.in_projector.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.in_projector.weight", .shape = &.{ 128, 768 } },
    .{ .name = "count_embed.transformer.out_projector.0.bias", .shape = &.{768} },
    .{ .name = "count_embed.transformer.out_projector.0.weight", .shape = &.{ 768, 896 } },
    .{ .name = "count_embed.transformer.out_projector.2.bias", .shape = &.{768} },
    .{ .name = "count_embed.transformer.out_projector.2.weight", .shape = &.{ 768, 768 } },
    .{ .name = "count_embed.transformer.out_projector.4.bias", .shape = &.{768} },
    .{ .name = "count_embed.transformer.out_projector.4.weight", .shape = &.{ 768, 768 } },
    .{ .name = "count_embed.transformer.transformer.layers.0.linear1.bias", .shape = &.{256} },
    .{ .name = "count_embed.transformer.transformer.layers.0.linear1.weight", .shape = &.{ 256, 128 } },
    .{ .name = "count_embed.transformer.transformer.layers.0.linear2.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.linear2.weight", .shape = &.{ 128, 256 } },
    .{ .name = "count_embed.transformer.transformer.layers.0.norm1.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.norm1.weight", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.norm2.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.norm2.weight", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.self_attn.in_proj_bias", .shape = &.{384} },
    .{ .name = "count_embed.transformer.transformer.layers.0.self_attn.in_proj_weight", .shape = &.{ 384, 128 } },
    .{ .name = "count_embed.transformer.transformer.layers.0.self_attn.out_proj.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.0.self_attn.out_proj.weight", .shape = &.{ 128, 128 } },
    .{ .name = "count_embed.transformer.transformer.layers.1.linear1.bias", .shape = &.{256} },
    .{ .name = "count_embed.transformer.transformer.layers.1.linear1.weight", .shape = &.{ 256, 128 } },
    .{ .name = "count_embed.transformer.transformer.layers.1.linear2.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.linear2.weight", .shape = &.{ 128, 256 } },
    .{ .name = "count_embed.transformer.transformer.layers.1.norm1.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.norm1.weight", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.norm2.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.norm2.weight", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.self_attn.in_proj_bias", .shape = &.{384} },
    .{ .name = "count_embed.transformer.transformer.layers.1.self_attn.in_proj_weight", .shape = &.{ 384, 128 } },
    .{ .name = "count_embed.transformer.transformer.layers.1.self_attn.out_proj.bias", .shape = &.{128} },
    .{ .name = "count_embed.transformer.transformer.layers.1.self_attn.out_proj.weight", .shape = &.{ 128, 128 } },
    .{ .name = "embeddings.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "embeddings.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "embeddings.word_embeddings.weight", .shape = &.{ 128011, 768 } },
    .{ .name = "encoder.layer.0.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.0.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.0.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.0.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.0.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.0.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.0.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.0.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.0.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.1.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.1.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.1.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.1.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.1.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.1.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.1.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.1.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.10.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.10.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.10.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.10.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.10.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.10.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.10.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.10.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.11.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.11.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.11.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.11.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.11.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.11.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.11.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.11.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.2.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.2.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.2.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.2.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.2.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.2.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.2.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.2.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.3.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.3.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.3.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.3.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.3.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.3.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.3.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.3.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.4.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.4.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.4.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.4.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.4.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.4.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.4.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.4.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.5.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.5.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.5.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.5.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.5.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.5.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.5.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.5.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.6.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.6.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.6.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.6.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.6.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.6.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.6.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.6.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.7.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.7.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.7.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.7.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.7.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.7.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.7.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.7.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.8.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.8.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.8.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.8.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.8.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.8.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.8.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.8.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.output.dense.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.9.attention.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.self.key_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.self.key_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.9.attention.self.query_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.self.query_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.9.attention.self.value_proj.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.attention.self.value_proj.weight", .shape = &.{ 768, 768 } },
    .{ .name = "encoder.layer.9.intermediate.dense.bias", .shape = &.{3072} },
    .{ .name = "encoder.layer.9.intermediate.dense.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "encoder.layer.9.output.dense.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.output.dense.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "encoder.layer.9.output.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.layer.9.output.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.LayerNorm.bias", .shape = &.{768} },
    .{ .name = "encoder.LayerNorm.weight", .shape = &.{768} },
    .{ .name = "encoder.rel_embeddings.weight", .shape = &.{ 512, 768 } },
    .{ .name = "span_rep.span_rep_layer.out_project.0.bias", .shape = &.{3072} },
    .{ .name = "span_rep.span_rep_layer.out_project.0.weight", .shape = &.{ 3072, 1536 } },
    .{ .name = "span_rep.span_rep_layer.out_project.3.bias", .shape = &.{768} },
    .{ .name = "span_rep.span_rep_layer.out_project.3.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "span_rep.span_rep_layer.project_end.0.bias", .shape = &.{3072} },
    .{ .name = "span_rep.span_rep_layer.project_end.0.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "span_rep.span_rep_layer.project_end.3.bias", .shape = &.{768} },
    .{ .name = "span_rep.span_rep_layer.project_end.3.weight", .shape = &.{ 768, 3072 } },
    .{ .name = "span_rep.span_rep_layer.project_start.0.bias", .shape = &.{3072} },
    .{ .name = "span_rep.span_rep_layer.project_start.0.weight", .shape = &.{ 3072, 768 } },
    .{ .name = "span_rep.span_rep_layer.project_start.3.bias", .shape = &.{768} },
    .{ .name = "span_rep.span_rep_layer.project_start.3.weight", .shape = &.{ 768, 3072 } },
};
