packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - canvas
  - core-js
  - esbuild
  - msw
  - protobufjs
  - sharp

overrides:
  lodash: 4.18.1
