#!/usr/bin/env python3
"""Capture published-tokenizer Unicode references and a tiny native test model."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import oracle


def zig_string(text: str) -> str:
    return '"' + "".join(
        "\\" + ch if ch in ('"', "\\") else f"\\x{ord(ch):02x}" if ord(ch) < 32 or ord(ch) == 127 else ch
        for ch in text
    ) + '"'


def capture(source: Path, model_dir: Path, destination: Path) -> None:
    provenance, _ = oracle.prepare_runtime(source)
    bundle = oracle.verify_model_dir("small", model_dir)
    from tokenizers import AddedToken, Tokenizer, models

    real = Tokenizer.from_file(str(model_dir / "tokenizer.json"))
    vocab = [("<unk>", 0.0), ("▁", -1.0), ("▁é", -0.2), ("▁café", -0.2), ("▁a", -0.3),
             ("a", -1.0), ("b", -1.0), ("▁b", -0.3), ("▁x", -0.3), ("x", -1.0), ("é", -0.5)]
    tiny = Tokenizer(models.Unigram(vocab, 0, False))
    tiny.normalizer = real.normalizer
    tiny.pre_tokenizer = real.pre_tokenizer
    tiny.add_special_tokens([AddedToken("[SEP_TEXT]", special=True, normalized=False)])
    cases = [
        "e\u0301", "cafe\u0301", " e\u0301  x\t\n", "a\u0315\u0300", "\u212b",
        "\u0958", "\u1100\u1161\u11a8", "İ", "i\u0307", "Ο\u0301Σ ς", "東京🙂",
        "a\U0001fae8\U0001fae8b", "\u00a0x\u00a0", "\u000bx\u000b", "\u0085x\u0085",
        "\u001cx\u001c", "a\t\t b", "x\u2003\u2003b", "e\u0301[SEP_TEXT]x",
        "a [SEP_TEXT]  x ", "[SEP_TEXT]x", "▁a", "a▁b", " ", "", "🙂🙂a🙂",
        "https://example.com/a user@example.com @User", "a" + "\u0315\u0300" * 64,
    ]
    rows = [{"text": text, "normalized": real.normalizer.normalize_str(text),
             "ids": real.encode(text, add_special_tokens=False).ids,
             "tokens": real.encode(text, add_special_tokens=False).tokens,
             "tiny_ids": tiny.encode(text, add_special_tokens=False).ids} for text in cases]
    report = {"format_version": 1, "scope": "tokenizer_reference", "provenance": provenance,
              "model": bundle, "generator_sha256": oracle.sha256_file(Path(__file__)),
              "real_model_qualified": False, "native_runtime_qualified": False, "training_qualified": False,
              "normalizer": json.loads(real.to_str())["normalizer"], "cases": rows}
    oracle.verify_upstream_checkout(source)
    with oracle.atomic_output_directory(destination) as output:
        oracle.write_json(output / "tokenizer.json", report)
        lines = ["// Generated by scripts/gliner25/capture_tokenizer.py from Tokenizers 0.21.4.",
                 "// Published tokenizer SHA256: " + bundle["files"]["tokenizer.json"]["sha256"],
                 "pub const tiny_tokenizer_json = " + zig_string(tiny.to_str()) + ";",
                 "pub const Case = struct { text: []const u8, normalized: []const u8, ids: []const i32 };",
                 "pub const cases = [_]Case{"]
        for row in rows:
            ids = ", ".join(map(str, row["tiny_ids"]))
            if len(row["tiny_ids"]) > 1:
                ids = " " + ids + " "
            lines.append("    .{ .text = " + zig_string(row["text"]) + ", .normalized = " + zig_string(row["normalized"]) + ", .ids = &.{" + ids + "} },")
        lines += ["};", ""]
        (output / "normalizer_fixtures.zig").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"status": "captured", "cases": len(rows), "output": str(destination)}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", required=True, type=Path)
    parser.add_argument("--model-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    capture(args.upstream, args.model_dir, args.output)
