#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Capture raw token IDs from pinned GLiNER family tokenizer files, without weights."""

import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path

from tokenizers import Tokenizer

from verify_family_contract import strict_json, verify_sidecar

HERE = Path(__file__).resolve().parent
MODELS = {
    "multi": "multi_v1",
    "multi-decide": "multi_decide",
    "decide-1b": "decide_1b",
}
TEXTS = [
    "",
    "apple",
    " apple",
    "café",
    "cafe\u0301",
    "e\u0301[L]cafe\u0301",
    "[SEP_STRUCT][P]intent[C][L]refund[L]cancel[SEP_TEXT]",
    "東京で田中さんが働いています。",
    "أريد استرداد المبلغ",
    "Отмените подписку, пожалуйста.",
    "İpek İstanbul'da çalışıyor.",
    "मैं दिल्ली में रहता हूँ।",
    "\u1100\u1161\u11a8",
    "🙂 café 東京",
    "a\t\n  b",
    "é[DESCRIPTION]e\u0301",
    "\u212b",
    "\u00a0hello\u00a0",
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "root",
        type=Path,
        help="Directory with multi, multi-decide, decide-1b subdirectories",
    )
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    contract = strict_json(HERE / "family_contract.json")
    runtime = importlib.metadata.version("tokenizers")
    if runtime != contract["oracle_runtime"]["packages"]["tokenizers"]:
        raise ValueError(f"unexpected tokenizers runtime: {runtime}")

    def quote(value):
        return json.dumps(value, ensure_ascii=False)

    header = (HERE.parents[4] / "scripts/license-header-apache.txt").read_text()
    lines = ["// " + line if line else "//" for line in header.rstrip().splitlines()]
    lines += [
        "",
        "// Generated by scripts/gliner25/generate_family_tokenizer_fixtures.py.",
        f"// Reference: tokenizers {importlib.metadata.version('tokenizers')}; raw IDs, add_special_tokens=false.",
        "pub const Case = struct { text: []const u8, ids: []const i32 };",
        "pub const Model = struct { directory: []const u8, model_id: []const u8, revision: []const u8, sha256: []const u8, cases: []const Case };",
        "pub const models = [_]Model{",
    ]
    for directory, profile in MODELS.items():
        model = contract["models"][profile]
        model_id, revision = model["repo"], model["revision"]
        path = args.root / directory / "tokenizer.json"
        verify_sidecar(path, model["sidecars"]["tokenizer.json"])
        data = path.read_bytes()
        tokenizer = Tokenizer.from_str(data.decode("utf-8"))
        lines.append(
            f"    .{{ .directory = {quote(directory)}, .model_id = {quote(model_id)}, .revision = {quote(revision)}, .sha256 = {quote(hashlib.sha256(data).hexdigest())}, .cases = &.{{"
        )
        for text in TEXTS:
            ids = tokenizer.encode(text, add_special_tokens=False).ids
            # Zig uses hexadecimal control escapes rather than JSON's \u form.
            literal = quote(text).replace("\\t", "\\x09").replace("\\n", "\\x0a")
            lines.append(
                f"        .{{ .text = {literal}, .ids = &.{{ {', '.join(map(str, ids))} }} }},"
            )
        lines.append("    } },")
    lines.append("};")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
