//go:build go1.22

// Package indexes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package indexes

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/go/pkg/antfly/lib/chunking"
	externalRef1 "github.com/antflydb/antfly/go/pkg/antfly/lib/embeddings"
	externalRef2 "github.com/antflydb/antfly/go/pkg/generating"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AlgebraicIndexStatsIndexType.
const (
	AlgebraicIndexStatsIndexTypeAlgebraic AlgebraicIndexStatsIndexType = "algebraic"
)

// Defines values for AlgebraicIndexStatsPlannerLastDecision.
const (
	AlgebraicIndexStatsPlannerLastDecisionFallback AlgebraicIndexStatsPlannerLastDecision = "fallback"
	AlgebraicIndexStatsPlannerLastDecisionSelected AlgebraicIndexStatsPlannerLastDecision = "selected"
)

// Defines values for AntflyType.
const (
	AntflyTypeBlob            AntflyType = "blob"
	AntflyTypeBoolean         AntflyType = "boolean"
	AntflyTypeDatetime        AntflyType = "datetime"
	AntflyTypeEmbedding       AntflyType = "embedding"
	AntflyTypeGeopoint        AntflyType = "geopoint"
	AntflyTypeGeoshape        AntflyType = "geoshape"
	AntflyTypeHtml            AntflyType = "html"
	AntflyTypeKeyword         AntflyType = "keyword"
	AntflyTypeLink            AntflyType = "link"
	AntflyTypeNumeric         AntflyType = "numeric"
	AntflyTypeSearchAsYouType AntflyType = "search_as_you_type"
	AntflyTypeText            AntflyType = "text"
)

// Defines values for DistanceMetric.
const (
	DistanceMetricCosine       DistanceMetric = "cosine"
	DistanceMetricInnerProduct DistanceMetric = "inner_product"
	DistanceMetricL2Squared    DistanceMetric = "l2_squared"
)

// Defines values for EdgeDirection.
const (
	EdgeDirectionBoth EdgeDirection = "both"
	EdgeDirectionIn   EdgeDirection = "in"
	EdgeDirectionOut  EdgeDirection = "out"
)

// Defines values for EdgeTypeConfigTopology.
const (
	EdgeTypeConfigTopologyGraph EdgeTypeConfigTopology = "graph"
	EdgeTypeConfigTopologyTree  EdgeTypeConfigTopology = "tree"
)

// Defines values for EmbeddingsIndexConfigFormat.
const (
	EmbeddingsIndexConfigFormatLsmPacked         EmbeddingsIndexConfigFormat = "lsm_packed"
	EmbeddingsIndexConfigFormatSegmentsBaseDelta EmbeddingsIndexConfigFormat = "segments_base_delta"
)

// Defines values for EmbeddingsIndexStatsIndexType.
const (
	EmbeddingsIndexStatsIndexTypeEmbeddings EmbeddingsIndexStatsIndexType = "embeddings"
)

// Defines values for FullTextIndexStatsIndexType.
const (
	FullTextIndexStatsIndexTypeFullText FullTextIndexStatsIndexType = "full_text"
)

// Defines values for GraphIndexStatsIndexType.
const (
	GraphIndexStatsIndexTypeGraph GraphIndexStatsIndexType = "graph"
)

// Defines values for GraphQueryType.
const (
	GraphQueryTypeKShortestPaths GraphQueryType = "k_shortest_paths"
	GraphQueryTypeNeighbors      GraphQueryType = "neighbors"
	GraphQueryTypePattern        GraphQueryType = "pattern"
	GraphQueryTypeShortestPath   GraphQueryType = "shortest_path"
	GraphQueryTypeTraverse       GraphQueryType = "traverse"
)

// Defines values for IndexType.
const (
	IndexTypeAlgebraic  IndexType = "algebraic"
	IndexTypeEmbeddings IndexType = "embeddings"
	IndexTypeFullText   IndexType = "full_text"
	IndexTypeGraph      IndexType = "graph"
)

// Defines values for MergeStrategy.
const (
	MergeStrategyFailover MergeStrategy = "failover"
	MergeStrategyRrf      MergeStrategy = "rrf"
	MergeStrategyRsf      MergeStrategy = "rsf"
)

// Defines values for PathFindWeightMode.
const (
	PathFindWeightModeMaxWeight PathFindWeightMode = "max_weight"
	PathFindWeightModeMinHops   PathFindWeightMode = "min_hops"
	PathFindWeightModeMinWeight PathFindWeightMode = "min_weight"
)

// Defines values for PathWeightMode.
const (
	PathWeightModeMaxWeight PathWeightMode = "max_weight"
	PathWeightModeMinHops   PathWeightMode = "min_hops"
	PathWeightModeMinWeight PathWeightMode = "min_weight"
)

// AlgebraicIndexConfig Schema-derived algebraic sidecar configuration. Public requests may opt into schema derivation, while materializations remain engine-owned.
type AlgebraicIndexConfig struct {
	// DeriveFromSchema When true, derive the algebraic capability sidecar from the table schema. Internal fields and materialization definitions are not public API.
	DeriveFromSchema bool `json:"derive_from_schema,omitempty"`
}

// AlgebraicIndexStats Compact public statistics for an algebraic sidecar index. Detailed runtime, adaptive, and materialization records remain internal diagnostics.
type AlgebraicIndexStats struct {
	ActiveProgressLifecycle         string `json:"active_progress_lifecycle,omitempty"`
	ActiveProgressRowsProcessed     uint64 `json:"active_progress_rows_processed,omitempty"`
	ActiveProgressTargetRows        uint64 `json:"active_progress_target_rows,omitempty"`
	AdaptiveBackfillingCount        uint64 `json:"adaptive_backfilling_count,omitempty"`
	AdaptiveCleanupRecommendedCount uint64 `json:"adaptive_cleanup_recommended_count,omitempty"`
	AdaptiveProgressCount           uint64 `json:"adaptive_progress_count,omitempty"`
	AdaptiveReadyCount              uint64 `json:"adaptive_ready_count,omitempty"`
	AdaptiveStaleCount              uint64 `json:"adaptive_stale_count,omitempty"`

	// BackfillItemsProcessed Number of documents processed during current backfill
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Backfill progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// CapabilityLifecycleStatus Schema-derived algebraic capability lifecycle, for example current, stale, or rebuild_required.
	CapabilityLifecycleStatus string `json:"capability_lifecycle_status,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error   string `json:"error,omitempty"`
	Healthy bool   `json:"healthy,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType            AlgebraicIndexStatsIndexType           `json:"index_type"`
	LastErrorReason      string                                 `json:"last_error_reason,omitempty"`
	ParseErrorCount      uint64                                 `json:"parse_error_count,omitempty"`
	PlannerFallbackCount uint64                                 `json:"planner_fallback_count,omitempty"`
	PlannerLastDecision  AlgebraicIndexStatsPlannerLastDecision `json:"planner_last_decision,omitempty"`

	// PlannerLastEstimatedResultBuckets Latest algebraic planner result-bucket estimate for the last selected or fallback decision.
	PlannerLastEstimatedResultBuckets uint64 `json:"planner_last_estimated_result_buckets,omitempty"`

	// PlannerLastEstimatedScanRows Latest algebraic planner scan-row estimate for the last selected or fallback decision.
	PlannerLastEstimatedScanRows   uint64 `json:"planner_last_estimated_scan_rows,omitempty"`
	PlannerLastFallbackReason      string `json:"planner_last_fallback_reason,omitempty"`
	PlannerLifecycleBlockingReason string `json:"planner_lifecycle_blocking_reason,omitempty"`
	PlannerLifecycleReady          bool   `json:"planner_lifecycle_ready,omitempty"`
	PlannerSelected                uint64 `json:"planner_selected,omitempty"`

	// Rebuilding Whether the sidecar is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// RecommendationCount Number of currently recommended algebraic shapes.
	RecommendationCount uint64 `json:"recommendation_count,omitempty"`
	SchemaVersion       uint64 `json:"schema_version,omitempty"`

	// TotalIndexed Number of documents reflected in the algebraic sidecar
	TotalIndexed uint64 `json:"total_indexed,omitempty"`
}

// AlgebraicIndexStatsIndexType Discriminator for the index stats variant.
type AlgebraicIndexStatsIndexType string

// AlgebraicIndexStatsPlannerLastDecision defines model for AlgebraicIndexStats.PlannerLastDecision.
type AlgebraicIndexStatsPlannerLastDecision string

// AntflyType defines model for AntflyType.
type AntflyType string

// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
type DistanceMetric string

// Edge A typed, weighted connection between documents
type Edge struct {
	// CreatedAt When the edge was created
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Metadata Optional edge metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Source Base64-encoded source document key
	Source []byte `json:"source"`

	// Target Base64-encoded target document key
	Target []byte `json:"target"`

	// Type Edge type (e.g., "cites", "similar_to", "authored_by")
	Type string `json:"type"`

	// UpdatedAt When the edge was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// Weight Edge weight/confidence (0.0 to 1.0)
	Weight float64 `json:"weight"`
}

// EdgeDirection Direction of edges to query:
// - out: Outgoing edges from the node
// - in: Incoming edges to the node
// - both: Both outgoing and incoming edges
type EdgeDirection string

// EdgeTypeConfig Configuration for a specific edge type
type EdgeTypeConfig struct {
	// AllowSelfLoops Whether to allow edges from a node to itself
	AllowSelfLoops bool `json:"allow_self_loops,omitempty"`

	// Field Document field containing target node key(s) for automatic edge creation.
	// Supports string (single target) or array of strings (multiple targets).
	// When omitted, edges must be provided explicitly via _edges.
	Field string `json:"field,omitempty"`

	// MaxWeight Maximum allowed edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum allowed edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// Name Edge type name (e.g., 'cites', 'similar_to')
	Name string `json:"name"`

	// RequiredMetadata Required metadata fields for this edge type
	RequiredMetadata *[]string `json:"required_metadata,omitempty"`

	// Topology Topology constraint for this edge type:
	// - tree: Single parent per node, no cycles
	// - graph: No constraints (default)
	Topology EdgeTypeConfigTopology `json:"topology,omitempty"`
}

// EdgeTypeConfigTopology Topology constraint for this edge type:
// - tree: Single parent per node, no cycles
// - graph: No constraints (default)
type EdgeTypeConfigTopology string

// EmbeddingsIndexConfig Unified configuration for embeddings indexes. When sparse is true, creates a sparse vector index (SPLADE inverted index). When sparse is false (default), creates a dense vector index (HNSW). For dense indexes, dimension can be omitted if an embedder is configured — it will be auto-detected.
type EmbeddingsIndexConfig struct {
	// ChunkSize Number of documents per posting list chunk (sparse only)
	ChunkSize int `json:"chunk_size,omitempty"`

	// Chunker A unified configuration for a chunking provider.
	Chunker *externalRef0.ChunkerConfig `json:"chunker,omitempty"`

	// Dimension Vector dimension for dense indexes. Required for external dense indexes. Can be omitted for managed dense indexes when an embedder is configured (auto-detected via probe). Ignored for sparse indexes.
	Dimension int `json:"dimension,omitempty"`

	// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
	DistanceMetric DistanceMetric `json:"distance_metric,omitempty"`

	// Embedder A unified configuration for an embedding provider.
	//
	// Embedders can be configured with templates to customize how documents are
	// converted to text before embedding. Templates use Handlebars syntax and
	// support various built-in helpers.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full document as context
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active user{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// Document with metadata:
	// ```handlebars
	// Title: {{metadata.title}}
	// Date: {{metadata.date}}
	// Tags: {{#each metadata.tags}}{{this}}, {{/each}}
	//
	// {{content}}
	// ```
	//
	// HTML content extraction:
	// ```handlebars
	// Product: {{name}}
	// Description: {{scrubHtml description_html}}
	// Price: ${{price}}
	// ```
	//
	// Multimodal with image:
	// ```handlebars
	// Product: {{title}}
	// {{media url=image}}
	// Description: {{description}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{title}}
	// {{#if author}}By: {{author}}{{/if}}
	// {{#if (eq category "premium")}}⭐ Premium Content{{/if}}
	// {{body}}
	// ```
	//
	// **Environment Variables:**
	// - `GEMINI_API_KEY` - API key for Google AI
	// - `OPENAI_API_KEY` - API key for OpenAI
	// - `OPENAI_BASE_URL` - Base URL for OpenAI-compatible APIs
	// - `OLLAMA_HOST` - Ollama server URL (e.g., http://localhost:11434)
	//
	// **Importing Pre-computed Embeddings:**
	//
	// You can import existing embeddings (from OpenAI, Cohere, or any provider), but only
	// for indexes configured with `external: true`. External indexes accept vectors written
	// directly through the document `_embeddings` field and do not generate prompts from
	// `field` or `template`.
	//
	// **Steps:**
	// 1. Create an embeddings index with `external: true`
	// 2. For dense indexes, set the index `dimension`
	// 3. Write documents with `_embeddings: { "<indexName>": [...<embedding>...] }`
	//
	// **Example:**
	// ```json
	// {
	//   "title": "My Document",
	//   "content": "Document text...",
	//   "_embeddings": {
	//     "my_vector_index": [0.1, 0.2, 0.3, ...]
	//   }
	// }
	// ```
	//
	// **Delete Behavior:**
	// - Use `"_embeddings": { "<indexName>": null }` to delete a stored external vector
	// - Omitting `_embeddings[<indexName>]` leaves the existing vector unchanged
	//
	// **Use Cases:**
	// - Migrating from another vector database with existing embeddings
	// - Using embeddings generated by external systems
	// - Importing pre-computed OpenAI, Cohere, or other provider embeddings
	// - Batch processing embeddings offline before ingestion
	Embedder *externalRef1.EmbedderConfig `json:"embedder,omitempty"`

	// External When true, embeddings are supplied externally via _embeddings and the index does not derive prompts from a field or template.
	External bool `json:"external,omitempty"`

	// Field Field to extract embeddings from (managed indexes only; not allowed when external=true)
	Field string `json:"field,omitempty"`

	// Format Dense vector index storage format. lsm_packed is the legacy packed HBC posting store. segments_base_delta stores immutable posting base records with append-only delta segments. Ignored for sparse indexes.
	Format EmbeddingsIndexConfigFormat `json:"format,omitempty"`

	// MemOnly Whether to use in-memory only storage (dense only)
	MemOnly bool `json:"mem_only,omitempty"`

	// MinWeight Minimum weight threshold for sparse vector entries (sparse only)
	MinWeight float32 `json:"min_weight,omitempty"`

	// Sparse When true, creates a sparse (SPLADE) inverted index. When false (default), creates a dense (HNSW) vector index.
	Sparse bool `json:"sparse,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	Summarizer *externalRef2.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating prompts (managed indexes only; not allowed when external=true). See https://handlebarsjs.com/guide/ for more information.
	Template string `json:"template,omitempty"`

	// TopK Default number of results to return from search (sparse only)
	TopK int `json:"top_k,omitempty"`
}

// EmbeddingsIndexConfigFormat Dense vector index storage format. lsm_packed is the legacy packed HBC posting store. segments_base_delta stores immutable posting base records with append-only delta segments. Ignored for sparse indexes.
type EmbeddingsIndexConfigFormat string

// EmbeddingsIndexStats Statistics for an embeddings index (dense or sparse)
type EmbeddingsIndexStats struct {
	// BackfillItemsProcessed Total items processed during backfill
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Backfill progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType EmbeddingsIndexStatsIndexType `json:"index_type"`

	// Rebuilding Whether the index enricher is currently backfilling
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalIndexed Number of vectors/documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`

	// TotalNodes Total number of nodes in the index (dense only)
	TotalNodes uint64 `json:"total_nodes,omitempty"`

	// TotalTerms Number of unique terms in the inverted index (sparse only)
	TotalTerms uint64 `json:"total_terms,omitempty"`

	// WalBacklog Number of documents pending enrichment in the WAL
	WalBacklog uint64 `json:"wal_backlog,omitempty"`
}

// EmbeddingsIndexStatsIndexType Discriminator for the index stats variant.
type EmbeddingsIndexStatsIndexType string

// FullTextIndexConfig defines model for FullTextIndexConfig.
type FullTextIndexConfig struct {
	// MemOnly Whether to use memory-only storage
	MemOnly bool `json:"mem_only,omitempty"`
}

// FullTextIndexStats defines model for FullTextIndexStats.
type FullTextIndexStats struct {
	// BackfillItemsProcessed Number of documents indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Progress of ongoing rebuild as fraction [0.0, 1.0]
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType FullTextIndexStatsIndexType `json:"index_type"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalIndexed Number of documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`
}

// FullTextIndexStatsIndexType Discriminator for the index stats variant.
type FullTextIndexStatsIndexType string

// GraphIndexConfig Configuration for graph index type
type GraphIndexConfig struct {
	// EdgeTypes List of edge types with their configurations
	EdgeTypes *[]EdgeTypeConfig `json:"edge_types,omitempty"`

	// MaxEdgesPerDocument Maximum number of edges per document (0 = unlimited)
	MaxEdgesPerDocument int `json:"max_edges_per_document,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	Summarizer *externalRef2.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating summarizer input text.
	// Uses document fields as template variables.
	// Same pattern as EmbeddingsConfig template.
	Template string `json:"template,omitempty"`
}

// GraphIndexStats Statistics for graph index
type GraphIndexStats struct {
	// AlgebraicGraph Algebraic graph execution health for bounded semiring traversal.
	AlgebraicGraph struct {
		Traversal *struct {
			Attempted   *uint64 `json:"attempted,omitempty"`
			Fallback    *uint64 `json:"fallback,omitempty"`
			Proven      *uint64 `json:"proven,omitempty"`
			Rejected    *uint64 `json:"rejected,omitempty"`
			ResultNodes *uint64 `json:"result_nodes,omitempty"`
		} `json:"traversal,omitempty"`
	} `json:"algebraic_graph,omitempty"`

	// BackfillItemsProcessed Number of edges indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Rebuild progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// EdgeTypes Count of edges per edge type
	EdgeTypes *map[string]uint64 `json:"edge_types,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType GraphIndexStatsIndexType `json:"index_type"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// TotalEdges Total number of edges in the graph
	TotalEdges uint64 `json:"total_edges,omitempty"`
}

// GraphIndexStatsIndexType Discriminator for the index stats variant.
type GraphIndexStatsIndexType string

// GraphNodeSelector Defines how to select start/target nodes for graph queries
type GraphNodeSelector struct {
	// Keys Explicit list of node keys
	Keys []string `json:"keys,omitempty"`

	// Limit Maximum number of nodes to select from the referenced results
	Limit int `json:"limit,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// ResultRef Reference to search results to use as nodes:
	// - "$full_text_results" - use full-text search results
	// - "$embeddings_results.index_name" - use vector search results from specific index
	ResultRef string `json:"result_ref,omitempty"`
}

// GraphQuery Declarative graph query to execute after full-text/vector searches
type GraphQuery struct {
	// Fields Which fields to return from documents
	Fields []string `json:"fields,omitempty"`

	// IncludeDocuments Fetch full documents for graph results
	IncludeDocuments bool `json:"include_documents,omitempty"`

	// IncludeEdges Include edge details for each node
	IncludeEdges bool `json:"include_edges,omitempty"`

	// IndexName Graph index name (must be graph type)
	IndexName string `json:"index_name"`

	// Params Parameters for graph traversal and pathfinding
	Params GraphQueryParams `json:"params,omitempty"`

	// Pattern Pattern steps for pattern query type
	Pattern []PatternStep `json:"pattern,omitempty"`

	// ReturnAliases Which aliases to return from pattern query (empty = all)
	ReturnAliases []string `json:"return_aliases,omitempty"`

	// StartNodes Defines how to select start/target nodes for graph queries
	StartNodes GraphNodeSelector `json:"start_nodes,omitempty"`

	// TargetNodes Defines how to select start/target nodes for graph queries
	TargetNodes GraphNodeSelector `json:"target_nodes,omitempty"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryParams Parameters for graph traversal and pathfinding
type GraphQueryParams struct {
	// Algorithm Graph algorithm to run (e.g., 'pagerank', 'betweenness')
	Algorithm string `json:"algorithm,omitempty"`

	// AlgorithmParams Parameters for the graph algorithm
	AlgorithmParams map[string]interface{} `json:"algorithm_params,omitempty"`

	// DeduplicateNodes Remove duplicate nodes (traversal)
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by edge types
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information (traversal)
	IncludePaths bool `json:"include_paths,omitempty"`

	// K Number of paths to find (k-shortest-paths)
	K int `json:"k,omitempty"`

	// MaxDepth Maximum traversal depth
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum number of results (traversal)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// WeightMode Path weighting algorithm for pathfinding:
	// - min_hops: Minimize number of edges
	// - min_weight: Minimize sum of edge weights
	// - max_weight: Maximize product of edge weights
	WeightMode PathWeightMode `json:"weight_mode,omitempty"`
}

// GraphQueryResult Results of a graph query
type GraphQueryResult struct {
	// Matches Pattern matches (for pattern queries)
	Matches []PatternMatch `json:"matches,omitempty"`

	// Nodes Result nodes
	Nodes []GraphResultNode `json:"nodes,omitempty"`

	// Paths Result paths (for pathfinding queries)
	Paths []Path `json:"paths,omitempty"`

	// Took Query execution time
	Took time.Duration `json:"took,omitempty"`

	// Total Total number of results
	Total int `json:"total"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryType Type of graph query to execute
type GraphQueryType string

// GraphResultNode A node in graph query results
type GraphResultNode struct {
	// Depth Distance from start node
	Depth int `json:"depth,omitempty"`

	// Distance Weighted distance
	Distance float64 `json:"distance,omitempty"`

	// Document Full document (if include_documents=true)
	Document map[string]interface{} `json:"document,omitempty"`

	// Edges Connected edges (when include_edges=true)
	Edges []Edge `json:"edges,omitempty"`

	// Key Document key
	Key string `json:"key"`

	// Path Keys in path from start to this node
	Path []string `json:"path,omitempty"`

	// PathEdges Edges in path from start to this node
	PathEdges []PathEdge `json:"path_edges,omitempty"`

	// Provenance Algebraic provenance labels folded into this result, when requested by an algebraic graph executor
	Provenance []string `json:"provenance,omitempty"`
}

// IndexConfig Configuration for an index
type IndexConfig struct {
	// Description Optional description of the index and its purpose
	Description *string `json:"description,omitempty"`

	// Enrichments List of enrichment names to apply to documents before indexing. Enrichments must be defined at the table level.
	Enrichments []string `json:"enrichments,omitempty"`

	// Name Name of the index
	Name string `json:"name"`

	// Type The type of the index.
	Type IndexType `json:"type"`

	// Version Version of the selected index implementation or storage format. For dense embeddings indexes, this is scoped to the format value. Defaults to 1.
	Version int `json:"version,omitempty"`
	union   json.RawMessage
}

// IndexStats Statistics for an index
type IndexStats struct {
	union json.RawMessage
}

// IndexType The type of the index.
type IndexType string

// MergeConfig Configuration for result fusion when combining multiple search indexes.
type MergeConfig struct {
	// RankConstant RRF k constant (1/(k+rank)). Defaults to 60.0.
	RankConstant float64 `json:"rank_constant,omitempty"`

	// Strategy Merge strategy for combining results from the semantic_search and full_text_search.
	// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
	// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
	// failover: Use full_text_search if embedding generation fails
	Strategy *MergeStrategy `json:"strategy,omitempty"`

	// Weights Named weights keyed by index name. `full_text` for the full-text search index;
	// embedding index names for vector indexes.
	// Unspecified indexes default to 1.0. Applied in both RRF and RSF.
	Weights *map[string]float64 `json:"weights,omitempty"`

	// WindowSize RSF normalization window size. Defaults to `limit`.
	WindowSize int `json:"window_size,omitempty"`
}

// MergeStrategy Merge strategy for combining results from the semantic_search and full_text_search.
// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
// failover: Use full_text_search if embedding generation fails
type MergeStrategy string

// NodeFilter Filter nodes during graph traversal using existing query primitives
type NodeFilter struct {
	// FilterPrefix Filter by key prefix
	FilterPrefix string `json:"filter_prefix,omitempty"`

	// FilterQuery Antfly query to filter nodes (same syntax as search filter_query)
	FilterQuery map[string]interface{} `json:"filter_query,omitempty"`
}

// Path defines model for Path.
type Path struct {
	Edges  []PathEdge `json:"edges,omitempty"`
	Length int        `json:"length,omitempty"`

	// Nodes Ordered list of node keys (base64-encoded)
	Nodes       []string `json:"nodes,omitempty"`
	TotalWeight float64  `json:"total_weight,omitempty"`
}

// PathEdge defines model for PathEdge.
type PathEdge struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Source   string                 `json:"source,omitempty"`
	Target   string                 `json:"target,omitempty"`
	Type     string                 `json:"type,omitempty"`
	Weight   float64                `json:"weight,omitempty"`
}

// PathFindRequest defines model for PathFindRequest.
type PathFindRequest struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by specific edge types
	EdgeTypes []string `json:"edge_types,omitempty"`
	K         int      `json:"k,omitempty"`
	MaxDepth  int      `json:"max_depth,omitempty"`
	MaxWeight float64  `json:"max_weight,omitempty"`
	MinWeight float64  `json:"min_weight,omitempty"`

	// Source Source node key (base64-encoded)
	Source string `json:"source"`

	// Target Target node key (base64-encoded)
	Target string `json:"target"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindResult defines model for PathFindResult.
type PathFindResult struct {
	Paths        []Path  `json:"paths,omitempty"`
	PathsFound   int     `json:"paths_found,omitempty"`
	SearchTimeMs float64 `json:"search_time_ms,omitempty"`
	Source       string  `json:"source,omitempty"`
	Target       string  `json:"target,omitempty"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindWeightMode Algorithm for path finding:
// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
// - max_weight: Path with maximum product of edge weights (strongest connection chain)
// - min_weight: Path with minimum sum of edge weights (lowest cost route)
type PathFindWeightMode string

// PathWeightMode Path weighting algorithm for pathfinding:
// - min_hops: Minimize number of edges
// - min_weight: Minimize sum of edge weights
// - max_weight: Maximize product of edge weights
type PathWeightMode string

// PatternEdgeStep Edge constraints in a pattern step
type PatternEdgeStep struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// MaxHops Maximum number of hops (>1 = variable-length path)
	MaxHops int `json:"max_hops,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinHops Minimum number of hops (1 = direct edge)
	MinHops int `json:"min_hops,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`

	// Types Edge types to traverse (empty = any)
	Types []string `json:"types,omitempty"`
}

// PatternMatch A single match from a pattern query
type PatternMatch struct {
	// Bindings Map of alias to matched node
	Bindings map[string]GraphResultNode `json:"bindings,omitempty"`

	// Path Edges traversed in this match
	Path []PathEdge `json:"path,omitempty"`
}

// PatternStep A step in a graph pattern query
type PatternStep struct {
	// Alias Name for this node (reuse alias for cycle detection)
	Alias string `json:"alias,omitempty"`

	// Edge Edge constraints in a pattern step
	Edge PatternEdgeStep `json:"edge,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`
}

// Pruner Configuration for pruning search results based on score quality.
// Helps filter out low-relevance results in RAG pipelines by detecting
// score gaps or deviations from top results.
type Pruner struct {
	// MaxScoreGapPercent Stop returning results when the gap between consecutive scores
	// exceeds this percentage of the total score range (max - min).
	// Detects "elbows" in score distributions regardless of score scale.
	// For example, 30.0 stops when a gap spans 30% of the score range.
	MaxScoreGapPercent float64 `json:"max_score_gap_percent,omitempty"`

	// MinAbsoluteScore Hard minimum score threshold. Results with scores below this value
	// are excluded regardless of other pruning settings.
	MinAbsoluteScore float64 `json:"min_absolute_score,omitempty"`

	// MinScoreRatio Keep only results with score >= max_score * min_score_ratio.
	// For example, 0.5 keeps results scoring at least half of the top result.
	// Applied after fusion scoring.
	MinScoreRatio float64 `json:"min_score_ratio,omitempty"`

	// RequireMultiIndex Only keep results that appear in multiple indexes (both full-text
	// and vector search). Useful for increasing precision by requiring
	// agreement between different retrieval methods.
	RequireMultiIndex bool `json:"require_multi_index,omitempty"`

	// StdDevThreshold Keep results within N standard deviations below the mean score.
	// For example, 1.0 keeps results with score >= mean - 1*stddev.
	// Useful for statistical outlier detection in result sets.
	StdDevThreshold float64 `json:"std_dev_threshold,omitempty"`
}

// SortDirection Sort direction for a single field. true = descending, false = ascending.
type SortDirection = bool

// SortField A single sort field with direction.
type SortField struct {
	// Desc Sort direction. true = descending, false = ascending.
	Desc *bool `json:"desc,omitempty"`

	// Field The field name to sort by.
	Field string `json:"field"`
}

// TraversalResult A single result from graph traversal
type TraversalResult struct {
	// Depth Distance from start node (0 = start node)
	Depth int `json:"depth"`

	// Document Document data (if loaded)
	Document map[string]interface{} `json:"document,omitempty"`

	// Key Base64-encoded document key
	Key []byte `json:"key"`

	// Path Sequence of keys from start to this node (if include_paths=true)
	Path [][]byte `json:"path,omitempty"`

	// PathEdges Sequence of edges from start to this node (if include_paths=true)
	PathEdges []Edge `json:"path_edges,omitempty"`

	// TotalWeight Product of edge weights along the path
	TotalWeight float64 `json:"total_weight,omitempty"`
}

// TraversalRules Rules for graph traversal
type TraversalRules struct {
	// DeduplicateNodes Visit each node only once
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter edges by type (empty = all types)
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information in results
	IncludePaths bool `json:"include_paths,omitempty"`

	// MaxDepth Maximum traversal depth (0 = unlimited)
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum results to return (0 = unlimited)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`
}

// AsFullTextIndexConfig returns the union data inside the IndexConfig as a FullTextIndexConfig
func (t IndexConfig) AsFullTextIndexConfig() (FullTextIndexConfig, error) {
	var body FullTextIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexConfig overwrites any union data inside the IndexConfig as the provided FullTextIndexConfig
func (t *IndexConfig) FromFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexConfig performs a merge with any union data inside the IndexConfig, using the provided FullTextIndexConfig
func (t *IndexConfig) MergeFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexConfig returns the union data inside the IndexConfig as a EmbeddingsIndexConfig
func (t IndexConfig) AsEmbeddingsIndexConfig() (EmbeddingsIndexConfig, error) {
	var body EmbeddingsIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexConfig overwrites any union data inside the IndexConfig as the provided EmbeddingsIndexConfig
func (t *IndexConfig) FromEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexConfig performs a merge with any union data inside the IndexConfig, using the provided EmbeddingsIndexConfig
func (t *IndexConfig) MergeEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexConfig returns the union data inside the IndexConfig as a GraphIndexConfig
func (t IndexConfig) AsGraphIndexConfig() (GraphIndexConfig, error) {
	var body GraphIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexConfig overwrites any union data inside the IndexConfig as the provided GraphIndexConfig
func (t *IndexConfig) FromGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexConfig performs a merge with any union data inside the IndexConfig, using the provided GraphIndexConfig
func (t *IndexConfig) MergeGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlgebraicIndexConfig returns the union data inside the IndexConfig as a AlgebraicIndexConfig
func (t IndexConfig) AsAlgebraicIndexConfig() (AlgebraicIndexConfig, error) {
	var body AlgebraicIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlgebraicIndexConfig overwrites any union data inside the IndexConfig as the provided AlgebraicIndexConfig
func (t *IndexConfig) FromAlgebraicIndexConfig(v AlgebraicIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlgebraicIndexConfig performs a merge with any union data inside the IndexConfig, using the provided AlgebraicIndexConfig
func (t *IndexConfig) MergeAlgebraicIndexConfig(v AlgebraicIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if t.Enrichments != nil {
		object["enrichments"], err = json.Marshal(t.Enrichments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enrichments': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	object["version"], err = json.Marshal(t.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *IndexConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["enrichments"]; found {
		err = json.Unmarshal(raw, &t.Enrichments)
		if err != nil {
			return fmt.Errorf("error reading 'enrichments': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &t.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
	}

	return err
}

// AsFullTextIndexStats returns the union data inside the IndexStats as a FullTextIndexStats
func (t IndexStats) AsFullTextIndexStats() (FullTextIndexStats, error) {
	var body FullTextIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexStats overwrites any union data inside the IndexStats as the provided FullTextIndexStats
func (t *IndexStats) FromFullTextIndexStats(v FullTextIndexStats) error {
	v.IndexType = "full_text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexStats performs a merge with any union data inside the IndexStats, using the provided FullTextIndexStats
func (t *IndexStats) MergeFullTextIndexStats(v FullTextIndexStats) error {
	v.IndexType = "full_text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexStats returns the union data inside the IndexStats as a EmbeddingsIndexStats
func (t IndexStats) AsEmbeddingsIndexStats() (EmbeddingsIndexStats, error) {
	var body EmbeddingsIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexStats overwrites any union data inside the IndexStats as the provided EmbeddingsIndexStats
func (t *IndexStats) FromEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	v.IndexType = "embeddings"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexStats performs a merge with any union data inside the IndexStats, using the provided EmbeddingsIndexStats
func (t *IndexStats) MergeEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	v.IndexType = "embeddings"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexStats returns the union data inside the IndexStats as a GraphIndexStats
func (t IndexStats) AsGraphIndexStats() (GraphIndexStats, error) {
	var body GraphIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexStats overwrites any union data inside the IndexStats as the provided GraphIndexStats
func (t *IndexStats) FromGraphIndexStats(v GraphIndexStats) error {
	v.IndexType = "graph"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexStats performs a merge with any union data inside the IndexStats, using the provided GraphIndexStats
func (t *IndexStats) MergeGraphIndexStats(v GraphIndexStats) error {
	v.IndexType = "graph"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlgebraicIndexStats returns the union data inside the IndexStats as a AlgebraicIndexStats
func (t IndexStats) AsAlgebraicIndexStats() (AlgebraicIndexStats, error) {
	var body AlgebraicIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlgebraicIndexStats overwrites any union data inside the IndexStats as the provided AlgebraicIndexStats
func (t *IndexStats) FromAlgebraicIndexStats(v AlgebraicIndexStats) error {
	v.IndexType = "algebraic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlgebraicIndexStats performs a merge with any union data inside the IndexStats, using the provided AlgebraicIndexStats
func (t *IndexStats) MergeAlgebraicIndexStats(v AlgebraicIndexStats) error {
	v.IndexType = "algebraic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexStats) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"index_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t IndexStats) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "algebraic":
		return t.AsAlgebraicIndexStats()
	case "embeddings":
		return t.AsEmbeddingsIndexStats()
	case "full_text":
		return t.AsFullTextIndexStats()
	case "graph":
		return t.AsGraphIndexStats()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t IndexStats) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IndexStats) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963IbR5Iw+ip1MLshUguAoCR7vJhw7KEpyuaMJPKI9HgnBg6w0J0AyuyualdVk4QZ",
	"jNhHOD/2Nb6X2if5orIufQUBEKCsb775Y1PoumZl5T2z7juRSDPBgWvVGd53VDSHlOKfR8kMJpKy6JTH",
	"cHcs+JTNzO8xqEiyTDPBO8POBXboxSDZDcSE+k5EsRgiKkmEHXNJTYc+Oc8nCYuIhF9zUFqRlC6IyDRh",
	"XAtiZyc4GLbvkts5S4CkVINkNGG/4c+KSEgp4wT4jHHoiVsOcb/T7WRSZCA1A2VXahY1nkqRju3QzfX/",
	"NAdOtMyha6cFoudQ2kZEMzphCdOLsCMzHrbSdJKAW3SfnHINktOETBkksSKUx/V1kximjDO7BSqBcKFJ",
	"ZiFydH5qdqAXGXSGnYkQCVDe6XbuejPRM7/21DXLegIXTpNeJpiZsDM0i394CD3F5BeIdOehWzvAC021",
	"au7/WKQZjcIqlKaaKc0iRaZCEspbTpSZ4frkLWjKEoiJzLlmKXQJjWmm2Y35q2XvEiIh43B0zIMrZnTG",
	"Bc7ZPEIamQHHmRQzCUqNEzaFaBElYD66HSstGZ+tDapuY1ApbpX5VwRKQWxGngqZUt0ZdnLG9ddvinMx",
	"A81AbjGZpnIGGufc9UwO/OMJja6nLEkYn40jkXP9XBNFBkfzbGyONk2BxxA/74QBis86iwQaL553CqVp",
	"As8yhT/8MdOQ1tC6evU/5ukEJBFTEosoTw0LIKE5iXNzq0iUSwlcEz9sp/ssi/UH21zld64J8U0IVYQS",
	"5CeWFA/6A6IFOewPyouLRT5JoFgcx91usLaC8hdUx5ybztUGbLDEP8IoXaStcEfTLAEP4S5BnOgSIYmE",
	"Sc6SeGy4JJOWtT2V2MVMXY9zRWfQsmr2G5jzN8wMqTphnEwWGtRujxmkFLI5/Yn5maSgzOoImyL3USQS",
	"eRIja5wAkaAlgxuItwDBHGii54sSy9iUvXY7CJ6x7V7fx1tm/pUyTrWQeLYFQO2WbqhklGtzjsDztDP8",
	"eyegSOfnp+8soUqPEbqGaCmzmqezxYxKBW6056BMWUI5Bzme0iQxF/9ZJ0HIxBAxxSxUPNwVJBBpxCe/",
	"kG1OoDIfKM2M2GNursoTPZ7k0TW0iV3vqQalS3TCjUNsx57tSPyAAanMNMRvwZAKvwfi99rf7dVdsj8V",
	"UR5kmDW3Zvr0pLj90nYV8HEHV8iPGxjGJBHRtRHEnmNwFFS2Imt+zHArdnsbHSMz+2zTvPQcLAIE1UJ5",
	"dpgsSKlz9+k7DLIpaiEFzVkmC5XnD1JtWQua0wzUjvHR6pDjG5CeXO1wcC00TcbIjtYVAyVM3WVkvKYQ",
	"u6Pa5f7xlKykYyh0idX+3KbWcj1NFpeOExdkncpoPqZqvBC57dztXMPiVkgUHeBOd7qduU6NBMvzFCSL",
	"Ot1OTDUY5bXTLaFWwvh1p9uZgcB12j/x3A3/TicQO6ScJGLSZB4PXSMRaMoj+GCkl8jCfErzxEAreTVW",
	"v+ZUIgtqCBLYjaTYL9DHG4iMZGElir0YuAIieLLY75MfFZBRJxKKcRh1sEcqYkgU0ZIyDjG5ZXpObAOi",
	"WMoSKo00ugf9WZ8cvz8975KzDPjRaRiNIUnIpIjzSD8yaCw0ca1KI/tRin2OOmbRuP/9pYOd5FHCYqCc",
	"xA4KZWmpArTK+jpdt/ttuPhJ3CYeHxHTNe6SW2CzubkNkeAcIjRnTEDfAvDi0jRsF5EE5JVULzM7zYFA",
	"PANySxVxrSsqDNXQc9j51J2loGlMNVq+aBwz2+y8tFA0ftWWd+aGs8sLY9Rv4wYETuQygjbtTsHXb3rA",
	"I2HIrG0WYEquYVEGiFFNtoCFNb2sXIRt9myLaFUhDAIittl72TV3mmlQo475012usRb23zTXcyEhHk8W",
	"o87+FovJs3gDFEUxzXXZNZ7aK7YEMPbjAZqSYzAEcq9Q+vd3qPXXOJHD2oA5btiw2p+ffiHMvt4yaYlJ",
	"lUGIXLdwBtfU8GlzIMrs/tcc5GI44j0icj0kZ7meCcZnrkGwU3MRg2nE+JCc8kikRRstKi0mQs+H5Duh",
	"52ZEOxjlRgoo9xrxEmW2q2UcOaieb0uFDV9f5ms4LrsSrH2aqAwiNmWRxVJ3PDUbcpKIWyPhTseJEJmq",
	"QLuN+gXJVBDsW4YnRViZT0ybIbcRTdFR0GJO8IQHvxueoynjBvqOMuEKrmGxpyw7pbkWKdUeCMhJjM40",
	"4hd5lgmpFbFnQfYU47ME3ED7RtWiUtKFwSrbRJG9NE80y0Irtd8fcSQGImVaG35o4ZHmCk00mRQ3zBBO",
	"uMsSFjEjO98wSsbYrI/Y8mT2Re/GZdLgTu2wfmQf6B1L89Sel1lKQTZ2ahRMGW9bz6CxHsY/y3o4TR/l",
	"Jua7ZykvkKO86JIXBT950eQeJRo4LksP1Sk+uSZBOPBuLyuzMlW5kGiLbuq+hdcKsRD/LTKRiNmiShJn",
	"kmbzBlG8dG3NFVEoTOqW6ZE+agkwJBcW+zOKJu0MJF6lLuGCoEKtTFOca0g+itKwqhBgK8TPDGvUA1ze",
	"kylfjevgmbZpPide9VCPumR/5GzKrLBaI5dBd1FWlwDVJ3izFdr+jPptXaFWGFVIX/FLVQO5OH9/9PaE",
	"MH4D0iqJMdztN8aa0kRBAbnysFaHqY76w8eLn/b75J2Q7rNbY5fELAVuNGMSUSN5e0pE2JRQ7rYF1nzg",
	"Ng0x+Z//+m/CNLllSWL6GCrZi0GjXtv0NEbznF+PFfsNqpRm8OpNdx3HCUiSCaUNlU2Y0gTHI3sOGqit",
	"dZB+GLrQGX79ZguNHscGtKj/i4RpZ9j5w0Hhxz9wTvwDbMb4bHxs2zuEQaeAA2gTe/5qz6QA+bR+Hn0S",
	"Lr/1Y3hHbrXRcfWoUO+jnM4grrYktwZrlh/jXuXgkLNkUkxgv09OZ1z4ZXi0c9OXYX24Bai9MjpOgyr/",
	"GMhriv+DtxesPqzibo5PXJfivDyMK6iJ16u7PJ6hdNupBKLyLEsYsmk7WGDTpXY8LvkuYgEK/TAuMiKT",
	"Is10EISseGLoLaRZQjX0n0EYeoeTaGFWLWmky7vCdex5pPLoZK7an3DZnvkigvldf2vm20Zn8sy7YtNR",
	"6Tij0XWbTadJ6ZQWks7Q/J1S3SdFb6TAcyAJzGi0IO7HH747DrTF9IU+UTBDujOeUAXjGBJN7SdFWJrm",
	"NjLF9zFtQvgFGltolgGPewZUxHV2A666VMEgU95xy2q20QNSSMdmaY/YjAXJcV29FFIhF3joAa5lC9k2",
	"KLmpsGfbEj2XoOYiqYDQIQBwLRmoBl8IEuE0EVRvIRDacTeiEw1m7/j7fo3BO/6+kqtbRl5B+a0og8rT",
	"lEr222oaapRBNRYZcJqxsZpTI8POgIORgfhs/L39U5Qoq6ddTVz7gfI4gQmVKhA4PNBivEAQn0aD+uQC",
	"gMy1ztTw4GAepvtF9SORHsxyFsOBs5dKg+wWSZw3zIUPmIVCkoguub//A5uSPfiVfDRC/6jzZzHno87+",
	"w4P5g+o55ff3kCh4eLi/N03M/w/Y9OHh/yF/EznyiPv7oxk8PJAFmG2LZKvIAy2y8XVNmGpSR/xEeBCp",
	"rAMULRMSdC65JfPWvr9cnjrcxvuwStJeEjt30QiWqwvYgRR5OrDfkDvXj9e5FJomBJs143T+74vP+Wdg",
	"y+6DUgr83YZ/r+v1tYsBLlk0h5rztxTDuA3vWNv3abmVOig0Ouf5xL67xRq7KC5iUMtueUEPsVllMXX5",
	"Zucr0yBT9Riwcs5+zYFgu2JpZVlhuYCz/SJvaYIhromYrRnUCDxG4zViGppW3aJ/Onr/+zmy3+VJcgl3",
	"umbMqbKHtWVhKwj3yoLwbsPJK8sNHPGpzKztnNw1rYeeOnLy2TnbuWdoYkoEt84QtxbD46ZGHWWCk78P",
	"+oOuYW8//5O/feH8bZonhrzd6c/H3p4hpOkJAT3Pxcw2o3jfS5rNH7VdN118aFt3sGx170E8A5yyLRaR",
	"Ke09ptjb2T/0HFgtNUmV3RSPKZk1L2WLDyOld9b3Nc5Ajv0hNFfnnVYFs7eOtQxkEX2wNyDfkpwnLGUa",
	"4v2tosy+WEW6WBlhPMs1MXe0P+I/KlAFKHxiVWkcvOOTBN2MF0btzag2OrZpVChxdpWFndL6cIICfX+v",
	"mU7g4WHE7+8jwTVw/fDQ2cKd8wjmr6dLlrC+xZ/tYvHG1u/UjFsKwXp2GLiDKMcLZSPhcYaJyDGyUUHK",
	"kN1qSW9AKpo0fSPhU5PjG3Cn2bqRow+loOs122dS3ABft7WEX9aPY8X2GKcdZPHVfZqn+/D0KJCnyEuW",
	"RnxhstInJxd9biNAlfi3B7ithwl1PpRzXaXIZX92437/owlKW3q0vxghCY9vtZLt7xQuyQcb/J5C0kcR",
	"wwXG5Leh1VuYMg6KzMWtuVQ2eN8cptQHpRihMiv5NQfJoBmkeg2LFvicuEge68p2VgiCbdcO5tggi8nI",
	"NuuIR3ZTxY5DhJuEKUjgEcTefrwNvTPTjKcs0asFJXNO72zLgptg+yaFdEu060drdsnWbVR4quwOMWJl",
	"1PmXoK24dCI16pAetjRfeuZLbSTXseRLdh/6Fuk4TSEM4hw0tbVYa7uPqsNuW0RwbcEb8R78fznIRdsF",
	"iBJquMsNlPB7Yf3ERtgBQqcaZAGog8puWy6CFS7biBWL5l70rDklyrHfO78VjEdJHsO4mKTpHAdt1pYn",
	"SUnVK+584yo8Je3RLmIJHT21ny1vjLEggF0A0GiOyLzd5B5nmzN/X1ILbZCbD0e0ezfDb+Plz6ikq3XB",
	"AkfPbXvsiRpIiz3JqSZKQ2ah5JUVh7y1WLnHJnZjXWjItkAxi8tjmjCqYCnuu8915K8ufs9oAQvyLaFJ",
	"sv8c1wG5WyGorzyVCgcNwf/bDOCkq/XwAfOT6pzfn3CB1z/vgj6eB1ytI5ykKWiQZaIQdDkM9smonk8Z",
	"d8JWQ88Ukul5uuz2hQaIGjkPgaYZnYGk/PpFl7xweTIclHqxzYUMk42Lq7l+QksNFEHMK/awRXJLDHFu",
	"5CWqYZlX5xOk4gZIaOdEmb1wGlsFqsTlRIJVtqsi66ChP9VDr4xcQyaLkvnsORmdwcVHeIz5XA6C2BXw",
	"rh9TtnFNBr3NJSF71z01F1KD0j38spU5LqV34xgyPV8u+haX1TbccjYvEKwhantxsBXIT5t9WYqPn/xz",
	"xey3hW49W3z+U1UJu5ZxakSo1bLA/Cds/sG03o3M/QnPv42QWbwQU0LLoneDe6RUo5y9VAxyDcheXRJi",
	"oPY3lIM+mLG2IEFLqbbC4CT8uuaKEIS240c8jicvagk9dIuylMkDzzPxpwBwG8BpIVroJ2JQyezscgPD",
	"tVptT+kMO6ZT/63zzmxq+Flt8tmBnWB3EqFd806EwctWI6D51ey6XVmuZLQguTc/cUNTJkIaGHm2h0y6",
	"0+1cjyu/oDrt9J4tjIb1u9OSkY2GKMYrGymOsl7/r5W5hix7a+owekVNVX16mkCLDuVzx0OTnQYJlJyL",
	"60vD78oWA7LHpqRhbKiHyW+MkUssBsc2g96lxCmyh4GxFTNDmHptd+wWBOwaFo9kYNrU76fbENrQ7y+w",
	"QFMzyrMlFMRUXKY8Ku5czDbzLbPjnHj797qLWsVStjwV6/Rrv1CFd7NoRRI6ATQ9JTGGoPl1W9LQteHX",
	"rugoxEanqZS2LPtJhdw99GtU36DVFsR+wwgKyoMjWXA4m3aGf3/8ANsC0x66K65ha27iql6NgJBVHVqL",
	"0j783KT8JZDcLytuUfq5GkyFKe9akSyXmVDQliJbxBI+FnZSBBxymloTGs2yBHlvYbGdwNQG+Mdwx/is",
	"T06KwUOWNZaOhZhQXao9m8ANJJVsgL93FKSUaxaNMf0PmTdGVyDK7ZyqtFtnMQOhDNI2EK4jPuExW8mp",
	"2ymVR1qeCf5X28jPHqqKOUejgZIBrL0eQjaSsYr002a2bNcSFaaIikQGsS+fYPuSG5rk0Ccup0FZf/fO",
	"khQaKcJusDYf4mZZC/6E4rKn2OpwWeY8uEW5wrVupp27Ww4oX49w+I5FpN46RMr3cgExq4iNbf4QqMbi",
	"I2Jx2TP78CRi6QfeiFau16m5+k0opeuzFFeWaA1zV0agfJXb4ykrR90NCfuPVLl86HY+gJxtUO3DMnMy",
	"zfGCI0uPRDqxtTFC1QrnzyzlLFZ5g6T8eoyp/bQtKO/Tp3fkmvjvZO/wYO/630yf/f3q1f560B/0dyrM",
	"Ky2pBlv74LGjRbBd+MbBWLReCMySVTYiYMyViJ1JTBlB2IpNhcetT67C8V8Fq3rDM40d/jTiAT1KQ1gK",
	"VE4UxEC+H7nzP5cy6hzBdzFEfXLkkpkZx6I1xBybYdufLt7Vwvvuy7Rk0H/d7WC0X5H23BketoXs3TIe",
	"i9tSRYAKlly8I9yANJQ3t82JaV7FkysMb7jqP1+2WhUfKonJUk4bGcnYnHhkwyMorlElDMAyUCdOuPM0",
	"QC4CE+yP/RGXcjoknyBimRQRTcgnyq/JO3tTe258QL4pQZFc2blCc3PBkI3mCR1xqXCwxDr4L0yfYiwP",
	"9mK0yYKkjB+k9A6jexkn1B+HWW2YPJRxs/1GfEpZIm5ADrFkXX1XhE0LGSBEqxpaRFlSLYJkwSzVFKvK",
	"2kFbKV7JyLvM32I9Qy6ur+6zs4CDO2Yzu639IzNM24CqLarBjDnOJEzZ3WMunmsw42CrLVLj7Wy/+qCN",
	"9S0StqhjYZialmGxp4w4qRZc0ztClacs5dmebqnYwlp+7vT7Zjw6/vG5lOUE+MwuZKuIpxZR8UzGICFu",
	"RoGRvUmlZt6zePxtBF/hudlhkbdtTtzXiqznaa1XZ3H7AorbVz/ctnTh9jX+vpCjfMd4/MkahZon+txO",
	"9Wblumfxrl/X1eXUuls7w8PBYEdFcmqe7FK2f5jsq13OtXtEqnuJdyjUL6l8emFLnXqS2kZRd13n9LJa",
	"PnCXU27orjYXr+ayfqzu5s+7uOben1295cHJ+jm8pTjZeCpyHm/Frl2xa81SGKfqufD192M022PTtuhS",
	"Gq6iTxkqMReZaihVRyEWznvkiXPJYzS37zckF85vattMFmQuMoJV6cneRAKN9bw3ZVJ5BbpLGBZk8uqL",
	"2sfxAhUcErNmm9boqG0oyu0zH70Wv6e0FHxmZi9Vso7mlPF9v8qWUV2MjMrT5oiJuLXDKU2kyDU67rxa",
	"VIJWiWxXaO0W3uJa3EtboMncLRTr2DZOqP2AMCSI/Qb19JA6gEK7FrjUjwhDnEzbJSdTUSbLUCsAVQHh",
	"dlDTILkRWjB6uL14aLn0JerTWSl4uelof7KoZPY0r9fkXVrdtTgR04fsjfLB4DUckm9DHmjPKkN4vPud",
	"ZxE5VgavOcV05zFsa8DJ3dQ6nAyE7BnhOncHmM0i654DMEvE7JMi4VsLbz+BUpQ6X+w/i5t3C8ZTBLK1",
	"xL24ws0YNOcLMFYi8JuFpSx1e9QqvGEgWx31MwwDTBhFKNuAvrgWS7MxJNqjJmyEgj9I9y4JU3bSzxaZ",
	"sP0Bt9PcI6SrltJak9/jZ4swX+J2DRWQUc7fk4CpZXhIaOpdRAnm6lgivI3QD84SskaAZmA3T4+J3Qb2",
	"MudtFtemiymTOZrBa0lxRlGKieDWckx+zWnC9KI/4j9AkilvrRS5Jom47UlI4AbDUnx/xsmno+9JxjJI",
	"0BQ9Wfgj4LMRt6POaKYIep9vmHvm1lrhReYHsq6NeqDt3RgHGM9oNs5ARq3FJi7sMDqXFTv/rX/lYUaz",
	"8KaJ4f4Yu3kDwVYOdxFArCxquVnoLLgG0VjnwCMpnwHZS+kdQZFpvz/ib3G3iow6kEzErRp1DFBs+5gZ",
	"1Jvk/mnfGZVx4grv2BYqogn0R/xd8W5il7we9AdEacPhbAlh3IPKKFfk9eBfQwRAsaaaZ+j1YNcsmk6U",
	"SHIN9kDaSmHIuJCncWGhWmif+NhqlLq9bwMScWuBjuEFI04lELjDeLm4BiyBadUFDmuDXqq260F/cLjr",
	"fVv8w3vUFvAGmS3QKhsbJFaE+5YELCYvSW3E+rkP+l+Ra4BMhfFMYxTxNUmAKk3mNJkWmOmvT3/EvdvQ",
	"Z4eiT8l1b8Dpq12Cydk3xuintsV7VldpPTNQM3stUoXnVGP5XnyIufB6ez/pHnpDgxd2xCmPq5m+9pmn",
	"aZ4gwWM8kkCVrWbqHtsz1MkuF6kTnUnAmJnizSM2xWRm7YsX0ISkoOcirj738IRarzoex3AzDrdiCTqV",
	"MYlx8pEoTXlsbleJevq7AyQF6ohNHZkO+4MaMrUhp+neI4cvlY5juLGFaTwEw5PZNDEcIGEgC/ZqzsiF",
	"LSjQ9at4uEsUa/MMXwipa6/MVG2QUpOgvPkXVaykiRnPfSwRbLQHUJGtotd1BYC/JdT/1FLd1839rr2o",
	"dxBnlVmArSNuXxTza2l7zF1Fqy9MdUfbLH9JPfLLuQONzTrWwu5hsmhWyq1bNe2IbSE4l96/uyzrJgDM",
	"h8AYuaDmG942/N1Wmir+vVW+19Pi0kPcNT4ossemJBG0apneWPZrDfCuvfj1TE99tWsyF/BrjnUgxNT6",
	"UpeEW1fi8tFy3AyMf3ylzxMrXl5/6WGkp23gGSP76+7jRnHHVhMpTQSfIc9wmS7P9LSYxTR7RbdwbxSU",
	"I09aM9jMz23Z3y3UojWJ+ZFnsv7KFNNFpQcr4gmb4fJlpjJbdJ0s/Et7RckCayva/0zpzY9xsKXpzkGS",
	"2KqgR7ur9nV3vQTkXVYjbCQkB7fxYNlqmrXhd7yeTZ4a+wwW300en3jW5WxhewmPENkQr+pTRPZ1vjWi",
	"rFsLUlbfN7JpHTYwumYty9g4l0m7MPfjp/deUzzlvkTT0fkpAR7jXkJVi7nW2fDgIBERTeZC6eE3g28G",
	"L/btS0c0UYJMwEj5+KrO0cfLd+//Nj79+O7k08nH45OxmQf4DZOCo6jhPRbVtxxa56jUIpOsjc/ji7pV",
	"V+WU3bU8R2O27OFm3+F11af65ISh+eAFdnxhdRvMlyBaXAPvWSOY79zFxwPdECgLoxhgn/Y9cC9UqYN7",
	"8+nhoLpLv7TH5WW7p6a8/HN3pRnPnKYLKWThUMO23YOFsj/iI95oxhShJAKuJUaZxuSHy8tzokDesAis",
	"/u0GUMWQ1lFqlPGeNgpgRKO5NSkYgJeAlNIM6dfZx4//6X63LE/IhYuJ3nPP85lmc3FLzpKEppTcCnmN",
	"bzGO+MuXx37iDwjv4cuXI94jCNchubCnhv/qKfZbaeuG95nDDB7nnCW6xzi+gYdr8ieADuEjvnBGJVw8",
	"PqXmKn6a1Rnp/NFjL/bmlm3B4pb7/nBIPtj3ewy8wELxVS9lPNdALi/fY6tXQ3IOUjGlzb05h8kkAdQQ",
	"DEKaFvZZv2mCtK+QYzwyRIL78pgsBm41dZcLqOqx4oFWLL2Khk+41Cob1WSvXkBqj11GVEDc8s+PD+87",
	"4gZkQrMxnoHrryCj0mbcdAyUQthLqdXg4aFMSh8houslrTxKlB9+bpLQIjY6WK7WV+ua97PIEvBJb/j0",
	"PkLVCDrfJXAD/tnRTILCPGW4AW6DsjO92O/69v6BP3z/yhkShtFUD4nKp1Pm0vlcvVQ/+AtF3Ck6S4eb",
	"jE7MXGHsXAEZRpWRqHSibq7cK1n+baeQAFMxgm3uAAsItNnzfue+H9rRhISApqtkzmPBtRQJ2tHxttvH",
	"C1ELt9Z+vH2Y7+by5ZY+BmXhZoDkIuYt0N07XQaACLz643R4dm5Q+ywVGjL9cDxe0mOrNw7K3CZA/ecm",
	"gzki+dI3NWkLX6mSlG0JxJrU4LyENo/wfD+7Z/vlwBMRXXe6flFt6QulwpKWctSeKlzDw9bKmos0i5W8",
	"2f72QhHPusiH94E7mwmQYJexxeZMFAzXXM/TEhNvzfFYwtDJnkPkfwu3gmvPlN8B1bkEz43f40LMvE50",
	"apvI8kF/PUpsMGCa4XaBFZZmrXNC23l7fmh2cmKxt5AuyGQGuIse8N7NYf8rsvfHr78hMUvVftco0D2j",
	"h7z/0Hv/de/mFdl7/c0b+9GMZ0fBW2vteUV20ZUTHPwrmUFyuCpEh/4mHPpVp+DI9TW33r2H7k61hWfX",
	"Bl5tpg3UN1DgYEko3fNS6bLTKA5jv7rCFhA/Taiv0JbvIJYiun4icfnpgrgBltEVfFbAt40k4C2giY2E",
	"HLYejOqSW5i4C6MXXWJ10FJv1SUnxxdEU3VNpMAehm2dHL8ijDuTO/7eX3bHIjEHCX1cdO/mTZfQlP4m",
	"eF8zTXnP/mwYRe/m1XBgB3krIuzqXxGMRaT69Fb1XddIpAcTC4yDhGpQ+iBXIO3bgva0e8o+Eg9xf67T",
	"pJ131ZZWvUlugo456Zk9mlz1gCrdO2zerwnV0bzloeU2TRXbYk5l9f3qQK4M0hr+jsGVei5FPptnue63",
	"l3hf/urxWa6zXNdePW5ikYWYVQId2KqEOgygVixBtRU28TE6or4ajG9wfCwDfnTaM/Ig1czMWZNJsFJx",
	"++z4tsaSMvHHeMJhz+4ZjkUGXaLyaF7k3YUaQV3/A8YodUmUUKXY1LEatA9ESa40yKqTbS065ddhqdTp",
	"W18jO7xlX0XIF13y4rHb8qJGt5r43PII/qwVVS4d3bDfA9nxC/aiiF9ouAn1JRRXpGVy81c25nA7xnih",
	"td5z9a+BYV/C4ZbYWKPAbIunVXzJkYDZ7T5QLXMetb7pUsMW35BMYE5vmJD93TACO83T+IBb4jLR8vwU",
	"c2AMd74yLP8aFlfFk9ZXx2c/nHw6GR+dn47/cvK3q3ZmvYyQW7QCPkuYmvduXvcHQUXqksPBqzdecLIN",
	"UcxMGJ/lNMHWj9B2h7iGroei95ZfVwl3+ap3ahe3JCI1V1ol7Xa6diGp1bN6WUDegbhdIqrCd6ks1LgY",
	"dRLmrZ3NLda8lq6igOX7vqiFvRFIch0TKeuZZd2oOX6Z+HW6nSr1wx887WtVpVostq2H0QQvLxXXaSB5",
	"xaRboTetozedXJUr71d28vFtYyk/2Mcn7LvFFpKKJILP8GUPaqMKU3rnDI42ML8M0o9nH0863c7F5dGn",
	"y04X5/h5J1SjSS82tY+VBvteiFkCjSf51+7/V5Aa7p7e31p/t+iP8sJ2/T+JXIN8+hjt8vwGA7TygQ36",
	"txor2uycSIpTEbdVELWPTjgXgA0+x8vmBEFFuODWqOneECN7LKUzVATymIkuMVRVdMn523dqvzvi3p6p",
	"g4uAKf4CHydtWjlsAyN0KC0XZAEa2Q8azK60zOGq6+0qWgLVqjQsVaTYGGolaDNVwGMyYZzKhV/yiNfX",
	"DDrq7/tCV8F4ZDQaoDGGT9xpfAmTz+yrbeSy1PCFsqyWKaK0mVOCygRXKLii+SyKILOd5xAA9z//9d8W",
	"wtOEzsgvuTJiS5J468+Ic6ELUYdZUHwUmnCA2FllnaxOEwk0XvjHfQIAnXx2VQAm4MtVd8SvZpAyznrh",
	"x96rXibhhsHtVZdcRQnLei/9X1FCs6v9qjiARqCrq6tflOAjfj/ihIwCZx11hmTUwQdz70adrv2IC7Zf",
	"lEihN811LqFXLLDnWvj24YPpZFBgxB9wzlZhbl2zcgshLSzLuzKa8mVymZ9SkYhyIzD4zt6y7x/xQ9Uv",
	"ypUWqPvNxW2poh6VMOKR8E8SG+xtlXrJZRjNKBellwp9tREej7jX9IxgIvLSnZxDkoH0Cr0fi1wslIbU",
	"WQFfvrzAoV6+HJLmS4hoUvQC3jx8/kWhhGfV9H07jPOdmXGKVRt6RHMtUopmvMSZEON2G2KQQofkK2K9",
	"bMqPbm7ena6OLiECdgOhsFMRKEeVvat32u79Ow+SHyxIcPMjftgnL1+qSOaTH3SavHxJesS9hGAx5UDp",
	"RQJE05mz8VtaQiKDtPbMUHv54fLDe4P05OrqqoAS/nJ/H8Ync50m4/CAo++A//cTK3KFUb2RXYCN8L3C",
	"yf0HsyT/u1mZ638Ux8poVVapsgHkkwTtA7akoCJ7WZfE7KZL5oe9+dddkjBHP8MSdC65IllCmdsenhN6",
	"uOQNxvPTmE5YwjR6TF8Z+MGvCLgTl3VCUPWXTBXmXO+IU0th9Ac2JXvwKwYr54qMOoZi38Cos//wcIR/",
	"mgsg7+8P2NRBruj0/xpFadTBghWG2Ow/PFzYv63CVO6F8B7x12bhKcSM4tq/B/4XpkksdCZFmmmCn3yg",
	"7o1lBSUWFbjRku3Y7rlMvkVu9ZZq+uOn07Dw4rNhIn1sM85l0tJg1PG3z0nKePGwR/+XbDbqtPZRr00H",
	"Z/I9mOTRNWjXKePLOk1ZAsODg4OM6vmBFi2TOOARYqiGt8qhzfnCEGfnWUBUuoqppsMr0iM2lpWEWFaq",
	"Kfnx06kKHA5b4mQHv2Qw+5Ot+tDt9/tXHjGvnKX5ihzYvxX+o0d+gomZ30XFB0oTGDUqUiHa3Y/mdmoG",
	"sE4Q84NCqmjr1vuGCEfT7OJ12aLla3LuWUP30DWsA9yo7PsBYEdhccducef2OU0fcIBTvnx5ivKNIXRv",
	"xS23DomukUtQ+9tjUydE7HdJhYMEwIaRjBxnCead9qQL0HxgE/gzswcJ3BZRoorgIYTuhqiZ7p/wzhsy",
	"WB3H2vs+iN9YklDXKlAGiyMQ5dKQBO/A9fv0O7MMIpNC2yKokyDoEeX7+jQhsqfAKJRlXh0erdsfeiqY",
	"JOIWYjIXSpPbOdOQMKXdx3PJbgwDPD23lBG5m5GakDpeXHx6R6jWNLpWHvH8Qq2NF8P4VIlLHQ4GH75r",
	"tNUsBZFXGr4ehCHxfEu208agrwZvvsnuuojNPXfuHo0uAIbB4GI9RH0m0PRyUBFj/uDh1+tFQqLb7A0S",
	"a7yGl0JwS7Txn86Tzsnl2dlHXy127xKjqs4kA27O5gxVWfJR2Nq0+0uJXzEFysh9a/ENJKf9s9O/P1B5",
	"DfJb67ZnPAauv32zqmsMNr5SfjvqjEa6lVz9ZJQipnCH/+GwEHdrw6nM3Y50l8zzlPKe9BjvQBGDYjPu",
	"5PaM4pU1sn0eaRT8EHxakPfvPxhhixBS9t++fPl60Pt68K/O0CAhzpEaoUfFsEp7f/98cfbRYCxmUTOu",
	"qS14OGezuRkYhzXtJcwd5tAoyiWNFv2wy7/AglS8vIhxx3Z3Xma09/ZqaItiXsOih5l7JKNMBmFCSrpw",
	"Z0JSPBQ1JFdG3Pj7H17/PCSUdV39jzTxEswlneQJlR5qZnQjYguZWggFiPlZzoJRy7R9//4DyajE1Rl5",
	"JzeECfOmMM0Le3xwkFH2pOryCALhO+AwZVqViep7cQsSLX6RUFo5SS/OI4T9NXovzLVMgXJFEmxt1hN6",
	"hJHeUWUkK6cngh3qPShlx0Gx372THPp8MFJ95CVY0iPvmCYpppYGlcBlijljFNKEsCMXOlriruXbckX2",
	"jBq1PzQiIPmDK5OItbzxFDGUTpGEXQO5Mqd3VSI2mPHgR7UX7orsMa73h+QU/2kprcpoZA7GHBS3Reqt",
	"batCucJI4UpeYVEXxmf7Q4LZViTEk1lLuMMZXGp5LC44dFHruXK3+sp3UAVT9bZt65HyAPJCNRZSNfvQ",
	"NpsC33oR5K82HuoC8Rcb0lzPhRySP1MO5K2wPLAd2fGTr6ZnuQ4hYCXcIXnlfjCsVQ3Jm68GDUrkaq+6",
	"nOvhy5eBDhk1xteRLd2hoNRYVm1L1GK+tntMp7j/gR+WcAVHd+Zla/wtOMiM6Xk+QZFSC8F7dlb82/X+",
	"XpDTSk3y1s40ya5BXTN+MBO2c0XhdKfkta6QRmWDWApY1rjJpT0+I6XaJv3wDv5bqqtfYqrxwyWdKfPh",
	"D5j3UXSkM/XwcH9v2MbDQ5fc3x+YBqZH5VF9XIP5zQg/QRbxJiTBm4t0iTpmToxFMIsr7AzDiv5XMkCM",
	"jS5oGp9LFsGQ/Mv9fWb+Ki3hQ6FvIKBQOnt0AQE8DQ2kZVmlxZQmPS60NYeD2pYgqs1amcwoYvYKPTx8",
	"tzCD+38F1avQ1iKqYSbkAs1NkLI8RY3tf/7X/0/O7b+9gFzqPBHxorTKly9PSg6Zv/oYCGfSuPr+5MPp",
	"x9PCOdbzvh68T9ZiTo5Ose3Z+cnHo6VtrXW63PC7owsMj/GqDao/RdOymnB0fqps1/fvjz4cjX84u7g0",
	"3VzANKrUEvs7VagRT3N4+Ob1m32749PU6Fvm9p9LwGlyQ4WLYu3udv1N5GibYti+qMVbijjbQ6OFXXDX",
	"+WhsvDxfBHPXfpdMco3RkCM+LQpgNyxeV3CnQXKaWG5y1Scn7ofQxVpRXSCqIreSaQ18xK2CnSx8aIQl",
	"gZ48XBU1sJX3fRrBIBb4Nr2P3yRWZ7eO5BG/woZX6CX1xrgrZwK70JBZOB32ybEE07ts63MvKbTvC80d",
	"xfML4c0FBbr0NsdVkOyv0Mzwk2S6zucrOxuSezLqWNsODvGRps6+M+oMyd/7/b79GLrYj/1+/2fycLXa",
	"qIsX1dptPyyIJ77BTOttGdggkGY0lff7oVVpwablveVzo066GNtTtYHXuOJB/7BLBv1X5j+vu8Qs1DR/",
	"8OZf5z6GBDSQ75xH3t3dHy3Dr0/3GIR4niTk4Qp1YDsm9bHW/gQd5pkJzlKGJK1yBn9vHfznK5IAvXE+",
	"2XCRXDh1zqM55TOI7XbMwo+pCkToA5tJaz+11ZC4zVNwnUNQJKJDyx21sKjd2yJiebIo9mYNF9ijoBFZ",
	"mUa03HRfisP5S6oTf4dhTVkwT5TXIKbThHEoHoWZgXIe5Za4LAxwKXwUr3sqpUlS9eFj1hRD2/1jtv0V",
	"4YKPxA1bV0mn6xwanW5HIAU2f9i57R9YH1B2uqWAMRdf0N0s9rjVJ7tmWEjgTmTve1z3/lNDROpccKMQ",
	"kYZ7aTA4LAWJvB788VURQNuMBaGsP8ON9GO4OXCD0YxZS0XlKY5a6CxGbXQWIpemfc/lIReRcWbmIj6k",
	"bZlV7HKHv1mEiD+ExyJEquBdP0KkFuXnM1xxW82VFHYiF1FRIIMjJXt//PqbLjn86vXXeLHxZCREIk2N",
	"uhDvt4faGRlDL40fc/s/TkQeE9+0HDLm8s8OX+z3ySfncEMUtuEExFAbn9dghS48BgPR/pr5gUuO9vF4",
	"k3UCTZYM3FhTJoVRcMcsXgNIrjE5fUv2lmy8G3LXqpDab4XIOiHeJTQtskH97Kg8Fw+TsCkKTeHlkv3+",
	"ykDtp8S2tIaDrEn6nFy8hNy9r+dN2Hpo7IZGLm/HcSZMFjVQQsKYy6RMFCuiOPAbc1eXEkEuUhaVQjUr",
	"SQXp3YQ6LOolVM6A7JVD52iS9MzJJ2kt26BJLC03QkXamhn+I/q2eP2lla/WV1bjqJ69LclDQLWiSRIf",
	"CXct3zF3TOULFkhDfV0vuuRFA1D1SNOWzSy/Dp48LNlU9/Eb49a+OiOihCdPSYTwi3mGC9YWL7XuBcO+",
	"T5Un6pryEnniwocbtSvE9Vu59PK1i47lQNWvXn/tb1ujsbuRq+QUox2aM+pbQRDvIIooGNqwjqSirnv9",
	"fr8UsrqJyLuRUOJO71GhpHpGTxBK1Jq5B1Vmu4es5oOzhBQtg68DxYQgkwzJq6++7pKvDl/ZcOOa+NIu",
	"sbSICEtBvYKAWUAulxCWjrseWUIBOGMlnFpJloqjLchS+ZEu2+CFQgEKT7556N4ytSa9al3l89Cr1vjM",
	"DWiW7b+MbpVaBJ8bDcFdBqYhesNQmEa2DOrnRclAP7bqr0cSP539eHny6YlqlgX+wQpat99d2hDpXHfE",
	"rbZ10Cbbdsmvt8APzH9el758M1kijQRNuE+dvmYUt1o0/yqaKGSNLD660yZ1dLr45hTSYcJKKlk9ts9H",
	"KdmUhIQ2LHfho2D31yZ7q0D5KGBcIC8mBU4ZyCC6PTqqkeMeQbG6RLdqhTugK61x62vQlIrWFnSwJlXY",
	"A65BZpIp6M0kjWG/SM3EKq1OKfbuvOMi0ZLsHb093reBpLme2xRmW+/R6cqKnB59wGxLcoU5lweUBVEk",
	"VyCvtjfMdElL6LAP+T7A6OkDDPheIhpFBkLeimPkIms961F24NPDb6BHGyadgxnoXvXkG1VMGvacwhzR",
	"KVkXOusYeoKO3kkXvVmU9dxvVZriTH8NelLKjx2310PEZzq0CIlzNLK1aTBeA/1ELIE+OUrQHIvRglqQ",
	"o7fH1lcueO/74/MyfVG/m1kI6+y1APJP5PDVN73DN4NvaoGOodVaViRPn6onWF185fqVUhSLm2god5ul",
	"qUteQG7OrncLSh8uK2z1/dnZ9+9Pxsfvz358O35/dnx0eXr2sSpMVYZ9VnPUUvrybIapJUapNWB1/uns",
	"zyfHl+tywrVp9uOl0Y4MHarUR1vyHr4qHqTTwiZ/hKIhzWq8vk5J7Ei/e4aqNrBtRHwjrAPDkoQpiASP",
	"VagnXZqtHKIyWHIr3Mu8j879k33/denUWIUIC2T5l2IrO66EFg4G7St52Pg0Hj+Ic5A9l9jekjMRDoMc",
	"JS7w2oZ3BnNoj/wGUhyIlGkj/GDUmU1scHW5vLGy5VVs3P6q1JBNUe2hWi3rfuWzPg4FtCg5n6GI0GlH",
	"B1875+krv4Q7XV/4IxXIUeiJsfRHaFWkHNXq5JG9QX/QO+wPqgbhaSKobr7CvTlKNda+1v22aWorr7ev",
	"OdR4aCScWBGU5/q0PiJhz7VP7HMZPvzSh+wRGkmhXDU9MhE5jynGXZGzUGdrsmjUszMqZCtClCqqNYsX",
	"++A4S2dtlcMscT5rzxdHIz4a8RcuHlVSLJ6r9jdaUCmntlrAadmzjHWYZr4Q11a0x8uSodjb9/YHsW3N",
	"pkJINfy3ZDHofHEVdVbWy6F3S0+nSaQKlPdEaqVm+ZgMM/PnYclHTdHj/E7mXLMUDr6HNKW9172zjx//",
	"sxXNIM3MSLlsLdjgSrxJymORclBYaK9U8Qrp1KtldCo85Pqq9HbYoEG/uh0XnN/y9snl5XkI6/Ux/PgI",
	"TIklV1EgokmiVjycj5W+s/F1C6BF1rsmyoASbVpU0hQ0yCVcRGTjrI3SRQnkaskwy8F0+CiYthPuqld6",
	"LkXGoqffatt/w+u81ERUDOgtRM9x4YpsXotOa5t2ooTmMfSU4Bx0703vq96rwauvBv/+6t9bdQ1Megwl",
	"aNyFLba4XNV4dJ5nubmHK2/u4aqb+7tco12tfh0GU0XOwGB2Z5dfdV1dIYSnXtZSZbP1r+tnZ25LSjdV",
	"Lwj1R9FfflV6N4fDwe5LM/X/eQW/QE5mYyefeDNcGZwd8bBa/aI2dJlK+wrKYmw2lOhFmzaPH+waMeso",
	"dNoVuvx+bFSkKeVxT/ayJFfrVil6hF3Wx2uxyYEycuEm8PZ9dnY7/8mmt1z9zqhFC53YtMbTyinQ0luf",
	"aFXRoVWjWov1rke1YVe7HrXdXrD1WjHU4jlGtR7YXY+8RGbbAXDbNbdtB25npG3FrtatCLT2Zdx9naBH",
	"WXo5brPECV8N3nxTcmxmuvemf9gaH1Yj6YP+Hx82oT2Pp060r3y36RNBii6nUoSi8phT0ZZK8TTSt1mC",
	"xZLt+6SLjYWyWspAm4ywu5j738VIWPOEvup/1ZsmVM1XilclUK90fpZH3VVEfv8Ltkb+H6dQPTkz4TOa",
	"MdrFjc2yEL5gA8aKYPzqvcLvr/uvh38cTP5RrfKlqP5/WJP8eveuLb/hM967VtF5s+SEHdlIasHyz2Ej",
	"MWhvrtxm2N979QyGkvV5d5A2twyRLwbasSlkh1D9clj8l0YlWtINPi+VaFeFN08J2CG1qAWO/4NTjI1N",
	"q5UoFfvYez2UPDzRaT8UNY7TXGkyCVWX49Zg8Ucoih2m5UUSrG8lpo2VuPg5miQTGl0To5liZNq660P8",
	"WfOl5X9SvK0p3s6MtxvTonZz59PTCOqqrmojRbuKOV9tY9hZRPaXFSWxsQWi2MvzGSD+aXz4Aj01D/gk",
	"y1S08A5uxaDz0xB4WnmCEO+7WXiRGeirWYX3D95+hzBhGhHoFOs/VUiFNZrarI7OoD/o43tjjhx1hp3X",
	"/UH/taEP9u19nifJw/8OAAD///j+afTzBAEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "chunking.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "embeddings.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
