// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/go/pkg/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/go/pkg/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/go/pkg/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/go/pkg/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/go/pkg/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/go/pkg/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/go/pkg/generating"
	externalRef7 "github.com/antflydb/antfly/go/pkg/libaf/logging"
	externalRef8 "github.com/antflydb/antfly/go/pkg/libaf/scraping"
	externalRef9 "github.com/antflydb/antfly/go/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ConnectionKind.
const (
	ConnectionKindCdc        ConnectionKind = "cdc"
	ConnectionKindExternalIo ConnectionKind = "external_io"
	ConnectionKindInference  ConnectionKind = "inference"
	ConnectionKindWebSearch  ConnectionKind = "web_search"
)

// Defines values for ExternalIoProtocol.
const (
	ExternalIoProtocolFilesystem ExternalIoProtocol = "filesystem"
	ExternalIoProtocolGcs        ExternalIoProtocol = "gcs"
	ExternalIoProtocolHttp       ExternalIoProtocol = "http"
	ExternalIoProtocolS3         ExternalIoProtocol = "s3"
)

// Defines values for InferenceConnectionConfigConfiguredModelTypes.
const (
	InferenceConnectionConfigConfiguredModelTypesChunker   InferenceConnectionConfigConfiguredModelTypes = "chunker"
	InferenceConnectionConfigConfiguredModelTypesEmbedder  InferenceConnectionConfigConfiguredModelTypes = "embedder"
	InferenceConnectionConfigConfiguredModelTypesGenerator InferenceConnectionConfigConfiguredModelTypes = "generator"
	InferenceConnectionConfigConfiguredModelTypesReranker  InferenceConnectionConfigConfiguredModelTypes = "reranker"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// CdcConnectionConfig defines model for CdcConnectionConfig.
type CdcConnectionConfig struct {
	// Dsn Source DSN or secret reference. Never returned by inventory APIs.
	Dsn string `json:"dsn,omitempty,omitzero"`

	// ExternalTable Source-side table or stream name.
	ExternalTable string `json:"external_table,omitempty,omitzero"`

	// Provider CDC provider type. Initially postgres.
	Provider string `json:"provider"`

	// PublicationName Provider publication or stream grouping name when applicable.
	PublicationName string `json:"publication_name,omitempty,omitzero"`

	// SlotName Provider replication cursor or slot name when applicable.
	SlotName string `json:"slot_name,omitempty,omitzero"`

	// SourceOrdinal Zero-based ordinal of the source within the table's CDC runtime.
	SourceOrdinal uint32 `json:"source_ordinal,omitempty,omitzero"`

	// TableName Antfly table receiving changes from this CDC source.
	TableName string `json:"table_name,omitempty,omitzero"`
}

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: antfly
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: antfly
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`

	// Connections Public connection resources keyed by stable connection ID. These
	// are the external systems Antfly can use for inference, external IO,
	// CDC, backups, indexing, agents, and related workflows.
	Connections map[string]ConnectionConfig `json:"connections,omitempty,omitzero"`
	Cors        externalRef4.CORSConfig     `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table,omitempty,omitzero"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   antfly-local:
	//     provider: antfly
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef6.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthEnabled Enables the health/metrics server. Defaults to true.
	HealthEnabled bool `json:"health_enabled,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int                 `json:"health_port,omitempty,omitzero"`
	Inference  externalRef9.Config `json:"inference,omitempty,omitzero"`

	// Log Logging configuration for Antfly inference services
	Log externalRef7.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes,omitempty,omitzero"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table,omitempty,omitzero"`
	Metadata          MetadataInfo `json:"metadata,omitempty,omitzero"`

	// MinShardSizeBytes Minimum size of a shard in bytes before it becomes eligible for automatic merge consideration. If unset, defaults to one quarter of max_shard_size_bytes.
	MinShardSizeBytes uint64 `json:"min_shard_size_bytes,omitempty,omitzero"`

	// MinShardsPerTable Minimum number of shards to keep for a table. Automatic merges will not reduce a table below this count.
	MinShardsPerTable uint64 `json:"min_shards_per_table,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef8.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor,omitempty,omitzero"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   antfly-local:
	//     provider: antfly
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   antfly-whisper:
	//     provider: antfly
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitFinalizeGracePeriod Minimum continuous readiness duration required before finalizing a split. Format: duration string like '15s', '1m'. Default: '15s'.
	SplitFinalizeGracePeriod time.Duration `json:"split_finalize_grace_period,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`
	Storage      StorageConfig `json:"storage,omitempty,omitzero"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool    `json:"swarm_mode,omitempty,omitzero"`
	Tls       TLSInfo `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// ConnectionConfig defines model for ConnectionConfig.
type ConnectionConfig struct {
	// Capabilities Namespaced actions and workflow uses this connection supports.
	Capabilities []string            `json:"capabilities"`
	Cdc          CdcConnectionConfig `json:"cdc,omitempty,omitzero"`

	// DisplayName Optional display name for UIs.
	DisplayName string                     `json:"display_name,omitempty,omitzero"`
	ExternalIo  ExternalIoConnectionConfig `json:"external_io,omitempty,omitzero"`
	Inference   InferenceConnectionConfig  `json:"inference,omitempty,omitzero"`

	// Kind Broad physical category for a configured connection.
	Kind ConnectionKind `json:"kind"`

	// Provider Provider token for connection kinds that have a provider-level service identity, such as web_search.
	Provider  string                    `json:"provider,omitempty,omitzero"`
	WebSearch WebSearchConnectionConfig `json:"web_search,omitempty,omitzero"`
}

// ConnectionKind Broad physical category for a configured connection.
type ConnectionKind string

// ExternalIoConnectionConfig defines model for ExternalIoConnectionConfig.
type ExternalIoConnectionConfig struct {
	// AccessKeyId Object-store access key or secret reference. Never returned by inventory APIs.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Buckets Buckets this connection is configured for.
	Buckets []string `json:"buckets,omitempty,omitzero"`

	// Endpoint Custom endpoint URL when configured.
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// Headers HTTP headers or secret references. Never returned by inventory APIs.
	Headers map[string]string `json:"headers,omitempty,omitzero"`

	// Hosts Hosts or base URLs this connection applies to.
	Hosts []string `json:"hosts,omitempty,omitzero"`

	// Prefix Key prefix when configured.
	Prefix string `json:"prefix,omitempty,omitzero"`

	// Protocol External IO transport protocol.
	Protocol ExternalIoProtocol `json:"protocol"`

	// SecretAccessKey Object-store secret key or secret reference. Never returned by inventory APIs.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Object-store session token or secret reference. Never returned by inventory APIs.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Whether S3-compatible endpoints should use TLS.
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// ExternalIoProtocol External IO transport protocol.
type ExternalIoProtocol string

// InferenceConnectionConfig defines model for InferenceConnectionConfig.
type InferenceConnectionConfig struct {
	// ApiKey Provider API key or secret reference. Never returned by inventory APIs.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// ConfiguredModelTypes Model types this connection is configured to serve.
	ConfiguredModelTypes []InferenceConnectionConfigConfiguredModelTypes `json:"configured_model_types,omitempty,omitzero"`

	// CredentialsPath Filesystem path to provider credentials when applicable. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// Location Google Cloud location when applicable. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	Location string `json:"location,omitempty,omitzero"`

	// Names Optional aliases for this provider instance.
	Names []string `json:"names,omitempty,omitzero"`

	// ProjectId Google Cloud project when applicable. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider Inference provider type, such as openai, anthropic, antfly, ollama, or mock.
	Provider string `json:"provider"`

	// Region Cloud region when applicable.
	Region string `json:"region,omitempty,omitzero"`

	// Url Provider endpoint URL when applicable.
	Url string `json:"url,omitempty,omitzero"`
}

// InferenceConnectionConfigConfiguredModelTypes defines model for InferenceConnectionConfig.ConfiguredModelTypes.
type InferenceConnectionConfigConfiguredModelTypes string

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir,omitempty,omitzero"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls,omitempty,omitzero"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef6.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	GeneratorConfig externalRef6.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef6.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local,omitempty,omitzero"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// WebSearchConnectionConfig defines model for WebSearchConnectionConfig.
type WebSearchConnectionConfig struct {
	// ApiKey Provider API key or secret reference. Never returned by inventory APIs.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Filesystem path to provider credentials when applicable. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable.
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// ExcludeDomains Exclude results from these domains when provider supports it.
	ExcludeDomains []string `json:"exclude_domains,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported.
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeDomains Only include results from these domains when provider supports it.
	IncludeDomains []string `json:"include_domains,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported.
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred result language, such as en.
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum ranked results to return.
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Region Preferred result region, such as us.
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Request provider safe-search filtering.
	SafeSearch *bool `json:"safe_search,omitempty"`

	// Service Provider-specific service flavor, such as agent_search for provider vertex.
	Service string `json:"service,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Provider request timeout in milliseconds.
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963IbOdIo+CoIzrchyYc33dxuftFxjizL3fpatrSSPJ5vmw4SrAJJjKqAagAlie3Q",
	"xj7C/tjX2Jc6T7KBxKVu4E2WZ/p8OzER0xYL10RmIjORl6+tiKcZZ4Qp2Rp8bcloTlIM/zyNo1POGIkU",
	"5eyUsymd6Z8zwTMiFCXQKJYM/kNkJGimW7YGrRuei4igdzcfERdIkkgQhQSZEkFYRLroI7knAgmicsFI",
	"jCYLRNk9YYqLBTq5OpfdVrulFhlpDVpSCcpmrad2izwqIhhORgpPErJs0o6kMUHQBOZWguAUMZyS4KCZ",
	"4Pc0JqI53Om7U+S+It2vi84ZVRQnyQJlXKqZIOGFZvkkoRHW44z0xM2xr9y4paal1c4EzzPKZrBs9DAn",
	"DOEs0w0nSXgbMuFq3VyCZH6uKBeSC5gy4WqLeQDGIy5iynDSnOz/IIJ3JliSGNk2iE+RmhNkeqIHquaU",
	"wS9wRjsSaUCLnClqjmjKRYpVa9DKKVOHB8UqKFNkRoReBnRdst8TpqbJwmKAIBGh9xqU0RyzGZFoKniK",
	"1Jyaec2qAlt9arcE+T2ngsStwW8FmnzxLfnk7yRSejXLSCOaY8rgXziOqV4eTq4qLagiKfzj3wSZtgat",
	"v/QKYuxZSux9xCmJT/VYF5TdwfbNCrAQeKH/rgIA2iOYHEWwtFzAqUs05QJNcZJMcHTXE0SJBUr4jEbd",
	"IRsymEIiLDThxESQGCVUKqlPcEYYEVhxIeEEkemLWeyH8wOd4WiOEsruCoKXCBcjaGoHfLMnQdC4GH2M",
	"Upx1h+x2TtCUCqnsPmIypcApSMRTIqFbTKY4T5TBW8ZtSxiaSiQzEtEpJTHs7dUr2B065cychBy8ejVk",
	"HTTmbESE4GI8QLdigRh5VKW1coYwWyBogXbtjHuuo8CKjBKaUlXuzVmy0B31VwRf0e7RwY97ZhTpOmt8",
	"53mwp/1U7oCTB7yQ4wE6gX8gDX4NhOp6zVbPHnGaJQR2OB6PFzhNhswg42DIkAMc/BuhTtF9gGYkpYx2",
	"pgmWc4T+gq7dEbpTM32QQYCB+wuhFD+OsFIkzZQcoEP3IXLwHqAKvAJT8yTBKe4kPMLJ0qk18nUoSygj",
	"65bf+DwyxDDQg5/DEJY8il04Mh8gzNRc8IxGpS3ymCQDFCU4j0lH6ptRdY46x52D/sFx/8eDHwHa+ghu",
	"NUZSpq8yFOEkkQM0BvgP0LBloT9sjTX7LX4vbW3YGg9ZS994cJCGx0Gv1uA3fWFboGouVIZqq93yu20N",
	"WmVotDQ/U2KhxyqfVWtw+PTU/lrpVz6J1tOXdnlpsIClk1RGsvCGGTXoWoPWcti1yldxy0O/9fT05SnA",
	"cqN5zu6IWMlcV/FU6E/ZbHRqBrIsfCkvhUYhbqo0/bnRgNW8A1YFGOt7aoaFFYowQxNS8EUr+cTkUbNI",
	"FhcIU2OBZvrNmKBpu4wNLuENZpVAUlP6SOLOcb9vCaxCE9NkYX61xACNzS8KixlRI8XvCJMDdNzvm9/5",
	"PREJzkof9O+SpJgpGm0yiWvbses0H3FGR7lINOnMlcoGvR4g7JxLNXjTf9Mftiw9VgnJb6+Ml/Bjq92q",
	"rrU1OO7X0XKaLLSwUN6rbtbXspFdJuCkWVxrEF5bq+2nrm+uFZrxKUgDXjZ/Nhk0xPsGAVyBgIqKuZAg",
	"RmiS6I4sDApLI2yVGp2/66LbOZFkyLQ8oTHVie9ILqQWe5AV1DRR5JIANVFmKaNdND+/bA/Z6bvTNtJi",
	"Rp7JtiEZymZthGd6P20gHkESrEiMHri4myb8QRNRKwg3sRYwMz7K7mYjA/5RQiejlMZxQh6wICOeEaYP",
	"+PTy+qYMN6DEkZxjEctRRkRZUbHc+7AO33eWflmeTojQopbpjxRHkSBahNCAwYiRByPTdsv4fNRuafab",
	"5mlrsN+QlNutx86Md+yvWp5+fQRLpRIEaJhqhJOER5VVKpGTxkJNH4lwrniKFY3MSpEgMIDRK3ZlllCl",
	"KJv1UiJmlM32SsL1hPOEYAbKXDohcfwNHNwMQNlMjs7sWKuZuJsxxMX9YEhPbz40mblf83pu3kb6etX4",
	"aJEzzNn9mjZh7b7xMt6u5/iVLNBpeYPA6YdMf7sjC+lWbXlMjO4pNuTJIrHINP3oZooLgnaFXk1KWEzi",
	"PS2sEHZPBWcpYQrdY0EBIQZ6+P0uevXqV9vx1atKV4BwJnicA2/YMyx/PB5PnJRmyKyY2CB+8BOOYwT0",
	"R7uaBO/Iwo0G/wXJy58I8hrQAI1t8wH6t6/GIDGojvMEotuB3shZYJ96U5JqqhOwoZjck4Rnuo3d0aWW",
	"9N00Y6PemNkBAyRRAGicaS1RUE3ahN3rCUz/DrrMCDs5H6Dx5dXZx5Pz0cnV+ejXs/8c288/g6g1QOOf",
	"zz6cf2x8PnFC0wCNTz7e/nJ9eXV+Wm90yudEkAEan17+cnZ9Vvo8ZDeEoN9uADYSfcAMz4je3pfdXswj",
	"2TNQk3uwfU2RCVEExTzKdStAtlVChqce2K2BfUemOEkaMoD5WJEBtJzV8WTaOTQ9dRODIUZa3USamMwI",
	"WCg6hHXu97vHG0kTB0ukifLk6+/9g9K9X19G+N5vt8qAKossYYBURzF9w9IDYXAF4FzNK7x/ihPZYP5n",
	"zPP+OdHSiuH2Gq31T1zQPyz/v357cmowROP6ydV5mP0XGv9z+b9mftJfxfoqIvHIDqsF+5/dDKtvhULV",
	"D1wLJ+cr74OSUWT5hWD07g3vg2I1m1wIRev/v98IRgn99huhOs6f4EZYw/LXXBjrboTvzfILAoH9lE0F",
	"DU5tPlY4tW1/0D0uLDpl20Tz3oCPlTHgl8PSjTPL1NEmF84sU52j7n6Q61dsHiWeXF9wlRubr8DTywaW",
	"Un+z2BoPhx9LN4HeQGVSs9DNOf+c4ETNR+YCiNcK/o73a0w1XXspUYJGEkki7onoIqvEgNKihwjzfDtv",
	"xoWqTHp00O831E4ulL9FNphVj1FVjGDQ5suB1zC3u198N2vUGhW3SsJnz7qrEj6bgQXKj5TiR6uSSfoH",
	"GU0Wyj6xOUi9/mG//+bN66M6tD7gR60CIt1Nq5DYqmaUIRikiz5JEms4xUQRkeorDC4RxREobFbprEBw",
	"v//D4Q9H+28OjmBlRsc8er3/Q//Nj28ODn4AABfKZ//ozfEPrzdWQf1el2nKB/1lu2yqyqXL11wUsVWa",
	"JWWzhAT05v3q4jdfNlE4xgqvO/EPtt05m3LoR9mSo63s0Cxo6TmiCZnqK48qLxeQhM7oJLFWAq+aa+Ub",
	"DDJSMwTDqNH5FOVMEtV2kgSQDmcE/Z5joQxMQ0hYAd3B6zdHh8dHx6+fB0AHiMa5hwARsorcEZLZ4zXn",
	"ik6q25bogSYJYlwhQeI8Iq4lmpCEP5jHv4jnTFVR4ln7ESTlCriCIkw9ixHISOBMc4JrGOvUDFWwhdK7",
	"7WiKIzC7rzIp/cIfUIrZwj34wgMewdHcYpOc8zzRkiVKMWUKazmzAonDEsEfPxMqAn+Tfd4MYIBihlot",
	"xrsJQ1K8JFhEcySI1MKzH7kpz/tVb2LfsaP+nhNBVwv1fm2byPS+8VYGfL9ykGwi0PE7hM0SGpC0zOeK",
	"sGP6ux6d+8Nu/zmqdfo4wbRjBwPl9n7fNHiGob6uWjt5JzRJK2ymX2WBB0NwGU7lOQLwqE5huoblK8M9",
	"I86TmD8wzeYojwP+JbYBMg0QnmoObEi00DrRrlRYqJ5UPOvBXb3XRe/BRWKAYovnyHgtoITeEbSzn+60",
	"0c5hX+54GWkAv6JdzetTynJF9ioU39pPGy4QVdoG74x3dj7YZUZINB8pPlLkUT2XznEeUz66ub1dTd5m",
	"so7iHXhv8245VWpvUvTN7a1vvIqqvXK+goz9pJuQsW+8FRlXYTookeDDnMqMiJVEuMmDWIlYjYrQsyMD",
	"JZXUpGUTBjQlN8J+4/3bg3WAxl+/KoGZPtoJOdGnrnnCT8NWt9sdtvwEPw1bbjhY/LD19LSMM9iG2z23",
	"BXa9xvJWmsYN4ne8udIFpDuaUoYTLVbNBI7IUtbgxB8tVVCW81wiQXBMGZGyIHrnn+SkQju4ZgTYiPVr",
	"OcWx1KxiP61yimO5U+MOx3J79qD3ax1ZAju0srxfl5XXjYACKonngW5/StDZjMDyBTdOR+s2eBxkhcea",
	"FU7pveOFssYMj7dnhooLPFurU96YZgWvkw9YpCONVuttsG8XGZaSSHSNpwpEe8JkbkUckI7bKNcKD4qp",
	"IJFCD4JqjkaZVATHoANO86RuqgKOp4hUuif4dnm1ifF4iSqvkrWc/fbixik/90RI2EMdC86ZfeO1LUDn",
	"cZd3cR79bh/sG00XvZAr3hp/1QhneEIT6v1XG9eNzLC+FrB5Wgf4uCdllEtg+KBA+MdumWcZFwrUJO/R",
	"13CdrDvtRXG09nk+4IBrnm+zBC+W+D9eZuYSRraZdbbjAn1a51hL+boVndmm5zy0sI2NK+euYWiUO8ri",
	"zR0XftWtVzryegdYcNewpkx/eHo2KxrM8b3WFd1InURTCZibaEQQjQlTVC3aSObRHGGJHshkZNSAIFiL",
	"z+t285lMbqBhExw1P1SATbuKxF9W0sGvFpo1ZiI4jlE2X0ga4QRFWJEZFwvLhp1YReISpIBHMq0H/lY6",
	"6Mo2q6hkUPxLADIrsKhBrziKiJSjO7IY0cBGLmHLHfsUAG3RHVm8oNv5JI/uiArwirfmQ4MdmL8cAKdc",
	"bMcXCIszTlng0jzNpeIpcg3Qp+sLI3AW0wV3MCd4nadFo0/NpHB7e4XsMCHQyq1gWzJFcxmC7C8c3I4F",
	"0uKZ3mYTyOCnrnkx3w66mSBT+tic8leyQObbRiDNBFc84snm/PLK9QBPMQ2+UYHaa/Dagvtl8VoSqe9c",
	"48S2dgHQ1nLQl1tDLslIykAcwec5UXMi0M1hR0MVK7BxOsyXzoaVS4JuL25CQkrTgd+AP8QtA6fUWNFZ",
	"4Y+GQJPRVz5yw5aZozxstVuzSIvMU5oQ4+7WaoNqEmSHy2/DJjc0b4krLjn7rPuCh1SQAkiqyUi3CFmv",
	"9UeIlFnHExU3jzgV0nXgc34iFWfmwqTY8s6/QVg2pCxB4N7GiRxl2Pk6lJf93p8R0g304gr7QtG7ER6D",
	"bsB8i/5KhCKPpaZoSkkS/zuShGjBVpHHrlbvg/zBdD4tpgmegHOvay7+Z861pH6a8DxG3gvvn7hULWzK",
	"FUIpTijWMrR526OygLXWUzCLyLb8nGsqDsoGFeDYhv9M2CwXUT0HqEacFaKmMS20i7CEtlWU2vbRu60J",
	"PuXRXXBmQWZB9DGgMV83iv8CI8tS3tOUTFYOt02M1QWPcFLVnxvMUUsLo5hWn0esQSeetOpCzTXnyurK",
	"XvRNEudfEmOFkdXrq2/NO27EmpWkNFFK2QVhM81u9jfSWyvvhY2NcRHNiVTG3jDKRbJSlisC6AQNnWHd",
	"EpNBqCE4p7hloI88Juj8Hdqdk0drUtnTe6dKwuHm0nl+a/GA8diSNGGCJ4kejzLFwTQaJblUwLdLJrz9",
	"kKnuuN/Xav7Bkm8HrXbrcMm3w1YTqiE412LpmsGDJnKNMq0FQcSYNxoXPkShYLbLa0e6CDNEy+FFYPH9",
	"JMtxbmO0WwJqeeSaZ9nKILnqmNYzYYx2zXb3SjdZaU1LHN66Q3Zpos/g5bm8VC5CsxSviGXTtjGIls0t",
	"RazSt/nzwaH58L2KD2HYjOMCTwOwLDnupTgL0UgoiOmFvRF9ONa3jHutBynZChoIf3PoWApOkssphG9t",
	"/0J9OCrdbRDlVeO8oAoHQrIPkfnkI4wFQTc3twgEY/NOrzFIc5G4wkzTRcea+e3Y8CbtmOrrwwqPPQxe",
	"tmFFz0siIOw5la+ISrbr3SXdWbfteH2vcFbs7exVFlr6svaG86q9syoErrrQ5Wfvvbc4uiOs6rHVMu+j",
	"da5ue0DIDGExSBMlFcV1kod6BcVm3O8NaK65eTdxialtwoq1azXowMW/hR9Oc1J5uLaPIZkgOTmrdtOs",
	"TEQA/6+sQnF7cYN0CzqlEYT00IRUsKinsbGneE+36mYkDR1CWPErTaH1vuVD35FFeOTQRpebJP8cOul/",
	"BbVOI/AIeF9AEJkRppA5gkIWBZnMOk+brdiVBM36Sw2JTYGd3xMhtKCwiRJAHqMkj8ko5qlLcFC3lUAD",
	"63Ljcy4QSZDtY+bxu3AvKIiq7dQ/ysxSSv5XNTjKO2DrhV7FLa4h8qgEjhSJUYaNs5wewqzMLqhi/Su9",
	"f7lpl0IAZCnb6h8IhjmdzRM6m4eMqisg4bsBLKTE4ES3ARwSzGa5ffiso5imcAFeVeB35ZoWOi1hL2Ls",
	"CJHDP5CIU/w4sge8/JkbTFexRwQP+W6r5Gp3sNol9TnGjn8ybJaZHRrIYRoWqJEvMVnjKSk9qdXUefJ7",
	"Tsp+Orp1x7rpTWmiwHUggMelt/2OvKNZh1sRsQO8kQj7IA82c3gLXM5RO1YZivyz4TTB91wUW4OI5ZFb",
	"1oasHAZjs5IysuK2sI1dpMkWN4Z11xilcmUaIQNnl6SEMpTSJKGSaF2vfHAec0MChvH8MjHghf9XwEuu",
	"pKSaoCxjn/FPkODktfvZuOS00Wd8f/BXEh200S/527Pr2z2/c6eHG4+txjD+wLSUUvU3842s89aN44oI",
	"bN5y8OpV3Z1KUbZoh3ys2miKIzLh/K73gO8P7kl0YH2vqiMbxxYY+vPJX6uRV2304eqwjd5fnJy20Yej",
	"k97Jyanp/45H0OWGkNLWKgE7NV+qb/KcemoHZMGgjbCwcGph8NP1RRe9x0kiQUPRDPHk4+37i/8cnX98",
	"f3Z99vH0bPTp+iIYXlbNERU2cdk11xdx6z3QhHFeM2qp0/UCR7izB27zJM3Uom28P6zq1d1MjjZobuK0",
	"tkJz06WC3DVUdlL1PcXlIDPNxMFmU4sJCwPToA2gscabki/fUnRMs8M2esD3bfRAJmkb8dmsrdlchHZT",
	"/IgOjj+83atio0YtOej1sgQrfXRdG3kd8dTEmc1yGhMwPpTIroqoTd+7IPKFH1MNLC3A6phXhdNSnGs6",
	"BmBJwsiuJ3JP10tme3ty82Io7kwBZbfE+nMqfLFIr7jG5K0QuIK6hSWJM7KBTSlMA0/tTXoZQWPbXvVr",
	"5elL02ZVfo3ZyEXZ3YArHi6evtQh/4mBabRqbDVvDazintw14ZiJFtuqYvoiI+CE5h9QCw+lkrQBSTdk",
	"44Jyiy7ynQHpjX3wKHK4sevRx+Q3M3KCblgRLW88jd7qq3HXipEn56aXsZeNTfBp+IJdcVev8I1u+jxv",
	"4u+8ytd5PB6/5F24LG9PE3+a99KcVHChRKHOYmd9i8GZUpHHVttNEXoED5POBpfOqpP2iysdeSFSnWRF",
	"ckmX06akHqDdk3c2L0A1h4BF2PcEq1wQI7tAEkxI7yMzgiFyhmKXYqBdinLLchapHH4OXziR3kh3BruC",
	"26Z6w8DlU8WBIi2CmWNUmsPFxzpVdhSB426LsM6nm1ZVPWuli84syjr2t+Zltd6C5Sx7jm5wBEFr6D9u",
	"Lj96U98Sy8+qTWwU7xuG8morgIVH+UpyoAknPXIdke7oxTDos6P/ITtnNzt7G1gJ3HS57ESEKYGT5h0Y",
	"tB50t5Aer0nEZwyen+xF6lYMMQ5qlHA20+tWJCHZnLOF/iMlMY1wMoppZOTvJRvaWrc/f1cXLX6+vPz5",
	"4mx0enH56d3o6vryP85ObzcXZ3JJRoTNMYtqQeFBb/RPkiDX2kDDPABPiFJEaFzNBY4WaDcCX76UC7K3",
	"xE0rnNxPq7vmCqmm6Pu2l6xq3j/zFhR60Fqqx2hWrcU2+7hYVWu8OdUhRvAe0TrFKWYIJ5LD6xdRIMNv",
	"pQEV9v1ld9UzBEiXBq+5ZQe3qgSJzih46e1Axx2jOkNGDOMpaDMBu87go4LLmhdYRA329FwSwt5X/emp",
	"V92lW9rqBzazp+Cj2rqrL2gT8NuuKl71ZlQijCzjoX+QGIG/rOPb4EFgB5DFkBBrkeaJoh1FiUARjuYm",
	"LFUDvASkFGdgMrz8+PFv9vfCawX8rSAPCU0wCA5z/oAuwScIwhbknk+Aayf2NgstsAFcB+jGnJpJjgjh",
	"536dk4V1+zS3z+4kp4nqUNZGzK7JnQBIgCdsgThghXnypUmCbLJRvbqE43jlsRd7s8s2YLHLvdgfoA8k",
	"1TvX8DL5pNFBxwTyoNvbC2h1MEBXREgqwaJ/RSb6Rouxwkby66AbiHCZgtEbxSTOC+nFxgdEuRC6s3H7",
	"j3DiDF9yuL0JBT8azmNTStbTTgZTTNqoylBKSkky7PKvaiiFM1I+lVnpCia6mRK3kimH9KtpniQQxziC",
	"mOnlHkshIaRJn3o4Z40z2R81DzZQRZShtwm5J90h+2xeVIgkwIfvCUPUGnD22q591fHAINEgmqoBkvl0",
	"Sh9B3zKh3rEffEcie4rGyOImwxM9lx87lwQNospIkFKbJQvjNqV3cw8oXuQdDOaq3MAwrWFX8yzcJu1t",
	"odKaGDbi0XTd/X/KmRLcvJ8CtUNH81JJJcos9RlfX+dFB+CC4Ypc2h5uGkjWs8UAPTV0rgEIwCuABW3N",
	"2dlBAYfQhKu5H47FS3o86wUAAL2F3n+C8uWaf+BeCRu7nssgNuQGqzXSxiIDamnKo7vVumgpT6fhHLVs",
	"nRtopcGruUjZufZuNr/tSOSuLvThomLuNznHS9hi4iiLC1eT53npEi8md75YnC270NGuReT/5qmCqb2m",
	"3gsXFyxEz2tFp9BE5h505FG6Bj2m6dvOX4WlWes3oen87fdhyWhTehGpZzhEuz+8foNimsq9NsJJ0vlA",
	"Gb340Ll43bk/QLuHb47MRz2eGQWoVksMJC45QlrBweeTdJLDuBAdutvc0M/JyviS2sJ31wYOvuHFZF6m",
	"tPKbiZNKl51GcRi16OoAiJ8n1Fd4y1sSCx7dPZO5fL5BdoBlfKV4N/x8U34zt+n7g3kQ4YGkHDdqHt5L",
	"lp82Oju9QQrLOyR44tLInJ0e+GgI83t3GY2ZPCRdWHTn/qiNcIr/4KyrqMLMpAcFoalzfzDoh21kMY9k",
	"Fz/Iru0a8bQ3McDoGcNGL5dEwBNNz5x2p3ALmas0Cd9dtaVVKclO0Cp8BFq57BAsVehhZ4JVNId8VBXB",
	"ZD+kqUJbk0GrmtnZsSvIeZUpmuomai54PptnueoGC83ENCUsHLx+massV8i3gOmaWGRtI6AEWrBVGbUf",
	"QK5ZQsinJ6HY2F14fTXgvmPvMTD0lwPpajKJlmaXzE5ZlquR+b1JTODP6/YMTWtxK8bPYeQeoF3apNHv",
	"ORGLNooSLKVxigTTrr5qTLhA1VVjIz7l1mG41Pk7K654Y0wNIXfaaGcVtezU+FYTnzf2d7m1fMMG2ji2",
	"4xbsH0bsQj0l1JdQkEjIR0QJmo0YeRgllJENRHgXYwkSuqAZpJiHvsVla89Uq102C4fH7CWZIUTOIqzW",
	"Y4triCZkju+piZJ+gYvATPO8e8AucZlouea9vZZRe9V7e5ORG7QqJ5zyKlIb7fcPjpzgZBqCmJlQNstx",
	"YtN1LeXtFnE1X/dut+a+rjLuMqm3aoRbEpGaKw2nxtr4df62gLx/oQ9JRFX4bm7YrrMwZ+1sbrHmQ2/j",
	"Wsy9D8+wfGopAliuvUTKemYlDrgxfpn5tdqtKveDHxzvC6pSAYtt8DCa4GWleJgGktedAgp+Exy96TVW",
	"IXm3srOP71qhzISKozlmcWJ5i0QJZzPNhebYBGCk+NEaHBMI7yiD9OPlx7NWu3Vze3J922rDHF9ehGs0",
	"+cW29rHSYOa5plGVYuP+5n31+f2N9fcb+oO88G39r3muiHj+GGF5fosBgvfAFv2DxoqQnRNYccrjUDnE",
	"dyRKTP0brEy4syE27+jNODNGTed9vktTPANFII8pbyPNVXkbXb17L/faQ+bsmco/EVDJdsAJs2nlMA20",
	"0CGVWKAFUXD9gMFsrEROxm1nV1GCYCVLw2KJio2ZHEg0SZAkLEYTyrBYuCUPWX3NREVdiD6s+LHYPFSQ",
	"jNR43mvmozcPpYJ8wx1prloqkVR6TkFkxpksstxGEclM53nhtv8//6//x0B4muAZ+nsutdiSJM76M2SM",
	"q0LUoQYUH7lCjBCXkt7K6jgRBMcLZCPCPACtfDYuAOPxZdwesrFN/10UZTjoZILcU/IwbqNxlNCs88r9",
	"K0pwNt4LJwP8u+RsyL4OGUJDf7MOWwM0tN4fw1bbfIQFmy+Sp6QzzVUuSKdYYMe2cO39B91Jo8CQPTlP",
	"mKYwt6lZOcBIn+UstdJoypbJZWe+LI/LAV1kmgC7WJHdUXEUQRIdrfvN+YP3jAVT05BFnAGEwWwdlnrR",
	"rR9NKxe/wF02wUIiuWAKg8F/yJympwUTnpdock6SjAin0Lux0A1EKlkr4KtXNzDUq1eD8vh2G2BSdALe",
	"3H/+uwQJz6jpe2YY+3amxylWrfmRd+6AYrZgBYzDNkQvhQ7QsU+XZ0fXlPeoqqObgqum4tc0TxIPYc1R",
	"ItPD7P2tA8kvBiS2LAXUjZCRyCe/qDR59Qp10DVJ+T1BBlN6Ui0gpffM2vgNL0GRRlpzZqC9/HL74cIV",
	"giigBL98/erHR3OVJi566OmpUjnCTSzReJj3+4eRWQD8m4xhcvdBL8n9rlfm6i/EsdRalVGqTILXSQL2",
	"gYQYtNvN2iim92003+/MX7dRQi3/9EtQuWASZQkEo+vtwTnBC5e4hxAKHJtkYAtfroL8DoA7+z3H+nco",
	"3YAFlYU51z3EyaUw+gudol3yO5IKq1yiYUtz7HsybO09PZ3APzUBiK9fe3RqIVd0+h9aURq2wD9RM5u9",
	"p6cb82+jMJV72aShh3rhKYkphrX/TNivVKGYq0zwNFMIPlmrop4cGHZxRfnbaMl2TPdcJD/BbfUOK/zp",
	"+twvvPisL5EutBnlIgk0MO6GmvqspAyEBz26f89mw1awjzzUHazJt2fCf22njC3rNKUJGfR6PoSzOYkF",
	"HkKo7PX56foC3WjmbF8WAJXGMVZ4MEYd9BZL8voIERZxffXBo92n63PpbzhoCZP1/p6R2b9PoEO72+2O",
	"HWKOraV5jHrm3xL+6KDPZGJSdplkkt6NzF3UoEjFRJmgUjea3akewDyCTKvxm46kxgBH3ayaGsq+MaLd",
	"qU0IOg4CXKvsex5gReJ4m3QdXQkeESmdwwFM+erVOcg3mtG94w/MPEi0tVwC2t8unVohYq+NKjeIB6wf",
	"SctxhmE+qlIAIhcuybDegyDMlF/GEsEh+O6aqenu10Dzmg1WxzH2vg/8D5ok2LbynMHgCIlyoVmCe8B1",
	"+3Q7MxdEJrg+IFvCyAJHur7O2xjtSkKqxYWKsr17robNSZLwBxKjOZcKPcypIgmVyn68EvReX4DnV4Yz",
	"wu2mpSbgjjc31+8RVgpHd9IhnluosfFC3VtZuqX2+32IP6i2tcFK5YaHfT8knG/JdtoY9KB/9CZ7NK6n",
	"HXvuDo1uCBl4g4t5IepSbuIaKmLMXxz8Op0IyjoP2REwayDDW86ZYdrwp31JZ+j28vIjMkiNdm/Bq+pS",
	"UML02ZgcbegjN56Fe0uZXzEFyMhdY/H1LCf82erfH7C4I+In82xPWUyY+uloXdeYAAwhofNwqILs6rNW",
	"iqiEHf53i4WwW+NOpWk7Um00z1PMOsJhvAVFTCSdMVdKCgPJatk+jxQIfgA+xdHFxQctbCGEyu+3r14d",
	"9juv+/+bNTRAmQgNQXhR0VeloV/wtH2Y06QolaCnmdPZXA8Mw+r2gswt5ji/x67f5a9kgSqvvLYMH+zO",
	"yYyGbseDMWznjiw69zjJCcowFV6YEAIv7JmgFA5FDtBYixu//eXwywBh2jYGpnaaOAnmFk/yBAsHNT26",
	"FrG5SF1QuYWY9BWlnFFLt724+IAyLGB1Wt7JNWOSCjMtCtseHyxkpDmpujwCQHhLGJlSJctM9YI/2NQA",
	"4CJqJb04jwD2d/B6ockyJZhJlEBrvR7fw4/0HksFgYmgJxIz1AWR0owjbey/Zuy+zweoKuYkWNRB76kC",
	"L9WSSuCyghhjFPAEvyPrOlq6XcvUMka7Wo3aG2gREP3FpRlRHEHItnGlkyZJ9Vif3rjEbLRa5m9ZQ3Bj",
	"tEuZ2hugc/jTZrrOcASZm7hAjICzjbFtVTiXH8mTZJF8aIDeg/Xa+5MZS7jFGVhqeSzGGYEgODS2VD12",
	"HWRxqTrbtnmRcgByQrWiKiF6H8rnTdFg+avxhzIRrKbMG9QVHKD/wIygd9zcgWFkh08uI4irSU9c3fkD",
	"+4O+WuUAHZn60xVO5PzRKUPXJz8PXr3yfKic279EQ16pMVe1yXel+7p6IAX9+/uwhCswujUvG+NvcYPM",
	"qJrnExApFeesY2aFf7uacBydawj7iM5gZ5xkd0TeUdabcdO5onDaU3Ja1zu3IePEUsCydpvcmuPTUqpp",
	"0oUD1dz9HVbVLzFW8OEWz6T+8BeoQVN0xDP59PT1q742np7a6OvXnm6gewzZ168lncwelRZ+vCziTEic",
	"NRd5ZVBLzwm+CHpxhZ1hUNH/SgaIkdYFdeMrQSMyQP/29Wum/1VawodC3wBAgXS2cgEePA0NJLCs0mJK",
	"k54W2prFQS18NWetTKYVMUNCT09vF3pw95dXvQptzad/HrYyQVKap6Cx/c//9/9GV+ZvJyCXOk94vCit",
	"sloj8a++FqQNO6vVL9T3mX1OK8UdnZxD23rgarWtsU6XG7pYSqfagPpTNC2rCSdXWhjXXS8uTj6cjH65",
	"vLmFWDjjMG1Ky0F/qwo1/Gn2948Oj2yg2nmq9S1N/VeCwDS55sJn3hxmqes/eQ62KQrtEXmkJt1+yeNs",
	"F4wWZsFt+0Zj/OXZwpu79tpokivwhhwyUy8dqhE1LF5jl4fb3CbjLvLpa10XY0W1jqgSigUowobMKNjJ",
	"wrlGGBbo2MN4VKzZvX1qwSDmUG/L+W8io7Obh+QhG0NDk0nOGePGLlRRkczAab+LTk3F87KtT5oVh/cF",
	"5o73UNCAWenUFmdS9vladx17yX4MZobPgqr6PV/Z2QB9RcOWse3AEB9xau07w9YA/dbtds1H38V87Ha7",
	"X9DTeL1RFwjV2G0/LJBjvt5M62wZ0MCzZjCVd7u+VWnBuuVXc88NW+liZE7VOF7Divvd/Tbqdw/0/x22",
	"kV6obv7kzL/2+ZhAfc+39kXe0u4nc+HXp1sFIZYnCXoam4qDMCZ2vta+rr9Zo57gMjUl4ytn8Ftw8C9j",
	"lBB8b99kPSFZd+qcRXPMZiQ229ELP8XSM6EPdGbS5hkLIWYmTsF29k6RgA4BGjWwqNFt4bE8WRR7M4YL",
	"6FHwiKzMIwKUblbj30uqE78Ft6bMmyfKa+DTKaR2dNUB2YzIZqaHZxaOXmXbX+MuuMJv2NZCLYWz2jqn",
	"7SLSVf9DwDNiq11yGLP+Be3tfI+Db7IbuoX42wntmnq8e891Eanfglu5iDSel/r9/ZKTyGH/h4PCgbbp",
	"C4KpC4SNyX3PDoYzaiwVBaiarrPgtdFa8Fzo9h39Z8UzTs/crhfBrSxzWSHcLTxE3CGs8hCpgndzD5Ga",
	"l58rrAjbaq6ksBNZj4oCGSwr2f3h9Zs22j8+fA2EDSdTzt8SdrVbnviqtP9a8quSy5gLfN3Z66JrVxpK",
	"o7AP124jF9dghC44hlqN9pXeJkuOdrW/ySaOJksG3ipItgGkIlAW7S7ZeLsoolWB1N7mya9rLt4lNC2i",
	"Qd3s1QwyiE5BaPL5c/fW5/14jm9L0B1kQ9Zn5eIl7O6iHjdhEk3RexzZuB17M0GwqIYSMMZcJJU8NWVR",
	"3NY/X8oEGU9pVHLVrAQVmNKQ5mOCxYyg3bLrHE6Sjj75JK1FGzSZpbmNTMoAMDP89+gnv8/wvVpfWbCM",
	"99KalKBWNFniCnfXMo3ZYyoTmGcN9XVBUHodUHVP08BmlpODYw9LNtVeTTF27esjIkp48pxACLeY70Bg",
	"IX+pTQnMJGF5pjyxYYqnG+duFFaI61S5lPjComPZUfX48LWjtkZjS5Hr5JR1SaLWSyryrtPtdksuq9uI",
	"vFsJJfXEUkG0fWZ6qVV+/8HYg+pluwtXzQdrCSla+rcOEBO8TDJAB8ev2+h4/8C4G9fEl7DEEhARloJ6",
	"DQMzgFwuISwddzO2BAJwRks4tZYtFUdbsKVyGQjTYEeCAAUn3zz0tVm+qvwquMrvw6+C/plb8CzTfxnf",
	"KrXwb27YO3dpmHrvDc1hGtEyoJ/HdAqm8yL1kOxuxhKvLz/dnl0/U82yuZ3W8Lq99tKGwOfaQ2a0rV5I",
	"tm2j3x8I6+n/Oyx9eTNZIo14TbiLrb6mFbeaN/86nshFjS2u3GmTO1pdfHsOaTFhLZesHts/jlPSaZHn",
	"GNJdOC/YvY3Z3jpQrgSMdeSFoMApJaKekDI8qpbjVqBYXaJbt8IX4CtBv/Vts455HazJFXYJU0RkgkrS",
	"mQkck5fIP+Z0ZYnOTz5AtCUaQ8xlD1MviuSSiPG3G2baKOA67Fy+TaLBHjh8722YzsxYzzqY9lx4+D3p",
	"4IZJpzcjqlM9+UYWk4Y9pzBH1NJqrTf0LM2CVuEp1vT33TKjoZMEzLHgLag4Onl3at7KOev8fHpV5i/y",
	"n2YW0gsKAfLf0f7Bm87+Uf9NzdHRt9rIirR1YrRSiGJBiZpzhyxNbbRDcn12nQci1f6yxFaVvGQXl6cn",
	"t+eXH2s1tcrDfldz1FL+8t0MU0uzt62F1ZY53Dbm2TM+yu5mI2M5HyV0MkppHCfkAQviM6adXl7fLC35",
	"kST8YVQi1PXRpucshtonpYwxZfYccX5HTQyJmrtSs3vGWd34D3bRR67IAJ1PbbYX+/uICzqjDLz/GVca",
	"mL/tvNr5Eo5PdZ1KNXH9un9r2Vfuzq0pl3MCT+Y28WSr3fpbxyaZJ3HnM1Vz3QSeUVvt1iWsotWIafjF",
	"Vs31dcQmxKQBogxpEPu49DLerVnJl21qQ7gdp0TNeVzf8c9nt6126+ryBv7zSf//u7OLs9szvaUrTag3",
	"+sPJ7ekvgb3d3l4hO647DmAdKza2fMJn7coefpPqLqhUUE/eLsthSWN5UBjfoAw4aOn2UAjQ9qgyKtPO",
	"ZZQyEQiQMDMGdyGRVxnIbyFfcVsL1mh7Wbf85ct2laJh4rUZPRu5mmD/VLqVBwmFPGZc1gklhNi2IfLl",
	"/ijRqvInSaZ5oiG14LkR/oWNZTAhOL6etA2Og2yAGulj8Ka2VTJwXIPn3zq3XOGkc6pv/O3gleLHkS9W",
	"4m7z1/1+KEw14SCZMWTLGuzZUDBTwEPjFTj1mYQ5riSCiz+CeJryss0svrhHf7MSCabkbZFz7dqWwP3G",
	"zEl+2HXZp1L6SOKJPgMtUxqbselsErjc7y9JTbUqG95zTdzFqiu5VyPBpewYL+RyUv/nv+B8tyQ9L2TI",
	"KbDC+A48DytsFHgAF757qgOLQsFcB3tt9/mbMxyYccKYHVjCnzyJQZFCcpQRMYp5tLzaEMvTCRGl9IgZ",
	"KbmsmoRnbFb8Ak6E1Yweq60dYfBtlHagTsYhoTs8fJO982wUeCz/6Hefcql5c0LuMVMlf6+i/JIWJitP",
	"sG1/SeFS7KJ1EZMRF2RZgZttidc8ez2PeO2TWZiRv9gDop7NT/Fsdhp63vsezLAJySKDQy0xqWZjoYKB",
	"mrsBUBT3YaXGEu3xYD1MNo2Zbq68nIzTeUkGxK5GQDAxCM3iMpWbQNg1q92iAPemaTDWyCzrEjCsoY/N",
	"uwfvxs27GytBvfvWeT7XiloWF53HZ8m6FhM2izDv/e/wRuBW0ul3X78dvN9/HfQueNqilNkK/AuSdHMr",
	"Abc+LwF6dwfvrWetfV+CabNWgn07L73CvnNt13tydb6tnZgLrdYkNKKqYqbIsJpbueZKEKAdSZV3MLWl",
	"E95RGfF7IhbojM0oA4lggMYzMN86o6XTvlDsWhNobM27OKMQ0D/W4/4s9AXm7NMDZ6Cu98RxShmECkE1",
	"SInG9RYWzgaAEv4ca+kgpVKaAEJfDQqkLElSzBSNOhb7rAjwP0xewLLUVm85xVJ1+v2jDQ3ZFfN1B2dZ",
	"Z5LTJCbCmLLtuq3X/cmHbxkLRxGRshMZpTgsH67e95/AyG0M3N+nkmO4qsTJ1dXFuTHdjk6vz96dfbw9",
	"P7m42UKCbcqRa8EcYENrpce1g76M8fYfCftnVvRYIiA31QRBIi7if6pgXK3W4Y0VtuLlaLUhOnax62tN",
	"YT7n4ZygGMv5hGMRIznneQL/eXAFFlzgeMTTFLNYdoesbAbUY5tyFwqzGCeckZ58wMKUNeiiGwLJhlzQ",
	"NEoxwxCXEJMs4Qub+8OYMH7NJ0QwoohEemtYcbFnS+WnRRpkO4KPMUgWlZTxZRP3Mh3VafVgfob8oBFO",
	"EhPbW34WJbFLVduwHS1zFl6aAbmkCSxP4e3z0jtm9yIFTmzt+1EmKBdULWqWb/MwqGUVxh5b7dZjgpsW",
	"bls4HrkxEBda8vHJoiA7ta/m4b2MYwIs21EPOK68d4kp7LpMOJT9Y2B6jO252/5xCePGOFd8HM5xrgQF",
	"ecL8lzK7SojYdnmLTX4JfI9pAmKHnfi/mamGLOLphDIjGJWT1ZaSglnJx8JEvnqlBYCMQH5+yHAUQ/It",
	"uTeAEDsD4DHqoI/mDfb06pOb1pSiYwzqy0Ge9eucKZqSSoOUKJxA/F8GJiT9Z6VBlMcYJvjr+bvzE3T6",
	"6d1J5ftjAp+v/uP6tve3ixMI1qcJiYtGJuwJBLJXr8y6AdB60lzxjklUgiakAjwv+Cxdxc9Xn+CbyvJS",
	"Cb3bq0/gmAduJn+7OLH9TZv3XEQGSCbAr2Q982v7bWjxdthqoyGgrvnXY4KHrS96mFuxcNsr5WApUMon",
	"XjHD6cUXgw2KPx8TPFBZbv5wk8IMpnyz3mJbc7jEX1enetNVc70ez9LYwP7bDtxqOxLcyohvNaWRS6ax",
	"Ts8OloGSkcCZURNhNJcVxeuJrTtCshFO9PIqIstx2lr6XKA40t0c17aJ60uVLCABVIKlMg7aRsUteePu",
	"dSuZ76tZunKbeMYOA7nuYqcEQWJSSNBElb4YPkmtEBXfXVacYes4HbbQbpHLS5/u/lz/to/mPBfwQ1//",
	"TfBML9cwuL3aBegGSvAfC9/GJDQw2/J3oBkNTCpGo0oWTvWpzDBkhvdphEob6f81Q1JYqDwDtsbIPREe",
	"JN0q1plDCpSMmz0LWRI+m1lcscgBxlhfEmHkHzrLmNJ4VQpYZ0tVFUqvMzZNuXv2HrITXzan+Ooq2Pye",
	"k5zEKM8gFz9+HMEPkCu9O2T2CPo28YdJABEX7KsGuKOg/Rc/jgyYR+ZYNtum4ppZV0kBw2sNnLBPqqgn",
	"1KKQS+LnHgD0P4fM6nJc/+4qRdkEaa7yy9wmAUJUIkHg6a1tfoVc2YJEhKlk0dFsd8honLgUlzYIdFGs",
	"hUqkuaTN3pTiO4IE56lH5U3heLgMjoYRjNLJZjC0fGOXMvTh7V7ZLmsB6ouTWFBQWcACZ5ngFhwACuRA",
	"YQTAEo2V6GjtTtGtnkWPzxCO76nUKzSTdhCOVK5PHdY9ZCaBi5ERJPJlEzVymuR9KV6AFZMLLKjmC48R",
	"0cDXU0AGHL01Lu40znA2kzSG/MBVfDTloSgDp0DKjClO6/Z17O7/+HrZwRRUsy0Rl8sKwChGsl7CIkpI",
	"WpyapWL9bZonSRsSsfseLqPicf8Q3VhbwCdWyCJwxV8TJRadE7gZzLv68rM0k5VO9BKqK02nNrHeyvWb",
	"MGzUr8F2v98PgjYZxTRgUIQsDUURO31eNrfSrcCe2X24QJkgMQXnOZlPXAdKpEkZO+6lSe9+v/dqbJ4s",
	"IT2Xs3nJorN1KB9/Net5cjVKbKYbg0fdv0vOjIBdvuj+z17XWDV7nkf30jpqtcKtlppBRlIJrMjMabHB",
	"umhfvVkV7slWu6Uv21a7NeE5i0kctKXWbEhEdKp6ip14gTSIBI01KD/gTJaezqV15aCi0auQTxhXJj8u",
	"lSjFGTCmcrIcP4+pY8QZKiQqEGXPp6VfDFYVz8BWvNgboLJ8gXZBJecMxUQr5W3LuKxEpFn7XmPon0D+",
	"GFRlDTtSIVS0KxLFnk+T7J7E5lgWWxqaAxm2yhAwmwLO2xRZdrFEGRbgkJQJYudw7avCTBtBkmegwgCE",
	"MspYWaqEtQJPBoFBopRCcTyzX81kAYSWVdqUxhKnBGW8wSK/tt6enJz3JjNi/MJ9jZ6Bx8GUCjXvRXPO",
	"7hadVHNBZdtWXuz3WwODriHHFrOYbVmDS51d5QMNZbjGBEoRJUaF+lrM/lQqW6QVm7OGx7lWTfea3XzR",
	"St3rtFIbdXknL9dAr+vqQ/iqblB2+I+iY60M8aquD4Iq1/GG/H5wQ35H7td67w34nu3gnBnuaUbEXmEs",
	"JKptSvX5dMdQwK6oJKex1F1cG7FQI3CGbLacJxtUBPq4WtjOaEZMct7MwaOLznA091+AmOWQYRTxbOFM",
	"WdCyjSSHXIBEGGHFZISGJHJWcpvkyjoU6l8hv7RbROF+aNxa/YZcWBQ1q7L824lUlBlxyghyfNoUh+o3",
	"c+hetjxouddk7Taw7SssLai93s6JJAH1jaaQ/UqRZGE4W4NsYVzZRvieUyBBMFh1nGtdghVhkb+A7NKs",
	"4TaF5Chqzq2x1ZNAib6dtXW4hMUNW3r9IVGoYMLArDnr/EEEr6q+MGddDfhtGTd1SU56kBP+nirjT5fp",
	"bRwebGcPsQAa2QynVWtF0y3Hq2fU+Dk8YKr8Y7UBteJgJ0uIIm1k3hL1Dq1wq9vrziuNDId9aexG+6n5",
	"LxgUGHd5WNuopDldO9nSSP8msT+Vrm1JAD5CP2NFHvAC3ZpvdR5y2A8yC3lY91Xf3mJ0OCq90zQeNpz9",
	"e/3TRr0Q+UkeU16pRt6MYTMfnDk5Ajdl3c0z1qbfj6sK6g5nlIYGNo2KE9TEQ5OEWqdXNCHqgWgxqJit",
	"nBCyvyQG5YGymD+snvsztFk+tVHqHkncMaPVdlxJ5Nvvh1fytPVprD4ILU57X9+GE4I/DHSS2GdAwwP9",
	"s0AHac7R4ylVWhErXRpWoPAW/+aBwvafhborUO2pWpt6Y4dCxUup3kpuR2F0cJVqn7/yW/Ko6gtXc0Hk",
	"nIdcucBSF5unEdeqeLOpVaVHu/1uv7Pf7VfTr0wTjkuvxQYEz0Gpxto3om9TFGYtebsKv8udIIsUuLaP",
	"J+qIM0miHC46c65dqMUgfbJjlyDXGe5MjWdQP7GRvi99VevJolE9noglRQVL9cvrC7/xqWgN+zaPrFli",
	"M8S5KLThkA2HbMdmfxZ4JnA2l3tbLah0p1bLJTfcn+BziQosTDNX9vqbeI9zV/Eucz87m+c3+vkXfjDo",
	"5Lzs393609WvXVudFj8uPZ0mkypQ3jGptZ7Nq3xjvQ3aKgjVsGrGHoV5uuz9TNIUdw47Wp8KohlJ4X0/",
	"F8HyiDZIR2AW85QRCdp6qb408KmDZXwqNWBoDQ6CgSaOf7VbFUGxEc3lkmh76asIgQFMq6JAhJMESMrP",
	"GFQ3FM9GdwFA86xzh6QGJfgVYoFToohYcovwbJSFOF2UkFwuGWY5mPZXgumZfitBkp4LntHo+VRt+m9J",
	"zkuDFIoBXZzC9yC4onaWQaeNQwuiBOcx6UjOGFGdo85x56B/cNz/8eDHoDsYlBjyBV8LRxO7xeVeYivn",
	"+S6Uu7+WcvfXUe4/hYxeavWbXDBV5PwO8QLryNWWHXwusZbqiG9Orv/wy21JoeQqgWB3FN3lpNK53x/0",
	"X74QcvdfJPgnvMlO55gWuehr6W/YiAjBRSsQemzam7MWC1e2kWm1opCstK4BlfSHrINw8oAXcoBO4L+6",
	"l2kuyAyLONGHy6eI5yriKdEd3PQDcH6CtpzB0z78XHXX4szZyirNk4Xu46Qe6Cdtc01kI3g9DfSA2868",
	"f7tO5YAI2AI4QHkIFQswfxTDB1/01p4LRFg8k2PZqLwXki1qAZAhMp6C/YRFi5HeUKIWISsLfDBrhNor",
	"vtNLkfE/T7wx7sQd0cmSXG4aNLlCjKmPF3BuJxI8qbeAt+vzYlzzX+LTN67+xbh4gE9sW+l67RTg61qf",
	"aF3s3bpRTazES49qHrFeetSwHeeb1woJJ7/HqCYP3UuPvESWfgHghjXqbx04fJGGSn5vGuO7MTG+fLXk",
	"lVd6OeKtdBMe9I/elNK7Zapz1N0PZsmtsfR+94enbXjP6kjT8MpftoiE127KIao+ehUqSzxHFguzvu0C",
	"WJds35We2FooqxVOCHtGv1TlgX+K8baWD+6ge9yZJljO14pXJVCvTQFXHvWl6hJ0/8RW4v/lFN1n12f4",
	"B5qXwuLGdlk//sSGpTUZRap0Bd8Pu4eDH/qT/6qvJaXkJ/9ln0r+DGlgnic6b1ei4YVsJLWSAd/DRqLR",
	"XpPcdtjfOfgOhpLN724vbX5joYBioBc2hbwgVP88V/yfjUsEii78Y7lEWBXevjDCC3KLWvr8/+IcY2vT",
	"asV7iLKZj+8rEup30RmFtA/mA/eu72kuIWGwPZ84mDJ/BUcpB0RWVHOo8u39qIuVWL9GnCQQM601U/AY",
	"3HR9gD+bOwf/i+N9G8d7MePt1rwIAvqWcR/4GLD6FO9pIG02WI3GOT6djnyEgahcwo209h98OxiePBoD",
	"F7VZGPh0uhIqx0FhtzgOyqgea+SXVQ0t3u83U/Oemy5uehSTBC/qvsMVIXtJYCJ+HGGlsbIWtn24ScSn",
	"hr7vXUaD/jrxXs+7ZLvgxrxs9nX7fQnvw7CF/fn1O+rWFRm6/V6q2MN6s9aLlUL4czlMbW30Kvby/Wxe",
	"/7J3/a/zOFhLb9EMCTPfA9dNM4bLpjZsUHlC7g3ePjv5xgWMoPegFubl4tlD3cAIm7PI6hIqxEfZlDcI",
	"zgHsnogJl1QtkNl+8XARk0k+04Kc6f6ABbzKgH/IlzId2gabvUNU91eryidSynCydK3clMkyGIgAxl20",
	"47oZP/uIJ1zQP8x7k+QJaaOdv0tuvfClEnmkiTgGztxGOwmfTVO1U4iWHTKd0ogSpjTf/gnCX1CGqZBQ",
	"ppRndiSa2FASB6/S8vWELcjlMk01iehuVZiVGm8Gt1poVzPHHCSM1DpakNedfL5BpgncRpAb0KXOuiML",
	"KHuP5IIp/Gi2RyJBFEo4v8uzesK/k883o5PT07Obm9GvZ/85On8XdJn3lYOJqvJtU6PbJLi8I4sOjUNQ",
	"cKp1QH86LNcGLQoY27ceedjFKf6DM/wAyUl3tKqyUyRm+7Hf75sz/EDZ+eVeNS9jrbOR0i4Im+lbfz90",
	"WgCpUQH/MPAtQIsz+NYDuDk7vT67LZ3DMw7BTFI6iyA6Eki7agSHZXFBOEFml9DW6e6apmzilEU5Re1W",
	"ew8tG2bpmBWFUn5LMpIyWZto0abCvbm56N1e3MDcN4eacTCTfqwcRuiTKZ58vmnbnIkmyU2EkwKV6pkO",
	"N2bga7J9hZNKknikcToUuTiniiS18jK6LcQk986vjJKfUHbn80hKCJKHmjFQuAjay3J5I7RLHiOSKVM/",
	"WxGkx6FTNEl4dDeyP45oJl2dmb1aYZRqgZkoZt3qL/s/HnT73YPu/vMK7WjhfFNg6LZQHoU+EhfJmZBB",
	"rwf5KOSh/ten64sGUGCOas2n96XOuSQITyRPckVsW8uZep8kEbIXY4V7e6aTmUV3meTRHVE9sx7XI110",
	"7O95BgfUq8OzPKbmVY0O28GxcY5rSeit7lHJL1SghpaHZ0Si3f2DH7p9/b/emzba75f+/cNBd/81/AU1",
	"fX/Uf74xf79uo/3XP3YPjo/s33vBRKIOeZ276sjpm1W1taFw2LewKfj1xvSexjkupVQ1SU6BBxTPZZX0",
	"WRup0X51kv5BRpOFInXzwdGb4x9eL9epIS6QT/3CbOIokyECmQErKY78eCsK+ZQysJtfXx+5BUOZx1G4",
	"qKBxvQmvE/qhBxqreW9OoOAQZSijj5CLwxSP9PngBNHbiitXr/XrWQnRXBIxwjMSkgo0IXROZlAqBHJL",
	"wdHCA2iJv1XK+RnV4N3b3n63v1O+KdENT42iQIQn38/0jmYkpngPCQK6YinPnZprZMKoWEX13ipPFXwc",
	"2PKS0Psq5MFlWhHsvpz1uVpZlMReegrEck+wJOGAS8h+8+n6wnJPkwihNA3OTGIQxTcJmyzV7lqWYmpN",
	"AinYpi/UxW06CLJCyvBpNv7tqxE2BiBLPA1bZe+g0mF8zzye25/+NUm5Ina4zU1gArp5/jElKppDvLL5",
	"cPXufdu2+aDx3P1xSx6VL+Mh97pDdgqqFY2hUqKWmErVB+DytDvUxKQom0lkg6mJyXGm5dg8Q/pI8MzV",
	"YCrQGV0TuD/1ui9FTARULtjvojNX7mBcmvGnYUvLNMPWuGSyoMyveMgOuug9JBYu4ahJ4zk2t6Uco1nC",
	"J/q6VkQwk6qFSI3jO9JezUN22EVjywtH8nBcGm3IjrrogsxwtPDPJgM0dvurNpZoV39/wAISd4MeQxOq",
	"FnsBy2MxX/OAXWWIygEYKxqkhGHcLr2+ryprygRNsQiK/nOlslV0+XxSCPKvBmF/xCmJUY2LyXVsrOQ4",
	"CuVEGE46OKNVntaq1OZy7Vzhw4IlVWtaDlpvCRZEoBrfaD2Fqfjw+0Dv5nBT2NWIcwUXqEHOYUXTtFDw",
	"TK0j35HFU6usrYdU6ICOXB3F/PMJ7nimRC6VqRi5dGor3rrpLRlriVjLCB37ufNKE1Q+SWjUeQUGmOcv",
	"083ollq9FJbKek4gW4Igf657JYBXldCLb05I1HBS9wfXMM6X+LHBW8vLbLqvmsgB1eGItOl2MUgnjotj",
	"N0670Y1Kk4lPkoREitTLeDZwCfKDGVTaXKn6Bx9ywwW/ej9UawBUL4ja7V1k32zKRE9P1jK8Ru4wmytb",
	"4mOqQTXJNd++I4uOsbAa8UxPb+uQS4JFNEe2JpBeAFUlURpVp7mBaYyXvdFbWlrJ3NfwtxBtDVqH3X73",
	"ULMEYyZgeZI8/X8BAAD//94jpjVbIAEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../go/pkg/antfly/lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef9.PathToRawSpec(path.Join(path.Dir(pathToFile), "../inference/config.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/logging.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/scraping.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "audio.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "chunking.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "embeddings.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "reranking.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
