//go:build go1.22

// Package embeddings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package embeddings

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CohereEmbedderConfigInputType.
const (
	CohereEmbedderConfigInputTypeClassification CohereEmbedderConfigInputType = "classification"
	CohereEmbedderConfigInputTypeClustering     CohereEmbedderConfigInputType = "clustering"
	CohereEmbedderConfigInputTypeSearchDocument CohereEmbedderConfigInputType = "search_document"
	CohereEmbedderConfigInputTypeSearchQuery    CohereEmbedderConfigInputType = "search_query"
)

// Defines values for CohereEmbedderConfigTruncate.
const (
	CohereEmbedderConfigTruncateEND   CohereEmbedderConfigTruncate = "END"
	CohereEmbedderConfigTruncateNONE  CohereEmbedderConfigTruncate = "NONE"
	CohereEmbedderConfigTruncateSTART CohereEmbedderConfigTruncate = "START"
)

// Defines values for EmbedderProvider.
const (
	EmbedderProviderAntfly     EmbedderProvider = "antfly"
	EmbedderProviderBedrock    EmbedderProvider = "bedrock"
	EmbedderProviderCohere     EmbedderProvider = "cohere"
	EmbedderProviderGemini     EmbedderProvider = "gemini"
	EmbedderProviderMock       EmbedderProvider = "mock"
	EmbedderProviderOllama     EmbedderProvider = "ollama"
	EmbedderProviderOpenai     EmbedderProvider = "openai"
	EmbedderProviderOpenrouter EmbedderProvider = "openrouter"
	EmbedderProviderTermite    EmbedderProvider = "termite"
	EmbedderProviderVertex     EmbedderProvider = "vertex"
)

// AntflyEmbedderConfig Configuration for the built-in Antfly embedding provider.
//
// Uses an embedded INT8-quantized all-MiniLM-L6-v2 ONNX model bundled directly
// in the binary. No external service, API key, or model download required.
//
// **Model:** all-MiniLM-L6-v2 (384 dimensions, text-only)
//
// **Features:**
// - Zero configuration — works out of the box
// - No network access required
// - Pure Go inference via GoMLX
type AntflyEmbedderConfig = map[string]interface{}

// BedrockEmbedderConfig Configuration for the AWS Bedrock embedding provider.
//
// Uses AWS credentials from environment or IAM roles.
//
// **Example Models:** cohere.embed-english-v4, amazon.titan-embed-text-v2:0
//
// **Docs:** https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
type BedrockEmbedderConfig struct {
	// BatchSize The batch size for embedding requests to optimize throughput.
	BatchSize *int `json:"batch_size,omitempty"`

	// Model The Bedrock model ID to use (e.g., 'cohere.embed-english-v4', 'amazon.titan-embed-text-v2:0').
	Model string `json:"model"`

	// Region The AWS region for the Bedrock service (e.g., 'us-east-1').
	Region *string `json:"region,omitempty"`

	// StripNewLines Whether to strip new lines from the input text before embedding.
	StripNewLines *bool `json:"strip_new_lines,omitempty"`
}

// CohereEmbedderConfig Configuration for the Cohere embedding provider.
//
// API key via `api_key` field or `COHERE_API_KEY` environment variable.
//
// **Example Models:** embed-english-v3.0 (default, 1024 dims), embed-multilingual-v3.0
//
// **Docs:** https://docs.cohere.com/reference/embed
type CohereEmbedderConfig struct {
	// ApiKey The Cohere API key. Can also be set via COHERE_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// InputType Specifies the type of input for optimized embeddings.
	InputType *CohereEmbedderConfigInputType `json:"input_type,omitempty"`

	// Model The name of the Cohere embedding model to use.
	Model string `json:"model"`

	// Truncate How to handle inputs longer than the max token length.
	Truncate *CohereEmbedderConfigTruncate `json:"truncate,omitempty"`
}

// CohereEmbedderConfigInputType Specifies the type of input for optimized embeddings.
type CohereEmbedderConfigInputType string

// CohereEmbedderConfigTruncate How to handle inputs longer than the max token length.
type CohereEmbedderConfigTruncate string

// EmbedderConfig defines model for EmbedderConfig.
type EmbedderConfig struct {
	// Provider The embedding provider to use.
	Provider EmbedderProvider `json:"provider"`
	union    json.RawMessage
}

// EmbedderProvider The embedding provider to use.
type EmbedderProvider string

// GoogleEmbedderConfig Configuration for the Google AI (Gemini) embedding provider.
//
// API key via `api_key` field or `GEMINI_API_KEY` environment variable.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims)
//
// **Docs:** https://ai.google.dev/gemini-api/docs/embeddings
type GoogleEmbedderConfig struct {
	// ApiKey The Google API key. Can also be set via GEMINI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 recommended).
	Dimension *int `json:"dimension,omitempty"`

	// Location The Google Cloud location (e.g., 'us-central1'). Required for Vertex AI, optional for Gemini API.
	Location *string `json:"location,omitempty"`

	// Model The name of the embedding model to use.
	Model string `json:"model"`

	// ProjectId The Google Cloud project ID (optional for Gemini API, required for Vertex AI).
	ProjectId *string `json:"project_id,omitempty"`

	// Url The URL of the Google API endpoint (optional, uses default if not specified).
	Url *string `json:"url,omitempty"`
}

// OllamaEmbedderConfig Configuration for the Ollama embedding provider.
//
// Local embeddings for privacy and offline use. URL via `url` field or `OLLAMA_HOST` env var.
//
// **Example Models:** nomic-embed-text (768 dims), mxbai-embed-large (1024 dims), all-minilm (384 dims)
//
// **Docs:** https://ollama.com/search?c=embedding
type OllamaEmbedderConfig struct {
	// Model The name of the Ollama model to use (e.g., 'nomic-embed-text', 'mxbai-embed-large').
	Model string `json:"model"`

	// Url The URL of the Ollama API endpoint. Can also be set via OLLAMA_HOST environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenAIEmbedderConfig Configuration for the OpenAI embedding provider.
//
// API key via `api_key` field or `OPENAI_API_KEY` environment variable.
// Supports OpenAI-compatible APIs via `url` field.
//
// **Example Models:** text-embedding-3-small (default, 1536 dims), text-embedding-3-large (3072 dims)
//
// **Docs:** https://platform.openai.com/docs/guides/embeddings
type OpenAIEmbedderConfig struct {
	// ApiKey The OpenAI API key. Can also be set via OPENAI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (uses MRL for dimension reduction). Recommended: 256, 512, 1024, 1536, or 3072.
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The name of the OpenAI model to use.
	Model string `json:"model"`

	// Url The URL of the OpenAI API endpoint. Defaults to OpenAI's API. Can be set via OPENAI_BASE_URL environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenRouterEmbedderConfig Configuration for the OpenRouter embedding provider.
//
// OpenRouter provides a unified API for multiple embedding models from different providers.
// API key via `api_key` field or `OPENROUTER_API_KEY` environment variable.
//
// **Example Models:** openai/text-embedding-3-small (default), openai/text-embedding-3-large,
// google/gemini-embedding-001, qwen/qwen3-embedding-8b
//
// **Docs:** https://openrouter.ai/docs/api/reference/embeddings
type OpenRouterEmbedderConfig struct {
	// ApiKey The OpenRouter API key. Can also be set via OPENROUTER_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (if supported by the model).
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The OpenRouter model identifier (e.g., 'openai/text-embedding-3-small', 'google/gemini-embedding-001').
	Model string `json:"model"`
}

// TermiteEmbedderConfig Configuration for the Termite embedding provider.
//
// Termite is Antfly's built-in ML service for local embeddings using ONNX models.
// It provides embedding generation with multi-tier caching (memory + persistent).
//
// **Features:**
// - Local ONNX-based embedding generation
// - L1 memory cache with configurable TTL
// - L2 persistent Pebble database cache
// - Singleflight deduplication for concurrent identical requests
//
// **Example Models:** bge-base-en-v1.5 (768 dims), all-MiniLM-L6-v2 (384 dims)
//
// Models are loaded from the `models/embedders/{name}/` directory.
type TermiteEmbedderConfig struct {
	// ApiUrl The URL of the Termite API endpoint. Can also be set via ANTFLY_TERMITE_URL environment variable.
	ApiUrl *string `json:"api_url,omitempty"`

	// Model The embedding model name (maps to models/embedders/{name}/ directory).
	Model string `json:"model"`
}

// VertexEmbedderConfig Configuration for Google Cloud Vertex AI embedding models (enterprise-grade).
//
// Uses Application Default Credentials (ADC) for authentication. Requires IAM role `roles/aiplatform.user`.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims), multimodalembedding (images/audio/video)
//
// **Docs:** https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings
type VertexEmbedderConfig struct {
	// CredentialsPath Path to service account JSON key file. Alternative to ADC for non-GCP environments.
	CredentialsPath *string `json:"credentials_path,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 for gemini-embedding-001; 128-1408 for multimodalembedding).
	Dimension *int `json:"dimension,omitempty"`

	// Location Google Cloud region for Vertex AI API (e.g., 'us-central1', 'europe-west1'). Can also be set via GOOGLE_CLOUD_LOCATION. Defaults to 'us-central1'.
	Location *string `json:"location,omitempty"`

	// Model The name of the Vertex AI embedding model to use.
	Model string `json:"model"`

	// ProjectId Google Cloud project ID. Can also be set via GOOGLE_CLOUD_PROJECT environment variable.
	ProjectId *string `json:"project_id,omitempty"`
}

// AsGoogleEmbedderConfig returns the union data inside the EmbedderConfig as a GoogleEmbedderConfig
func (t EmbedderConfig) AsGoogleEmbedderConfig() (GoogleEmbedderConfig, error) {
	var body GoogleEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGoogleEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided GoogleEmbedderConfig
func (t *EmbedderConfig) FromGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGoogleEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided GoogleEmbedderConfig
func (t *EmbedderConfig) MergeGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVertexEmbedderConfig returns the union data inside the EmbedderConfig as a VertexEmbedderConfig
func (t EmbedderConfig) AsVertexEmbedderConfig() (VertexEmbedderConfig, error) {
	var body VertexEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVertexEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided VertexEmbedderConfig
func (t *EmbedderConfig) FromVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVertexEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided VertexEmbedderConfig
func (t *EmbedderConfig) MergeVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOllamaEmbedderConfig returns the union data inside the EmbedderConfig as a OllamaEmbedderConfig
func (t EmbedderConfig) AsOllamaEmbedderConfig() (OllamaEmbedderConfig, error) {
	var body OllamaEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOllamaEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OllamaEmbedderConfig
func (t *EmbedderConfig) FromOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOllamaEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OllamaEmbedderConfig
func (t *EmbedderConfig) MergeOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAIEmbedderConfig returns the union data inside the EmbedderConfig as a OpenAIEmbedderConfig
func (t EmbedderConfig) AsOpenAIEmbedderConfig() (OpenAIEmbedderConfig, error) {
	var body OpenAIEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAIEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) FromOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAIEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) MergeOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenRouterEmbedderConfig returns the union data inside the EmbedderConfig as a OpenRouterEmbedderConfig
func (t EmbedderConfig) AsOpenRouterEmbedderConfig() (OpenRouterEmbedderConfig, error) {
	var body OpenRouterEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenRouterEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) FromOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenRouterEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) MergeOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBedrockEmbedderConfig returns the union data inside the EmbedderConfig as a BedrockEmbedderConfig
func (t EmbedderConfig) AsBedrockEmbedderConfig() (BedrockEmbedderConfig, error) {
	var body BedrockEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBedrockEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided BedrockEmbedderConfig
func (t *EmbedderConfig) FromBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBedrockEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided BedrockEmbedderConfig
func (t *EmbedderConfig) MergeBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCohereEmbedderConfig returns the union data inside the EmbedderConfig as a CohereEmbedderConfig
func (t EmbedderConfig) AsCohereEmbedderConfig() (CohereEmbedderConfig, error) {
	var body CohereEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCohereEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided CohereEmbedderConfig
func (t *EmbedderConfig) FromCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCohereEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided CohereEmbedderConfig
func (t *EmbedderConfig) MergeCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTermiteEmbedderConfig returns the union data inside the EmbedderConfig as a TermiteEmbedderConfig
func (t EmbedderConfig) AsTermiteEmbedderConfig() (TermiteEmbedderConfig, error) {
	var body TermiteEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTermiteEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided TermiteEmbedderConfig
func (t *EmbedderConfig) FromTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTermiteEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided TermiteEmbedderConfig
func (t *EmbedderConfig) MergeTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAntflyEmbedderConfig returns the union data inside the EmbedderConfig as a AntflyEmbedderConfig
func (t EmbedderConfig) AsAntflyEmbedderConfig() (AntflyEmbedderConfig, error) {
	var body AntflyEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAntflyEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided AntflyEmbedderConfig
func (t *EmbedderConfig) FromAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAntflyEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided AntflyEmbedderConfig
func (t *EmbedderConfig) MergeAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedderConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["provider"], err = json.Marshal(t.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *EmbedderConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &t.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8Rb/XLbOJJ/lS7OXsX2SZQdZ7IpbU3tObaTeNdfZTs7uzdKWRDZkjAmAQYAbWtcrrpH",
	"uD/uNe6l9kmuugFSlETZTm737p9EJtFAoz9+6A/wIUp0XmiFytmo/xDZZIq54J97yo2z2WE+wjRFs6/V",
	"WE7oeYo2MbJwUquoH/nnpRH0N4y1ATdFGJUyc12pwE8CyLNINYHC6FuZookHaqA+W7QgVHiNKRydXr3r",
	"fi2FcvI3TEFkWfdEKnl80j1+2719DWenp3+FXKeYwahUaYYppNJg4rLZQEnl15ZKmFkMpxrw3qFRIgOL",
	"5lYm2IG98yO4wVkHtAnzpPpOZVqkYPBrKQ2mzNnW1gm97W9trTKxsfvuDaQyR2WlVrYDDu9dV6tstulJ",
	"P6BwpUHb39oaqC78OxoNyYKc/v4f/wV32txY0KUDPfaM63safqpBoaO3IJIEra05o7fnpUH4qEGqMRpU",
	"CcKtFPBRnxz/NepEeC/yIkNSUyXoqB8JVkL02IncrMCoH+nRr5g4evAeU6OTm+/T8t7PlxAmeFLDNC4x",
	"mKJyUmQWxkbngOpWGq1yVI6UcbR3AkZnaIP4D/1OgNVAkoRET9FgzAt1UU0yaafd2zcdELn4TavYSSdU",
	"179mjdy+7m/7yQ50wlNMnStsv9dLdWJjcWfjQJrovDfyG+llwqF1vdKimZQyxR6bie3asii0cZjGU5dn",
	"i7LmIVE/WsNi1GlqIywUdSKDEy/e0nZRWNfdIZUURhdonET2wpFwyfTayt/Qa2UsysxF/Z3OkoauyIBo",
	"LNBYVtFcJWRAaJ0Fp0EXTuY0xE2NLifTonRxVFuGVA4naIiPsKmHloUqpXsPOjqgeUuLsIHxJO7AqzVy",
	"eNWBV08p69Vm3JTrE+IM3FpnpJoQs5Uo27gl8/Pva8utNhBwoWa8VsQyK3MNtSxOv4prhXfXmVRebbWi",
	"xiKzuKysn6fopmhIbEwLCu+Aab1vEItSFaVjaIERjrXBuT4b+hppnaFQ0SPLwMNE1P8lKO9Li8fvs1C/",
	"z+E97TpfD9jKgDQUhby+wdkQxhKzlDx8uH/26fDi8Hrv/Oj6z4d/Gy4gwK0wUowyXOv9S0awG2/DRhBy",
	"B3a2XzMi281OGJiXmZOZVJNSZDz6CSAIZkYgYDCgao+nWfRy1sh1pX0UJplepzopaQNR7S/RKqeL/u+X",
	"W/X0ILF2Gw6SDyKOYV8oEJnVMEKw6Fjmi/JtF2+b+Tb31bDcli0u8nVZYCLHEi3bBtHTSebtliymQpp0",
	"bjCWvUqVOdno6vzhydcSzSzqREkmrJVjmbAV8oPSOmS+v7RspIFY1R5albEqXiVyrI7hFSP3KOchbhEV",
	"WmdfYcuZUiXCLUn38PRghZVP+o7WmQoKbbwkLWRaTQgrpsLHN7m4B6dvUEGGauKmTZGenp0eRp3o8mrv",
	"4irq8BqrgnoxVKyChMiys3HU/+Uh0grDr98ZHEf96IfePJLshTCy91HrSbYMNo+dp4n+gsbh/TcSnWWZ",
	"yMW3EhWo9o6+g+hClw7NNxK2x1rPUbXi9XNEV2hy6b6VqjXif/xCZItQNUezpyespjqvxi/bXj3Rl8cv",
	"y86wB6UieEmXYmeCljpnWDmEqiUtJEIROlbEmMKddFNwmBcc45GnJaV1mqOhqb6DCoksCIMDlWh1S6aY",
	"0sj2gxiu6tko/vnEjjsSxoKdKSfuQah0oELoyCisSzvPjqaYFWiqkLeaCy5n1mEesoetrUueamur35w/",
	"bIP2v1GdZtP69a+WjzMfwG76afZFMpVqQvPMuRYGQZRO58LJRGTZDBKRTCtZ1YIfZQhXV8f1kduHHyGX",
	"qnRoq9m1IhEtzm4wQXmLDFvjMstqCYOwNDlR+L2/r0TyyYuENz9QOzFsbdnElKNPLs+2tqALF5jrWwRv",
	"KT3rZhmCExPKI1NK+IxIHCQUFHmdcUD16erkeKAAYDgczqXETx4e6vmBIvtr5ku5x8eKgP+vFrYwHJTb",
	"27uJZ4B/45AXr14QS9Vz4izQ76WppUDPx3li7NDAKOPcKUNvdhtFB1J524HpTnf6tgOZ7AC6JN6sWXCl",
	"URaKTMiwPdZTYZAiWaQkVqRiJDPpZiS/1yQ//MqCO/xaCnoO5KjCSBt8KdEqleRZIrNrZfSDHMMGfgXr",
	"hCstDCKROHmLg2jz8XGPf5IDmIeHnhwHyc2J/o2iwkFkKV4QGdNc+t8+OmxSsbwHapcYzzGVgnn/iOrP",
	"0kGqXWF0XjjgVyH3p8VpIxzz5ToVGQQdrt2OJy9N9pPMxQQPhBOfL45qxuev3VTamMdclyZrGTCIKu8L",
	"YQE7HlPEvxaTQdRKY3eJQKWFlsr1RmVygy4QFWod0Vhm2O/1eoVw057TLYsE4QEQalT5Kny+OIZLQuRQ",
	"kWBTGqbCif4QuvBeWHz7BlAlOsUU6Dl8vjiyVVLkR/JivV8LnPxhxASdOI6HlWEOSQj9Xm8IPf/b8h9d",
	"+BlHtL71dlojTaUgHzWm6EiNWlWzhZ3SBMc6YTPJ0DIqAu2+cqkhy5GGXe522aydJKiyThsxQdgYa5ML",
	"1w8DlwVO+clmLbC9mrn9wNy50QlaK9VkLretrSOShCWgOwilI0w7YNByqLshx6AQU0w3O7BwgtSCrWc6",
	"P/hgPWDeuwq6kHOlsTTWQUF7MKhSpNNLWGAl1OQEakR+wT5PMLg4T0mcw4n+TWaZCKNqZPA2gklpCBJo",
	"x0ZntX1UO/MHRGE0KQhTGM1qzdmK1qKjY8jChkWKnptn9UWVT232KxTMMn2HKUy1dXA3lQ4zaV14eW7k",
	"LR2AR+ceGfl0KwzeMjpeXl58AOGcSG5sZXgVo77qkclcEozWp9TO9vbJ+5WxTuaoy4WBu9v1lKzfeX1v",
	"ddLX22/eFfcdtuZu0HtlRpeI/Tq79HW3WGrOM3sLYcwPlfy63UQTLg3UGwZrdsMrrZUHbf7T245UcHV2",
	"dgreqGHjipKA7pmRqEg3Zxy3w6l2vMDmWvCbLwEMb4zBtoac9tch2TgR5gbNT1zVAKlSVO6nN8+Rpsgy",
	"RPPTIBoMXCtc/TwVDqTlHf4xWCHvVloQ/shKXAemZS5U11QWH0SRopUThSkfA4VglwXrTJk4DvxYfE7D",
	"8fEJBVsAcOSqsNHC1tbudvft9r+ErMpgWjIacc2Rjkrvv3+6PDsli80oBZPKCalomamcTGlinpbGG5wG",
	"yxFJUhqRzOJ6l3/GGSxUh9ni9v3uqpjR++2wP+Tt3OCseyuyEqEQ0tTBhDFiFnQCOSvF9mFI4cYvP+x+",
	"6YOQHZ9Nd/KsimCuxKjMhKmkRrNTiK1N7iVUS6xa5azO4Gns8fEJFMIwdxTvlARM1glFoXCgOAmSsV5T",
	"y/EIC+E9KhxLZ5ugeqzv0HB5I9HW2RDppWXCsie1lJbcMkehKCWm0cRPTVHP9EFYiqwM2kIri36qY7TW",
	"z8Nhf+GBvaY5oag+qSJY6MIH6SCnh/OUgA4wCrp85s2YUO/ojHOW5una9JYhbIy0zjb7FALCDxStjSXl",
	"8CBYi4kuaYFM3iAMSXvDBtg4U2J9ynqHG8KGVG6zD0f8p0daW4iEFEOKUmj5HGFAWECueqbaJYew4esC",
	"m334wKU6i4Uwwmnjy37BZpjV5lxKK+xw1jMMXj2sCOz8UK0Kebp0RekqAVVBtZMuQ9qHMzo4HYnlL5jQ",
	"8pdsvzxQlG6qTR/+JBTCgfZnYLux86scneCwhf8CQB/h9uF1eEBHq+3Dmx+3V5DowO+Q4PZi72N/a6vG",
	"IUpjwv6bPlQnNf6oJi14WvhaopGhpcFz1+dhw1Z49lBL85Wu+QkykW5ajjikdFqrrl+VfwfqjxqOSMJ5",
	"ZQmtxCIrbtDeSNWbaE+8kHAGLVVZ10G1IQ7aGrJcOk2uvPooSvVDYlYoofuBcItvUuH4xZWYWHrxA4pk",
	"PndMunx8fHigY+PxsQMPDz0aQBQD9fDQyMmCqij4qWOREPPQ7leYPPemRWsqkXvm5nWG/kL+1yhAXFMu",
	"SIPPjUywD797eCjoV4OFk3m+wYLi6OxJBmrxrGQgLWw1mGksuj/P1oINUvC1uurCYpSIeRd6fHw/o8mr",
	"v+rUa56tJcLhRBvK2AqDuSxzztj+/t//Cef+7ypAbhCPdDprcLm1ddioPv8lVJ+rhujw4+HJ0enRvBPQ",
	"rQrb7E++aAh7Rzz27PzwdG/tWF/Baw58v3d5eP354rhKbTj9mQ9tpgl75xSME+nx8d7J3vWns8srIvO1",
	"RG4OoWH6kAqFLCejnIQC2P7OzpvdN6Hre5RTvkXef26QlykJhQ/r2nfwrr/pkmtTkscD3kvLVPMiOWxw",
	"0cIz3AkFaW5ZCzWry12bFI1LlWSlP3/dFPO6G04INNOlaRxgPqwgDBtez9cKDZoYrqbSwmhG0ZOv6A/U",
	"vMQ2QYUhpLcOCz7+74x0aOGWwdrOV3Y69K9SvA+VrUuHhd/+Tgz7Bglz6jEh2fHFuSmCKAqjCyNpUB2F",
	"cynjZ1px6Uhe2EwfHmAQ+TIMz30q8lCKGUR9+CWOY/+yJvEv4zj+Ao/Dhd4TszscDn+1tPoDwe0gYp+i",
	"qQbRyQwqnBxEHf+6KjvwgBpFKaqglatRDYZp5IM/kgZRPrv2wrxm3pnj7XinA9vxa/pntwPEKA1/HKim",
	"s322CPvC1g52IifG1wbZkITS3G70s3OsRzm8l1+L/dEUn+2STQYT8Eng/GIFJ+VMMbf/omn/LVbsuans",
	"eGnh99zELurUu8mDHo8zqbCqw0o1QRtaQy3deO4r19Td3a7NRZYtNuN0gUpIrkuvFKtbG3GrZedmZyi0",
	"YSaYSyWjTsTZ/33UiTRDCv3wC/ofhtsIUadxJyB0BztR7v92vpIfdapbHG2Nr9Y2ywt7ujXawsZHZnvz",
	"e/u7y6j+Tf1dL7KGura3dxod3t3t37/2Hd72Rq6Q8YQ3Eqd42wuTiUL6zHtuQouWUrdcI8JKGt+lPztR",
	"jTtRn1aeN3fb2Fy0qKD7b2vvVkp4qr27KN6Xt3cbe2n0H/22VjmZ1z1CO3RuDAE+Nn7/9l0Hdn7cfcvO",
	"zJoxmOg8p/A33Wy/TUJnplt7RSPsfz/TZQrV0OatjASVMyLbebUZw0VoILEJ+2YhEMLoYh4Xgbdlkmir",
	"UFpaxWtU+3Sz+CVd4jUTr/BUGE0J27VMXyCkMBiODmBjzcY79cWxRUlttkqkNGsu+1D8E3bbMNOqljpf",
	"nZNBWydIcgxKO7DhkoC3Cx+xRv2oNDL6/sZ0a7P3hXgXgrs1GOfLzY0jhytKRt6KZMZRT3UEkZZZNIyG",
	"pcmaSLgQT6K6JQddi3xK5zJpXIViB6tus+T3IxFMp5sJM0HYaF52EVnWJXVneX0rcR1C+hOIs0GfK/8x",
	"+aneZ/sBuszZ0tFZHWlsOVF7bLyKg09cK2s6VlBT06tqPFjm61UHXq0IavkGV8tm1vtAhQlrNtV52k0C",
	"7003aYf0hp2sxfP5DtYy84/yqrbbEC/1Kqb93shhOcdbEzmElpZdk8otu+Jaj2sPDJv3yX7cfVu52Mrg",
	"4IbPRSRFJhwpJvYRHzseByPclH9JTGJvunEcN26WfUtA+03hR9Dek+HHoo6+I/ywq2ufcVWwEXNU5jS3",
	"ow0+VE5CDj8fWVfpOSCoo48+vP7xbQd+3HntbwUuBSrP3nStHH+tqJ9BLS/I9bHA2nlfhkUc6hayYVPP",
	"YtFctXMsCiVOroX7Aa8sh0qs+VWlVzWVF4JUK5f/QJBqvX31DUDl6deBVWNE3SIS9V0kEmR92YBgZSkC",
	"DDd4UznmSm/dZuJbPi/BwYuzz1eHF9+ZRXmJ954BuM3O2oEMbp2B8slUry107cDXO1Q9+me38ebdaE3c",
	"Uee5sQjpGOVlSzdtnwNCbZaw8MmdrkJiyLS/HRaDJTwLjYtq+7+DRzmG+ssEGM38DVGS0eaLse45UT4p",
	"GA91kr/tGEs0dZD25KwUsT1hYsux23Mcfi+YtF+TfCGSBOJ1MFK9ljZ8BPWqcfHv5Lj+9ICmy5azDl+r",
	"nX/tRODRbFm3VmZ9t4ZwqetIE4m/8AcbOebazOBfoUBjpXWo3Gbc+qmST39o3e5I2ObN7cZCPHAHwqx8",
	"X7D9uiAPfN1YFc5xRO/qCiQT07BLqSYZjjM5mTpIMS2LLDTDqjtqSWkYT72pEZvVVy3rwHA0Qd5FF1X3",
	"dif+cSGxWvtVl4/n/Cx8+8Xf8Jl/mDH0Ggm4hcb2fGOpNww1cG1m8SqUrcmS3m2/e92AtWWeF5GsKga2",
	"wthLEvjKKJ9PTfZOrz4c/+366vDi5OjqWw7/tt09ffY/+anRcoGFo62NXBQcvKxTxVwTS0jSIt/vBY/W",
	"a+ovwI6FMk5dlFmNIzZQOTSFkRa7EyNS3Gx8UVfM/aPqV+83vrDb2DvY3/Q3pUs39Q5Dg+vima0/uIMh",
	"f3bXE7LOWEqLZvi/r9R2GjcymycW35/riTKVukeWrddkUAlJqCrrUvrkq+ldIXsVGN1iV6zUeHsTdN3F",
	"s8IOlnoEKwXeeX0yapQbo5dUfuuiXZTPupOk6IZni74bWgErrtv4MPK6EG66akLnwk35U7FwYoiEb4z4",
	"C0ncCJUZxrCXcU+Gr8M6DXsH+/4yiFbdj/vnTe+1/291YmKoTZB/gJ3X77o7b7bfLd3krUe9qKxcRTSL",
	"GlxkfsH9Gp8Fzj2RwLGt9NyBV1iS7rp3aB2Xolvr9GdnH48Pr/ePzz4fXB+f7e9dHZ2dLuZcC9P+U+vT",
	"a/Hln1apXlOlfoGszi/O/nS4f/XS2PmFQP3IX7iN9Sqne8onv+dHVZV6MeJg3CaBzZO51VjPQv2V+8F7",
	"5lI6luW87w9VR3HxcqxvD3qHi7bj7Zi//uVQt5BRP9qNt+NdwhDhpjbqqzLLHv8nAAD//19Z/gevPwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
