// Copyright 2026 Antfly, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package chunking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package chunking

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly/go/pkg/sdk/oapi"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// AudioChunkOptions Options specific to audio chunking.
type AudioChunkOptions struct {
	// OverlapDurationMs Overlap duration in milliseconds between audio chunks (default: 0).
	OverlapDurationMs int `json:"overlap_duration_ms,omitempty,omitzero"`

	// WindowDurationMs Window duration in milliseconds for fixed-window audio chunking (default: 30000).
	WindowDurationMs int `json:"window_duration_ms,omitempty,omitzero"`
}

// BinaryContent Binary media content with format-specific metadata.
type BinaryContent struct {
	// Data Base64-encoded binary data (valid WAV, PNG, etc.)
	Data []byte `json:"data,omitempty,omitzero"`

	// EndTimeMs Audio: window end time in milliseconds
	EndTimeMs float32 `json:"end_time_ms,omitempty,omitzero"`

	// FrameDelayMs Animation: display delay in milliseconds
	FrameDelayMs int `json:"frame_delay_ms,omitempty,omitzero"`

	// FrameIndex Animation: frame number
	FrameIndex int `json:"frame_index,omitempty,omitzero"`

	// StartTimeMs Audio: window start time in milliseconds
	StartTimeMs float32 `json:"start_time_ms,omitempty,omitzero"`
}

// Chunk A chunk of content. Text chunks have mime_type text/plain.
type Chunk struct {
	// Id Sequence number of the chunk (0, 1, 2, ...)
	Id uint32 `json:"id"`

	// MimeType MIME type: text/plain, audio/wav, image/png, etc.
	MimeType string `json:"mime_type"`
	union    json.RawMessage
}

// ChunkOptions Per-request configuration for chunking. All fields are optional - zero/omitted values use chunker defaults.
type ChunkOptions struct {
	// Audio Options specific to audio chunking.
	Audio AudioChunkOptions `json:"audio,omitempty,omitzero"`

	// MaxChunks Maximum number of chunks to generate per document. Zero (the default when omitted) means unlimited: the document is chunked in full. Set an explicit value up to 4096 to cap output; any chunks beyond the cap are silently omitted, so treat a result whose chunk count equals `max_chunks` as potentially truncated.
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Text Options specific to text chunking.
	Text TextChunkOptions `json:"text,omitempty,omitzero"`

	// Threshold Confidence threshold for model-based chunking (0.0-1.0).
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// InferenceAudioChunkConfig Audio chunking configuration for inference, including VAD options.
type InferenceAudioChunkConfig struct {
	// OverlapDurationMs Overlap duration in milliseconds between audio chunks (default: 0).
	OverlapDurationMs int `json:"overlap_duration_ms,omitempty,omitzero"`

	// Vad Options for Voice Activity Detection (VAD) based audio segmentation.
	Vad VADOptions `json:"vad,omitempty,omitzero"`

	// WindowDurationMs Window duration in milliseconds for fixed-window audio chunking (default: 30000).
	WindowDurationMs int `json:"window_duration_ms,omitempty,omitzero"`
}

// InferenceChunkConfig Configuration for chunking requests to Antfly inference.
// Combines shared text options with inference-specific audio/VAD options.
type InferenceChunkConfig struct {
	// Audio Audio chunking configuration for inference, including VAD options.
	Audio InferenceAudioChunkConfig `json:"audio,omitempty,omitzero"`

	// MaxChunks Maximum number of chunks to generate per document. Zero (the default when omitted) means unlimited: the document is chunked in full. Set an explicit value up to 4096 to cap output; any chunks beyond the cap are silently omitted, so treat a result whose chunk count equals `max_chunks` as potentially truncated.
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	//
	// Example: fixed
	Model string `json:"model,omitempty,omitzero"`

	// Text Options specific to text chunking.
	Text TextChunkOptions `json:"text,omitempty,omitzero"`

	// Threshold Confidence threshold for model-based chunking (0.0-1.0). Used by ONNX text models and VAD audio models.
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// InferenceChunkContentPart Content part supported by chunking requests.
type InferenceChunkContentPart struct {
	union json.RawMessage
}

// InferenceChunkRequest defines model for InferenceChunkRequest.
type InferenceChunkRequest struct {
	// Config Configuration for chunking requests to Antfly inference.
	// Combines shared text options with inference-specific audio/VAD options.
	Config InferenceChunkConfig `json:"config,omitempty,omitzero"`

	// Input Input content to chunk. Supports two formats:
	// - Text string: `"This is a long document..."`
	// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
	// - ContentPart: `{"type": "text", "text": "..."}`
	Input InferenceChunkRequest_Input `json:"input"`
}

// InferenceChunkRequestInput0 Text to chunk
type InferenceChunkRequestInput0 = string

// InferenceChunkRequest_Input Input content to chunk. Supports two formats:
// - Text string: `"This is a long document..."`
// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
// - ContentPart: `{"type": "text", "text": "..."}`
type InferenceChunkRequest_Input struct {
	union json.RawMessage
}

// TextChunkOptions Options specific to text chunking.
type TextChunkOptions struct {
	// OverlapTokens Number of tokens to overlap between consecutive chunks. Helps maintain context across chunk boundaries. Only used by fixed-size chunkers.
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Separator string for splitting (e.g., '\n\n' for paragraphs). Only used by fixed-size chunkers.
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk.
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`
}

// TextContent Text content with character offsets.
type TextContent struct {
	// EndChar Character position in original text where chunk ends (exclusive)
	EndChar int `json:"end_char"`

	// StartChar Character position in original text where chunk starts
	StartChar int `json:"start_char"`

	// Text The chunk text content
	Text string `json:"text"`
}

// VADOptions Options for Voice Activity Detection (VAD) based audio segmentation.
type VADOptions struct {
	// MaxSegmentDurationMs Maximum segment duration (ms). Segments longer than this are split. Useful for Whisper-compatible chunking. Default: 30000.
	MaxSegmentDurationMs int `json:"max_segment_duration_ms,omitempty,omitzero"`

	// MinSilenceDurationMs Minimum silence duration (ms) to split speech segments. Gaps shorter than this are merged. Higher values produce longer, fewer segments. Default: 300.
	MinSilenceDurationMs int `json:"min_silence_duration_ms,omitempty,omitzero"`

	// MinSpeechDurationMs Minimum speech duration (ms) for a segment to be kept. Shorter segments are discarded. Default: 250.
	MinSpeechDurationMs int `json:"min_speech_duration_ms,omitempty,omitzero"`

	// SpeechPadMs Padding (ms) added before and after detected speech. Default: 30.
	SpeechPadMs int `json:"speech_pad_ms,omitempty,omitzero"`
}

// AsTextContent returns the union data inside the Chunk as a TextContent
func (t Chunk) AsTextContent() (TextContent, error) {
	var body TextContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContent overwrites any union data inside the Chunk as the provided TextContent
func (t *Chunk) FromTextContent(v TextContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContent performs a merge with any union data inside the Chunk, using the provided TextContent
func (t *Chunk) MergeTextContent(v TextContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBinaryContent returns the union data inside the Chunk as a BinaryContent
func (t Chunk) AsBinaryContent() (BinaryContent, error) {
	var body BinaryContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBinaryContent overwrites any union data inside the Chunk as the provided BinaryContent
func (t *Chunk) FromBinaryContent(v BinaryContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBinaryContent performs a merge with any union data inside the Chunk, using the provided BinaryContent
func (t *Chunk) MergeBinaryContent(v BinaryContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Chunk) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["mime_type"], err = json.Marshal(t.MimeType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mime_type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Chunk) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["mime_type"]; found {
		err = json.Unmarshal(raw, &t.MimeType)
		if err != nil {
			return fmt.Errorf("error reading 'mime_type': %w", err)
		}
	}

	return err
}

// AsExternalRef0TextContentPart returns the union data inside the InferenceChunkContentPart as a externalRef0.TextContentPart
func (t InferenceChunkContentPart) AsExternalRef0TextContentPart() (externalRef0.TextContentPart, error) {
	var body externalRef0.TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0TextContentPart overwrites any union data inside the InferenceChunkContentPart as the provided externalRef0.TextContentPart
func (t *InferenceChunkContentPart) FromExternalRef0TextContentPart(v externalRef0.TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0TextContentPart performs a merge with any union data inside the InferenceChunkContentPart, using the provided externalRef0.TextContentPart
func (t *InferenceChunkContentPart) MergeExternalRef0TextContentPart(v externalRef0.TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExternalRef0MediaContentPart returns the union data inside the InferenceChunkContentPart as a externalRef0.MediaContentPart
func (t InferenceChunkContentPart) AsExternalRef0MediaContentPart() (externalRef0.MediaContentPart, error) {
	var body externalRef0.MediaContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0MediaContentPart overwrites any union data inside the InferenceChunkContentPart as the provided externalRef0.MediaContentPart
func (t *InferenceChunkContentPart) FromExternalRef0MediaContentPart(v externalRef0.MediaContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0MediaContentPart performs a merge with any union data inside the InferenceChunkContentPart, using the provided externalRef0.MediaContentPart
func (t *InferenceChunkContentPart) MergeExternalRef0MediaContentPart(v externalRef0.MediaContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InferenceChunkContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InferenceChunkContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInferenceChunkRequestInput0 returns the union data inside the InferenceChunkRequest_Input as a InferenceChunkRequestInput0
func (t InferenceChunkRequest_Input) AsInferenceChunkRequestInput0() (InferenceChunkRequestInput0, error) {
	var body InferenceChunkRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInferenceChunkRequestInput0 overwrites any union data inside the InferenceChunkRequest_Input as the provided InferenceChunkRequestInput0
func (t *InferenceChunkRequest_Input) FromInferenceChunkRequestInput0(v InferenceChunkRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInferenceChunkRequestInput0 performs a merge with any union data inside the InferenceChunkRequest_Input, using the provided InferenceChunkRequestInput0
func (t *InferenceChunkRequest_Input) MergeInferenceChunkRequestInput0(v InferenceChunkRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInferenceChunkContentPart returns the union data inside the InferenceChunkRequest_Input as a InferenceChunkContentPart
func (t InferenceChunkRequest_Input) AsInferenceChunkContentPart() (InferenceChunkContentPart, error) {
	var body InferenceChunkContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInferenceChunkContentPart overwrites any union data inside the InferenceChunkRequest_Input as the provided InferenceChunkContentPart
func (t *InferenceChunkRequest_Input) FromInferenceChunkContentPart(v InferenceChunkContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInferenceChunkContentPart performs a merge with any union data inside the InferenceChunkRequest_Input, using the provided InferenceChunkContentPart
func (t *InferenceChunkRequest_Input) MergeInferenceChunkContentPart(v InferenceChunkContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InferenceChunkRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InferenceChunkRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fhtb+O4Ef4rA7XAJoAse1+6aN1PaXK42w/7gibNFl0HCS2ObHYpUktSjn2B/3sxJCXLtuz4ti1wB9x+",
	"WYcih8+8PZyZpyTXZaUVKmeT8VNi8zmWzP+8qLnQl/Naff1YOaGVX+RocyP838k4iR/AVpiLQuTgNDA6",
	"BjmdE2qWJWlSGV2hcQK9BL1AI1l1z2vD6PR92Sc4bIJmEwgFpZBSWMy14ham6B4RVfc2C2ccC1ZLN4bR",
	"OV1csqUo6zIZ//ntmxH9S5NSqLA0ShO3qjAZJ0I5nKFJ1mnyKBTXj8ehffZ7DiMrtIFCLJEPgrQdg3RA",
	"viZI3wN03S7p6b8xdwT9b0Ixs7rUyqFy+6jDZyiRCwZ52AWPws0Jb8ncoHVhiY5x5ti+52i1RzKz+PbN",
	"AFWuOXKYhotoL5wtmBQcPl/cpvDpw48poMuz8yRNwp3JOJmuHCatNtYZoWakDSp+70SJvR7wgTmGaF5U",
	"HGjrriO61xRSM7e5R9XlNDi8MKzEe46SrfqvUqL0bh4DF7aSbAV+c89l+9EUhAvFcXlUst8HEVSfIOuY",
	"cafaw2/+Xov0RZanALqVSfmxSMZfnhKtMP76o8EiGSd/GG5oZBg5ZHiDS9cE5Do9vnc7fNd3tH87+gTf",
	"1/wav9Wo8sZ4oAtwcwy5BmejFF6m8CqFLPNRt2PYNFkOZnoQV2uh3OtXpG9Jdg6ru/e9f/f+B6BPY3C4",
	"dMNKMqHSkOHDR7ZIQZRshsNKzUKw78f2Ok0MfquFQZ6Mv5BW3Rvv9ux/l+56O6qniyaPMyBLNyQ4ZwuE",
	"VmIHZ9Y68yCff0IzIHRoHQkvxKxhOWK1ltPhQkooBEpugRkE7c8zCQP4GY0e6lI4hxwWTNZoobbRJWgg",
	"kp/dZxdvRPpxLEz236S1Z8/7oHyPxwKzdgIkmslpmKFCwxxCRcB0XpfemP9Co+GM4iiChcc5KohKnUOJ",
	"TFmolRSlcMjHPuSa4yBs1JVT+hW1lBlcowOmAJeVFLlwwS5QVwTizegvb+n/nFWga1fV7q/A1KqBOcWV",
	"JoKjqGaVt7YVEpWTqwZRClaDM8gcMDBoA2LdGB1yXSsH+K1m0sLDxlgPwCxUmiJIMClX4EytcuaQbz1J",
	"BPC5d5OC7DnXeTbY8ZybG7RzLXtS+5LCj/vkbnf5KCw1RzmYMou886iOstHgZRZe0z2Sa3V52avIMfJ7",
	"pwo0hGITeR7Z7AANbyDt549oZKUgVC5rTttuL65i/tjfVq20YPw5l99eXHWc/RsurtooOBoAlwcZEyKp",
	"etq5UK6Qq000ZBN1qcupUGjBzplB7km7iYpQpbW7N4VaeHW68TNR38eqh4P8d3b9FbCrZ7xgfG8xYjbK",
	"gWS3NLhpah8KOX+KdK8tZvCDcHM08MIffOGD04qykghOf0W1w6cpaAMsilBUnRZGl+FvO4xvuR0+0af1",
	"kBTCJSNpHWh7Nf2v6JGAf9CH6Qo+fvjwz5BtQTdgintKDrwSFv9vb0qTaRQkn5hxvQr6Tq2imt7WVaWN",
	"C8j3qIVQnlaXx8wUanbfKdE9gOfK9M7R99RKbp2929Pt7wEb6bVNS3lLoSfx0g4lCVXVPcZ6R8ttc+vi",
	"s5DBdbCbBfeoY7trxxM1CGVzCNAxPEySm7mwRDEMpFazDWll2SR5oAMddcfw8DTxvp0kY5gkvrOeJClM",
	"fJ8cFif1aPQ6n/oO2f/GsKMtz8O2tn+YJOvn7qFgDULCL1rzAOnkVgjscAPp2tikJz1/oSe6Xt9tabx3",
	"7noCfy+7Txoouba5OTpP8jzWI/LDpjX0O0hkPNNWRrlWFvPaiUUkUJvBTygrCyUTyjGhQlgtHbDcaBtf",
	"IZjqWnFmBNoMPiq5Iq712RlqFCt+bjsfu0X7L0cn1VgWK2aY06av9Y2fYgAHSq+kcM5zHWazLIUXk4ma",
	"TFQgfDowM6ya2/PT4O5TODMzdAdNfeM/d5vxYHGqAEIu/mIbrA+F0aFBV2iFuwOufM4My51HVFjs6z1R",
	"8Xva1kPA7eFKW9HUpNqImaCG14fE4xxNUw4gValnuMxlbcUCz4/Mc/43F3pZ/fOn5sE9UCTExIqGfG5Q",
	"4YVtQU83ZutL9k7xfzDNKSpvtcgRLnInFsKt4Aod5l7ts9uLq3MIb3h4ji3OiI99fb3vRKq94o7jTUZT",
	"tcbNm27jrKTMuA7L1j8CaMDNmQJHT4OvDynFfAFR1NIr8HkubIVmQLTJnJhK7ExKrrb6kazXT6VQ977s",
	"zPEZ4CFRIG7eBk685sEReWI+b9SzGfzIKmotqHbYVadEM0OewU9iRvVhnNhURvM6x2iBFAp8RNMR2NXq",
	"iE4ex4kqBczbGhW+Cm3c5DRMEb5i5TK4jso0kLwuXNicGU7qtABf/ekAwAiuYrwX1yfGfXvucTDuJ9tY",
	"aIO+QmSF87MsClXkEfyWWfou7eOyYwVVT4EjhcJmxL49yz/zKRIHkHHS/t+P8LNThvWnDEwjvu6QdCaK",
	"vXnpef+zE2WjolfiS6i1OqRziLLoaxp0Pj5k3fLDbk18/Inx3UYtnSg1ZxJ88bNv9wNU3BF0kuJezKl6",
	"72xudF37ArrQPSVFHD6sKgzUHAoexZtQ69RgTjjf7V02bcgNnUrSZIHGBnGjbJT5gbquULFKJOPkdTbK",
	"XpNxmJvbZKxqKdf/CQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
