apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - antfly.io_antflybackups.yaml
  - antfly.io_antflyclusters.yaml
  - antfly.io_antflyrestores.yaml
  - antfly.io_externalinferencepools.yaml
  - antfly.io_inferencepools.yaml
  - antfly.io_inferenceproxies.yaml
