// Package websearch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package websearch

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/go/pkg/libaf/s3"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BraveSearchConfigFreshness.
const (
	BraveSearchConfigFreshnessPd BraveSearchConfigFreshness = "pd"
	BraveSearchConfigFreshnessPm BraveSearchConfigFreshness = "pm"
	BraveSearchConfigFreshnessPw BraveSearchConfigFreshness = "pw"
	BraveSearchConfigFreshnessPy BraveSearchConfigFreshness = "py"
)

// Defines values for ExaSearchConfigSearchType.
const (
	ExaSearchConfigSearchTypeAuto    ExaSearchConfigSearchType = "auto"
	ExaSearchConfigSearchTypeKeyword ExaSearchConfigSearchType = "keyword"
	ExaSearchConfigSearchTypeNeural  ExaSearchConfigSearchType = "neural"
)

// Defines values for LinkupSearchConfigDepth.
const (
	LinkupSearchConfigDepthDeep     LinkupSearchConfigDepth = "deep"
	LinkupSearchConfigDepthStandard LinkupSearchConfigDepth = "standard"
)

// Defines values for LinkupSearchConfigOutputType.
const (
	LinkupSearchConfigOutputTypeSearchResults LinkupSearchConfigOutputType = "searchResults"
	LinkupSearchConfigOutputTypeSourcedAnswer LinkupSearchConfigOutputType = "sourcedAnswer"
)

// Defines values for SerperSearchConfigSearchType.
const (
	SerperSearchConfigSearchTypeImages   SerperSearchConfigSearchType = "images"
	SerperSearchConfigSearchTypeNews     SerperSearchConfigSearchType = "news"
	SerperSearchConfigSearchTypePlaces   SerperSearchConfigSearchType = "places"
	SerperSearchConfigSearchTypeSearch   SerperSearchConfigSearchType = "search"
	SerperSearchConfigSearchTypeShopping SerperSearchConfigSearchType = "shopping"
)

// Defines values for SerperSearchConfigTimePeriod.
const (
	SerperSearchConfigTimePeriodD SerperSearchConfigTimePeriod = "d"
	SerperSearchConfigTimePeriodM SerperSearchConfigTimePeriod = "m"
	SerperSearchConfigTimePeriodW SerperSearchConfigTimePeriod = "w"
	SerperSearchConfigTimePeriodY SerperSearchConfigTimePeriod = "y"
)

// Defines values for TavilySearchConfigSearchDepth.
const (
	TavilySearchConfigSearchDepthAdvanced TavilySearchConfigSearchDepth = "advanced"
	TavilySearchConfigSearchDepthBasic    TavilySearchConfigSearchDepth = "basic"
)

// Defines values for VertexSearchConfigService.
const (
	VertexSearchConfigServiceAgentSearch VertexSearchConfigService = "agent_search"
)

// Defines values for WebSearchProvider.
const (
	WebSearchProviderBrave  WebSearchProvider = "brave"
	WebSearchProviderExa    WebSearchProvider = "exa"
	WebSearchProviderLinkup WebSearchProvider = "linkup"
	WebSearchProviderSerper WebSearchProvider = "serper"
	WebSearchProviderTavily WebSearchProvider = "tavily"
	WebSearchProviderVertex WebSearchProvider = "vertex"
	WebSearchProviderYou    WebSearchProvider = "you"
)

// BraveSearchConfig defines model for BraveSearchConfig.
type BraveSearchConfig struct {
	// ApiKey Brave Search API key (or set BRAVE_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// Freshness Freshness filter: pd=day, pw=week, pm=month, py=year
	Freshness BraveSearchConfigFreshness `json:"freshness,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// Spellcheck Enable spellcheck suggestions
	Spellcheck bool `json:"spellcheck,omitempty,omitzero"`

	// TextDecorations Include text decorations (bold, italic markers)
	TextDecorations bool `json:"text_decorations,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// BraveSearchConfigFreshness Freshness filter: pd=day, pw=week, pm=month, py=year
type BraveSearchConfigFreshness string

// ExaSearchConfig defines model for ExaSearchConfig.
type ExaSearchConfig struct {
	// ApiKey Exa API key (or set EXA_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// EndPublishedDate ISO date/time upper bound for published date filtering
	EndPublishedDate string `json:"end_published_date,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// ExcludeDomains Exclude results from these domains
	ExcludeDomains []string `json:"exclude_domains,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeDomains Only include results from these domains
	IncludeDomains []string `json:"include_domains,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// NumResults Provider-specific result count override
	NumResults int `json:"num_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchType Search mode to request from Exa
	SearchType ExaSearchConfigSearchType `json:"search_type,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// StartPublishedDate ISO date/time lower bound for published date filtering
	StartPublishedDate string `json:"start_published_date,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// ExaSearchConfigSearchType Search mode to request from Exa
type ExaSearchConfigSearchType string

// FetchConfig Configuration for URL content fetching.
//
// Uses go/pkg/antfly/lib/scraping for downloading and processing. Supports:
// - HTTP/HTTPS URLs with security validation
// - HTML pages (extracts readable text via go-readability)
// - PDF files (extracts text)
// - Images (returns as data URIs)
// - Plain text files
// - S3 URLs (requires s3_credentials)
//
// Security features (from go/pkg/antfly/lib/scraping.ContentSecurityConfig):
// - Allowed host whitelist
// - Private IP blocking (SSRF prevention)
// - Download size limits
// - Timeout controls
type FetchConfig struct {
	// AllowedHosts Whitelist of allowed hostnames for fetching.
	// If empty, all hosts are allowed (except private IPs).
	// Example: ["docs.example.com", "api.example.com"]
	AllowedHosts []string `json:"allowed_hosts,omitempty,omitzero"`

	// BlockPrivateIps Block requests to private IP ranges (SSRF prevention).
	// Blocked: 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
	BlockPrivateIps *bool `json:"block_private_ips,omitempty"`

	// MaxContentLength Maximum content length in characters (truncated if exceeded)
	MaxContentLength int `json:"max_content_length,omitempty,omitzero"`

	// MaxDownloadSizeBytes Maximum download size in bytes (default: 100MB)
	MaxDownloadSizeBytes int                      `json:"max_download_size_bytes,omitempty,omitzero"`
	S3Credentials        externalRef0.Credentials `json:"s3_credentials,omitempty,omitzero"`

	// TimeoutSeconds Download timeout in seconds
	TimeoutSeconds int `json:"timeout_seconds,omitempty,omitzero"`
}

// FetchResult Result from fetching a URL via go/pkg/antfly/lib/scraping.
//
// Content is automatically processed based on MIME type:
// - HTML: Readable text extracted via go-readability
// - PDF: Text extracted from all pages
// - Images: Returned as base64 data URIs
// - Text: Returned as-is
type FetchResult struct {
	// Content Extracted/processed content
	Content string `json:"content"`

	// ContentType MIME type of the original content
	ContentType string `json:"content_type,omitempty,omitzero"`

	// FetchTimeMs Time taken to fetch and process in milliseconds
	FetchTimeMs int `json:"fetch_time_ms,omitempty,omitzero"`

	// Title Page title (extracted from HTML)
	Title string `json:"title,omitempty,omitzero"`

	// Truncated Whether content was truncated due to max_content_length
	Truncated bool `json:"truncated,omitempty,omitzero"`

	// Url The URL that was fetched
	Url string `json:"url"`
}

// LinkupSearchConfig defines model for LinkupSearchConfig.
type LinkupSearchConfig struct {
	// ApiKey Linkup API key (or set LINKUP_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Depth Search depth to request from Linkup
	Depth LinkupSearchConfigDepth `json:"depth,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// OutputType Linkup response shape to request
	OutputType LinkupSearchConfigOutputType `json:"output_type,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// LinkupSearchConfigDepth Search depth to request from Linkup
type LinkupSearchConfigDepth string

// LinkupSearchConfigOutputType Linkup response shape to request
type LinkupSearchConfigOutputType string

// SerperSearchConfig defines model for SerperSearchConfig.
type SerperSearchConfig struct {
	// ApiKey Serper API key (or set SERPER_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchType Type of search to perform
	SearchType SerperSearchConfigSearchType `json:"search_type,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimePeriod Time period filter: d=day, w=week, m=month, y=year
	TimePeriod SerperSearchConfigTimePeriod `json:"time_period,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// SerperSearchConfigSearchType Type of search to perform
type SerperSearchConfigSearchType string

// SerperSearchConfigTimePeriod Time period filter: d=day, w=week, m=month, y=year
type SerperSearchConfigTimePeriod string

// TavilySearchConfig defines model for TavilySearchConfig.
type TavilySearchConfig struct {
	// ApiKey Tavily API key (or set TAVILY_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// ExcludeDomains Exclude results from these domains
	ExcludeDomains []string `json:"exclude_domains,omitempty,omitzero"`

	// IncludeAnswer Include AI-generated answer summary
	IncludeAnswer bool `json:"include_answer,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeDomains Only include results from these domains
	IncludeDomains []string `json:"include_domains,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// IncludeRawContent Include raw HTML content of pages
	IncludeRawContent bool `json:"include_raw_content,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchDepth Search depth:
	// - basic: Fast search with standard results
	// - advanced: Deeper search with more comprehensive results
	SearchDepth TavilySearchConfigSearchDepth `json:"search_depth,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// TavilySearchConfigSearchDepth Search depth:
// - basic: Fast search with standard results
// - advanced: Deeper search with more comprehensive results
type TavilySearchConfigSearchDepth string

// VertexSearchConfig defines model for VertexSearchConfig.
type VertexSearchConfig struct {
	// ApiKey Provider API key or secret reference. Prefer named web_search connections for production use.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path. Falls back to GOOGLE_APPLICATION_CREDENTIALS.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location. Falls back to GOOGLE_CLOUD_LOCATION.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// Service Google Cloud search service flavor
	Service VertexSearchConfigService `json:"service,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// VertexSearchConfigService Google Cloud search service flavor
type VertexSearchConfigService string

// WebSearchConfig A unified configuration for web search providers.
//
// Each provider has specific configuration requirements. Use the appropriate
// provider-specific config or set common options at the top level.
//
// **Environment Variables (fallbacks):**
// - EXA_API_KEY
// - SERPER_API_KEY
// - TAVILY_API_KEY
// - BRAVE_API_KEY
// - YOU_API_KEY
// - LINKUP_API_KEY
// - GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_CLOUD_PROJECT, GOOGLE_CLOUD_LOCATION
type WebSearchConfig struct {
	// ApiKey Provider API key or secret reference. Prefer named web_search connections for production use.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// WebSearchProvider The web search provider to use.
//
// - **exa**: Exa neural/semantic web search API
// - **serper**: Serper.dev Google Search API (simpler setup)
// - **tavily**: Tavily AI Search API (optimized for RAG)
// - **brave**: Brave Search API
// - **you**: You.com Search API for agent and research workflows
// - **linkup**: Linkup Search API for web search and content retrieval
// - **vertex**: Google Cloud Agent Search / Vertex AI Search
type WebSearchProvider string

// WebSearchResponse Response from a web search query
type WebSearchResponse struct {
	// Answer AI-generated answer summary (if supported by provider)
	Answer string `json:"answer,omitempty,omitzero"`

	// Query The search query that was executed
	Query string `json:"query,omitempty,omitzero"`

	// Results List of search results
	Results []WebSearchResult `json:"results"`

	// SearchTimeMs Time taken to perform the search in milliseconds
	SearchTimeMs int `json:"search_time_ms,omitempty,omitzero"`

	// TotalResults Total number of results available
	TotalResults int `json:"total_results,omitempty,omitzero"`
}

// WebSearchResult A single web search result
type WebSearchResult struct {
	// PublishedDate Publication date if available
	PublishedDate time.Time `json:"published_date,omitempty,omitzero"`

	// Score Relevance score (provider-specific)
	Score float32 `json:"score,omitempty,omitzero"`

	// Snippet Text snippet/description from the result
	Snippet string `json:"snippet,omitempty,omitzero"`

	// Source Domain name of the source
	Source string `json:"source,omitempty,omitzero"`

	// Title Title of the search result
	Title string `json:"title"`

	// Url URL of the search result
	Url string `json:"url"`
}

// YouSearchConfig defines model for YouSearchConfig.
type YouSearchConfig struct {
	// ApiKey You.com API key (or set YOU_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint You.com API endpoint URL
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8x7fW8bOZL3Vyn08wCxDb3Y8e7MrA7zh8ZWctp1YsNyJheMAi3VXZJ47iZ7SbZeJsh3",
	"PxTZbHVLlK145zIHA4LUzSoWyapfvdFfolhmuRQojI56XyIdLzBj9usvii1xhEzFiyspZnxOD1ma3s6i",
	"3m9fov+vcBb1ov/X3TLoltTdjzhtEH5tfYlyJXNUhqNlznI+ecQNfU1Qx4rnhksR9dys4KihfzeER9zA",
	"iVSg0cAv9/1fB5P+3XDyj8EnQLGEJVOnUSsymxyjXqSN4oKmi2YK9UKg1vszvPGvYMZTg6oHefJzwjYt",
	"yFc/rxAfW5BnP2dSmEUL8s3PG2QqakUoiizq/RblSdSK8hV9ZPSxiT4H5tc5pmm8wPjRCTBjRWqinlEF",
	"tnbkGQg2TRG2FKCL+Rw1vdbbtU2lTJEJYm5wbSYJxlIxN6g+xYylem+OoYjTIkEgSqhRwslUpkkLuGEp",
	"jyFj6hGVPg3M+rV6JKf/jbGJvn7encQdduFYw0wq2D3MzliMReNhruSSJ6ghV3zJ4k17JuNCYwLavV9x",
	"swBuNMiVAC4SzFEkKIz9vrb8zs5GaIq8d3Y2FhcdGPG5gCIHZmBhTK573e6UZuzEMus6rl2W8+5YvO7A",
	"WzSVks2UzCBhejGVTCWO87WMde/srOLEct5xPDpbpizPu4mMiwyFsWsfi2hvt1rRYM2+uzUN1mzPiAb/",
	"1T/KhFAkk7yYplwvMJkkzOA+/+HoFuhN1/AMochzVDCVhUjs8VfUdkxpbsQ9NNvaaugkkRnjQoeW4lRY",
	"oS5So91xmQVqBE/TirjBzNLu8S8fMKXYhn5z8cx8tyLdQDnqj5pUFNmkZLU/4Z0zBdXWOcZ8xuNyVohl",
	"IQzIJSrFE4xaUcbWPCM0en3eijIu3I+Laj4uDM5RWRyyijNxL2ooEbHCyGjXgkujzCRBhQSF/ypQG7fq",
	"wZrVULAkF1golkat6BE3K6mSMBYapsw3qlIqVy9UpRcBFdmJW0tXY8aE4TGscFqikIUZGsI1yNzwjP+O",
	"TqzA4BYs+HyR8vnC6BYwkYBCozguMYGczXEsYikMGbjlcN9/awexOaHaSqrHWSpX+khkwzXrMP4iKEtk",
	"rDuePoRXb9DUseq5LfxwfwPlymBGpFzM7So+aNQwl938cd5lwszSTTfl066OFcu5mFviRK5EKllCv2k3",
	"ciVj1JpYwKjIc6mM7o1FG/7z4eGuSx8jmlA7/6AxLhQ3G1iylCclBNPYdzd2yzWc4NooFhsNClli/a11",
	"hUvOYC7b7iFPudmcEuXd9RtSsQYhjbcvh5ljqdAUSmhgmnSSwYf7oXbUKePC8bdM6Nno0sl7QjbFFWrQ",
	"l5NYIfkyzlIiHIuRX8cMmSlo0Ik9ycOb17lyO+4p3bGc2q3qp2RECSykNrBacIMp18YKSL7WIAzvYJrK",
	"+JF2/WQ0un8DucIlSSSFXcl1eSyg+e8IKc+4sat54BnKwtjzVjLVVoF2XJKbfUKzB8Duo5cH5AxYTVLB",
	"MnSWUVOi4Qwwy82mRUPtMA1MYUV4gusYc+OCCLswfdqxJpvlKfbgt3Hk1Z0ekNceRy0Yk+NsPvxsl3I8",
	"otv9m5TzTniunw33fiEKD62aYHYrNSgmrG7tHkZnLCwdJj24eP1j55z+uj+14OK89v3H152LH+yvi9ct",
	"uPgb/fzJ/f6hbuM+qGtF6/ZctulpWz/yvC2tkCxt55J8iCqjya/W5UxK656kKOZm0VjoX8/Pz893V/rO",
	"uakKFRwdcAHxgpFRodJwYlQhYmYwAT4DOkdMMKkFJDVnRkJ4pJiQSk6mG4PNLb84/8tPf/3xh8PSJA2d",
	"5gIsDzgpOfTg4vz83S9hAZo2S/M+FbeRH9cTmaOg+EwvmMJkoi8nVzUWpFLOmCYaYymS5mou95ZRmWRJ",
	"RivwlPsifz2E6/c2tNi3S/fcORBvgMAsuDusPIhEBGAlGpGfpAAhY4bHLE03Hs8xgSmjTyng3fDdAEi4",
	"nsfqHtw3wLmEXkwCMF2idA8emiOt4AQSFve3cE28Ca4xIbwmIX74yxa2Labh2jRGtXkI10plDsWnpQzd",
	"7WL94EBQ5I1pG5k1lNVvDsGjWSBIxedcsPQplva8JqQXkywAuQTaYNgjCgIdO7jua0mRMp6m/LA2ka6a",
	"NCDuHZsj2HeVw/RnQQcbTC8quw85BzQLVBVwrJiGLUwkhQ1OA4gUypULlQa2YoFWpc2COe52N5Ay+5lU",
	"GaMAuVA8GFyWDjyhKJiYV0dZi323xnbDxWORf/e8z027l/rdDN//48PdUdlfgvkOxlMcLxKmkkNpgyXZ",
	"yxucKLXUocEG82DKIAuTFyaQtrgY+77MoVrhZSvUuRQaQS9YXs9k6lLsMNKyUDEmfaFXqAIyvSitKOXZ",
	"KYCUT7mGQuOsSO3QegLhZPF5A0tdGqGNKmIKC5OxUOjrI9+YMKR27o6WL88ZaixCacMIVY7qu2u8m3ZP",
	"40eD+7vB/VEafzBVdi/2lO2hhOfyJCiQQ0XwsadlNlFe2VKBdUbkVFIW2y96IXPyn0EzsFieo+IyOYDn",
	"7mVVySwLmb6OWZUx96qYZH2rqBWRsJs/St3dGXQSXMJbKefpXumvPKSq6MdAc4q9FTCSXzDDl9ZeS/Kr",
	"QhuZeS6U61H2nOVouB2ZKx77lBGZ3tCRF/mRpqAraV9kC1tyaxZhY3hgS55uvrsxuGn3jOGh/+vw5tNx",
	"xb8/qRzHHP4+l0T5enZ/2J6jQGUDA0cLusgypjbBaOBPqfr5SRVbTRrh4zEVe8VWrpDhgyE5c7FtcH0l",
	"hgWc95RpHj/puW0cbof14A3TplGC907b7wmNZcmSiZhS0mtEsus6QSYVAmm1wgUKTdZakdZwyIvlef1R",
	"UOQtYLgLQeWLvUqer8P1h8DyPOWxa5C0SrDiYj4WucL2Nrj32uH2xyodJ0yzFb8U7XpAx1L57Oh5SDJW",
	"OFuJeLF7rvMIQdKvqAyu/7cgqZYeT3LmlXDHUS95jMBiV9f+++j2PdDQDrxhaUrJWfxofcDt7dubwaR/",
	"d3czvOo/DG/fT67uB9eD9w/D/s2oEwxamWETbaQK5Ch9W2D1Ck+Znx0Iw+sgq1Q6DWha0TyVU1vvbvL2",
	"7iqVRQKe8sB6rm5uP1xPbm7dkoJz50rSaU14wOs3pioH0hqemuzu/vbvg6uHTjjqscex0xygvZociHsa",
	"EpQmX3KBWcqWsh5nNDh9PjS/mBMwVoVmL0b5zb9rPXWiJR9wY8On+iIkaSy3MWUXnC1tUcbXu8EsuCti",
	"2g4GJhDaNLl0Oa6d0HU2SqXUINVYLFHxGceEcgPNDeoOUOJaRk8KjKRcnmv459LK8U+XFlNe37cFmld6",
	"LHDNtaGN2VUcxyOWoqwxhiCqbE1fcx2TsBsYiDkXaEGJiwZLC1hXCplBYKK5UbZBWi1uLC478FYxYSq1",
	"8VjAYluJMBL+VdB0ZoE7BxsGvpgk6MytOLYlWwYFfIltxtssz9vTgqcJqiditV1w20cQKIQ7kHhPS7bp",
	"W7W3LiUbsNojWDANVXuvyaWsK2QEuB1wSoS0dUrmijOD5H92O4SltpfxXSyzTApwVVxNjoVYGJlDiktM",
	"yxMeiCVXUtBE8CtTnI5Yw8mMpSmhhz61p9+u94ltB6ORSdmKWSOcpCeN+xn04NPth/rPZv2BnjwN8q0g",
	"jrXCUGpPNeF0YhkXzEgbRmbMpVe9L5Ht2B9ybfu3XSgIZoeG7zbzW5FLiw+ND9SBLPblFOyGSQKJdCty",
	"3v0QSSDdaEUOHA6RBMKBVrSRxaHxn2SxEwL4CGDznmW0vV5La6+ey1d867uKdqxCxwoNKJyhQhFjB+7s",
	"dxAsc5hYuhUyAoGx03nbK1YyKexvKDQGvd6/Eab4KZzAbnM7MLLVfe8QtuxhxjFN/gM0oh+7YVn6xFHU",
	"ugPfFhHRpvWvr/7AwCi41ANXRWzH6ImT9UOqewywWqDwsfY0xRBfnzkdnTX19aPFvJqPBNenrfUIKH3a",
	"1pZJCu1azLYAfDhp3Pb1/y1BKjZWFK1tN/kIMVIm5gWbh8rv1jBI//wYe3I+QTnBzrzTglcoXtGnps+Z",
	"enXqEC7LU5oIxfNR8LMh759vG02X0KIzEOCi9qDmZmzdvJHjG5qH2oeiyKaoanU/v8vVAX/bBZ0XxPr/",
	"V3b5qbSicgK9IzPKu5rXUDgP6txWz92IoJYXVr+LR/pMcEfLCx3MgdgMfY5y7G1NNkOvAYHLSC/osIcS",
	"oeOznbBOXLuVWOVsJlPBQ/Od6Gy3pR5o7t+XPZ5aG/qZ7uFO76zSkM9PxeJ3NT3a7+EFom5aKnn9sb0C",
	"dHaGa3Z21nvmghfFHW64C8mI4qliNpz4urUtOJ86WhebEW2o+gQnewWnks7GpUS2e13Wvd7Igl5+kgWl",
	"NnWOxMbdG3NFp92ekKN3gSmx2GtH7aYuxMY7xqr75Lg4lSIu35IQN2p9aG8QlkFvFcq2yrjcRZ1VHF3F",
	"raGiQaUe92WnL3iRwfUA3Y2A+iptbrl/YalWeW7Y3eESM5zw2dZpw3RTaWGwpu7mDSpyXbJtVxrXGBeN",
	"cGDL7OA10pvyUlXTPdUL1kfhcXlBJFDO9n2y4+4ZlD2xMpW3Ih110UAalh6+K/tAr2u+2DsBtmQ8bUaT",
	"h/DH834Sfg5dk+mD5oKsoKZWjuGeXj137/WO3pfhk73bymeNZVQXEuhlm3Y96MLiYGx/3yhEI5zslRBO",
	"61PMUslqV0vc/lr2guc5BjbCXr8p33Zrr6qeyXZb9mW2be59nte2x2LzPH/9pRwa9FnBGykP9jKKp945",
	"oD0mwUsiH+5vDjH4pksiTkI3SUjZdjPq79Eg9M5kt0NYq9c8978BBxK+Oucq5/twf3PMrn17cXbfKVrH",
	"7x83r1hYV8njurPzPrMtFUdhqq7OWFTu76nWTV0EWrCrX774P0s2jlW4PHnMbcLengJYgUgHgglG/+PI",
	"11xJzuH19rZ1WX9pu1pAVYXZywj6H0eT/tXVYDQipZkMr10qK6Qhheo0ou+NLFTbzdd+xE2bJ9+mW6PL",
	"NpkBM5xC8Eq7fOSvLzssY79LwVaa9vEVSAWvKDdNF1Kb3t/Oz89f2TN7x8XwtpkZ7BJHNnG7Ka+6XgQ7",
	"F7RBk+0Wh/e3rGNtt/llezwaXN0PHmpb/dw+l7y32x3u/mjNpZjYVkKgG15mK+AWYseWbQfaRoNZLhUF",
	"QnE9ZXx2eSFhLe+2kyOE0BonWqfHpmej0U334WbkbqVcNiqE24u+RG9H9D+OWmDzMPvTasxWR57/T7iv",
	"tkg0k6ENREEo4L3tkw2DZkPA4s7HQFvB3XrfxucO12yOVw7Ftb1Mk5ZuU4+F1RWbcNJj/89qGhIpXhlY",
	"UNphuw02vO04AHKOlWIhD69VMa8BxC5U127BF53zzrm9weeAKupFl53zziWFRcwsdNQTRZp+/Z8AAAD/",
	"/yWNfYB3OgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/s3.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
