// Package websearch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package websearch

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/go/pkg/libaf/s3"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BraveSearchConfigFreshness.
const (
	BraveSearchConfigFreshnessPd BraveSearchConfigFreshness = "pd"
	BraveSearchConfigFreshnessPm BraveSearchConfigFreshness = "pm"
	BraveSearchConfigFreshnessPw BraveSearchConfigFreshness = "pw"
	BraveSearchConfigFreshnessPy BraveSearchConfigFreshness = "py"
)

// Valid indicates whether the value is a known member of the BraveSearchConfigFreshness enum.
func (e BraveSearchConfigFreshness) Valid() bool {
	switch e {
	case BraveSearchConfigFreshnessPd:
		return true
	case BraveSearchConfigFreshnessPm:
		return true
	case BraveSearchConfigFreshnessPw:
		return true
	case BraveSearchConfigFreshnessPy:
		return true
	default:
		return false
	}
}

// Defines values for ExaSearchConfigSearchType.
const (
	ExaSearchConfigSearchTypeAuto    ExaSearchConfigSearchType = "auto"
	ExaSearchConfigSearchTypeKeyword ExaSearchConfigSearchType = "keyword"
	ExaSearchConfigSearchTypeNeural  ExaSearchConfigSearchType = "neural"
)

// Valid indicates whether the value is a known member of the ExaSearchConfigSearchType enum.
func (e ExaSearchConfigSearchType) Valid() bool {
	switch e {
	case ExaSearchConfigSearchTypeAuto:
		return true
	case ExaSearchConfigSearchTypeKeyword:
		return true
	case ExaSearchConfigSearchTypeNeural:
		return true
	default:
		return false
	}
}

// Defines values for LinkupSearchConfigDepth.
const (
	LinkupSearchConfigDepthDeep     LinkupSearchConfigDepth = "deep"
	LinkupSearchConfigDepthStandard LinkupSearchConfigDepth = "standard"
)

// Valid indicates whether the value is a known member of the LinkupSearchConfigDepth enum.
func (e LinkupSearchConfigDepth) Valid() bool {
	switch e {
	case LinkupSearchConfigDepthDeep:
		return true
	case LinkupSearchConfigDepthStandard:
		return true
	default:
		return false
	}
}

// Defines values for LinkupSearchConfigOutputType.
const (
	LinkupSearchConfigOutputTypeSearchResults LinkupSearchConfigOutputType = "searchResults"
	LinkupSearchConfigOutputTypeSourcedAnswer LinkupSearchConfigOutputType = "sourcedAnswer"
)

// Valid indicates whether the value is a known member of the LinkupSearchConfigOutputType enum.
func (e LinkupSearchConfigOutputType) Valid() bool {
	switch e {
	case LinkupSearchConfigOutputTypeSearchResults:
		return true
	case LinkupSearchConfigOutputTypeSourcedAnswer:
		return true
	default:
		return false
	}
}

// Defines values for SerperSearchConfigSearchType.
const (
	SerperSearchConfigSearchTypeImages   SerperSearchConfigSearchType = "images"
	SerperSearchConfigSearchTypeNews     SerperSearchConfigSearchType = "news"
	SerperSearchConfigSearchTypePlaces   SerperSearchConfigSearchType = "places"
	SerperSearchConfigSearchTypeSearch   SerperSearchConfigSearchType = "search"
	SerperSearchConfigSearchTypeShopping SerperSearchConfigSearchType = "shopping"
)

// Valid indicates whether the value is a known member of the SerperSearchConfigSearchType enum.
func (e SerperSearchConfigSearchType) Valid() bool {
	switch e {
	case SerperSearchConfigSearchTypeImages:
		return true
	case SerperSearchConfigSearchTypeNews:
		return true
	case SerperSearchConfigSearchTypePlaces:
		return true
	case SerperSearchConfigSearchTypeSearch:
		return true
	case SerperSearchConfigSearchTypeShopping:
		return true
	default:
		return false
	}
}

// Defines values for SerperSearchConfigTimePeriod.
const (
	SerperSearchConfigTimePeriodD SerperSearchConfigTimePeriod = "d"
	SerperSearchConfigTimePeriodM SerperSearchConfigTimePeriod = "m"
	SerperSearchConfigTimePeriodW SerperSearchConfigTimePeriod = "w"
	SerperSearchConfigTimePeriodY SerperSearchConfigTimePeriod = "y"
)

// Valid indicates whether the value is a known member of the SerperSearchConfigTimePeriod enum.
func (e SerperSearchConfigTimePeriod) Valid() bool {
	switch e {
	case SerperSearchConfigTimePeriodD:
		return true
	case SerperSearchConfigTimePeriodM:
		return true
	case SerperSearchConfigTimePeriodW:
		return true
	case SerperSearchConfigTimePeriodY:
		return true
	default:
		return false
	}
}

// Defines values for TavilySearchConfigSearchDepth.
const (
	TavilySearchConfigSearchDepthAdvanced TavilySearchConfigSearchDepth = "advanced"
	TavilySearchConfigSearchDepthBasic    TavilySearchConfigSearchDepth = "basic"
)

// Valid indicates whether the value is a known member of the TavilySearchConfigSearchDepth enum.
func (e TavilySearchConfigSearchDepth) Valid() bool {
	switch e {
	case TavilySearchConfigSearchDepthAdvanced:
		return true
	case TavilySearchConfigSearchDepthBasic:
		return true
	default:
		return false
	}
}

// Defines values for VertexSearchConfigService.
const (
	VertexSearchConfigServiceAgentSearch VertexSearchConfigService = "agent_search"
)

// Valid indicates whether the value is a known member of the VertexSearchConfigService enum.
func (e VertexSearchConfigService) Valid() bool {
	switch e {
	case VertexSearchConfigServiceAgentSearch:
		return true
	default:
		return false
	}
}

// Defines values for WebSearchProvider.
const (
	WebSearchProviderBrave  WebSearchProvider = "brave"
	WebSearchProviderExa    WebSearchProvider = "exa"
	WebSearchProviderLinkup WebSearchProvider = "linkup"
	WebSearchProviderSerper WebSearchProvider = "serper"
	WebSearchProviderTavily WebSearchProvider = "tavily"
	WebSearchProviderVertex WebSearchProvider = "vertex"
	WebSearchProviderYou    WebSearchProvider = "you"
)

// Valid indicates whether the value is a known member of the WebSearchProvider enum.
func (e WebSearchProvider) Valid() bool {
	switch e {
	case WebSearchProviderBrave:
		return true
	case WebSearchProviderExa:
		return true
	case WebSearchProviderLinkup:
		return true
	case WebSearchProviderSerper:
		return true
	case WebSearchProviderTavily:
		return true
	case WebSearchProviderVertex:
		return true
	case WebSearchProviderYou:
		return true
	default:
		return false
	}
}

// BraveSearchConfig Configuration for Brave Search API.
//
// Brave Search provides privacy-focused search with its own independent index.
//
// **Setup:**
// 1. Sign up at https://brave.com/search/api/
// 2. Get API key from dashboard
//
// **Docs:** https://api.search.brave.com/app/documentation
type BraveSearchConfig struct {
	// ApiKey Brave Search API key (or set BRAVE_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// Freshness Freshness filter: pd=day, pw=week, pm=month, py=year
	Freshness BraveSearchConfigFreshness `json:"freshness,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// Spellcheck Enable spellcheck suggestions
	Spellcheck bool `json:"spellcheck,omitempty,omitzero"`

	// TextDecorations Include text decorations (bold, italic markers)
	TextDecorations bool `json:"text_decorations,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// BraveSearchConfigFreshness Freshness filter: pd=day, pw=week, pm=month, py=year
type BraveSearchConfigFreshness string

// ExaSearchConfig Configuration for Exa neural/semantic web search.
//
// Exa is optimized for semantic web search, highlights, and retrieved page
// contents for RAG and agent workflows.
//
// **Setup:**
// 1. Sign up at https://exa.ai
// 2. Get API key from dashboard
//
// **Docs:** https://docs.exa.ai
type ExaSearchConfig struct {
	// ApiKey Exa API key (or set EXA_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// EndPublishedDate ISO date/time upper bound for published date filtering
	EndPublishedDate string `json:"end_published_date,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// ExcludeDomains Exclude results from these domains
	ExcludeDomains []string `json:"exclude_domains,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeDomains Only include results from these domains
	IncludeDomains []string `json:"include_domains,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// NumResults Provider-specific result count override
	NumResults int `json:"num_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchType Search mode to request from Exa
	SearchType ExaSearchConfigSearchType `json:"search_type,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// StartPublishedDate ISO date/time lower bound for published date filtering
	StartPublishedDate string `json:"start_published_date,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// ExaSearchConfigSearchType Search mode to request from Exa
type ExaSearchConfigSearchType string

// FetchConfig Configuration for URL content fetching.
//
// Uses go/pkg/antfly/lib/scraping for downloading and processing. Supports:
// - HTTP/HTTPS URLs with security validation
// - HTML pages (extracts readable text via go-readability)
// - PDF files (extracts text)
// - Images (returns as data URIs)
// - Plain text files
// - S3 URLs (requires s3_credentials)
//
// Security features (from go/pkg/antfly/lib/scraping.ContentSecurityConfig):
// - Allowed host whitelist
// - Private IP blocking (SSRF prevention)
// - Download size limits
// - Timeout controls
type FetchConfig struct {
	// AllowedHosts Whitelist of allowed hostnames for fetching.
	// If empty, all hosts are allowed (except private IPs).
	// Example: ["docs.example.com", "api.example.com"]
	AllowedHosts []string `json:"allowed_hosts,omitempty,omitzero"`

	// BlockPrivateIps Block requests to private IP ranges (SSRF prevention).
	// Blocked: 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
	BlockPrivateIps *bool `json:"block_private_ips,omitempty"`

	// MaxContentLength Maximum content length in characters (truncated if exceeded)
	MaxContentLength int `json:"max_content_length,omitempty,omitzero"`

	// MaxDownloadSizeBytes Maximum download size in bytes (default: 100MB)
	MaxDownloadSizeBytes int                      `json:"max_download_size_bytes,omitempty,omitzero"`
	S3Credentials        externalRef0.Credentials `json:"s3_credentials,omitempty,omitzero"`

	// TimeoutSeconds Download timeout in seconds
	TimeoutSeconds int `json:"timeout_seconds,omitempty,omitzero"`
}

// FetchResult Result from fetching a URL via go/pkg/antfly/lib/scraping.
//
// Content is automatically processed based on MIME type:
// - HTML: Readable text extracted via go-readability
// - PDF: Text extracted from all pages
// - Images: Returned as base64 data URIs
// - Text: Returned as-is
type FetchResult struct {
	// Content Extracted/processed content
	Content string `json:"content"`

	// ContentType MIME type of the original content
	ContentType string `json:"content_type,omitempty,omitzero"`

	// FetchTimeMs Time taken to fetch and process in milliseconds
	FetchTimeMs int `json:"fetch_time_ms,omitempty,omitzero"`

	// Title Page title (extracted from HTML)
	Title string `json:"title,omitempty,omitzero"`

	// Truncated Whether content was truncated due to max_content_length
	Truncated bool `json:"truncated,omitempty,omitzero"`

	// Url The URL that was fetched
	Url string `json:"url"`
}

// LinkupSearchConfig Configuration for Linkup Search API.
//
// Linkup is useful for web search, source retrieval, and structured
// research workflows.
//
// **Setup:**
// 1. Sign up at https://linkup.so
// 2. Get API key from dashboard
//
// **Docs:** https://docs.linkup.so
type LinkupSearchConfig struct {
	// ApiKey Linkup API key (or set LINKUP_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Depth Search depth to request from Linkup
	Depth LinkupSearchConfigDepth `json:"depth,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// OutputType Linkup response shape to request
	OutputType LinkupSearchConfigOutputType `json:"output_type,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// LinkupSearchConfigDepth Search depth to request from Linkup
type LinkupSearchConfigDepth string

// LinkupSearchConfigOutputType Linkup response shape to request
type LinkupSearchConfigOutputType string

// SerperSearchConfig Configuration for Serper.dev Google Search API.
//
// Serper provides a simpler alternative to Google Custom Search with
// competitive pricing and easy setup.
//
// **Setup:**
// 1. Sign up at https://serper.dev
// 2. Get API key from dashboard
//
// **Docs:** https://serper.dev/docs
type SerperSearchConfig struct {
	// ApiKey Serper API key (or set SERPER_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchType Type of search to perform
	SearchType SerperSearchConfigSearchType `json:"search_type,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimePeriod Time period filter: d=day, w=week, m=month, y=year
	TimePeriod SerperSearchConfigTimePeriod `json:"time_period,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// SerperSearchConfigSearchType Type of search to perform
type SerperSearchConfigSearchType string

// SerperSearchConfigTimePeriod Time period filter: d=day, w=week, m=month, y=year
type SerperSearchConfigTimePeriod string

// TavilySearchConfig Configuration for Tavily AI Search API.
//
// Tavily is optimized for RAG and AI applications, providing
// pre-processed results with summaries and relevance scoring.
//
// **Setup:**
// 1. Sign up at https://tavily.com
// 2. Get API key from dashboard
//
// **Docs:** https://docs.tavily.com
type TavilySearchConfig struct {
	// ApiKey Tavily API key (or set TAVILY_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// ExcludeDomains Exclude results from these domains
	ExcludeDomains []string `json:"exclude_domains,omitempty,omitzero"`

	// IncludeAnswer Include AI-generated answer summary
	IncludeAnswer bool `json:"include_answer,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeDomains Only include results from these domains
	IncludeDomains []string `json:"include_domains,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// IncludeRawContent Include raw HTML content of pages
	IncludeRawContent bool `json:"include_raw_content,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// SearchDepth Search depth:
	// - basic: Fast search with standard results
	// - advanced: Deeper search with more comprehensive results
	SearchDepth TavilySearchConfigSearchDepth `json:"search_depth,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// TavilySearchConfigSearchDepth Search depth:
// - basic: Fast search with standard results
// - advanced: Deeper search with more comprehensive results
type TavilySearchConfigSearchDepth string

// VertexSearchConfig Configuration for Google Cloud Agent Search / Vertex AI Search.
//
// Use this for bounded Google Cloud search over configured data stores or
// verified websites. The provider token is `vertex` to match Antfly's
// existing Google Cloud provider convention.
//
// **Setup:**
// 1. Enable Discovery Engine API in Google Cloud
// 2. Create an Agent Search app/data store
// 3. Grant service account access to query the serving config
//
// **Docs:** https://cloud.google.com/generative-ai-app-builder/docs
type VertexSearchConfig struct {
	// ApiKey Provider API key or secret reference. Prefer named web_search connections for production use.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path. Falls back to GOOGLE_APPLICATION_CREDENTIALS.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location. Falls back to GOOGLE_CLOUD_LOCATION.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// Service Google Cloud search service flavor
	Service VertexSearchConfigService `json:"service,omitempty,omitzero"`

	// ServingConfig Agent Search serving config ID.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// VertexSearchConfigService Google Cloud search service flavor
type VertexSearchConfigService string

// WebSearchConfig A unified configuration for web search providers.
//
// Each provider has specific configuration requirements. Use the appropriate
// provider-specific config or set common options at the top level.
//
// **Environment Variables (fallbacks):**
// - EXA_API_KEY
// - SERPER_API_KEY
// - TAVILY_API_KEY
// - BRAVE_API_KEY
// - YOU_API_KEY
// - LINKUP_API_KEY
// - GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_CLOUD_PROJECT, GOOGLE_CLOUD_LOCATION
type WebSearchConfig struct {
	// ApiKey Provider API key or secret reference. Prefer named web_search connections for production use.
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint Provider endpoint override when applicable
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// WebSearchProvider The web search provider to use.
//
// - **exa**: Exa neural/semantic web search API
// - **serper**: Serper.dev Google Search API (simpler setup)
// - **tavily**: Tavily AI Search API (optimized for RAG)
// - **brave**: Brave Search API
// - **you**: You.com Search API for agent and research workflows
// - **linkup**: Linkup Search API for web search and content retrieval
// - **vertex**: Google Cloud Agent Search / Vertex AI Search
type WebSearchProvider string

// WebSearchResponse Response from a web search query
type WebSearchResponse struct {
	// Answer AI-generated answer summary (if supported by provider)
	Answer string `json:"answer,omitempty,omitzero"`

	// Query The search query that was executed
	Query string `json:"query,omitempty,omitzero"`

	// Results List of search results
	Results []WebSearchResult `json:"results"`

	// SearchTimeMs Time taken to perform the search in milliseconds
	SearchTimeMs int `json:"search_time_ms,omitempty,omitzero"`

	// TotalResults Total number of results available
	TotalResults int `json:"total_results,omitempty,omitzero"`
}

// WebSearchResult A single web search result
type WebSearchResult struct {
	// PublishedDate Publication date if available
	PublishedDate time.Time `json:"published_date,omitempty,omitzero"`

	// Score Relevance score (provider-specific)
	Score float32 `json:"score,omitempty,omitzero"`

	// Snippet Text snippet/description from the result
	Snippet string `json:"snippet,omitempty,omitzero"`

	// Source Domain name of the source
	Source string `json:"source,omitempty,omitzero"`

	// Title Title of the search result
	Title string `json:"title"`

	// Url URL of the search result
	Url string `json:"url"`
}

// YouSearchConfig Configuration for You.com Search API.
//
// You.com is useful for agentic search and research-oriented result
// retrieval.
//
// **Setup:**
// 1. Sign up for You.com API access
// 2. Get API key from dashboard
//
// **Docs:** https://api.you.com
type YouSearchConfig struct {
	// ApiKey You.com API key (or set YOU_API_KEY env var)
	ApiKey string `json:"api_key,omitempty,omitzero"`

	// CredentialsPath Service account JSON path for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_APPLICATION_CREDENTIALS or ADC.
	CredentialsPath string `json:"credentials_path,omitempty,omitzero"`

	// DataStore Agent Search data store ID for provider vertex.
	DataStore string `json:"data_store,omitempty,omitzero"`

	// Endpoint You.com API endpoint URL
	Endpoint string `json:"endpoint,omitempty,omitzero"`

	// IncludeContent Ask the provider to return extracted page content when supported
	IncludeContent bool `json:"include_content,omitempty,omitzero"`

	// IncludeHighlights Ask the provider to return highlighted passages when supported
	IncludeHighlights bool `json:"include_highlights,omitempty,omitzero"`

	// Language Preferred language for results (e.g., 'en', 'es', 'fr')
	//
	// Example: en
	Language string `json:"language,omitempty,omitzero"`

	// Location Google Cloud location for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_LOCATION, then global.
	Location string `json:"location,omitempty,omitzero"`

	// MaxResults Maximum number of search results to return
	MaxResults int `json:"max_results,omitempty,omitzero"`

	// ProjectId Google Cloud project ID for provider vertex. Shared Vertex credential field; see vertex.yaml#/components/schemas/VertexCredentials. Falls back to GOOGLE_CLOUD_PROJECT.
	ProjectId string `json:"project_id,omitempty,omitzero"`

	// Provider The web search provider to use.
	//
	// - **exa**: Exa neural/semantic web search API
	// - **serper**: Serper.dev Google Search API (simpler setup)
	// - **tavily**: Tavily AI Search API (optimized for RAG)
	// - **brave**: Brave Search API
	// - **you**: You.com Search API for agent and research workflows
	// - **linkup**: Linkup Search API for web search and content retrieval
	// - **vertex**: Google Cloud Agent Search / Vertex AI Search
	Provider WebSearchProvider `json:"provider"`

	// Region Preferred region for results (e.g., 'us', 'uk', 'de')
	//
	// Example: us
	Region string `json:"region,omitempty,omitzero"`

	// SafeSearch Enable safe search filtering
	SafeSearch *bool `json:"safe_search,omitempty"`

	// ServingConfig Agent Search serving config ID for provider vertex. Defaults to default_config.
	ServingConfig string `json:"serving_config,omitempty,omitzero"`

	// TimeoutMs Request timeout in milliseconds
	TimeoutMs int `json:"timeout_ms,omitempty,omitzero"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hxvc9s4kvdX6eLzVMV2UZId787M6mpeaGwlp10ndlnO5FKjFBciWxLOJMAFQMmaVL77VQMkRUqQrXjm",
	"NvfClSqXRAKNBtD967/KlyCWWS4FCqOD/pdAxwvMmP34i2JLHCNT8eJCihmf00OWptezoP/bl+D/K5wF",
	"/eD/9TYEeuXs3kectiZ+Db8EuZI5KsPREmc5j+5xTR8T1LHiueFSBH23KrjZMLgZwT2u4Ugq0Gjgl9vB",
	"r8NocDOK/jH8BCiWsGTqOAgDs84x6AfaKC5ouWCmUC8Ear27wpvqFcx4alD1IU9+Ttg6hHz18wrxPoQ8",
	"+zmTwixCyNc/r5GpIAxQFFnQ/y3IkyAM8hX9yejPOvjsWV/nmKbxAuN7x8CMFakJ+kYVGG7xMxRsmiJs",
	"ZoAu5nPU9Fpv9jaVMkUmiLjBBxMlGEvF3KDmEjOW6p01RiJOiwSBZkJjJhxNZZqEwA1LeQwZU/eo9LFn",
	"1a/1Izn9b4xN8PXz9iLusgtHGmZSwfZldidiIloPcyWXPEENueJLFq87MxkXGhPQ7v2KmwVwo0GuBHCR",
	"YI4iQWHs5wdL7+RkjKbI+ycnE3HWhTGfCyhyYAYWxuS63+tNacVuLLOeo9pjOe9NxOsuvEVTC9lMyQwS",
	"phdTyVTiKF/KWPdPTmpKLOddR6O7IcryvJfIuMhQGLv3iQh2TisMhg/sedoURX9An4YPbEeNhv81OEiJ",
	"UCRRXkxTrheYRAkzuEt/NL4GetMzPEMo8hwVTGUhEisA9Ww7plQ4ou5b7cHKaJTIjHGhfVtxQqxQF6nR",
	"7sLMAjVCNScMuMHMzt2hXz5gSrE1fefiifWuRbqGctSftagosqgktbvgjVMG1dE5xnzG43JViGUhDMgl",
	"KsUTDMIgYw88Izx6fRoGGRfuy1m9HhcG56gsElnBidyLBk4ErDAy2NbhUi0zSWAhQeG/CtTG7Xr4wBo4",
	"WE4XWCiWBmFwj+uVVIkfDQ1T5htFKZWrZ4rSs6CK9MTtpacxY8LwGFY4LXHIAg0N4RpkbnjGf0fHlmdw",
	"CAs+X6R8vjA6BCYSUGgUxyUmkLM5TkQshSEVtxRuB2/tIDYnXFtJdT9L5UofiG34wLqMPwvMEhnrbjXf",
	"h1hv0DTR6qkj/HB7BeXOYEZTuZjbXXzQqGEue/n9vMeEmaXrXsqnPR0rlnMxt5MTuRKpZAl9p9PIlYxR",
	"ayIB4yLPpTK6PxEd+M+7u5se/RnTgtpZCI1xobhZw5KlPClBmMa+u7JHruEIH4xisdGgkCXW4lpjuOQM",
	"5rLjHvKUm/Uxzby5fEMi1ppI4+3LUeZIKjSFEhqYJplk8OF2pN3slHHh6Fsi9Gx87vg9Ip3iCjXo8yhW",
	"SNaMs5QmTsS42scMmSlo0JG9yf2H171wJ17NdNdybI9qkJISJbCQ2sBqwQ2mXBvLIFlbgzC6gWkq43s6",
	"9aPx+PYN5AqXxJEUdieX5bWA5r8jpDzjxu7mjmcoC2PvW8lUWwHaMklu9YhW94Ddx4ofkDNgDU4Fy9Bp",
	"RkOIRjPALDfrkIbaYRqYwnriET7EmBvnRtiN6eOuVdksT7EPv02CStzpAdntSRDChAxn++Fnu5XDEd2e",
	"X1SuG/FcP+nw/UIzKmjVBLMbrkExYWVr+zK6E2HnYdKHs9c/dk/pX++nEM5OG59/fN09+8F+O3sdwtnf",
	"6OtP7vsPTR2v3LoweOjMZYeedvQ9zzvSMsnSTi7JhqjSn/xqTU5UaneUopibRWujfz09PT3d3uk7Z6Zq",
	"VHDzgAuIF4yUCpWGI6MKETODCfAZ0D1igknDIWkYM2KiQoqIRDKarg22j/zs9C8//fXHH/Zzk7Rkmguw",
	"NOCopNCHs9PTd7/4GWjrLK37mOdGdlxHMkdB/pleMIVJpM+jiwYJEimnTJHGWIqkvZvznW3UKllOox1U",
	"M3dZ/roP12+ta7Grl+65MyCVAgKz4O6wci8SEYCVaER2khyEjBkeszRdV3iOCUwZ/ZUC3o3eDYGY61dY",
	"3YfbFjiX0IuJB6ZLlO7DXXukZZxAwuL+Bq6JNsE1JoTXxMQPf9nAtsU0fDCtUR3uw7VSmH3+aclDb7PZ",
	"arDHKaqUaeOZtYS1OhyCR7NAkIrPuWDpYyTtfUUkF1HmgVwCbTDsHgWBjh3ctLUkSBlPU75fmkhWTeph",
	"94bNEey72mBWd0EX6w0var33GQc0C1Q1cKyYhg1MJIV1Tj2I5IuWC5V6jmKBVqTNgjnq9jSQYvuZVBkj",
	"B7lQ3OtclgY8IS+YiNdX2fB9N8p2xcV9kX+HyM8tvBP8XY3e/+PDzUHxX4L5FsqTJy8SppJ9gYOdshM5",
	"OFYawUOLDObeoEEWJi+MJ3BxXvZtGUWF/m0r1LkUGkEvWN6MZZpcbBHSslAxJgOhV6g8PD0rsCj52UqC",
	"lE+5hkLjrEjt0GYI4XipIgeWukBCG1XE5BgmE6GwypF8Y8iQ2rW7Wj4/amiQ8AUOY1Q5qu8g827hHZkf",
	"D29vhrcHyfzecNm92BG3uxKiy7sgZw4VQciOnNlgeWXTBdYgkWFJWWw/6IXMyYZ6FcHieY6Ky2QPpruX",
	"dT6zTGdW2cw6mbmTyyT9WwVhQMyu/yyBd3fQTXAJb6WcpzsJwPKS6tQfA83J/1bAiH/BDF9ajS2nXxTa",
	"yKyiQvEeRdBZjobbkbnicRU2ItNruvIiP1AZdM3ts7RhM90qhl8d7tiSp+vvoA5u4R11uBv8Orr6dFgK",
	"8Dsl5ZjD4KdCqSqvPRh15ihQWffAzQVdZBlTa69P8F1yf9Wiiq2ilhN5SOZesZVLZ1QukZw5D9e7vxLF",
	"PAZ8yjSPH7Xe1hu3w/rwhmnTSsVXhrs6ExrLkiUTMQWml4ik2c0JmVQIJNcKFyg06Ws9tYFEFVsVrT8L",
	"jCoNGG2DUPliJ59XZeMGI2B5nvLYFUrCEq64mE9ErrCzcfEr6XDnY4WOE6rZvF+Kdj+gY6mqGOlpUDKW",
	"OZuPeLaJbtLwgdKvqAw+/O+BUiNMjnJWieGWsV7yGIHFLr/99/H1e6ChXXjD0pSCtPje2oHr67dXw2hw",
	"c3M1uhjcja7fRxe3w8vh+7vR4Grc9bquzLBIG6k8scrAJlorkacI0A6E0aWXVCqdDLT1aJ7Kqc17t2lX",
	"JiuVRQLVzD37ubi6/nAZXV27LXnXzpWk+4q4x/K3lioH0h4eW+zm9vrvw4u7rt/zsdexVSSgs4r2+D4t",
	"DkqlL6nALGVL2fQ1WpQ+71tfzAka64RzxUb5qXoXPnajJR1wY/23+iwsaW23tWQPnDZtcKbKe4NZcJfM",
	"tJUMTMB3aHLpYl27oKtwlEKpQaqJWKLiM44JRQiaG9RdoAC29KAUGEkxPdfwz6Xl458uPKb4fmATNa/0",
	"ROAD14YOZltwHI1YijLX6AOpskh9yXVMzK5hKOZcoIUlLlokLWRdKGQGgYn2QdlSab25iTjvwlvFhKnF",
	"psICFtuMhJHwr4KWMwvculg/9MXEQXdu2bHF2dIt4EvsMN5hed6ZFjxNUD3ir22D2y6CQCHchcQ7UrIJ",
	"4uqzdYHZkDUewYJpqMt8bSplfiEjyO2CEyKko1MyV5wZJAu0XSkspb308GKZZVKAy+ZqMi1EwsgcUlxi",
	"Wt7wUCy5koIWgl+Z4nTFGo5mLE0JPfSxvf1Os15sKxmtaMpmzloOJT1pdWrQg0/XH5pf21kIevI4yIde",
	"HAv9UGpvNeF0YxkXzEjrSGbMhVj9L4Gt3e8zbrt9L+QGs33Dt8v6YeCC433jPfkgi305ubv+KZ5wOgyc",
	"fd83xRNyhIEDh31TPA5BGKxlsW/8J1lsuQCVB7B+zzI63kpKG6+eiliqEnjt71iBjhUaUDhDhSLGLtzY",
	"zyBY5jCxNCukBAJjJ/O2ZqxkUtjvUGj0Wr0/4KZUSziG3eF2YWyz/JVB2JCHGcc0+Q/QiNXYNcvSR66i",
	"USX4No+IDm1wefEnOkbere5pGbGVo0duthpS9zPAaoGi8ranKfroVrHTwXHTQN9bzGvYSHD12katgAKo",
	"TY6ZuNCu1GwTwfvDxk19/w8xUpOxrGhtq8oHsJEyMS/Y3JeGt4pB8leNsTdXhShH2J13Q3iF4hX91fR3",
	"pl4dO4TL8pQWQvG0F/yky/v9daNtEkK6AwHOa/dKbsYe2p05VWFzXxlRFNkUVSP3V51yfcHf1qjzDF//",
	"/8opPxZW1Eagf2DP6E3Daiice2VuI+duhFfKCyvfxT39TXBLygvtjYHYDKsY5dC+TTbDSgI8TUnPqLT7",
	"AqHDox2/TFy6nVjhbAdT3kurKtLZdmndU+S/LSs9jXL0E1XErRpaLSGfH/PFbxpytFvL83jdtFWy+hPb",
	"CnRygg/s5KT/RKMX+R1uuHPJaMZjCW04qnLXNul87OY634zm+vJPcLSTcirnWb+Upm03zrrXa1nQy0+y",
	"oNCmSZHIuP4xl3bargy5+c4xJRI7Rant0IXIVIaxrkE5Kk6kiMq3BMStbB/aTsLS6a1d2bD0y53XWfvR",
	"td/qSxrU4nFb1vu8DQ2uEug6A5q7tLHlbuNSI/fc0rv9SWY44rON0YbpupZCb1bdresV5CZnm+o0PmBc",
	"tNyBDbG97aRXZXNV2zw1U9YH4XHZKOJJaFe1ssP6Dcq6WBnKW5YOajiQhqX7e2bv6HXDFldGgC0ZT9ve",
	"5D78qWg/Cj/72mUGoLkgLWiIlSO4I1dP9b/e0PvSfbI9rnzW2kbdmEAvO3TqXhMWe33721YqGuFoJ4Vw",
	"3FxilkrWaDFx52vJC57n6DkI24ZTvu01XtVVk82x7PJsi927NC9tlcXGeVUbTDnUa7O8nSl3timlmr11",
	"QTtEvM0iH26v9hH4pmYRx6FbxCds2xH1v6dIWJmT7SphI2Pz1K8E9oR8Tcp11Pfh9uqQc/v29OyuWbSm",
	"v3rcbrWwxpLHTXNXWc2OVByFqSs7E1EbwMfKN00WaMMug/nsX5msHSl/gnL3vl9SlC8pypcU5UuK8iVF",
	"+ZKifElRvqQoX1KULynKlxTlvydFecivfPo74ZgND8jD8GrT4OO46oEgF2N0ufkVZOlsdJzhq12OHfEf",
	"fBxHg4uL4XhM/ms0unS4LaQh/7vbErW1LFTHrde5x3WHJ99mOcfnHdIXZjjJW20+KzHX512Wsd+lYCtN",
	"Uc0rMv+vCIjThdSm/7fT09NXVirecTG6bqvB9uTAotRV+RO0M28nER1QtDli//mWTtvmmJ93xuPhxe3w",
	"rnHUT51zSXtz3P5uLK25FJFt7fH0p5aqCW4jdmzZBkTHaDDLpWJq3cBWfcD2fMxa2h3Hhy9jojHSOj0U",
	"i8bjq97d1dh1ip+33OHND/Bovh0x+DgOwYKO/WolZiMjT/8fFV+tRzSTvgNEQQ58FZ0+Gh23o18bmn70",
	"xNDu16ibfLnLMlhAK4fig21wT8s0lp4IKysWXelx9d9IaEikeGVgwZZlaG3TzV2XDnCJroBYKCG29lxb",
	"aREXT2m34bPuaffU/q7GAVXQD867p93zIAwoUtBBXxRp+vV/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/s3.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
