//go:build go1.22

// Package embeddings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package embeddings

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CohereEmbedderConfigInputType.
const (
	CohereEmbedderConfigInputTypeClassification CohereEmbedderConfigInputType = "classification"
	CohereEmbedderConfigInputTypeClustering     CohereEmbedderConfigInputType = "clustering"
	CohereEmbedderConfigInputTypeSearchDocument CohereEmbedderConfigInputType = "search_document"
	CohereEmbedderConfigInputTypeSearchQuery    CohereEmbedderConfigInputType = "search_query"
)

// Valid indicates whether the value is a known member of the CohereEmbedderConfigInputType enum.
func (e CohereEmbedderConfigInputType) Valid() bool {
	switch e {
	case CohereEmbedderConfigInputTypeClassification:
		return true
	case CohereEmbedderConfigInputTypeClustering:
		return true
	case CohereEmbedderConfigInputTypeSearchDocument:
		return true
	case CohereEmbedderConfigInputTypeSearchQuery:
		return true
	default:
		return false
	}
}

// Defines values for CohereEmbedderConfigTruncate.
const (
	CohereEmbedderConfigTruncateEND   CohereEmbedderConfigTruncate = "END"
	CohereEmbedderConfigTruncateNONE  CohereEmbedderConfigTruncate = "NONE"
	CohereEmbedderConfigTruncateSTART CohereEmbedderConfigTruncate = "START"
)

// Valid indicates whether the value is a known member of the CohereEmbedderConfigTruncate enum.
func (e CohereEmbedderConfigTruncate) Valid() bool {
	switch e {
	case CohereEmbedderConfigTruncateEND:
		return true
	case CohereEmbedderConfigTruncateNONE:
		return true
	case CohereEmbedderConfigTruncateSTART:
		return true
	default:
		return false
	}
}

// Defines values for EmbedderProvider.
const (
	EmbedderProviderAntfly     EmbedderProvider = "antfly"
	EmbedderProviderBedrock    EmbedderProvider = "bedrock"
	EmbedderProviderCohere     EmbedderProvider = "cohere"
	EmbedderProviderGemini     EmbedderProvider = "gemini"
	EmbedderProviderMock       EmbedderProvider = "mock"
	EmbedderProviderOllama     EmbedderProvider = "ollama"
	EmbedderProviderOpenai     EmbedderProvider = "openai"
	EmbedderProviderOpenrouter EmbedderProvider = "openrouter"
	EmbedderProviderVertex     EmbedderProvider = "vertex"
)

// Valid indicates whether the value is a known member of the EmbedderProvider enum.
func (e EmbedderProvider) Valid() bool {
	switch e {
	case EmbedderProviderAntfly:
		return true
	case EmbedderProviderBedrock:
		return true
	case EmbedderProviderCohere:
		return true
	case EmbedderProviderGemini:
		return true
	case EmbedderProviderMock:
		return true
	case EmbedderProviderOllama:
		return true
	case EmbedderProviderOpenai:
		return true
	case EmbedderProviderOpenrouter:
		return true
	case EmbedderProviderVertex:
		return true
	default:
		return false
	}
}

// AntflyEmbedderConfig Configuration for the Antfly inference embedding provider.
//
// Antfly inference is Antfly's built-in ML service for local embeddings using ONNX models.
// It provides embedding generation with multi-tier caching (memory + persistent).
//
// **Features:**
// - Local ONNX-based embedding generation
// - L1 memory cache with configurable TTL
// - L2 persistent Pebble database cache
// - Singleflight deduplication for concurrent identical requests
//
// **Example Models:** bge-base-en-v1.5 (768 dims), all-MiniLM-L6-v2 (384 dims)
//
// Models are loaded from the `models/embedders/{name}/` directory.
//
// Example: {"api_url":"http://localhost:8082","model":"bge-base-en-v1.5","provider":"antfly"}
type AntflyEmbedderConfig struct {
	// ApiUrl The URL of the Inference API endpoint. Can also be set via ANTFLY_INFERENCE_URL environment variable.
	//
	// Example: http://localhost:8082
	ApiUrl *string `json:"api_url,omitempty"`

	// Model The embedding model name (maps to models/embedders/{name}/ directory).
	//
	// Example: bge-base-en-v1.5
	Model string `json:"model"`
}

// BedrockEmbedderConfig Configuration for the AWS Bedrock embedding provider.
//
// Uses the AWS credential chain: environment variables, web identity, shared credentials, ECS task roles, and EC2 instance roles.
//
// **Example Models:** cohere.embed-v4, amazon.titan-embed-text-v2:0
//
// **Docs:** https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
//
// Example: {"model":"cohere.embed-v4","provider":"bedrock","region":"us-east-1"}
type BedrockEmbedderConfig struct {
	// BatchSize The batch size for embedding requests to optimize throughput.
	BatchSize *int `json:"batch_size,omitempty"`

	// Dimension Output dimension for Bedrock embedding models that support configurable dimensions.
	Dimension *int `json:"dimension,omitempty"`

	// Dimensions Alias for output dimension when using OpenAI-compatible configuration fields.
	Dimensions *int `json:"dimensions,omitempty"`

	// InputType Cohere Bedrock input type, such as search_document, search_query, classification, or clustering.
	InputType *string `json:"input_type,omitempty"`

	// Model The Bedrock model ID to use (e.g., 'cohere.embed-v4', 'amazon.titan-embed-text-v2:0').
	//
	// Example: cohere.embed-v4
	Model string `json:"model"`

	// Region The AWS region for the Bedrock service (e.g., 'us-east-1').
	//
	// Example: us-east-1
	Region *string `json:"region,omitempty"`

	// StripNewLines Whether to strip new lines from the input text before embedding.
	StripNewLines *bool `json:"strip_new_lines,omitempty"`

	// Truncate Cohere Bedrock truncate behavior.
	Truncate *string `json:"truncate,omitempty"`
}

// CohereEmbedderConfig Configuration for the Cohere embedding provider.
//
// API key via `api_key` field or `COHERE_API_KEY` environment variable.
//
// **Example Models:** embed-english-v3.0 (default, 1024 dims), embed-multilingual-v3.0
//
// **Docs:** https://docs.cohere.com/reference/embed
//
// Example: {"input_type":"search_document","model":"embed-english-v3.0","provider":"cohere"}
type CohereEmbedderConfig struct {
	// ApiKey The Cohere API key. Can also be set via COHERE_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// InputType Specifies the type of input for optimized embeddings.
	InputType *CohereEmbedderConfigInputType `json:"input_type,omitempty"`

	// Model The name of the Cohere embedding model to use.
	//
	// Example: embed-english-v3.0
	Model string `json:"model"`

	// Truncate How to handle inputs longer than the max token length.
	Truncate *CohereEmbedderConfigTruncate `json:"truncate,omitempty"`
}

// CohereEmbedderConfigInputType Specifies the type of input for optimized embeddings.
type CohereEmbedderConfigInputType string

// CohereEmbedderConfigTruncate How to handle inputs longer than the max token length.
type CohereEmbedderConfigTruncate string

// EmbedderConfig A unified configuration for an embedding provider.
//
// Embedders can be configured with templates to customize how documents are
// converted to text before embedding. Templates use Handlebars syntax and
// support various built-in helpers.
//
// **Template System:**
// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
// - **Context**: Templates receive the full document as context
//
// **Built-in Helpers:**
//
//  1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
//     ```handlebars
//     {{scrubHtml html_content}}
//     ```
//     - Removes `<script>` and `<style>` tags
//     - Adds newlines after block elements (p, div, h1-h6, li, etc.)
//     - Returns plain text with preserved readability
//
//  2. **eq** - Equality comparison for conditionals
//     ```handlebars
//     {{#if (eq status "active")}}Active user{{/if}}
//     {{#if (eq @key "special")}}Special field{{/if}}
//     ```
//
//  3. **media** - GenKit dotprompt media directive for multimodal content
//     ```handlebars
//     {{media url=imageDataURI}}
//     {{media url=this.image_url}}
//     {{media url="https://example.com/image.jpg"}}
//     {{media url="s3://endpoint/bucket/image.png"}}
//     {{media url="file:///path/to/image.jpg"}}
//     ```
//
//     **Supported URL Schemes:**
//     - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
//     - `http://` / `https://` - Web URLs with automatic content type detection
//     - `file://` - Local filesystem paths
//     - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
//
//     **Automatic Content Processing:**
//     - **Images**: Downloaded, resized (if needed), converted to data URIs
//     - **PDFs**: Text extracted or first page rendered as image
//     - **HTML**: Readable text extracted using Mozilla Readability
//
//     **Security Controls:**
//     Downloads are protected by content security settings (see Configuration Reference):
//     - Allowed host whitelist
//     - Private IP blocking (prevents SSRF attacks)
//     - Download size limits (default: 100MB)
//     - HTTP downloads time out after 30 seconds by default; zero disables the deadline
//     - Image dimension limits (default: 2048px, auto-resized)
//
//     See: https://antfly.io/docs/configuration#security--cors
//
//  4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
//     ```handlebars
//     {{encodeToon this.fields}}
//     {{encodeToon this.fields lengthMarker=false indent=4}}
//     {{encodeToon this.fields delimiter="\t"}}
//     ```
//
//     **What is TOON?**
//     TOON is a compact, human-readable format designed for passing structured data to LLMs.
//     It provides **30-60% token reduction** compared to JSON while maintaining high LLM
//     comprehension accuracy.
//
//     **Key Features:**
//     - Compact syntax using `:` for key-value pairs
//     - Array length markers: `tags[#3]: ai,search,ml`
//     - Tabular format for uniform data structures
//     - Optimized for LLM parsing and understanding
//     - Maintains human readability
//
//     **Benefits:**
//     - **Lower API costs** - Reduced token usage means lower LLM API costs
//     - **Faster responses** - Less tokens to process
//     - **More context** - Fit more documents within token limits
//
//     **Options:**
//     - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
//     - `indent` (int): Indentation spacing for nested objects (default: 2)
//     - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
//
//     **Example output:**
//     ```
//     title: Introduction to Vector Search
//     author: Jane Doe
//     tags[#3]: ai,search,ml
//     metadata:
//     edition: 2
//     pages: 450
//     ```
//
//     **Default in RAG:** TOON is the default format for document rendering in RAG queries.
//
//     **References:**
//     - TOON Specification: https://github.com/toon-format/toon
//     - Go Implementation: https://github.com/alpkeskin/gotoon
//
// **Template Examples:**
//
// Document with metadata:
// ```handlebars
// Title: {{metadata.title}}
// Date: {{metadata.date}}
// Tags: {{#each metadata.tags}}{{this}}, {{/each}}
//
// {{content}}
// ```
//
// HTML content extraction:
// ```handlebars
// Product: {{name}}
// Description: {{scrubHtml description_html}}
// Price: ${{price}}
// ```
//
// Multimodal with image:
// ```handlebars
// Product: {{title}}
// {{media url=image}}
// Description: {{description}}
// ```
//
// Conditional formatting:
// ```handlebars
// {{title}}
// {{#if author}}By: {{author}}{{/if}}
// {{#if (eq category "premium")}}⭐ Premium Content{{/if}}
// {{body}}
// ```
//
// **Environment Variables:**
// - `GEMINI_API_KEY` - API key for Google AI
// - `OPENAI_API_KEY` - API key for OpenAI
// - `OPENAI_BASE_URL` - Base URL for OpenAI-compatible APIs
// - `OLLAMA_HOST` - Ollama server URL (e.g., http://localhost:11434)
//
// **Importing Pre-computed Embeddings:**
//
// You can import existing embeddings (from OpenAI, Cohere, or any provider), but only
// for indexes configured with `external: true`. External indexes accept vectors written
// directly through the document `_embeddings` field and do not generate prompts from
// `field` or `template`.
//
// **Steps:**
// 1. Create an embeddings index with `external: true`
// 2. For dense indexes, set the index `dimension`
// 3. Write documents with `_embeddings: { "<indexName>": [...<embedding>...] }`
//
// **Example:**
// ```json
//
//	{
//	  "title": "My Document",
//	  "content": "Document text...",
//	  "_embeddings": {
//	    "my_vector_index": [0.1, 0.2, 0.3, ...]
//	  }
//	}
//
// ```
//
// **Delete Behavior:**
// - Use `"_embeddings": { "<indexName>": null }` to delete a stored external vector
// - Omitting `_embeddings[<indexName>]` leaves the existing vector unchanged
//
// **Use Cases:**
// - Migrating from another vector database with existing embeddings
// - Using embeddings generated by external systems
// - Importing pre-computed OpenAI, Cohere, or other provider embeddings
// - Batch processing embeddings offline before ingestion
type EmbedderConfig struct {
	// Multimodal Declare that this model supports non-text content (images, audio, video, PDFs),
	// even if the model isn't in Antfly's built-in model registry yet.
	//
	// When `true`, Antfly treats the model as multimodal and will send binary content
	// (images, audio, etc.) to the provider instead of extracting text. The provider's
	// API is still responsible for accepting the content — this flag just tells Antfly
	// not to strip it.
	//
	// Not needed for models already in the registry (e.g., `multimodalembedding`,
	// `gemini-embedding-2-preview`, `clip-*`, `clipclap`).
	//
	// **Example:**
	// ```json
	// {
	//   "provider": "vertex",
	//   "model": "some-future-multimodal-model",
	//   "multimodal": true
	// }
	// ```
	Multimodal *bool `json:"multimodal,omitempty"`

	// Provider The embedding provider to use.
	Provider EmbedderProvider `json:"provider"`
	union    json.RawMessage
}

// EmbedderProvider The embedding provider to use.
type EmbedderProvider string

// GoogleEmbedderConfig Configuration for the Google AI (Gemini) embedding provider.
//
// API key via `api_key` field or `GEMINI_API_KEY` environment variable.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims)
//
// **Docs:** https://ai.google.dev/gemini-api/docs/embeddings
//
// Example: {"api_key":"your-api-key","dimension":3072,"model":"gemini-embedding-001","provider":"gemini"}
type GoogleEmbedderConfig struct {
	// ApiKey The Google API key. Can also be set via GEMINI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 recommended).
	Dimension *int `json:"dimension,omitempty"`

	// Location The Google Cloud location (e.g., 'us-central1'). Required for Vertex AI, optional for Gemini API.
	Location *string `json:"location,omitempty"`

	// Model The name of the embedding model to use.
	//
	// Example: gemini-embedding-001
	Model string `json:"model"`

	// ProjectId The Google Cloud project ID (optional for Gemini API, required for Vertex AI).
	ProjectId *string `json:"project_id,omitempty"`

	// Url The URL of the Google API endpoint (optional, uses default if not specified).
	Url *string `json:"url,omitempty"`
}

// OllamaEmbedderConfig Configuration for the Ollama embedding provider.
//
// Local embeddings for privacy and offline use. URL via `url` field or `OLLAMA_HOST` env var.
//
// **Example Models:** nomic-embed-text (768 dims), mxbai-embed-large (1024 dims), all-minilm (384 dims)
//
// **Docs:** https://ollama.com/search?c=embedding
//
// Example: {"model":"nomic-embed-text","provider":"ollama","url":"http://localhost:11434"}
type OllamaEmbedderConfig struct {
	// Model The name of the Ollama model to use (e.g., 'nomic-embed-text', 'mxbai-embed-large').
	//
	// Example: nomic-embed-text
	Model string `json:"model"`

	// Url The URL of the Ollama API endpoint. Can also be set via OLLAMA_HOST environment variable.
	//
	// Example: http://localhost:11434
	Url *string `json:"url,omitempty"`
}

// OpenAIEmbedderConfig Configuration for the OpenAI embedding provider.
//
// API key via `api_key` field or `OPENAI_API_KEY` environment variable.
// Supports OpenAI-compatible APIs via `url` field.
//
// **Example Models:** text-embedding-3-small (default, 1536 dims), text-embedding-3-large (3072 dims)
//
// **Docs:** https://platform.openai.com/docs/guides/embeddings
//
// Example: {"api_key":"sk-...","model":"text-embedding-3-small","provider":"openai"}
type OpenAIEmbedderConfig struct {
	// ApiKey The OpenAI API key. Can also be set via OPENAI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (uses MRL for dimension reduction). Recommended: 256, 512, 1024, 1536, or 3072.
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The name of the OpenAI model to use.
	//
	// Example: text-embedding-3-small
	Model string `json:"model"`

	// Url The URL of the OpenAI API endpoint. Defaults to OpenAI's API. Can be set via OPENAI_BASE_URL environment variable.
	//
	// Example: https://api.openai.com
	Url *string `json:"url,omitempty"`
}

// OpenRouterEmbedderConfig Configuration for the OpenRouter embedding provider.
//
// OpenRouter provides a unified API for multiple embedding models from different providers.
// API key via `api_key` field or `OPENROUTER_API_KEY` environment variable.
//
// **Example Models:** openai/text-embedding-3-small (default), openai/text-embedding-3-large,
// google/gemini-embedding-001, qwen/qwen3-embedding-8b
//
// **Docs:** https://openrouter.ai/docs/api/reference/embeddings
//
// Example: {"api_key":"sk-or-...","model":"openai/text-embedding-3-small","provider":"openrouter"}
type OpenRouterEmbedderConfig struct {
	// ApiKey The OpenRouter API key. Can also be set via OPENROUTER_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (if supported by the model).
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The OpenRouter model identifier (e.g., 'openai/text-embedding-3-small', 'google/gemini-embedding-001').
	//
	// Example: openai/text-embedding-3-small
	Model string `json:"model"`
}

// VertexEmbedderConfig Configuration for Google Cloud Vertex AI embedding models (enterprise-grade).
//
// Uses Application Default Credentials (ADC) for authentication. Requires IAM role `roles/aiplatform.user`.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims), multimodalembedding (images/audio/video)
//
// **Docs:** https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings
//
// Example: {"dimension":3072,"location":"us-central1","model":"gemini-embedding-001","project_id":"my-gcp-project","provider":"vertex"}
type VertexEmbedderConfig struct {
	// CredentialsPath Path to service account JSON key file. Alternative to ADC for non-GCP environments.
	CredentialsPath *string `json:"credentials_path,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 for gemini-embedding-001; 128-1408 for multimodalembedding).
	Dimension *int `json:"dimension,omitempty"`

	// Location Google Cloud region for Vertex AI API (e.g., 'us-central1', 'europe-west1'). Can also be set via GOOGLE_CLOUD_LOCATION. Defaults to 'us-central1'.
	Location *string `json:"location,omitempty"`

	// Model The name of the Vertex AI embedding model to use.
	//
	// Example: gemini-embedding-001
	Model string `json:"model"`

	// ProjectId Google Cloud project ID. Can also be set via GOOGLE_CLOUD_PROJECT environment variable.
	ProjectId *string `json:"project_id,omitempty"`
}

// AsGoogleEmbedderConfig returns the union data inside the EmbedderConfig as a GoogleEmbedderConfig
func (t EmbedderConfig) AsGoogleEmbedderConfig() (GoogleEmbedderConfig, error) {
	var body GoogleEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGoogleEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided GoogleEmbedderConfig
func (t *EmbedderConfig) FromGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGoogleEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided GoogleEmbedderConfig
func (t *EmbedderConfig) MergeGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVertexEmbedderConfig returns the union data inside the EmbedderConfig as a VertexEmbedderConfig
func (t EmbedderConfig) AsVertexEmbedderConfig() (VertexEmbedderConfig, error) {
	var body VertexEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVertexEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided VertexEmbedderConfig
func (t *EmbedderConfig) FromVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVertexEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided VertexEmbedderConfig
func (t *EmbedderConfig) MergeVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOllamaEmbedderConfig returns the union data inside the EmbedderConfig as a OllamaEmbedderConfig
func (t EmbedderConfig) AsOllamaEmbedderConfig() (OllamaEmbedderConfig, error) {
	var body OllamaEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOllamaEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OllamaEmbedderConfig
func (t *EmbedderConfig) FromOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOllamaEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OllamaEmbedderConfig
func (t *EmbedderConfig) MergeOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAIEmbedderConfig returns the union data inside the EmbedderConfig as a OpenAIEmbedderConfig
func (t EmbedderConfig) AsOpenAIEmbedderConfig() (OpenAIEmbedderConfig, error) {
	var body OpenAIEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAIEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) FromOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAIEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) MergeOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenRouterEmbedderConfig returns the union data inside the EmbedderConfig as a OpenRouterEmbedderConfig
func (t EmbedderConfig) AsOpenRouterEmbedderConfig() (OpenRouterEmbedderConfig, error) {
	var body OpenRouterEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenRouterEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) FromOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenRouterEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) MergeOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBedrockEmbedderConfig returns the union data inside the EmbedderConfig as a BedrockEmbedderConfig
func (t EmbedderConfig) AsBedrockEmbedderConfig() (BedrockEmbedderConfig, error) {
	var body BedrockEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBedrockEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided BedrockEmbedderConfig
func (t *EmbedderConfig) FromBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBedrockEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided BedrockEmbedderConfig
func (t *EmbedderConfig) MergeBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCohereEmbedderConfig returns the union data inside the EmbedderConfig as a CohereEmbedderConfig
func (t EmbedderConfig) AsCohereEmbedderConfig() (CohereEmbedderConfig, error) {
	var body CohereEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCohereEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided CohereEmbedderConfig
func (t *EmbedderConfig) FromCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCohereEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided CohereEmbedderConfig
func (t *EmbedderConfig) MergeCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAntflyEmbedderConfig returns the union data inside the EmbedderConfig as a AntflyEmbedderConfig
func (t EmbedderConfig) AsAntflyEmbedderConfig() (AntflyEmbedderConfig, error) {
	var body AntflyEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAntflyEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided AntflyEmbedderConfig
func (t *EmbedderConfig) FromAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAntflyEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided AntflyEmbedderConfig
func (t *EmbedderConfig) MergeAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedderConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Multimodal != nil {
		object["multimodal"], err = json.Marshal(t.Multimodal)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multimodal': %w", err)
		}
	}

	object["provider"], err = json.Marshal(t.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *EmbedderConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["multimodal"]; found {
		err = json.Unmarshal(raw, &t.Multimodal)
		if err != nil {
			return fmt.Errorf("error reading 'multimodal': %w", err)
		}
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &t.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xHzrcttIsuarZKBnw5IWJHVxexyc6JiVJdnWjG4hqad3oukQi0CSrBZQBVcVJLEVithH2B/nNc5LzZOc",
	"yKwCCJKgJHtmzvnjpoC6ZOXly0sl+jFKdF5ohcrZqP8Y2WSKueCf+8qNs9lRPsI0RXOg1VhO6HmKNjGy",
	"cFKrqB/556UR9DeMtQE3RfBzQaoxGlQJAvIyUk2gMPpOpmi6AzVQK+OkDXPfWBiVMnMdqeD0BCyaO5kg",
	"b5DpRGTzFS2UlhY+Pzv7v5DrFDPbHahjV+1kG5tPUGEg9V66KeRl5mTHSTSQiGRKQzZyzLWZwf+GAo2V",
	"1qFym0zs1tZHFK40aPtbWwPVgRMmhPbtjITFtHUjHrgDYVXaBf3eScW5UYZwfX3CA3cbu8IFjuhdKpyg",
	"9f1kGnYl1STDcSYnUwcppmWRyWQugUSrpDSGlpApKieJTINfS7TO+pMcPYi8yBBOmV/9rS0YTZBP0UHV",
	"udvp/ggbf3z3HlKZ280YRJZ1TqWSJ6edk3edu13Y2Hv/1r+k9fwqIAxCpkWKKYyNzlkThl4iPQx6ZHuP",
	"SuT41BtCKg0mTptZN4oj9ASRgolC3pQmi/rR1Lmi3+uxwKfauv777fe7URzxmlE/WqY5iqNKvaJ+JFiR",
	"oid+WKBxEu3C+su6fD1F+PnyBPSYST+utXL/4hhQpYWWynXhQCgQmdUwQrDo4E4K2D+7/njy95vjs49H",
	"l0dnB0c3tA6qO2m0ykkQd8JIkvTCWdcecKxNLlzUj0ojozhys4JGW2ekmtCBAgPaDjDXQR4ExG3YyEVh",
	"wWlYJ425MDYXKWxh8RI1T3FEuiUNplH/10Dal3qYHv2GiSOiP2BqdHL7nYjyyxWEBdaByc8WbT02Mciq",
	"LzJIpkKqfqs0bAz3OApW4mYx2KkwmDZm2xiODq7ACXsLRvMMoVI4OtgFqawTpB78vLvOsBI9RYNdJrpz",
	"9zYGkYvfteo66YTq+McOH1znbre/7Rc51AlPJfWw/V4v1YntinvbDVMTnfdGnhm9TDi0rldaNJNSptjz",
	"Iu7Ysii0cZh2py7PFi2ssp8l0hbNJ2wQkXgnXjSl7aCwrrOzalQj4ZLpjZW/o5foWJSZi/o7cYuK8lig",
	"sSzeuTgrjCJN1YWTOQ1xU6PLybQoXXeufFI5nKAhOlKZo7K8+rIqnZeuKB3UI3i7VS3yHAM3FQ4C2xbR",
	"uV7AvkCCXaVhP5PC8sZ6mZr7KarKeRWo9o875IyFk7RnsmgGErN0ze5SFaW78c9XjYkkXJ+ZhwINjcGW",
	"yRSEBYvCJNObVCcl2UZcPfhaopnFkGTCWjkO/iUG8i9ZaR2S9Xe/EZwqOjw0HR+SoEuLsIHdSTeGN0sK",
	"+SaGN89Zy5slsFrV5xXiKl1uo45ww7+vYaciuIo/KkJrS1gmYW4iLZvTr+JG4f1NJhXaBUsZi8zisrX8",
	"MkU3RUNs4rmg8B547tzDBpnig4MRjrVpuICGeEZaZygUUeFMqRLhXtaWaiCMcCrupDbdfwL9/drfB/6B",
	"rnVB5MUx3OKM/fCQnPstzobeYkhbhwfnn48uj272L45v/nr092G7W16H3l6XUE0yaaedu73uNmwEmcWw",
	"s737tgqR/EAOKDOpJqXIePQzgB60lcDcYAg1vGdeROumfUdL1toIhlYpXcRzv117OHSLs3aTCJwPLG6P",
	"fRb5uzbqWbGGZdwKhtByxEW6rgpM5FgGZ0/zKWLzZsA4GzxHIx5n5ERV5qSjq+s3ES+Ko0XI4wcV4DVU",
	"uxXwqjO0CmOVvRychXBzRck9SHqEXASZ1tVXyFq084qyo7PDFVI+63vaZypUmgVAsZBpNSHomQrF9OXi",
	"AZy+RQUZqombNll6dn52FMXR1fX+5XUU8x5fvh8qVkFCZNn5OOr/+hhpheHXHwyOo370Q2+ewfZC+tr7",
	"pPUkWwabp/j5SX9D4/DhGyedZ5nIxbdOYm//HZMudenQfOPE9rj7pVmteP3SpNaawdMXmrYIOoyTuU5F",
	"S6BwiElGqSTHY24qbbCEEJpZUFpxDEAxEifKGzIXEw7Ny1TqGAjydAwXhx/tZjxQeIcKpLcyv5S06o0D",
	"qVqKDX4AhQHWmRnM0LFv+IVitaEzJQ7jqrzhDApnG8sKC/ODcZ5wL7MMLKoURlIJM6tIHqhlmtEl3U2y",
	"Qlqugm3OMVCkhBH44IxIHCEDHb4L142Bb6z3g9KCdbSnQVtoZTmUJFAUSYKFnzzFmnH/+H//4Tk8zsQE",
	"fistBRJZVhVhBkppNw8+pGfFmXagEDnN16aKnkVmUKQzYirtUDMwREzDOWNqhBvGAzWcYC6V7NQPO7ud",
	"wuCdxPthDMMkk0Vnq/qVZKIYbi76aq7FDIfD36xWA/U4UACD2u0Noj4Mojs27EEU+5dMsH9jdY6dcelK",
	"g505gZ0wohpfv6BJpAID9cR7toZXc5f7vK1UVnJRjV8GyHqhL09flhF7H0pFPjBdzhNI1GpdpFRtaSER",
	"ilx4NRlTX5NymBecUJLQk9I6zSnYVN9D5S65zDNQiVbM1pRVtjX4hOt6NYrxP7N3GQljwc6UEw9kIANV",
	"JVwUKuiyYYhTzAo0VV5drQVXM+swDxW4ra0rXmprq99cPxyDy3lVyDWtX/9mOeby2fKmX+bAV/9onTnV",
	"BEKidDoXXELLQvkuba/f1XFhH36EXKrSoa1WJ3N7cIurG0xQ3iFby7jMsprDBCOJn+HP/qFiyWfPEj78",
	"QO10YWvLJqYcfXZ5trUFHbjEXN8heE3pWTfLEJyYWMaiACCQkKZ6mXES8fn69IQ0HYbD4ZxL/OTxsV4f",
	"pi7PbgJwPD1VE/i/1cYWhoNye3sv8QTwbxzy5tULIql6TpSF+ftpaim58bmNGDs0MMo4Tc/Qq91GEUMq",
	"72KY7nSm72LIZADNmgRXGmWhyIQMx2M5FQYpe8MUCKDESGbSzYh/u8Q//MqMO/paCnoOnIEbaeel1FSS",
	"ZYnMruXRD3IMG/gVrBOutDCICKbvcBBtPj3t808yAPP42JPjwLn5pP9DqcsgshTUEsJsPj1d+d8+hWnO",
	"Yn4P1B4RnmMqBdP+CdVfpYNUu8LovHDAr0JFjzZnlJ77pdoFrTmOn16a7Cd2UYfCiZ8vj2vC56/Jc3R5",
	"zE1pspYBg6iyvhC7suHxjO5vxWQQtc6xezQhlFt7ozK5RRcmFWrdpLHMsN/r9Qrhpj2nWzYJzAMg1KiK",
	"Y1zvvSJEDlV9VqVhKpzoD6EDH4TFd28BVaLJ39Fz+Pny2NZujUfyZr3fCpz8acQT4m63O6wUcxiqvEPo",
	"+d+W/+jALzii/a3X0xppau/MqU2KjsSoVbVaOCkt4C8g6IFlVAQ6fWVSQ+YjDbvaaxaWrNNGTBA2fJG5",
	"HwYuM5yS6M2aYfs1cQeBuAujE7RWqsmcb1tbxxzUENAd6nvlLwNiCkY4H9uQ4xA5bMaw4EFqxtYrUfDm",
	"AfPBVdCFnNCPpbEOCjqDQZUieS9hgYVQTydQo+mXbPMEg4vr+LLbqf5dZpkIo2pk8DqCSWkIEujERme1",
	"flQn8w6iMJoEhCmM6ugObDXXonN8R7VhkVK8pq++rJL+zX6Fglmm7zGFqbYO7qfSYSatCy8vjLwjB3h8",
	"4ZGRvRuFSoyOV1eXH0E4J5JbWyleRagvtWYylwSjtZfa2d4+/VCN/Xx9fQFpfTInKTEtXYDivW06klap",
	"pVOGFf4Ev6PRkErLpXR2ZCmKlDA8rMrq0Kh4rtCwu/32ffEQs/J3gppUWneF2K8rJv4ypys11056C1HP",
	"DxW7O51EG77hesvYzlZ7rbXyGM9/elWTCq7Pz8/A2wBsXFNi2zk3EhWJ8pxzUTjTjjfYXIuV8y04ju76",
	"Om2NUO2vQwJ9Kswtmp+48AdSpajcT29fmpoi8xDNT4NoMHCt6PYLJU7S8gn/HJSWTystCO/hEhfDtMyF",
	"6pjKQAIrUrRyokJsXwi2cIr/y8RxnMjscxpOTk4pNgOA5lXr1tbedufd9v8KlQKDacngxfcg5Fm9uf/l",
	"6vyMFDxDyIVUTkhF20zlZEoL87I03uA0aI5IktKIZNatT/lXnMHChSxr3IE/XRViejMf9od8nFucde5E",
	"ViIUQpo69jBGzIJMIGeh2D4MKTr59Ye9L30QMvYVojjPqoDnWozKTJiKa7Q6ReTa5J5DNceqXc7rqhSN",
	"PTk5hUIYpo7Co5JwzDqhKHIOM04DZ6yX1HL4wkz4gArH0tkmBp/oezRcsku0dTYEhmmZMO9v+c6BzDJH",
	"oSxkPJroqWfUK30Ulqw/5JLolzpBa/06nCUU3g/Uc04pCUiqgBc68FE6yOnhPIMgf0cxmq8mMSbUJzrn",
	"FKfpjJvWMoQNSrU2+xQxwg8U3I3lA9EhWIqJLmmDTN4iDEl6wwbYUOpWO2VvcEPYkMpt9uGY//TAbAuR",
	"kGBIUAotux0GhAXkqleqTXIIG77WtdmHj1x+tlgII5w2vpQddIZJba6ltMKYk6RhsOphNcHOfXBVnPb3",
	"SBWDqhjcSZchncMZHYyO2PI3vtWFK9ZfHihKN9WmD38RCuFQe6huV3Z+laMTHOXwXwDoA+I+7IYH5Ilt",
	"H97+uL2CRIf+hAS3l/uf+ltbNQ55Z+HfNmyozoG8Zycp+LnwtUQjwzUrr127z4au8OqhPuyrt3MPMpFu",
	"Wo44AnVaq47flX+H2Z80HBOH80oTWieLrLhFeytVb6L95IX8NEipStIOqwP5fpM5L5e8ybUXHwW1fkiX",
	"BUrofijc4ptUOH5xLSaWXvyAIpmv3SVZPj09PpLbeHqK4fGxRwNoxkA9PjZSuCAqipXq0KUqM2m1SuSF",
	"Vy3ak9sGiLh5WaK/kC426hU3lDrS4AsjE+zDHx4fC/rVIOF0np4woziYe5aAmj0rCUsLWQ1iGpsezJO7",
	"oIMUq63uurAZ5W3ehJ6ePsxo8eqvOlObJ3eJcDjRZsYlKcxlmXOC94///P9w4f+u4unG5JFOZw0qt7aO",
	"Gjcqf6s6F0IFZPjp6PT47Hh+u9WpLmvYnnwhHPaPeez5xdHZ/tqxvirdHPhh/4o7WapMiLOl+dBmVrF/",
	"QbE7TT052T/dv/l8fnVN03x9nO9P0fD8kDmttL7s7Lzde7vpT3ycU3pG1n9hkLcpCYWP6vucYF1/1yWX",
	"siSPB3yQlmc1msM2uMbhCY7DJQvfYgs1q6tjmzGMSgdaZbOBogOSd3hAu1IgG+KDQ6NE5r3JsAtH4UE9",
	"xVda4Y6B18K9kc6hGiifj2ezqqHBQ2AFD8ObOc3V5SUFBqkGpV3VT8bpRl44f/07UEMeOORrzqp2NwwV",
	"syuHhefTThcODNLsZmnQeorbz8XVkY8EyKhCdPqANuY7P3/pTFOHdWQ/5KrEL0a6ZT+/cLI+PMIg8qUg",
	"XuJM5KEcNIj68Gu32/Uv6yn+Zbfb/QJPw5cLv2yovrZ7OoMKfOtSblX64AE1NHM5vdutRzUIppGP3s8N",
	"onx246V6w7QzxdvdnRi2u7v0z14MRCgNf6pKxOH+FzN0CB/CPXqw3Z+9w1/e7jkOqTLL4GnIKbNfU3BC",
	"j1ze84roaaQNznPJkLYgg19bF/8yhAzFXUjjakPya0GpkqlQE0z9cYjwA2FrEDqVE+PLrWxsQmnuWgiT",
	"6/5FVocWG/W8WLLbSuM5r67P5uscPGOOEUUTI1os3VNT36ksbvyBm5GKuprRpEGPx5TMVqVtqSZow5Vw",
	"SzcVt6XM7zH2OjYXWbZ4Ca8LVEJyqX+l/v9CO19Nf+NGOFy/+juUKA43HVEcaYZd+uE39D8MXx9GcaO3",
	"K3QFxFHu/w5Nk23X3K2Xqq/s4Kj9EGx8YmI3v7ebY9nffVM3x8pl0/b2TqOfY2/7j7vzrtbVtg0huxM+",
	"SDfFu15YTBTS1yTmirPaz8oNFtFMl4bGd+jPhc412nneytFG5qIeBYl/WzNHJYTnmjkW2fv6Zo6lLrzQ",
	"beCPtUrJvCIUmh/myhBAY+OP797HsPPj3js2YZaMwUTnOSUG6WZ7KxxFE25tf1c4/0GmyxSqoc2WrgSV",
	"MyLbebPZhctwE8cq7FsDgHBFF/OIEbwuE0df6oSr2i/WiPb51pDX9ISsWXiFpsJoSmVvZPoKJoXBcHwI",
	"G2sOHoNp5dRmK0de03fdUNOqKD3fndNkW6eOcszhkQ0tQV4vnu+efnUbSmtrxyvxLoS9azDuZPkLBq61",
	"GXknkhlHfZXjISkzaxgNS5M1kXAh0kZ1Rwa6FvmUzmXS6J9caO/PH0YiqE4nE2aCsNFsbRNZ1iFxZ/lS",
	"3/8qQnq/w3myryL8OfmpPme721ymbMlhVo5szRcBnDWs4uAzPahNwwpialpVjQfLdL2J4c0Ko5bbP1sO",
	"s94GKkxYc6j4eTMJtL/8bUJDT77nk4SKmH+VVbX1Pr3Wqnju90YOy9nvmsjhqmozak9yl01xrcW1h4PN",
	"7tEf995VJrYyOJjhSxEJZXwkmK6P89jwOBjh7obXxCT2ttPtdht9pN8Sxn5T+BGk92z4sSij7wg/7Cu/",
	"Alh0qxvsVE5DdWM+sr6/4ICgjj76sPvjuxh+3Nn1PcBLgUp7bNISDKxl9Quo5Rm5PhZYu+7rsIhD3UI2",
	"dOpFLJqLdo5FofjLtwR+wBvLoRJLflXoVbXplSDVSuW/EKRaey2/Aaj8/HVg1RhRX56JuqmLGFl3bRCs",
	"rHyswol2KsdcA68v4Lhd6jU4eHn+8/XR5XdmUZ7jvRcAbjNeO5DBLR4on0z12kLXGL7eo+rRP3uNN+9H",
	"a+KOOrvtipCOUV621Ff/EhBqs4SFz550FRJDfv3tsBg04UVoXBTbfx88yjHU35PBaDZved18Nda9xMpn",
	"GRO6dvmbvLFEUwdpz65KEdszKrYcu71E4feCSWtf+SuAZCETq/OqVSjYQOXQFEZa7EyMSHFz/jnkfjH/",
	"NLi6jDuYf9wIG/uHB5u+a7R0U/+tMA2u818Lx/un/IUjDPk7x56QddBRWjTDf77YEkNLc3DV1N3j/uge",
	"t3SvCYIS4lBVmaEIyJfBOkL2qu+w77AjVso0vQm6zqK47WCpuLdSo5mXGKJGxSB6TfGmzrujfNaZJEUn",
	"PFsEklDDWwGRxjepN4Vw01UVuhBuyt3a4WM1kfB1uO+24FsemWEX9jMupnJroNOwf3jgb7q16nw6uGiC",
	"iv0fK/UQQW2M/BPs7L7v7Lzdfr/U1ViPelVlqAKlRQkuEr9gfo3PAueWSHDdVj2K4Q2WJLvOPVrH1aTW",
	"Utv5+aeTo5uDk/OfD29Ozg/2r4/PzxbDpoVl/60lprX48m8rNq0pNL2CVxeX5385Orh+rft7JVA/8Sdp",
	"Y93yCa/y8evFcVVoWvyfLTBuE8Pm8dhq1Gfnn5scfmAqpWNezi81oboKWGwU9HV9b3DRdne7y59fs7cq",
	"ZNSP9rrb3T3CEOGmNuqrMsue/isAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
