// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/pkg/libaf/logging"
	externalRef7 "github.com/antflydb/antfly/pkg/libaf/scraping"
	externalRef8 "github.com/antflydb/termite/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: termite
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: termite
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`
	Cors     externalRef4.CORSConfig               `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   termite-local:
	//     provider: termite
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef0.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int `json:"health_port,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef6.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table"`
	Metadata          MetadataInfo `json:"metadata"`

	// RegistryUrl URL of the model registry for the Antfarm dashboard. Defaults to https://registry.antfly.io/v1
	RegistryUrl string `json:"registry_url,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef7.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   termite-local:
	//     provider: termite
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   whisper-local:
	//     provider: termite
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`
	Storage      StorageConfig `json:"storage"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool                `json:"swarm_mode,omitempty,omitzero"`
	Termite   externalRef8.Config `json:"termite,omitempty,omitzero"`
	Tls       TLSInfo             `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef0.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	//
	// Generators can be configured with custom prompts using templates. Templates use
	// Handlebars syntax and support various built-in helpers for formatting and data manipulation.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full context data passed to the generator
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//    - Useful for cleaning web content before summarization
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//    - Use in `{{#if}}` blocks for conditional logic
	//    - Compares any two values for equality
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// RAG summarization with document references:
	// ```handlebars
	// Based on these documents, provide a comprehensive summary:
	//
	// {{#each documents}}
	// Document {{this.id}}:
	// {{scrubHtml this.content}}
	//
	// {{/each}}
	//
	// Valid document IDs: {{#each documents}}{{this.id}}{{#unless @last}}, {{/unless}}{{/each}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{#if system_prompt}}System: {{system_prompt}}{{/if}}
	//
	// User Query: {{query}}
	//
	// {{#if context}}
	// Context:
	// {{#each context}}
	// - {{this}}
	// {{/each}}
	// {{/if}}
	// ```
	//
	// Multimodal prompt with images:
	// ```handlebars
	// Analyze this image:
	// {{media url=image_url}}
	//
	// Focus on: {{focus_area}}
	// ```
	//
	// Structured data encoding:
	// ```handlebars
	// User Profile:
	// {{encodeToon user_data indent=2 lengthMarker=true}}
	//
	// Please analyze this profile.
	// ```
	//
	// **Common Use Cases:**
	// - **RAG (Retrieval-Augmented Generation)**: Format retrieved documents with citations
	// - **Summarization**: Clean HTML content and structure summaries
	// - **Query Classification**: Format queries with metadata for better classification
	// - **Multimodal**: Include images/audio/video in prompts
	// - **Data Formatting**: Convert structured data to readable text
	//
	// **Best Practices:**
	// - Keep templates simple - complex logic belongs in application code
	// - Use clear, descriptive field names in context
	// - Handle missing fields gracefully (templates use "missingkey=zero" by default)
	// - Test templates with representative data before production use
	GeneratorConfig externalRef0.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef0.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96XIct5oo+CqIPD0hUrc2kpJs1w3HbYqiZLYpkZekjn3G5ahCZaKqcJgJpAEkybKC",
	"E/MI82NeY17qPskEPiyJXGrhIrf7XEdHH4uVWD/gW/EtX6KYZzlnhCkZDb9EMl6QDMM/jzib0bn+Vy54",
	"ToSiBH6PF5gy+BdOEqooZzg9r7SgimTwj38TZBYNo7/1y0n6dob+J5yR5EiPdUrZdXTfidQyJ9EwwkLg",
	"pf47ITIWNNczRMMI2iOYHMWwtEJg/U2iGRdohtN0iuPrviBKLFHK5zTujdiIwRQSYUEQFwkRJEEplUoi",
	"PkNzwojAiguJbqlaINMXs8QP5wc6xvECpZRdI0FmRBAWE4lwOQKaLhHDGUEzwTOkFgRNytEnKMN5b8Su",
	"FgTNqJDK7iMhM8pIgqYk5hmR0C0hM1ykCt0uCEOM25YwNJVI5iSmM0oS2NvLl7A7dMSZOQk5fPlyxLpo",
	"wtmYCMHFZIiuxBIxcqeCtXKGMFsiaIF27Iy7rqPAioxTmlEV9uYsXeqO+iuCr2jn1f53u2YU6TormhFe",
	"tPa0n8IOOL3FSzkZokP4B9Lg10Cortds9fgOZ3lKYIeTyWSJs3TEzGUcjhhygIN/I9Qtuw/RnGSU0e4s",
	"xXKB0N/QhTtCd2qmDzIXYOj+QijDd2OsFMlyJYfowH2IHbyHqAKvlql5muIMd1Me43Tl1PrydSlLKSOb",
	"lt/4PDbIMNSDn8AQFj3KXeSC39CEiCHCTC0Ez2kcbJEnJB2iOMVFQrqSM0ZU91X3dXd/sP968N3+dwBt",
	"fQRX+kZShg7PT1CM01QO0QTgP0SjyEJ/FE0QF8HvwdZG0WTEok5EzEFqAmF7RcNfNCGyQI2GUQWqUSfy",
	"u42GUQiNqBPBkemxwrOKhgf3950vlX7hSUT3v3bCpcECVk5SGcnCG2bUoIuG0WrYRZ3IAV9TNgf96P7+",
	"15Lg8ek/Saw0xYsXBbsmYi1xXUdTUzodwxiUzcc8JwzndHxkBrXkfCVdhUZtlFVpXHSjAtl5B2QLbq/v",
	"qYkXVijGDE1JSSMTfc0pS8idJpcsKS9PjRya6bcjiKbtKpK4gk6YVQJ6zegdSbqvBwOLbCV+KCIyqiw5",
	"sJgBrc0vCos5UWPFrwmTQ/R6MDC/8xsiUpwHH/TvkmSYKRpvNYtr3LUrNR/1+RUi1Yi0UCof9vtwfRdc",
	"quG3g28Ho8hiZxWt/AbDWwo/Rp2outho+HpQuaR2cVEnquxWtxvcdyK3TriiZnXRsH1xUcfPXd9d1Drl",
	"fStOcLHVvc9okqTkFgtS3vyzi8vw2sM9GssFFokc50SMFZ46OhSixDt741iRTYnQgoLpgxRHsSCaAWrE",
	"wIiRWwRj9EL4v+pEmnhkRRYN9/yOKFNkDju/68551/5aUKbevILlUalHMssb4zTlcYVCznAqSR1535lO",
	"EuFC8QwrGpulIkFgBEBjtCPzlCpF2byfETGnbL6rF2yXMOU8JZjpNZBsSpLkiQTIDELZXPqDOLbjrqdB",
	"bvY2IuQHRXop5kOTFvn1byZGHaQ5RYqV/udqwuTXtA1l8o1XkSY9x49kiY7CDQKhGjH97ZospVu1xY8E",
	"3VAMsxEWi2WuSALNFBcE7Qi9moywhCS7mu8SdkMFZxlhCt1gQeFyDPXwez308uWPtuPLl5WuAOFc8KSI",
	"9YJ2DcGaTCZTJ3BgpmbpspzYYEHrJ5wkCM6d9vTRX5OlGw3+C0KEPxHkhfkhmtjmQ/RvXySJBVHD6jj3",
	"IIXs640ct+xTb0pSjYICNpSQG5LyXLexOzrTQqubZmIkdTM73ABJFAAa51rhEVTjOWE3egLTv4vOcsIO",
	"T4ZocnZ+/OnwZHx4fjL+8fgfE/v5A0gNQzT5cPzx5FPj86Hj/0M0Ofx09cPF2fnJUb3REV8QQYZocnT2",
	"w/HFcfB5xC4JQb9cAmwk+ogZnhO9vV93+gmPZd9ATe7C9jV2pkQRlPC40K3gsq3jkR57YLcG9l2Z4TRt",
	"cDDzscLAtJjQ9WjaPTA9dRNL3o3ktRUznM5Jd4ol6RLWvdnrvd6KGe6vYIbhRkJ+2L7gKmcyfUE5DTex",
	"mfntB8yvvpsHMD/CgCfgQi02M4Nj5nnBgmhua6i/vtr6Jy7o75YfXLw9PDK3RN/3w/OTdnZQKrBP4QeY",
	"ej7wwQ24nhGUimoLJzg8WcsCApV+NQ8wWuOWLKBczTY8oGz9vzsTMCrU05lAdZw/ARPYQOU38IhNTOBr",
	"U/kSQWA/oaLboM3mY4U02/b7vdelPSLUrJusAj5WxoBfDgImM8/Vq214zDxX3Ve9vVYyX9HYAzJfX3CV",
	"+pqvmhBVzANBf7PYGluAH6FXuYHKpGah7cykjdAvCE7VYpxzoSqE/tX+YFAnkudcKE+8Tcd+RpSgsUSS",
	"iBsiesiqMKCy6DGqCgoMWtNL7jtRyuebCHp+PR+ndIpn45TP5xUzgyfpGb6zWoykv5PxdKkMo6ju4iO+",
	"0yoS0m20ioWt5kIZgh499FmSRK8/IcAjGTFEVnEE+oxVyio72xt8c/DNq71v91/BMowO9urN3jeDb7/7",
	"dn//G9h4qZwNXn37+ps3W6tofmNrtUe3sab2GPAjQzsTq0dKyuYpaVEl96rr3X6lROEEK7zpOD/adids",
	"xnU/QeZUKrE0kk19Z58vTvV29LWDi45c81KUYGqGRYYSLBdTjkVSvYlaUpLDft/16xm+0aO8f7MX7jva",
	"1HLGRYaV3rOgpewilaBsbjaScUXGMWeKMLX9rZaxwHl4rS9goCMzTnnHBclTK2CNZzgGo2EdXD/wW5Rh",
	"tkS2MTw5EBwv7E2XC16kWppAGaZMYS1bVE7/ILjErx91DwQR+MkWRTNIFShm2PVinJu8TYqTBIt4gQSR",
	"WnjyMzTlOb+DbVR6O+pvBRF0vVDn17aNTOcbP8jk6FcOnC0Gta5L2DylLZzWfK4wO9Pf9ejeHPQGj9Om",
	"srsppl07HCgiN3umwSNMi9V9hDyvZb1V/me6tipTboy2pUYrzJPrLI+tPNbwpJjzNOG3TJNwypMm2h7Z",
	"Bsg0QHimiLAoW2oeaEcqLFRfKp73gR/t9tB7oEpDlNi7jgxBQim9JujFXvaig14cDOQLTxWH8Cva4Yyg",
	"jLJCkd0KBYj2sgZ1q+K6ohnpvbPzwS5zQuLFWPGxVnCfpLgVCeUe5y+vrtaju5m4q3gXXgzcmdWwv4nh",
	"l1dXvvE6LPfK2hq09pNug9a+8YPQugpfQMDbBZU5Edug5DYG/QB1jcjYdxNojAjEZvvzNpKzG2Gv8Zrn",
	"wTpEky9flMBMH+2UHOrT1xTi+1HU6/VGkZ/g+1FU2fEour9fZXWxDUMc90tZZWqpDP6wd4YWeD3A2gJo",
	"7F6wVwt2Hrut8GaYOYiknj6gKZlpRVgJOp8TIAKCG5eCTWTidSuZeK3JxIzeODoha4Ti9cMJheICz8km",
	"SnBpmpW4L2+xyMYa4ptNUm+XOZaSSHSBZ0pTAkmYLKwIAFJxBxVa+kUJFSRW6FZQjeGUSUVwAjrArEjr",
	"qjxQAEWk0j3Bc8PL0IwnpN2a5Y5+w35ts7GWCd2/mzqOSjeS0KvTSydW3xAhASD1K3XCFBEMp8i2AEUI",
	"JN3K4Q56A1Ama2IuCHi/FVSQJBr+Ugr95dm2CqorNLQV+s2ah7NfW3DoVKNm9c40PIg0Wo4TKir3JzL7",
	"TqZR/RJdcK7s/eBW18Bp6mxOesfI7reqbbxwI76ookowUUbZKWFztQiF6hXg9atu23ZFkWpsmIt4QaQy",
	"uKdJ2Vp5fJNuU6dKuVZYjCHLLQN94glBJ+/QzoLcWfKyq2FClURajSukYarGXKeRxr6zMU2m9HiUKQ5s",
	"M04LqUDHCMj7Xhsxfj0Y6Fu6v+LbftSJDlZ8O4iaBLkG/xYgtp1Eza+sgXKHxouLMoStb5UXOUqLZJtj",
	"19mF44AIa84ZuNqAvPBZhj5fEy0gerCHI9fs1GsdxqpjWteTCdox24Whm2taYT7vjdiZ8cQCe0u4VC7a",
	"Zin101AwMvw09Acs/XYe9BgAZ+Q91yrvDc1T06fqbA8toAus/hnO25CmzX/naS8X3vHoAcNc6D5uiDYR",
	"5PLAURCcpmcz8Eva0nJxUEJWkIQwRXEqwXepRn2L+Jq0iDeXB8h8Mtf9Vitr6PLyCs1oSiS6pWkKd0FT",
	"jKRCULNl19DUrh0bWIkjrG8OKnT2oOVwckFm9K65pLPc0EeUY7VAphXwe8Ba4ta7Q3rzXsfR+375iNF/",
	"sVtZaPBlIzclLMk5ZXozdldNatNGfyzve4vja8KSKoszEm2dgtseaGq6IBiyExFWZHohrpM80CsoN+N+",
	"b0BzA/fdxi5Y2wTYhq0wvq5bC/N/gDGyOak82NjH4Ev98Mxq247HSWVNt2YiWpDiXF88xdHV6SXSLehM",
	"C1MEcKJytfr6ivYV7+tWvZxkbSdzTZbrp7gmyzVDX5Nl+8htlKRGefyzU52Stdg/AqYRWnZNf0drtSpy",
	"eFIq0TtH4AVpFE652wueM+H1MnhyoyRNgOc0379aHy+r6jj6CDMMX75c47RaejV3XCueF9K32dsb7Pkv",
	"B93X3QWm14X+9GpvsL9vJnzHY5jGGaMTHsued+LsxTzrE2Ye5fCUF6prxusbEPT5DRE3lNzWVWMtZjun",
	"uleD7950nuBIqtWaDJTOQpBoOOh9c1/nzxbuzYO+qhyrPaseOpkhxr0pJemAL7wE6qSvaePM2o+s7fqH",
	"G9/8amJa6intjYOHYn0XBZG5ViWDSYJXLAvMkO6uhWsTKLMiTe0Lx8k7J3WUkDJfFNdCtOc9q6d4UX5t",
	"XMEXNS1+7UIb8KwcfQsaK8FTiQRmCc8YkVqt9tjLGdoZ9Abdvd5gt4d+oPMFEegGpwXRItQ1QbxQeaFQ",
	"pvUDM0QvfHeZpRxbRu8fJfwDRfm6aI4TFsvzcYs4fsXz7jWSGgBa68ixwBlRRPQQCKvSoLwX9BTP0Y+I",
	"54FnIDyoFFNJfiv0DYRr034z9BLyFtmyiFNSyJZFhCA6TEFVB7qnNaMS9k+DS+tLm76FwWtbFUudZIJ2",
	"uJWPOvoqSm/gpAaDvdS+29v4YlY3JQAO/bqZrbwlieDx9WOZyk+XyI6wgq0A6T83f0iE41hfY8UtlzH3",
	"wkOnA/pvBx1m+HfOOtaVroM+Uq02puY9iKsFEXIlSwnI+0pc7N7sDQcdpOWannEP6B50vxlMu5RJJYpY",
	"2QYY1tFj/AZ3c8Hh13Wc5Vb2bBfNWqYGMH0wzqp+IYmYF9Szl64s8pwLRZLeQmVpi2L2VHK7kbzWb6w7",
	"Sk86azRya9jWyeLWHdufguettrcrewHNd38n3SakZt5xOyN7NsL7h1LU56GJT1nzY6lMzVRQ4e0u0q3B",
	"yX17c7RiqbfRDC4D7zOIVhqxLjIBaZV4NGguyByLJNVnyWeaN8Y8I7qDm74S77Yquq6Mj9sqPK4SBbU+",
	"FM91CvRGs5WoE0KoXID5Iwiy+rXlntePAejpI2m96bxae+BZpsnzQ9SHmof0A3UHM2FXdPO0kBV9wX0p",
	"/4m7gwOgNGvIt3neBtLtzX39eIHVA+T/yppaX8+fKvDbY9hW2q+CeHtRfyZAHIuXY313UtWm95oP5oJo",
	"cCDf6bko5H+ewlE/yOZBsMCiaQ8lVCxqekF9vDYTmtQ37iHwdn2ejSH9pY/8V9dHHsuhW5hCacDmjGxh",
	"yq6PyPk8JU27+4MG+TsRitw9cZAzkPGfOMiVeUp+6lLAt/wZBrnghSLiiQOtUP4eOMpKy+QDx2mXTu5/",
	"bb6AlFz1cW9A565/HV38wL/e/9ppvDsWDLTx6qucdSJZo/1+KN+2nPOwHYAkxvkhLqTime6V5Upahwrv",
	"19NDV95zqpBkxH7ALEnJFAuJ5JIpfGcCH4w6CWydFxJNC5qqLmVoQdKcCJtlA8gKuF3oPvDUnGFG8yIN",
	"Aw/chOhyKRXJbFKKly8vYbqXL4coWINdqB5zxwlUC//5nxIkKqP57pphjnC8oGyuxym3hgUpo2Bxmi5R",
	"jOOFB5GD+TQl6Orq1Mt7Q/Tae9TY0TlT5E5VRxckJkBpnXkwNq0MCMDJBXzVK4+RBhhvHSB/MIC0oT4Q",
	"iyNjUUx/UFn68iXqoguS8RuCzK3pS7UEn/C5cXgjd0rgWKE4JZiZoHzgQj9cfTx1wTUl2OCXL1/8+Gih",
	"stS5Q9/fV6Jx3MQSTUbFYHAQmwXAv8kEJncf9JLc73plLqYlSSRi5DalTJ8EOExOU61FkxRiVyTayTso",
	"oTcdtNjrLt50UEo7iKi4t+uXoArBJMpTeJLX24ODAxlF3IAnME7wlKZULW2fwDkIoALeQGSK7DadD5Ys",
	"sgy74DcfPUR+A5gf/1ZgPSRE0mBBpUVJ/6qNU7kSvH+jM7RDfkNSYVVINIpwrFF4FO3e3x/CP7986dOZ",
	"hXfZ/t+1VjOKwECHU2h+af5ttJuwV3lKnyUIpBMY5/5+YkAs68s1KWt8NKneFfhMLpG65U6kAknFbl2D",
	"5ECDJCMJxQCVD4T9SBVKuDJEBcEn64Sj8UD3z4pU0YwnOHUQXwko070Q6fc0w3PyDiv8+eLEw6X8rBZU",
	"9qDNuBBpS4ORDw2w0jGQB+jR+2c+H0WtfeSB7mDtpn3znms75WxVpxlNybDf989vzUmsKyVCmrY5cxwY",
	"bi81CyEG1+EgJppQDCeoi95iSd68QoTFPCGWhn6+OJHOTGZawmT9f+Zk/t+n0KHT6/UmDlsm1odmgvrm",
	"3xL+6KKfyFTPb/MZlVkBHEpoOQ4CamKDDGY0u1M9ADzhmid/oN3w9O7wfAJw1M0uD7qAMIpqgmrdr9DO",
	"zHo2TloBrtX3XQ+wQ784G12BzgWPidTcq4Tby5cnGhJSk+N3/JalHIOaKoikv5ME7dAZYoQkJAHNnd0Q",
	"OAPFS8D6kc7fvZeGrN8pR08JmBKs97DegyDMZInCEsEh+O6a0uruF0CING2ujmP47kf+O01TbFtRh2Dm",
	"jpC4EJrYOGXI7dPtzLCxXHB9QDZW1QJHur6SAAOWaEcSUo0iLbML7bpgxcM05bckQQsuFbpdUEVSKpX9",
	"eC7ojWbTJ+eGlgAPzgW5AZJ9eXnxHmGlcHwt3cVzCzVhW2A5kgEv3RsMPr5ttLUmp7DhwcAPCeeLEpoR",
	"Bi6QjUH3B6++ze86cJu79tzdNbokZOjNMGWMELzJVuSsvzn4dbsxWMpG7BWwAUDDK86ZYQfwp7k7lKGr",
	"s7NPVuhBO1dak+ueCUqYPpsz0IXQJ25iLndXEr9yCgTkDUi89CSn/TNKwV/mIxbXRHwPzrUQ58LU9682",
	"dU0IwBA8tUcj1UquflpghaiEHf4Pewtht1QibJhhrDpoUWSYdYW78RYUCZF0zlzMMAaURebpA6RSAJ/i",
	"6PT0o+zB0CfexCTRy5cHg+6bwf9hrRCCWJ8cY5TT7Arw9z8uzz7pG5uW8VF6mgWdL/TAMKxuL8jC3hwc",
	"x4XA8bLnd/kjWaL3BLTigBYfmd056dfg7WQ4ge1ck2UXmCTKMRVewhECL+2ZoAwORQ7RRMtAv/zt4Nch",
	"wrRjoo86WeoY9hWeFil2UjOMrnUADgFy4LVqISZ96LCiGZA13fb09KNW/aWTtgtNmKTCLKFsbnt8tJCR",
	"5qSqQpIFwlvCyIwqGRLVU35LhAmi4FJJK34mRQyw18dSSI2WGcFMohRa6/X4Hn6k91hqcc+ZyMxQp+aZ",
	"ztnTckPYfZ+PED7u5GzURe+ptey4MGbp3bxgMYYm+B0Zv7CQu4bYMkE7U87T3aGWS9HfnN+Y4ghSC6KY",
	"F3oC8Laf6NObBMRGiYJ4LmsQboJ2KFO7Q3QCf1qX/RzH4HbLBWJEAh8BglChXH4kj5KlX+gQvQdLtiQ5",
	"tu6MXCBl7wwsNRyLcUbgnRdNLFZPXAdZMlVn5zbWMgcgJ0MqqlKi96G8I5wGy9/Bsxpdwv018fyQL2KI",
	"/gMzgt5xwwPbLzt8ci5eLnUecenx9u0PmrXKIXplMmNVKJHLtkQZujj8MHz50tOhMGgnwCF3RyyrNs7K",
	"uq8L/Cvx3/PD4K7A6Jfmbdw4xpccZE7VopiCSKk4Z10zK/zbBf9zdKIh7GPtWzvjNL8m8pqy/pybzhW1",
	"2J6SUwX10itKipHegn36XUD4TshhtDSZwPPRgsgAfzqlY3BIJW+cOrSEhBBfvvwN7JW+m+YU79y8X74Y",
	"cTy5vx/qtqU2Cb8H2qT+2tcjmT/+jlOalOs/eSeHqGWqYPwvX/5WMHhe+/cUS3V/30FfvvTNT/qrH9ze",
	"nKNA3ymNEk3wGJ3LiLJjo8vc31urhNaPqx+83gWe1wL9z4KIpW6nL9bSbVSPaImX/snaC4YlNIOPXQtE",
	"/e9gF34iu52PpSplFS64ASB/thz6IcPp8ncCx2Aawew1LctpUCP2nseFRPqufvky0/8eY0FwMP9ljXeD",
	"YNEKUIDLueCgMuhJAxmkkESMregEksp+VYrRtNUs6DwlWBKEw33kZtCeX9TLl0c8yzgDxfcISyK9IUlj",
	"zM4FUYKSG5x2D4t5ZoSyD/45YVeL6ibSCtJ6UnJDkhp/QTE1SCytfSpEQt3/CIwtWvD3cjjYyhy4HNoS",
	"OwBcGHSUapHIUZdgHZY+mbkdzQSaNiVKc9G40tOMWd4NPdIJi9MiIfZq9CFGs6/xnGsiaE2ApqPWsu3M",
	"yprLjoyC1CariVCrsZYrIrVShmNFYw/8HwnJg1hMk2wFdW0mkjtjfUBTknKto1CGcO4jkJC+KnoQfaJx",
	"SrDoIG8lvSH2aZfhDELAHB7pDsZeiDJqZE0r6M4FjsmsSNMl2lGhkRONItv0miy//50IPoq0MhU+xl/p",
	"3ZW9bAJg8yamjCkWYGOtSKXvuJ5g9Yuu1lY6WyUCaXnKXfOwch4YrZuviSue1YO3ROsVYBOeQEyaIneR",
	"S3wSdcpl6X8IeCCIOpF1Q4o6Fa/T4DXaxWNnutUWXgTtDztbehGYziu9CExqnt2Vj/71ZDDhs3/wLRfc",
	"/33QG+i/2x/+Me3NYUW9hNz0bQ+cU6OAGl+GFs+stS/0dovuhb7tsddldlw7wFHKiwSVSSCtE1YhuzFh",
	"SuDUep8+u5vu1q/kLal51r+TB8fe6oRbH/BF9bdc8OAXe7B1X7OWRbU8tnMt6o9pssUJ2Mbo5N1X8yXb",
	"3/h0v/8v50u2nedsgEzOGvn1nGHbH4q3pGym87qHQNvC21FMTnGtlVPmwgtNEjd6g2OTx57PZhATqLnA",
	"KqJoXFh7B8NvBtMO+u2WsP3e6+E3+1PNnEkuCbnuij3zNTOutMNvph3d7wYPD15N22mj4SugDqV0KrBY",
	"/hl8VENyYgHaSkpCoGiiEYBF/+kBoyUaMTw4mNbpSDjAnxjvVyU7+OHq6twbdbxvImVIkpizxLwgWQCW",
	"uTgq8devXw3QzndlvgItuwqQ+3XfFIu5ixbS+qtM+S1aYJHcYuPCsibd0b8wwQpA+gcQrFZ3km0JFnRe",
	"R7BaJTAjEFcEL/NTV8Oug/hBB/FXXZN4sI2uaHldg6NnswNrAvMEcctuY5249VRnRo2nGiEehq7d/a/g",
	"0bi9bOYVlw001ICvXRwzY7wo/wnHqv+2J9wQvvysz+zg+IxH8OcR2P5spKvEpD+GdLU7sT2AfJkB1spc",
	"ZSsvd2HvyaW36j0hNJ2DJxufy6r2Bu9rCmnd2iS72+ThfnZ+/Oni7PPV8cVWXu5AZtElSc3zvrXYQBIJ",
	"AOykmm/SIK3F1pFLnuSSrEb6N6/z99cUiIl2q9PIiX1pCQszuV3bDLkWqArsYVYKoMyUaEIFUzSFRBWy",
	"iGNCErmKnVTX3EHbrLeDjM7er6t6nRHLiMJdYMF9kw/2oFcN7Voh63qLSQ9b5R/nVP9/txoL0JeEJV39",
	"r65N3Us56wKrkA8IFKhuu2ld8tabpwULBAflAwaOMEM4lRxyQRAFV7d5Tf+4SIE/EXN9cLhAJQtEiJMU",
	"8nfMKBGemVaP/MVuDx1TtSDC9uDCYVFWSBXmDq9y2MbNaZp/YJiWxDmA0nzWWKJsxfNeE83hccT2tqg+",
	"Yk1c335nVYT5pbm5bchB1IlW0APNh3wtu6YCVytX968noDxHGMazyzF/SAzEJukjzOPTWDt8bPHyDvIy",
	"aWW5oaZo7OGz2dhKE5RUE6TtNzJ/+XbGnfPO+K9TnCI71FogtGcULk+GMqrHGvtlycpy9gbNzOQnpoub",
	"HiUkxUt9vTKaptRaDiqqfXsi8mopt2DSg85GsmxrOLre4akPNhkV9LwrtnswaNmvm33TfuszbXHDVsSL",
	"bCnc2t7rJFvXhErI2p0uXwQ+/x9PXfyzsdW0WBrBa2rEzj59+hldaCKeEfSh1AVlr+LzpYKYW+/g4EXj",
	"ETOkPqEy5jdELIOkaDaZSpnhqz8pkwGuNDNwxu6EWVX/A8m0INeFpe4Yp/kCkte/xzHZNUNUvMScG2y5",
	"W1gv44jc2YSNWh5KSE5YQlhs339bYAGIOZvRmGpB6Oj8c//D+WdE7khcuBfew0Lxbrlzx2BtcoP1+4dZ",
	"Qe0K3XG1eGm9IlZYQ7ZR59wFeZg+1/nPNemWNNYqNxnOg4QRIRi/6H73/RKYNVvEqiv0r2rMDc/7L2vu",
	"1wqUbI9I3IKsV94UzSioan610N8hTBGRCypJdy5wQnZdekqJDgNfDOd3F2QLRDuH72xhqGoRKX3a6MPR",
	"eajWyRHbMau5KFgHffjxuAOetYUi6JjNKSO71kEpKE8IyY8tP0nITQeJgo3YZB7DQHrS0F+k67z/Uj6n",
	"bNJDFwbkEp0cfkSCpwRN9P/KPqbeLFxIIiZ/mAcALNw5AcQ86xu/iq5WQ/zRdJ1RICVYsNBQHWj75aN+",
	"FLzRR501ZoD22jb+aTrKlt15nHftb1Uzgff/2GgiiMsLMs6xq0TWlsLOyQw4Bh9b48Ltctr10CVREn04",
	"O/twejw+PD8/PTk6vDo5+zQ+ujh+d/zp6uTw9LLdblAX9A/fHRnHW8669Vu5hcOEs3FXwVzdUgXdghQx",
	"JeZpOtnmVNFBL0ihAdi9JVKBpt5mM7FwODo9+/xufHpmQFFLYBwO++fKqPZg140SbquzHDzV9WKV28Vm",
	"+J9fnP3H8dHV9lar/3I69l+pDp7GwSu1MIzIXVbE2IJ928eRy6srtPOTKU+wW1XItnkLCMrJbXwH0Fwq",
	"KPugfy9jFI1bKHCyLD/ooFt800G3ZJp1EJ/PO2iW4lgLz3do/zVEdD3oJRaitWW/WhGkZttuVIPY3jRd",
	"e7JF7yspa6pw2h6lIb97q2KkJ9JftXa0Yra3h5fHY608rZpuo9bUpLFhoYzqguwFapDSbdPCrijs8tik",
	"HWtxY6ssDpURDKt4yghWlQmGeGoWiDrEHpUC4vPqBBCsUganZ8pAppp/adJb+vMucwJ+XT4FhP/Wteke",
	"Yx8g2qsjvVu0M3JMDN5OfNFK5C7Wjr978LQ3McLiBOJfAh576REcQmp3PJM3vaxvcBlW7FRMJyc6SthB",
	"P+Gb/b+TeL+DfijeHl9c7a6pwNNSWmebsjrrSupMJpMqefpKJWfW36VW60Z4L1r8ub3TdiDPm/lWumKv",
	"R5UteJk7xpCZtRxh9TqD/pm2XgOoBlOtHuUtb41L3Hj7dZBXlC07bcfbQTMckynn1/1bfLN/Q+J9e+wr",
	"eeJPh3+v1tXtoI/nBx30/vTwqIM+vjrsHx4eVZniJSlNZpVirM95se63N+YF1pwWtnX46er96T/GV8cX",
	"H0+uno1zVRbgK0k5PgXqQO05Mzw8rSmdzBDJcrWsZrR9NG+rs5KH2llqBK4MNCgp3TMYVxoWaHSpBMEZ",
	"ZfOORgwMhQqpj0zqBE4lecFiVfjUJlsYKKqYBgJb9YqWRcfNHONgjmioREE6UYrZvMBzMo6hDlREWPfz",
	"5Qbzw1czLLTdyvWbCMQss5+2SurtUG4vLlWDRyjGOdBUp3AXxHWE0CiPHdAHLAmye3y5Ik7jiUYN1733",
	"AKS+IDGfM5NVteI99MJkKR6nnM31uhVJSb7gbKn/yEhCY5yOExobkrhiQ4/S7at07WlafSHJmLAFZjFJ",
	"Nhc3+ywJcq39m00Zy+eyEaAdCJgHdX637fasImXxoqiWXTXvdEf6Z9KaaG+7SjGNcWFEG1MfNcXW9idG",
	"w8rNkpAbsvbEaMM6Dc0UBZNlQ/Pqki7Dci4ujQzTqGBzBnRGTLfghUJGzDbZEMqHuJowAc+OwDtsZOKM",
	"3pGkK+nvZMTAQEF/t9w0KVfjnvdik1kM8RsiFgS7QpD6pMGUfbsgzqvuomCQj8L40nVhzQnJU760Ca+g",
	"Th7cC5CG/8ELlHD2QkG6GkSyKUkSyuZ9WISfGceCS2kqcrlut5gpBJYMnGrpvshdtKVN82BW6F90TfG8",
	"tsWCa4FZqy3rJW2hHzc/ZOMg0iV5MAuAFZ99+vRzF8cxScF0GEDP2bOD1eZESCohYBaa9f1+TVo22ebr",
	"Bi1lNHw9qFe7MAXxXEFTfTopzr3lU7f3WRSiYaRBoptjMScqaDW4v1+FWmuQantFuDGqPZHq4Nuos1uh",
	"fptSOyvSFAqTjqEo8uoyc21sr4noejgnkCfkDlBjZk4UTJpvU3KjRfSfFt6ZSaEdckMYolaS2+249tUK",
	"UgbnhvFMDZEsZjNq0hCaWs6JH/yFRPZeGFOYmwxP9Vx+7EISNIwrI2FBTKZsqHWnd3Nj8lz4qyiNA1mV",
	"+AZVM7vymuZdV2ShCy/g+kZCHHvnQQaEVReutCOYoo3EI8Em7uONzLcLAt5yho6Y8HvpERBS6fjyiAA6",
	"k0woTHhtYIjL9NzmADKScWHjyDQgS8BBW3OOdlC4T2jK1cIPx5IVPZo8cFugP1u+zSbDajdPAvdYVYF6",
	"HT16BPFZbwdorLjFGJCZQO1yhZZ0rjIFbEewnl/EaJCtp/ikeBG0VaFe9fz2AAW4fKBapbI/wrjrLtaa",
	"g65Yd51P7Avo+MLYTIyEA3esJtF0EFzzQPGGdxzrBROb8/U+MNVduqU9LlJjS/HRneQKybF0TsPIqjOQ",
	"Fws8WZw2CIU7vYtZVZgzko6imjAa0cYWCg9A4nyDwG/LeaC5MrMmC8WOpBlNMSDbgt+68LxbLq6lSzNw",
	"5Cb2piktCgEUh+iyLoWW65wurRew0Wl3nPddR0uisCYHbxAgD9nSFK+x9Rk1N7Vujnp1kGlv3SGHXmOw",
	"bAMW5/C2N0QfDb0HAc1Acb9r/H3Q1dUptNofovNStDsnU60na55jDGpdZNzYZymdLxRKSFKUNhGbpzQu",
	"hNCdjQO5ViJs+ENDJtzCVlaTGp9Mth8mRpbsrSaoHcMH8kCvTe9+abWqUmZuWlK1CmQmSdDJp6tvu78V",
	"mCnAEZym3Y+U0dOP3dM33Zv98H5PC5akJPHq14i5UpqUYbHsoU+Bj6PFs457aet4X3yUuNyO7orWXx4b",
	"i9g5+PZVmeVRdsAltKvlinYPzP+TCF5j3f/r//5/DeYhrQ5aljDld7r5J44YUfqrqxLlVqa/nheCoA88",
	"cOgEFwD+8fTn6pVrqh2rtPOWs7f50B93+GEtrHUHr9sFhjOD8iHr4sJ7R8k11U+gWAlM1CVsnlK56N68",
	"8jWrFFWYdc1nOKib/a9Xu6pd9FqxxCpWl9lpXJmnqJBdgqVqe1GeYhUvoOZ51ZW9jQ1DW5PmdBYqDZ5a",
	"aaLLbcJGpBaCF/NFXqhnr5q1Ag4vOujFusNqlBZcCc5nrpgVOkWZg6gvpTyhlsn1v/IxI7djyCa+WRH6",
	"yeo/oOcImiNGbpHJRO59VyjLC2Wc0G06J3+eKyxy27uGtBACU4rgcXTA1oJZQQK+akmk2t046A28lthB",
	"e4N9oN9yt2MbgoiVUjYvcAqtH1ocCYapIj8c1NhdCsgxOXavacHbWHOlrcWSnlYaqU1teGw9pHBfoRrQ",
	"3GItKtDWcDTJMOH5n8/sddY3hvuMsYFVI9AIm+PbXyCjYdSJqhnn4AewC+p1/7qdKtN6GFsVPCov+Wqn",
	"wNbRm/54omAxVjXoHn9611jKD/wWhHmTUA4gKVHK2VyTkAU20lCG71zmWUhgGIL009mn46gTXV4dXlxF",
	"HZjj16eFtbdQkCbteIxBsmVg845SG34bk2TLWOYR9HnGMorVM40FzizPN5YJYn2e8dplxEcO1spnHjmW",
	"VbmfZ7BWLeipTlhr0OT5K/KwVRzYTbmyGk+ZUlJxW5pHS4gLfhtkH8WCjFilXEG7cFKt3YNaS/eM2Kba",
	"Pf/7lOXxOYexLNOH/lWF5ytV4flDS+lAeuFnqqfzV8Gbvwre/FXw5q+CN38VvPmr4M1fBW/+KnjzV8Gb",
	"vwre/FXw5g8reOMrzFQKYTSLjVyZ49NSqmnSgwOFIjVYVb8kWMGHKzwPqs2UHfHcV5yx1WXKejVfvgQ6",
	"mT2qStEPK/Po3TcWeW6ulp4THtr14ko7w7Ci/wUGiLHWBXXjc0FjMkT/9uVLrv/VXhWmLAezdgEePA0N",
	"pGVZwWIeVVknmEwrYgaF7u/fQsUc95dXvUptLcaKzLnQGlsuSEaLDDS2//X//T/o3PztBOSg85Qny2CV",
	"L18eB6b3v1vTuw9s+3D88eRTECvbdVb9MMTj8ATa1uNqq22NLTFs6EI9nWoD6k/ZNFQTDs9PpOl6enr4",
	"8XD8w9nlFUTbGS8SUKkF9LeqUMPPYW/v1cEr+0B+kml9S2P/uSAwTaGp8LE3i1ns+gcvwDZFoT0id1RC",
	"r8AZz2RBMgvuWGu8cRliS2/u2tXSOIV6M8B/1YJkpd82ZWjJCxEwMFt3ekHQJLDV2depHgJv8OkSaiUD",
	"qRux0sQWxMZLRXJg/7eCKiKt16YsZ7ZllsFT1IWHKZKb7e/10JEgmub4NlbZMca5BUE4zwXPBdWNvBQO",
	"poyfRBi9ZXXKcDND9AWNImOGgbE/4cyaYkbREP3S6/XMR9/FfOz1er+i+0lrUOM/pZ79iya3owhwSg81",
	"ij4ukaOTo6hjPjuzAzTwVFRLFXpm1ypYsG75xbCkUZQtxwaYxjkYVjzo7XXQoLev/+egg/RCdfP7EQuR",
	"rV6B6SOdC2MbhIuEmXFMsg62zh/IwK/l/pl0sbU7WbqeTpeBDwoo5dCjvP95eP9bbrFZjXeUrE78Fh72",
	"c696h2tw5RKsHZayOZHNGD73Cglv7b5396ArM5ymrbV+7jc/9ax3/2xao5+3uI8v6PNQH9Jt35geVuDn",
	"8MQX83nsU3idBzzoKdymIikPdzDYCx7DDwbf7JvH8MfUBSpB1vR3g9fpSFNW3b6r/+xEnkpFQz1zIwFQ",
	"ZZnV+2evxP1TShC150+pgHf7l/BgL5X0it/stz0al1YS+3JcXgZLbHa+efNtB+29PngDqA8nE0butvvj",
	"PF8FJZeTKqmmB+og58JuRA44Bg3R3pYOwiuOdv27+jYP6isGfq4iR2hnxcY73iOvCqn2WMBHFvcpZ69G",
	"ECM6Q4wrZJMk2HvxjKnpt33Sflg1oBWkz9isA761ruwPQAyIZCHSSkKZUCgl7Ebj7UqCyHhG48DHDPDO",
	"+QNld1Nsb1TXZALcCd2FcJpCtYc0816gqwhnUDTIKNz/I/7e77OdC9dXVuO/jgGucCQGAbtJHp+hglB9",
	"XRAJWwdU3TWuZTOrUcORihWb6jy80kx7dvfynjwmRsIt5isjW5vPx8Mq2TxSztgyL5N9LpMr1MQ6hq5E",
	"xHahM3TUe33wxmFeo7HFzk3yy6bMTpslGHnd7fV6gcveQ4TlpxTwWVmg4PApwkpLfr0zk6WtlFDcdSrv",
	"0Q6woI/WPlC29C8AID54WWWI9l+/6aDXe/vG3bIm1mydnG8lqB9cyqeK2ivH3Y5EgWCc0+BObSRRLRVl",
	"KhkSTYMXEgQrOPnmoW9MzVWlXa2r/Pq0q9XH7OGlbFbQsAeWsamJkdaROqEzMC6XeVDk85ewWVniZQPd",
	"2+2sbAg0rzNi1SoPFfnXlD3s6/85CL58O31QuZeaZ/Mm+shFjUSu3enKIi9/vpIuT6WadIZ8gAhEybmw",
	"vd2tSeAmUK4FzKYaLO2jQpmz1VesLultWuEz05h2984HlhNYQV0eXkogUF2M1bgMUdM0JXw8b7URrwjx",
	"RDs2ZP2/BQkodntrMvxDUgsTOts2kYmMdIHwQWBk3XHRBEeGaS9qsZGm89MjJNtp5HROYBddwro3e73X",
	"Fe1sZSiekf7MKOCHY3yNmsUXiPN5dbGkYQmGh8Rs7gfUrr7mFVnznrV8wdcNBd9/Qra0FuONyZdWK2DQ",
	"OIqV9Qta4PvMNKXV///xqewbUsfXyWT/bDnkNxuHO4HLaMjfwMGvD6nq+vrC893nSC5fnlB/TlS3ylka",
	"wdUNm/Lq/PMbjc0Pyjj/9fLLPzVL/B9hmjaFoJqA/O9ob//b7t6rwbc1V2PfaitL9r9QavtnMomvpC9f",
	"zTj+h6WhfxD9zmiSpOQWC1KGD51dXJZUu8Zm05TfjgPU3ByIe8ISTWRJkJIoJMgx59eUyI6p8rEgWHOx",
	"XRMgYnx2e+gTV2SITmY2nZD9fcwFnVMGETeMQwnAX168fPFreypG18nOUFn3L5H1LOle6X6d6BDcVGxe",
	"zagT/dy9MKIWSbo/UbXQTeKY5JqUncEqokYc0Q9mIpOOxAYFQc4pypAGsZfeqsUK167kQZUH3Y4zohY8",
	"qe/4w/FV1InOzy7hP5/1/747Pj2+OtZbOteoeak/HF4d/dCyt6urc2THdccBxGLNxlZP+Khd2cNv4tkp",
	"lZAFwi3L3ZLG8npQmxauDDhF6vb6f12PKmky7Vz6MhP1A/lAE3DRE0WVZPzSFp8RdQJbUt4LvzwIBnbi",
	"jQlLG8nAYP9UupW3Igq5y7msI0rbxbYNneNNnFKiZenPksyKVEMKHIE00xA2fsiEvTkkN5gBMVoCLn0C",
	"EQwAbUFwUoPnz90rrnDaPdI8/mHwgsKB82oU8MGbZuG+H/gtxPyinbII1q6rhAIXQd8rcKQ1epq9Sj7m",
	"D2LYwmWbWVrKTWws+ieIwG3J/i7g96fmkPGjPyyHDGSh7Bp3e9HPZDfDIuZejezW8sqMWD2xDPpKeWW2",
	"WtjOm26Kl0Qg83O103/NdDPNW2L8nR53S2z8/YrL8VWTTJg527NM7Hbc5yfnljDjtL8YtyzhT54+osxz",
	"Nc6JGCc83qbek03EmJPAhdzY4Ni8/AWcequJUNbbVtvBt1XCh/LCrRbB24dvkn6ej1lbRSG3+4xLTbdT",
	"coOZCpw6geloNgXZ5itOIR3PwHAQS2z9QGXMBZG99nKu28vhTUQ2D/GPQ2T7iN+CyNEzujTo2fwUj3bX",
	"aXM4eN63tSZsm1At82jUMudq8tbcgwlZAQAp7sO/zXuYvx+b4fOQPAerdxFmi3VpBlrEtkYQPzGXniUh",
	"JTDB6xtWvjKdQvMEHpKYZEuZZ5vsE1vi0+OGskbkZxmrlV8/bihj06gP9eAkuO1UI2CYFiec23lgC0wI",
	"m8eY9/8nvJi6lXQHvTdvh+/33rT6YN1vkeUXDAsbsXm9q3RzWy2u0j6puHcQKz2evS+0tViucn3e9r48",
	"8JXtGYl5nd9ao15FHg5eGx7vivm4YtFPJO6taPAwP/PSOnhhAXV4fvLQVwZTfD+lMVUVk1eO1cLKweeC",
	"wE4lVV7lsFVG3vnS36Zqrl7BELmSuFZXcpp8WSKdQGP7OIBzCglZJnrcD0ILPO51Y+ieN+o9cZJRBqGe",
	"cVokRKJJvYWFtwGghD8nWprMqJQmANyrZiCVS5Jp/THuWmpgRcZ/N1kgQym/3nKGpeoOBq+2fAapPH50",
	"cZ53tdqrFUJ4CLHrtlFThx+fMpbR7rqxMbC06xPr9/0neCIxzyOtlVIeVId3Szv9Rni00OyNasHGQf98",
	"5WRWqChNRU2QmIvkP1U1WZO7/bBIKK8kcG+pyGmqwvoahIojeN702a6bLMylX04saR5nbQObRsg1grIE",
	"NE2pq1w/JeqWEBbOFgaRD1a8mt1SlvDb9XP/BG1WTw0FMiCvtxmttuNK8o/BoH0l9w87ivWncE5E1xsq",
	"G1zPnwQ6TG1eJOP14eM1uuh3InifZ1QpkriSxFoBtLnEXTSFbJ4m7H2TdvOgS3ZfTe+9tbkjLG8dmj5W",
	"FCa2ycAfuewrcqfqq1YLQeSCt2mTwEoTsAj6Vua9VyNmvSpRWQK5rcxxs5zxQ25SY+Fb4TTojJtRelVJ",
	"8k8tpchtH4/IMWeSxAU84psT7UHONumTorhEGq5Wkil8MuUFSzBkQzD1q+EJbrpspN4nQrZfhSD3e33h",
	"lz5lhaHutmRlSpVJkGffykcjNhqxFzZLjMBzgfOF3H3QggL2UU0835DA4XOzvHvuasE8nN6kfD6vqqzt",
	"IvWpaddCZGrVuGTjiqTkxogL2yFcfUWn0B3SRC+NEPa4cS6h+wPBcerWXoo6lM14Q6Bx4LkhYsolVUtk",
	"dl1qnwmZFvOo47rfYgHeOUJwMK2UUo9t0JRtNuysFg8gMspwunKhtuC8TTkCoO2hF67bC+uXmHJh3oY4",
	"kzwlHfTin5Lb2x7kQtISZwe9SPl8linz1VQoIbMZjamWmq7J8vsg5RAES/HcFTVJLbF2wAqWryeMOpEZ",
	"O+pEulsVYEHjNUCTB+Udr7o41LgaSP/ja7JslSIPf7p0zz/XZAnyow/zuSZLKHfkki7B3kgsiEIp59dF",
	"3ijJ+tPl+PDo6Pjycvzj8T/GJ+9aBU0fyEhUVT42IcNGW7kmyy5N2stiGt28hcRVEtw1iuvIA5vfH9+C",
	"pvlCa70vSvfH7waDgTnAj5SdnO1WZfda5wheSk8hhRGk329mgQdIjUv4twPfArQ8g6cewOXx0cXxVXAO",
	"jzgEM0lwFq1p7gno0Ia6r2K+OEVml9DWpoYChCJZzgUWy9De8KC9ty0bZumaFa2ojillum311MvL0/7V",
	"6SXMfXmgqQYzSRhlLfsUtDj86bJjK5OVbuL+Km1TMjPA7ljgvMbHFGHKZSNc6/NEkrG+0G36gEsmGDqd",
	"6LZQKqh/cm5UgpSya/+OLcOSxlpzg7FDpye0Q+5ikisTvwu5CaW+X5CfcGx/HNNcOu+T3Zq7RNXtJE5Y",
	"r/rL3nf7vUFvv7f3OPcbSIe5JTB0W5t9jDj9CBJtghcNpMiEZJ11oMAcVU+w90FnrYHgqeRpoUV6aGvJ",
	"Uv+zJEL2E6xwf9d0MrPoLjYJp82GZntky679vcjhgPp1eIZjakLV6PAwODbOcSP+vIWcvWGZkfJqIIHZ",
	"nEi0s7f/TW+g/6//bQftDYJ/f7Pf23sDf0Ec4Xf6z2/N3286aO/Nd73916/s37utjkHu8o5tHsux1Xhr",
	"brENO45pDedOWUJvaFLgwKVDoxo2BKD0uqn40IQeNHutr9H4buxXpyXo8XSpakVC9gavvn39TYvTj9MY",
	"QfLmM78wI9JA0AZlyAwYrCoYb417T/C2YX5988ot2GT3bXcu3h+8+nbVOqEfuqWJWvQXBNyQKEM5vQPf",
	"eONE7otqujSh4crN4OshWkgixnhO2kQCjQjdwzk4CYAnFxwtuAQG9K3i1mue8d697e/1Bi9CNokueUZs",
	"xiuPvj/Ra5qThOJdJAiY4Pytd0V/MSpXUWVa4VTb1YdfwyH0pkpJcJXeA1svOW49vIAkXm5qsZBo5b49",
	"csVnEXOJGxdUhtPgPE+hBAjfph5/4M7XXvq1hWi1bNP77nGbA4yskS/seY6if/tixIwhSBH3oyi0epUn",
	"4XLTbq/AbcnTH3ruFyTjitixtn9BEtDNk40ZUTb+zHw4f/e+Y9t81Nfb/QF5mH19gN0eZNuTPKUJuE1r",
	"KSl4PgKe2UiCbK0UtqCjll2L3Bd4tZX9yqtzQYBt6nWfiYQIlyPt2L1XTYIZvx9FWpQZRROwXmREEQF+",
	"fHbFkCPtPSRTC26nqR89MUxSTtA85VPNpRURDGVYxQsi9e2GoEDdBpKvTywJHMuDSTAaJCk+JXMcL7U0",
	"mOr9DdHE7a/aWKId/f0WiwQ53QUywe5CsEsV/cr5mgfsnvYqB2DLLC4IQ4zbpdf3VaVIuaAZFq3i/kKp",
	"fB1GPhIJWslWA58/4cyVzqxUjltPvSpVmYznZhfntErKooonnmvnXKBLSlT1bh9GbwkWRKAauYjuW/HX",
	"HNkzg+7yYFvA1dByDf736t6d5j40DQklndQa8TVZ3kehbt6mMLdoxNVRzD/vgakzJQqpjOP4yqmtPOum",
	"twisRWAtFHTt5+5LjUrFNKVx9yXYWh6/TDejW2qVEawU7pwEtuJ2/Fl4ScuNekTp5BWmqWbpHH9ejbfN",
	"gACb62qJlylpW5cuTFJXaet4YxBEHNnGbpxOoxuVJj+9JCmk7q9pUY0rBPlozQ3aXnn6I8+24TxV5Qbw",
	"0OqfyqrsoMar+Q0RgiaVF9nyBlk/o7Fes/t30+DeFo3lhe6NKqSvibggKMFyMeWaR8oFL1L4z23d3T7m",
	"WYZZInsjFsrz3jwDWdhxyhnpy1ssTJHhHrokUHvYZetHGWZ4TpIRS0ie8qUtOmOEwx+LKRGMaEHHaIJc",
	"7FrhIStD0O0IPlggXVaK9IdxXqsCwVvcknw8X98/rtkXimep762lEMISreVzd12DCCzO2J1WEFMcdaI5",
	"b0ZZvTX9keuPuHDaljknfUa+tLW/hAkBVw/nIwDpWN67giR2TRPw2Ld/DE2PiQW77Z8EBz7ROD2pZHVQ",
	"goL7kfkvZXZxkKDfZvK1GXbxDaYp2P7sfP/NzDBiMc+mlBn5GYKBpNMkfG4PK7taUMiXL9FOQnINFc4g",
	"qiWBfOy7Q0ioPOcT1BZnsYPTW7yU5VI66Oj8M+IsXXaQTPktkQoKSk30oUAu5k+ffkYXBVM0I1p+t8Hh",
	"XT3Z9yM4u87ZxdUo6qAZlsr3v0vxBNKjfzz9Gf18etjS9y7FnZ9PD3XXq/PP/aPP7w77R+efXbA3wEa+",
	"fGl2BIBHXXSoiaopWIOmpAJV70AFHeIigRV8+vvJu5NDpEdHH84/m29ckCyF4fI8JeiIC/LxFO1kOD67",
	"tNBwz5EaAGZElRdmS+Abc3X+GRJYQaOfTw/trKbNey5i4kFbifXwO/rFQE9vH2Bh/jHno+hXPcSVWLp7",
	"ElTvKS+lL9lTDjXUe/bjDVVemD/MN/eXn+EcwkE0UMC0nHpL/5EFkx8WwFXrbWAFC7Pg00JN6jODVPmd",
	"X55BdL22qOMXZn80/zIUYHsmaKXM8ddjhp3ompB8jFN6U3s6fJ1FK2PnFEe6m6Pe1pSmuYBJl2IqkKVY",
	"KpMX0fhlB69MWgEOso9Uy8QVzjZnhgHxw7viQA1UqBBGlWYQnyXQgSTQ0YEKjqLX2ShCO2UxOX3Eewv9",
	"2x5a8ELADwP9N8FzvVxDaXdrjNANlOLfl76NqahhtuV5oRkNYgWMip0une9mZYYRM0RY38uskYIFnmGx",
	"UIVJhc7IDREeJL3q5TOH1PRQ5vPHv4+XNwN8cHxOmrEP+Q2vyUpTa+CcE6S18dTaW/uc2X/EDr2WF9oC",
	"jY3zt4IUJEFFDvlQ8N0YfgBVoTdiFv4DW3bGlB9JSqJZg9qrVfZlA+OxOZOHbtOepEONBk5ImhWpwozw",
	"QoJoA0I3XG5YsBarBYHo0g7wxpRgCGOKCVPOh8Tmp5IljuycXnxGmnCapIJbAMO4pJDZzNa3AztHSQX0",
	"6Iyz7u9E8BrgDlYBzmxxnE23A5qFyA5l6OPb3TDUyG7Kp4NqgRHk8LdgWgkig1EB1myGChQpoBAai5Mb",
	"KvUKzaRdhGNV4NSue8RMvSAjo0gtpJhj0bfR6AMZXvqHWqqBfRcTkpiNgPeD3hrEl2rBei5pAoWHqxfQ",
	"vqIxyIBDmX2rEDytX+fBd29WHUyJJg+9zuEjFIxi7skKmhBc3vLULNrqb7MiTTtQnt33cAU8Xw8O0KV1",
	"Xf7MSpEH2O8FUWLZPQQ+YGxKq8/STLbhnq9avynWgAY12O4NBitDI8dSCazI3ClqK4xUzpcFWEDUiTQf",
	"iToROK2RpDXCpOnbWdUF7MShuok+4lwG8RzShuxT0ehVsl7GlQnWphJlOAcsDAsR+XmMdyIPyQQIeiez",
	"4BcDwjKk13LO3SEKWSfaMS+CDCVE650di6WW2dMkJbuNob8H1jqsslE7UskvOxVmCbK2NWwYuCywLLc0",
	"MgcyikIImE0BmWly4x0sUY4FPHvngtg5XPsqn+4gckNYnbR6COWUsZA5wFqBAAE7lCijd1CfAvarKQqA",
	"0NIFG18vcUZQzhv04Ev09vDwpD+dE5NR0GcBG/o7mFGhFv14wdn1sptplFe2bSX6ei8amuvaZg4zixkn",
	"VKx41vLZyYBu2ZJ2llIWU/cVvDadwglmJReLIsMUpEav+FJOeh/kQ9My+3EjhVip3VS6OcdL6HXkbAIb",
	"OgkbaWR6XVRjq9Z1i/mc0d/LjvA3CKobu0IRHNvxkvy2f0l+Q+7Xeu+qyPp/9XvWvNR37VwY+g3Nidgt",
	"gwyI6oAeV2aPAB/V0hOZBhp1XfpszNPqesd5ugUH+rReXsxpTkx149ztvoeOcbzwXwBj5YhhFPN86cxA",
	"0LKDJIdiikSEru1Qhc/KItNC2eww+lco0O0WUeaS8YzHSiwhrdzJKNv5VGRHWuV8tVuXOVtf4C0VWZ3f",
	"pkbPbfsKUWpVra4WRJIW3YJmYItVJF0a2uSddvVwsoPwDaeARGDW8SEFKVaExZ5z2BVZoyJYjJFacGsI",
	"9Jc4wNDymbidNo0iveztBdOqOgZz1iH+yyoy6Cri9OOU5t0bqkyuxFxv42D/YQq6BZBzl6lq0M3cCE7M",
	"AouT4ugWU+Ujcg2oFYcHzZQo0ilLcDkRTLfXndcqvgcDaQwae5n5Lyi5jLvitB0UKEYXTgIyMqqp40Wl",
	"axuIaa/QB6zILV4i6+5TJwcHg1YCIA/qycSe9hxSC2xyxuBmaJNuCV7UG571zdTGF9GkzkmoXv4UikyV",
	"RVKN34PmxjbLn6lTgWzMpN47VYGDSq1gMdTJxia22HgDRYPeoLenYWQ3qoHYG/QOok5kne9Ykab3/38A",
	"AAD//5GGPHerKwEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/audio/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/reranking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../termite/pkg/termite/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
